### PR TITLE
Docs/generating shader includes

### PR DESCRIPTION
**Pull request by JordanL8**
### Purpose of this PR
Adds information about generating shader includes to synchronize data and constants between C# and shaders

### CODE REVIEW

**Comment by JordanL8** [comment]
Unsure about backports for this due to the menu items UX pass. @alex-vazquez what versions were the Edit > Rendering UX pass backported to?

**Comment by alex-vazquez** [comment]
@JordanL8 , that change was not backported :)

**Comment by JordanL8** [comment]
Ah no backports for this then, thanks!

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
yup no backport

**Pull request merged**
