### PR TITLE
Added the multicompile for dynamic lightmaps to support enlighten in ray tracing (case 1318927).

### PR DESCRIPTION
**Pull request by anisunity**
https://fogbugz.unity3d.com/f/cases/1318927/
After investigation two seperate things need to be fixed. 
We need to re-add the multi-compile back into HDRP shaders but dynamic lightmaps (done in this PR).
We need to have thel injected in the RTAS. that will be handeled by @IonutNedelcuUnity.

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
note for me: TODO: retarget to master after hd/bugfix merge

**Comment by iM0ve** [comment]
Hello, please briefly describe what testing has been done so far. Thank you!

**Comment by anisunity** [comment]
@iM0ve as mentionned in the description and the fogbug this is just a part of the fix. nothing can be tested until the engine part is merged. This doesn't change anything.

**Comment by iM0ve** [comment]
Thanks. So we should wait for the c++ and then have a look

**Review by sebastienlagarde — APPROVED** [review]

**Comment by iM0ve** [comment]
Please let us know when/if testing is possible, whats tested and how could QA help with additional testing

**Comment by sebastienlagarde** [comment]
waiting for https://ono.unity3d.com/unity/unity/pull-request/123896/_/graphics/raytracing/dynamic-lightmaps-support

**Comment by sebastienlagarde** [comment]
> Thanks. So we should wait for the c++ and then have a look

@iM0ve so the C++ PR have landed, the current PR can be tested with a custom revision in the mean time

**Comment by INedelcu** [comment]
I added a simple Demo project here https://fogbugz.unity3d.com/f/cases/1318927/ at the end.

**Review by iM0ve — APPROVED** [review]
I have tested that the bug described in the fb case was fixed. Also checked that other ray tracing effects are still working. Warnings in the screenshots are not related to this PR

Before:
The reflections on the wall where missing (black)

Unity_RwMKO6iDhd


After

lptays6OYu

**Pull request merged**
