### PR TITLE
[HDRP] Fixed max shadow crash

### PR DESCRIPTION
**Pull request by alelievr**
### Purpose of this PR
Fix this issue: https://fogbugz.unity3d.com/f/cases/1290357/
Backport case for 10.3: https://fogbugz.unity3d.com/f/cases/1294583/

Note: To avoid paying the CPU cost of culling for shadows that we won't use, I disabled the `ShadowCasters` flag on the culling options when shadows are disabled.
We don't allocate the shadow atlases anymore either.

---
### Testing status
Manually tested with the template scene, now setting max shadows on screen does not produce any error.

---
### Comments to reviewers
There might be some side effects on the shader variable side, even if we shouldn't use them when shadows are disabled. But I haven't encountered this case while testing.

### CODE REVIEW

**Comment by FrancescoC-unity** [comment]
This LGTM, but can you check if all is fine when having cached shadows? (Update mode set to OnEnable/OnDemand)

**Review by JulienIgnace-Unity — APPROVED** [review]

**Comment by alelievr** [comment]
@FrancescoC-unity I played with those options and nothing unexpected (no shadows).

**Review by FrancescoC-unity — APPROVED** [review]

**Review by TomasKiniulis — CHANGES_REQUESTED** [review]
@alelievr I can't get this working. After setting max shadows even with clean template library along the repro steps it still gives me the following:
```
ArgumentException: ComputeBuffer.SetData() : Accessing 832 bytes at offset 0 for Compute Buffer of size 208 bytes is not possible.
UnityEngine.ComputeBuffer.SetData[T] (System.Collections.Generic.List`1[T] data) (at <da7cdc01e3cf4ce5b78778fcf6bb28ca>:0)
UnityEngine.Rendering.HighDefinition.HDShadowManager.PrepareGPUShadowDatas (UnityEngine.Rendering.CullingResults cullResults, UnityEngine.Rendering.HighDefinition.HDCamera camera) (at C:/Users/Tomas/Documents/Github_Projects/Graphics2/com.unity.render-pipelines.high-definition/Runtime/Lighting/Shadow/HDShadowManager.cs:706)
UnityEngine.Rendering.HighDefinition.HDRenderPipeline.PrepareLightsForGPU (UnityEngine.Rendering.CommandBuffer cmd, UnityEngine.Rendering.HighDefinition.HDCamera hdCamera, UnityEngine.Rendering.CullingResults cullResults, UnityEngine.Rendering.HighDefinition.HDProbeCullingResults hdProbeCullingResults, UnityEngine.Rendering.HighDefinition.DensityVolumeList densityVolumes, UnityEngine.Rendering.HighDefinition.ProbeVolumeList probeVolumes, UnityEngine.Rendering.HighDefinition.DebugDisplaySettings debugDisplaySettings, UnityEngine.Rendering.HighDefinition.AOVRequestData aovRequest) (at C:/Users/Tomas/Documents/Github_Projects/Graphics2/com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs:2753)
```
i7vUk4rUob

Shadows are not displayed correctly without error spam only after reopening the project, but setting shadows above from zero and back to zero brings the issue back

**Review by TomasKiniulis — APPROVED** [review]
Tested new changes with multiple quality levels and rendergraph enalbed/disabled. No exceptions occur anymore on my end when Maximum Shadows on Screen are set to 0

**Review by sebastienlagarde — APPROVED** [review]

**Pull request merged**
