### PR TITLE
[ShaderGraph] [backport] [2021.2] Use VPOS for fragment stage screenspace calculations

### PR DESCRIPTION
**Pull request by cdxntchou**
### Purpose of this PR

*** This backport is paused, waiting on full fix for regression introduced by original PR ***

Fix for https://fogbugz.unity3d.com/f/cases/1352662/

2022.1:
 + https://github.com/Unity-Technologies/Graphics/pull/5428
 + https://github.com/Unity-Technologies/Graphics/pull/5784
 + https://github.com/Unity-Technologies/Graphics/pull/5867
 + https://github.com/Unity-Technologies/Graphics/pull/6040

2021.2 backport:
 + https://github.com/Unity-Technologies/Graphics/pull/5817
 + https://github.cds.internal.unity3d.com/unity/ScriptableRenderPipelinePrivate/pull/246
  (Console Test PR)

This PR includes both of the 2022.1 PRs.
TODO: include third PR

The issue is that the calculation for screenspace position is calculated from world space position via applying the matrix transforms.  However, the calculation is prone to floating point error, that is exacerbated greatly when the camera is far from the origin and the pipeline is not using camera-relative "world" space.

You can see in the examples below that the error can easily grow to be larger than a pixel.

This PR fixes this by changing the calculation in the fragment shader, to be based on the value returned by the VPOS fragment input.  This value is not based on the projection matrices, independent of camera position, and much more accurate overall.

Docs ticket: https://jira.unity3d.com/browse/GSG-593

Test example:
Left sphere visualizes frac(screenspace pixel coordinate) using a gradient (red, black, green) where 0.5 is black.
Right sphere shows a screenspace checkerboard alphatest pattern

Before:  (at 20000 distance from origin) -- quite a bit of inaccuracy
image

After:   (at 20000 distance from origin) -- perfect 0.5 centered pixel coordinates everywhere!
image

Implementation Details:
We introduce two new global values that ShaderGraph can produce, and nodes can request, in addition to ScreenPosition.
The values are defined as:
PixelPosition                 2D pixel coordinate of the current fragment or vertex. Pixels are centered at 0.5.
NDCPosition                2D coordinate (0,1) across the viewport; equal to PixelPosition / ScreenResolution.
ScreenPosition (raw)     4D Clip Space homogenous coordinates of the current fragment or vertex.

Both PixelPosition and NDCPosition are calculated from VPOS in the fragment stage, and are calculated from ScreenPosition in other stages.

---
### Testing status

Tested in both HDRP and URP:
* Tested that Screen Position node and slots work correctly in both fragment and vertex shader.
* Validated that "Raw" mode works identically to previous, returning clip space ZW.
* Tested that the other modes return exact values in the fragment shader, based off of the VPOS value.
* Tested that VFX screen position works.

Added a Yamato test to validate screen position accuracy in fragment shader.  Previously you would have a good amount of error in the screen position from the floating point roundoff on the matrix transform calculations.  Now it gives exact pixel coordinate values out to at least 3 fractional digits.

Updated reference images.  Note that the new accuracy actually changes the test results for the dither node, because the position is slightly different (now more accurate), and the specific test we use is extremely position sensitive.

Master base branch:  34fcac461d87311010e5f868f08939208222291f

Yamato:
ShaderGraph: 🟢
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/2021.2%252Fsg%252Ffix%252F1352662/.yamato%252Fall-shadergraph.yml%2523Nightly_ShaderGraph_2021.2/9020876/job/pipeline

HDRP: 🟡 -- failures same as master
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/2021.2%252Fsg%252Ffix%252F1352662/.yamato%252Fall-hdrp.yml%2523PR_HDRP_2021.2/9018618/job/pipeline

master:
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/2021.2%252Fstaging/.yamato%252Fall-hdrp.yml%2523PR_HDRP_2021.2/8982528/job/pipeline

failures: -- same as master
HDRP on Linux_Vulkan_playmode_mono_Linear on version 2021.2 -- same 2 failures (after rerun) 🟡
HDRP on OSX_Metal_playmode_mono_Linear on version 2021.2 -- same 3 failures 🟡
HDRP on Win_Vulkan_playmode_mono_Linear on version 2021.2 -- same 2 failures 🟡
HDRP on Win_DX12_playmode_mono_Linear on version 2021.2 -- same 2 failures 🟡
HDRP on Win_DX11_playmode_XR_mono_Linear on version 2021.2 -- same 2 failures (after rerun) 🟡
HDRP on Win_DX11_playmode_mono_Linear on version 2021.2 -- same 2 failures 🟡

URP: 🟡 -- failures same as master
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/2021.2%252Fsg%252Ffix%252F1352662/.yamato%252Fall-urp.yml%2523PR_URP_2021.2/9021101/job/pipeline

master:
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/2021.2%252Fstaging/.yamato%252Fall-urp.yml%2523PR_URP_2021.2/8982696/job/pipeline

failures: -- same as master
URP_Lighting on Android_OpenGLES3_Standalone_il2cpp_Linear on version 2021.2 -- non-test-related failures on both 🟡
URP_Lighting on Win_Vulkan_Standalone_mono_Linear on version 2021.2 -- same 1 failure 🟡
URP_Terrain on OSX_Metal_playmode_mono_Linear on version 2021.2 -- green on rerun 🟢
URP_Foundation on Android_Vulkan_Standalone_il2cpp_Linear on version 2021.2 -- green on rerun 🟢

Console Tests:

Console Test PR:

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by jessebarker — APPROVED** [review]
LGTM (matches PR to master)

**Review by ellioman — APPROVED** [review]

**Review by julienf-unity — APPROVED** [review]

**Review by ernestasKupciunas — APPROVED** [review]
Approving without testing. Looks good! Developer did a great job by manually testing his changes and adding new automated tests.

**Review by PaulDemeulenaere — APPROVED** [review]
I double check the expected changes from 4f9f0c859b5f20e08c0ad168c9aa0735a2ea103f
Launching full VFX [yamato ](https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/2021.2%252Fsg%252Ffix%252F1352662/.yamato%252Fall-vfx.yml%2523VFX_2021.2/9097515/job/full-pipeline)by security but concerned job (VFX_URP) are already 🟢 
LGTM! Thanks for the backport.

**Comment by sebastienlagarde** [comment]
@cdxntchou what is the status of this PR?

**Comment by cdxntchou** [comment]
Closing this for now, the number of regressions on the change in trunk is too high

**Pull request closed without merging**
