### PR TITLE
Commiting matching changes to git from ono

### PR DESCRIPTION
**Pull request by hugobd-unity**
Commiting matching changes to git from ono PR https://ono.unity3d.com/unity/unity/pull-request/134449/_/ceng/text/input-field-refactor/staging.

---
### Purpose of this PR
This PR is a backport of https://github.com/Unity-Technologies/Graphics/pull/6179.
Corresponding [fogbugz](https://fogbugz.unity3d.com/f/cases/1385748/).

---
### Testing status
This will be manually tested by QA. (Jonathan Harlev)

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by jonathan-harlev** [comment]
Verified fix in vfx graph. Capacity value or event name no longer resets to previous value.

**Review by jonathan-harlev — APPROVED** [review]

**Comment by VitaVFX** [comment]
In VFX Graph checked reproduction. Quickly went around input fields, SG, textures, dropdowns, Subgraph Event name, Capacity various combinations with saving, compile, clicking the void space after entering/changing value. Seems good! 🟢

**Review by VitaVFX — APPROVED** [review]

**Review by julienf-unity — APPROVED** [review]

**Comment by hugobd-unity** [comment]
@julienf-unity converting from a draft PR to a PR seems to have removed all approvals. Could you approve again ?

**Comment by hugobd-unity** [comment]
@julienf-unity could you merge the PR ? I don't have the rights to do it myself.

**Pull request merged**
