### PR TITLE
Add DOTS instancing support to HDRP/LayeredLit

### PR DESCRIPTION
**Pull request by JussiKnuuttila**
Prior to this PR, HDRP/LayeredLit did not support Hybrid Renderer. This PR adds support, and defines as DOTS instanced those layer parameters for all four layers, that were already exposed for HDRP/Lit.

### Checklist for PR maker
- [x] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ]  Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)
- Other: Hybrid Renderer test project

### CODE REVIEW

**Comment by JussiKnuuttila** [comment]
The code added by this PR should be changed to conform to the new format after PR https://github.com/Unity-Technologies/Graphics/pull/1579 has landed.

**Review by sebbbi — APPROVED** [review]

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
@JussiKnuuttila : Looks like there is an error in the PR: 		Shader error in 'HDRP/LayeredLitTessellation': Unmatched #endif at Packages/com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitProperties.hlsl(475) (on vulkan)

Code change is ok, just get Yamato green and we will merge.

**Comment by sebastienlagarde** [comment]
@JussiKnuuttila , Yamato have an issue:
message: Shader error in 'HDRP/Lit': unexpected #endif at /build/output/Unity-Technologies/Graphics/com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitProperties.hlsl(474) (on d3d11)
could you check? thanks

**Comment by JussiKnuuttila** [comment]
> @JussiKnuuttila , Yamato have an issue:
> message: Shader error in 'HDRP/Lit': unexpected #endif at /build/output/Unity-Technologies/Graphics/com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitProperties.hlsl(474) (on d3d11)
> could you check? thanks

I will check and fix this. I will also add support for LayeredLitTessellation since it was requested.

**Pull request closed without merging**
