### PR TITLE
[VFX] Staging to Master

### PR DESCRIPTION
**Pull request by PaulDemeulenaere**
---
### Purpose of this PR
- Sticky note title had wrong font size while editing [(#301)](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/301) @julienamsellem 
- Vfx/fix/1365868 vcs toolbar dropdown [(#286)](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/286) @julienamsellem 
- Fix Collision & Zero scaled [(#299)](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/299) @PaulDemeulenaere 
- Fix GPU event particle init after restarting VisualEffect [(#297)](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/297) @gabrieldelacruz 
- Avoid error when using select-all shortcut to delete vfx content [(#305)](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/303) @ludovic-theobald 
- Bounds helper Edit Mode test [(#303)](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/303) @ludovic-theobald
- Force read Alive in update when use somewhere else [#302)](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/302) @ludovic-theobald 
---
### Testing status
Yamato 🟢 

---
### Comments to reviewers
N/A

### CODE REVIEW

**Review by julienf-unity — APPROVED** [review]
Ok. I just added a note in  [#302](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/302) I'm wondering if the fix could have side effects

**Comment by PaulDemeulenaere** [comment]
Awaiting for some result in Yamato before hitting the "Squash" button ⏳

**Comment by PaulDemeulenaere** [comment]
URP compilation broke on master, see this [conversation](https://unity.slack.com/archives/C89KFUUCT/p1642007490065600)

**Comment by PaulDemeulenaere** [comment]
Only Formatting failing (not related to this PR), ready to be merge 🎉

**Pull request merged**
