### PR TITLE
[GSG-1367] Fix copy paste in Blackboard

### PR DESCRIPTION
**Pull request by patrickfournier**
NEEDS https://github.cds.internal.unity3d.com/unity/unity/pull/20232 : LANDED

### Purpose of this PR

- Fix copy paste of items in the blackboard.
- Reenable blackboard tests and make them run faster
- Remove the custom code for prompt save on quit. GTF handles that.

---
### Testing status

- Reenabled and fixed tests related to blackboard (com.unity.sg2/Tests/GraphUI/BlackboardTests.cs)
- Manually copied/pasted variables in the blackboard, within a graph and across graphs.
  - Used the "Check Blackboard Sanity" menu item to check if Blackboard and CLDS contained the same information.
  - Inspected the variables in the Inspector to verify all data was copied.
  
image

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by stummy** [comment]
TestRail cases covering this:

**Review by stummy — APPROVED** [review]

**Comment by stummy** [comment]
I've taken the liberty to do some testing on my end and I've found some issues:
- When I copy/paste, cut/paste, or duplicate an exposed property, the copied property becomes unexposed
- When I cut/paste a property, the copied property gets set to the top of the Blackboard
- When using shortcuts to cut/paste (ctrl+x/ctrl+v) a property, I notice that I _sometimes_ have to press ctrl+v a few times in order to get it to paste
- Copy/paste, cut/paste, or duplicate a property with a mode (ex: Color property set to HDR mode), the copied property's mode does not persist and gets reset to default values

**Comment by patrickfournier** [comment]
Thanks @stummy 

> When I copy/paste, cut/paste, or duplicate an exposed property, the copied property becomes unexposed

Fixed

> When I cut/paste a property, the copied property gets set to the top of the Blackboard

This sometimes happen to me too. It is unrelated to my PR and could be normal, depending of the current selection I think.

> When using shortcuts to cut/paste (ctrl+x/ctrl+v) a property, I notice that I sometimes have to press ctrl+v a few times in order to get it to paste

I cannot repro this.

> Copy/paste, cut/paste, or duplicate a property with a mode (ex: Color property set to HDR mode), the copied property's mode does not persist and gets reset to default values

Fixed

**Comment by bencloward** [comment]
I am able to copy and paste blackboard items, but the items in the blackboard don't show up in the material inspector. In that in the scope of this change/fix or is that a separate bug? And my shader won't compile with this error:

**Comment by bencloward** [comment]
Looks like my issues were caused by some weird merging issues locally. After cloning the repo and trying this branch there, everything works well.

**Review by bencloward — APPROVED** [review]

**Review by stummy — APPROVED** [review]

**Comment by patrickfournier** [comment]
Obsolete due to SG2 going in a new direction.

**Pull request closed without merging**
