### PR TITLE
Fixed UI rendering issues with Universal Lit and Unlit subtargets.

### PR DESCRIPTION
**Pull request by joshua-davis**
Also updated the comment on the other Universal targets to be more clear.
This is seemingly from the order of passes changing with the addition of the picking and selection passes.

# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [x] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [x] Have you updated the changelog? Each package has a `CHANGELOG.md` file.

---
### Purpose of this PR
https://fogbugz.unity3d.com/f/cases/1352225/
UI rendering was broken in game view for the URP Sprite targets (lit, unlit, custom). This was mostly fixed back [here](https://github.com/Unity-Technologies/Graphics/pull/5344), but UniversalLit and UniversalUnlit also needed fixing. The comment was also updated on all of the sub-targets to be more clear.

---
### Testing status

Verified the test project given in the bug.

Setting both shaders to Lit:
image

Setting both shaders to Unlit:
image

Setting both shaders to SpriteLit:
image

Setting both shaders to SpriteUnlit:
image

Setting both shaders to SpriteCustomLit:
image

---
### Comments to reviewers
It seems like the addition of the Selection and Picking passes broke UI rendering in the game view. This seems to be from the order of the render passes which shouldn't be the case as passes are supposed to be by name. In order to fix this HUP quickly this change is being made.

### CODE REVIEW

**Review by jessebarker — APPROVED** [review]
LGTM

**Review by GrantLamb-Unity — APPROVED** [review]
Looks good, thanks for the updated fix!

**Review by kennytann — APPROVED** [review]

**Review by pbbastian — APPROVED** [review]
The changes should go in the URP change log, since all the changes were in that package. Other than that it all looks good :)

**Review by aleksandrasdzikia — APPROVED** [review]
Looks good. As said before, nice description :)

**Pull request merged**
