### PR TITLE
Test packages against their minimum compatible editor version

### PR DESCRIPTION
**Pull request by theopnv**
### Purpose of this PR

Not properly setting up the minimum editor requirements for the Graphics packages leads to situations where packages break with some versions of the editor.
We recently had a case where the HDRP package was broken with editor version X because it required it as the minimum compatible version but only actually worked with version Y.

This is because tests when publishing are using the latest version of the editor (eg version Z). So in that case the breakage between version X and the package was not spotted. 

This PR introduces a new test, part of the ABV: `test_all_project_[platform]_min_editor` It uses the editor version specified by the `unityRelease` field of the package.json files. This makes sure our packages are compatible with the minimum version they require, in addition to all the other tests using the latest version of trunk.

#### How it works

A new editor priming job was created. It retrieves the unityrelease from the package.json files [here](https://github.com/Unity-Technologies/Graphics/pull/1803/files#diff-026ecab52331b78ace245354bbe78a5cR35). It stores it in `tmp_unity_revision.txt`. The unity-downloader-cli command then uses it to retrieve the newest changeset associated to this revision.

---
### Testing status

**Automated Tests**: 

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/yamato%252Fproject%252Ftest-min-editor/.yamato%252F_projectcontext.yml%2523all_package_ci_project_trunk

- [Example of passing tests](https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/yamato%252Fproject%252Ftest-min-editor/.yamato%252F_projectcontext.yml%2523test_all_project_macos_min_editor/3403062/job)
- [Example of failing tests - I put 2020.2.0a5 as the minimum version and tests are using it and failing as expected](https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/yamato%252Fproject%252Ftest-min-editor/.yamato%252F_projectcontext.yml%2523test_all_project_macos_min_editor/3405358/job)

### CODE REVIEW

**Comment by sophiaaar** [comment]
to clarify, we now test packages against their min compatible version AND the latest editor version? or only min?

**Comment by theo-pnv** [comment]
> 
> 
> to clarify, we now test packages against their min compatible version AND the latest editor version? or only min?

Against both --> image

(Image taken from https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/yamato%252Fproject%252Ftest-min-editor/.yamato%252F_projectcontext.yml%2523all_package_ci_project_trunk/3403063/job/pipeline, note we're using trunk, here it's 2020.2.0b2 AND the min compatible version, here it's 2020.2.0a20.)

**Comment by sophiaaar** [comment]
> (Image taken from https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/yamato%252Fproject%252Ftest-min-editor/.yamato%252F_projectcontext.yml%2523all_package_ci_project_trunk/3403063/job/pipeline, note we're using trunk, here it's 2020.2.0b2 AND the min compatible version, here it's 2020.2.0a20.)

in this pipeline, where is the priming job for the trunk tests?

**Comment by theo-pnv** [comment]
> in this pipeline, where is the priming job for the trunk tests?

There is no priming job for the trunk tests (even on master, downloading unity is part of the Test job https://github.com/Unity-Technologies/Graphics/blob/67c4f5be2e8c00a3ea36fbc4320af09ca58b2548/.yamato/_projectcontext.yml#L268).

Before the editor pinning feature, we could have added an editor priming for these jobs, but I think it's not relevant now that the revision is pinned directly right in the Test job?

**Comment by sophiaaar** [comment]
ohhhhh yes sorry, you're right

**Review by sophiaaar — APPROVED** [review]

**Pull request merged**
