### PR TITLE
Fixed RTGI getting noisy for grazying angle geometry (case 1266462).

### PR DESCRIPTION
**Pull request by anisunity**
https://fogbugz.unity3d.com/f/cases/1266462/
### Purpose of this PR
This PR tries to improve the denoising of RTGI to get rid of high frequency noise at grazing angles. While there is no miracle solution. The changes in this PR should help reduce that artifacts.
This PR also removes the second denoiser radius that is now deduced from the first denoiser radius.

The PR should be tested extensively by the QA who reported the issue to see if this is overall an improvement.

### Testing status
The DXR tests are green after updating the screenshots.
I tested mainly on the scene that was used to report the issue and after the fix I was not able to repro the high frequency noise.

### CODE REVIEW

**Review by iM0ve — APPROVED** [review]
**Approved.**
The noisiness at grazing angles is lower, as intended. See the comparison below:

**Before:**
before

**After:**
after


I also found that with default settings the overall image is less blurry

**Before:**
before

**After:**
after

Whats tested:
* If bug case is resolved (first comparison)
* If there was a regression in RTGI quality (second comparison). The quality of GI noticeably increased not only from grazing angles.
* If there is performance regression. On custom DXR office demo project, before and after PR I had the same ~27fps, on 720p.
* Checked all Screen Space Global Illumination parameters still work

**Comment by iM0ve** [comment]
Oh since we remove a parameter. We should update the documentation?

**Review by iM0ve — CHANGES_REQUESTED** [review]
Oh since we remove a parameter. We should update the documentation? Other than that it's good.

**Review by sebastienlagarde — APPROVED** [review]

**Comment by anisunity** [comment]
Doc updated

**Review by iM0ve — APPROVED** [review]

**Pull request merged**
