### PR TITLE
Fix issues with initialization of cached area shadows

### PR DESCRIPTION
**Pull request by FrancescoC-unity**
This is a fix for https://fogbugz.unity3d.com/f/cases/1338347/ 

So the bug mentioned was fixed by another PR, but there was still an issue in that situation. The new issue just shows black area light shadows, but without any error in console. This PR fixes said issue. 

Note that while the bug in case only applies to 10.x.x without RG, there is an issue that slipped through more recent packages. 

**What did I test**: the repro case.  

**Note for backport**: this should backport trivially, but this line https://github.com/Unity-Technologies/Graphics/compare/HDRP%2Ffix-cached-area-shadows-init-params?expand=1#diff-df4fd395887dcbe1aa3489bddf28c6c3b8e6aadc100d58d1d051515d5e958184R395 won't exist in older packages. Please let me know if you want me to do an explicit backport.

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
Yes, we will need backport of it

**Comment by sebastienlagarde** [comment]
it miss a changelog

**Comment by FrancescoC-unity** [comment]
I pushed with wrong git account, the changelog is indeed me :D

**Review by TomasKiniulis — APPROVED** [review]
Looks good. Tried tweaking various shadow settings, changing update modes, adding multiple area lights on 2021.2 as well as 2020.2 with Render Graph disabled. Didn't encounter more shadow artifacts or compute shader errors.

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
will redirtect this PR to master after hd/bugfix is merge as it may require different backport

**Pull request merged**
