### PR TITLE
[10.x.x] MSAA samples count fallback descriptor fixup

### PR DESCRIPTION
**Pull request by manuele-bonanno**
### Purpose of this PR
When creating a RenderTexture descriptor, check that the requested MSAA samples count is supported by the current device. If not, assign the correct samples count fallback value to the RenderTexture descriptor. This avoids decoupling between the actual MSAA samples count the RenderTexture is created with by the engine, and the RenderTexture descriptor value in the URP code

---
### Testing status

**Manual Tests**: Tested locally on a Mali GPU which don't support 2xMSAA: when requesting 2xMSAA, the fallback to 1x (no AA) is correctly detected and the descriptor is updated. 4xMSAA and higher value are correctly supported and the descriptor values are working as expected.
- [x ] Opened test project + Run graphic tests locally
- [x ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the 
 
- Other: 
Yamato: https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/universal%252Fmsaa_fallback_descriptor_fixup

---
### Comments to reviewers

updated the Unity version in all graphics packages because of the new API SystemInfo.GetRenderTextureSupportedMSAASampleCount()
API 2020.2 PR: https://ono.unity3d.com/unity/unity/pull-request/113279/_/2020.2/graphics/manuele/render_texture_msaa_fallback_api_new

### CODE REVIEW

**Review by aleksandrasdzikia — APPROVED** [review]
Seems to be right. Tested on Meizu Pro 6 and Huawei P20 (both have Mali GPUs), when requesting with 2xMSAA, it fallbacks to 1x. With 4xMSAA it stays at == 4x.

**Review by phi-lira — APPROVED** [review]

**Comment by phi-lira** [comment]
I think in 10.x the bump is already b8

**Comment by phi-lira** [comment]
This PR needs action to merge conflicts.

**Comment by manuele-bonanno** [comment]
this is targeting the wrong branch (was created when 10.x was master, now should target 10.x.x/release). Recreating it as a backport PR since the same change landed in 11

**Pull request closed without merging**
