### PR TITLE
[10.x.x] Fix incorrect intermediate resolution when rendering to RT

### PR DESCRIPTION
**Pull request by pbbastian**
### Purpose of this PR
Fixes [case 1261287](https://issuetracker.unity3d.com/product/unity/issues/guid/1261287/). The repro project renders into slices of a render texture by modifying the `Camera.rect` property. When we then create intermediate textures in URP, we use the target texture resolution, but that doesn't account for the `rect`. This PR instead uses `Camera.pixelWidth` and `Camera.pixelHeight` when rendering to a render texture.

---
### Testing status

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally
- [x] Built a player
- [x] C# and shader warnings (supress shader cache to see them)

**Automated Tests**: We already have 119_CameraToRTWithViewportRect in UniversalGraphicsTest to test this, but the threshold was set too high to fail. I've lowered the threshold, and modified the scene to cause a bigger change when things are wrong.

The modified scene looks like this without the fix:
119_CameraToRTWithViewportRect

With the fix it looks like this:
119_CameraToRTWithViewportRect expected

**Yamato**: https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/urp%252Ffix-1261287

---
### Comments to reviewers
There is an issue with UniversalGraphicsTest on Win_DX11_playmode_XR that I am not sure what is caused by.

### CODE REVIEW

**Comment by thomas-zeng** [comment]
Adding DennisD from XR QA to verify the PR.
This is a low risk PR from XR dev perspective and it should not impact real XR use case. Please test this for regression. 
What I have tested:
Template scene with mock/WMR+ Run yamato ABV in XR mode

**Review by thomas-zeng — APPROVED** [review]

**Comment by pbbastian** [comment]
Regarding CI failures:
* There are no changes to HDRP in this PR, so ignore that
* The Universal error is due to an unrelated bug that also exists on `master` (`NullReferenceException`)
* The VFX_URP error is due to the VFX sphere texture having compression turned on, and the intermediate render resolution now being smaller, but correct, so it now more clearly shows the compression. I'm going to update the reference image for this.

**Comment by pbbastian** [comment]
Adding @Unity-Technologies/gfx-qa-vfx due to updating of the said test image.

**Comment by phi-lira** [comment]
@pbbastian please fix merge conflicts.

**Review by DennisDeRykeUnity — APPROVED** [review]
In the most recent SRP ABV (per link below) the only XR-specific failure I see is "HDRP_Hybrid on Win_DX11_playmode_XR".  However, both this pipeline and its non-XR equivalent failed due to something beyond the tests; no tests ran for either pipeline, probably a problem with Yamato.  I re-launched both of these pipelines today and they passed.  

Stereo Universal and stereo Shader Graph tests are also green.  

https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/urp%252Ffix-1261287/.yamato%252F_abv.yml%2523all_project_ci_fast-trunk/3356244/job/pipeline

Using the following configuration, blurriness does not occur when following the repro steps for case 1261287.  Also I see no obvious regressions when viewing the URP Template scene in Play mode on Quest in Link mode.

- Unity (trunk 6f56d84adaf2)
- URP (urp/fix-1261287 693576f)

I approve on behalf of XR QA, though the appropriate Graphics QA staff should also have the opportunity to review this.

**Review by VladNeykov — APPROVED** [review]
Checked on the VFX side and ran the extended FTP coverage, besides the **009_MultiCamera** test scene from the main vfx graphics tests, there doesn't seem to be any other overlap of this PR and the VFX graph.

**Review by ellioman — APPROVED** [review]
Looks good.

**Comment by pbbastian** [comment]
CI status ✔️ 
- Only HDRP things are failing due to a timeout, and I have no changes to anything HDRP.

**Pull request merged**
