### PR TITLE
[Fogbugz 1324000] Fixing unlit emissive reflections

### PR DESCRIPTION
**Pull request by kecho**
### Purpose of this PR
Fixing fogbugs: https://fogbugz.unity3d.com/f/cases/1324000/
Unlit emissive was too dark, because there was a missing pre exposure multiplication.

Repro steps : 
- Open attached project
- Open SampleScene_Exposure0
- Notice that both lit and unlit ray traced reflection looked similar
- Now open SampleScene_Exposure_12
- It's the same scene with fixed exposure of 12, HDRI sky exposed to 12 and higher intensity dir light

Expected : Same result as the non exposed scene
Result : Unlit emissive is black. 

Before:
image

After:
image

---
### Testing status
* Tested with many levels of exposure in the unlit material, and now the material behaves correctly.
* Tested on PC with auto exposure and several fixed exposure values.
* Running all platforms tests (DXR and standard). Likely we might need screenshot update.

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
@remi-chapelain can you ensure this is cover in one of our test. Also guess we need to check for both unlit with emissive and lit with emissive.

**Comment by sebastienlagarde** [comment]
@kecho in your test, is your mesh emissive only or does it have a color + emissive contribution? (we should check the later if not check)

**Comment by kecho** [comment]
> @kecho in your test, is your mesh emissive only or does it have a color + emissive contribution? (we should check the later if not check)

My test is emissive only, black color. I did test with color as well and looked correct.

**Comment by remi-chapelain** [comment]
I'll add a test in DXR Test project in this PR as stated in the bug and take care of screenshots if some needs updating.

**Review by sebastienlagarde — APPROVED** [review]

**Review by remi-chapelain — APPROVED** [review]
Verified the fix quickly. 

Added 4 tests to cover reflections of emissive
- Low exposure perf mode
- high exposure perf mode
- Low exposure quality mode
- high exposure quality mode

108_ReflectionEmissive_Perf_Exposure_0

108_ReflectionEmissive_Quality_Exposure_0

High and low exposure look the same because the value of emissive and sun are adjusted accordingly. Only noticeable difference is the reflection resolution in performance vs quality; 

Ran all DXR Tests locally (All 🟢, which proved we didn't have proper coverage for this) since yamato is overloaded, I'd say we're good to merge without testing on yamato

**Pull request merged**
