### PR TITLE
Lighting/templates hdrp realtimegi

### PR DESCRIPTION
**Pull request by DavidLlewelyn**
### Purpose of this PR
This PR is a substantial change to the authoring of the HDRP template Scene. The primary reason for the work was to add Enlighten Realtime GI compatibility to the Scene. 

Note: "Compatibility", not a complete optimization as this would invalidate some of the Scene setup for Baked GI. The intent is simply that the user can now change the GI backed to "Realtime GI" and the Scene will behave elegantly, with fairly optimal bakes.

Additionally I have:

- Optimized all Lighting Settings Assets to better suite their intents (fast iteration through to better quality)
- Remodeled some questionable meshes from the original asset drop. These were causing Enlighten to fail
- Taken advantage of HDRP's Static Shadow Caster where appropriate for faster shadowmap generation
- Create optimal hand-authored UVs for all static meshes. These give ideal results in Enlighten, and improve import times
- Added a RealtimeGI Lighting Settings Asset for users to experiment with, if needed
- Fixed various baked lighting issues in the original Scene, such as the notable seam in the first room

image
image
image

---
### Testing status
I have manually played through the Scene to verify that no lighting issues have been introduced to the Baked GI, as well as verified the lighting when the backend is swapped to Enlighten. I have also played-through and checked all collision meshes and input scripts.

---
### Comments to reviewers

In order to see the Realtime GI as expected, the directional light will need to be changed to mode "Realtime". This is expected when using Enlighten.

Please could you ensure that the Scene plays-though as expected from the original. Please feel free to test the various new Lighting Settings Assets, but note that only "High" and "Ultra" will give shippable results. 

Known issues: The final room has an emissive material configured for BakedGI by default. Because of the way that the GI pathing works in the UI, it therefore cannot also support Realtime GI. Changing the backend to RealtimeGI means that the final room will be darker than expected until the user swaps the mesh TR_CurveWall_01_BakedGI_LOD0 to TR_CurveWall_01_RealtimeGI_LOD0. 

This is manual setup for the user, but should be considered unnecessary. To reiterate the above, the intention for this PR is just to stop the editor from behaving unexpectedly when changing the backend type from BakedGI to Realtime GI.

### CODE REVIEW

**Review by iM0ve — CHANGES_REQUESTED** [review]
**Testing status: In progress**

**Whats tested:**
* Generally close inspection of areas of the project to find unexpected changes
* Compared the new PR vs stock 12.0.0 template
* Compared the new PR to Path traced results
* Bake (todo)
* Try enlighten (todo)

**Issues:**
1) **Fixed** One reflection probe has incorrect data. Need to clear GI cache and rebake the probe

Capture

2) **Fixed** Reflection probe is too dark compared to master.

https://user-images.githubusercontent.com/36502659/121190154-71255b80-c873-11eb-9137-4bdd48f580af.mp4

3)  **Fixed** New path tracing issues, likely due to the 1st room model change

https://user-images.githubusercontent.com/36502659/121190538-d5481f80-c873-11eb-9dd0-67ecd619a21e.mp4

4) Baked reflection probes wont capture decals and provide brighter results than expected. Not this PRs fault but affecting the baked data of the PR (incorrect bake).

https://user-images.githubusercontent.com/36502659/121335370-30851b00-c923-11eb-8367-f38e7fc16f64.mp4



Unrelated issues found:
https://fogbugz.unity3d.com/f/cases/1341990/

**Review by iM0ve — APPROVED** [review]
Updated my review. All issues fixed, good to go :)

**Review by radishface — APPROVED** [review]
Finished reviewing the following revision: 24e037e
Reviewed using: 2021.2.0a20

The most glaring issue is Mixed lights not contributing to realtime GI. This was initially observed by @iM0ve. An issue was logged here: https://fogbugz.unity3d.com/f/cases/1313737

Please note that the issue mentioned previously was not introduced by this branch.

No other issues were found. Approving.

**Comment by sebastienlagarde** [comment]
All good, merging the Pr

**Review by sebastienlagarde — APPROVED** [review]

**Pull request merged**
