### PR TITLE
7.x.x/backport/terrain opacity blend

### PR DESCRIPTION
**Pull request by spaceburp**
### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [x] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [x] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [x] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?
Backport for case 1283124. Parent PR https://github.com/Unity-Technologies/Graphics/pull/3083

---
### Testing status
Describe what manual/automated tests were performed for this PR
- Manually tested painting and verifying that artifacts previously seen have been removed
- Manually tested 2 - 4 layer blending with different layers with different Opacity as Density states
- Manually tested +4 layer blending and verified that density blending is disabled with >4 Terrain Layers
- Manually tested Heightbased Blending feature for < 4 layers to make sure nothing broke there
- Ran automated tests, specifically the one that was originally failing and made us aware of this issue in the first place: 038_Terrain_Blend
- Created automated test for Opacity as Density blend with < 4 layers

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by phi-lira** [comment]
While looking for PRs that need backport to 7.x I discovered this PR. Do you still plan to land it?

**Comment by spaceburp** [comment]
> While looking for PRs that need backport to 7.x I discovered this PR. Do you still plan to land it?

ya. i'll be working on landing it

**Comment by spaceburp** [comment]
tests green now. should be ready to merge

**Review by erikabar — APPROVED** [review]
Developer already tested, approving

**Comment by LandonTownsendUnity** [comment]
image
bug is still reproducing for me

**Review by phi-lira — APPROVED** [review]

**Review by ghost — APPROVED** [review]
This works as a partial fix as it fixes the problem close up; however the problem still exists on the basemap and this needs to be fixed separately

**Pull request merged**
