### PR TITLE
[10.x.x] Universal/bugfix/overlay camera requires depth

### PR DESCRIPTION
**Pull request by Jonasmortensen**
# Purpose of this PR
Fixes issue with overlay cameras breaking soft particles if camera anti aliasing was set to subpixel morphological. [case 1241626](https://issuetracker.unity3d.com/product/unity/issues/guid/1241626/)

# Testing status

**Manual Tests**: 
- [x] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)

**Automated Tests**: 
Added automated test 145 which renders particles shooting through a cube. The particles have a soft particle material and should be fading when intersecting the cube as can been seen in the reference image:

# Yamato
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/universal%252Fbugfix%252Foverlay-camera-requires-depth

# Comments to reviewers
The fix was to reorder some code that sets cameraData.requiresDepthTexture based on post processing and whether the camera is render type Overlay.

### CODE REVIEW

**Review by ellioman — COMMENTED** [review]
Looks fine but I'd like to get QA to test this change with our test projects to make sure everything works as it should.

Also, run Android GLES3 & Vulkan, iPhone and DX12 tests on Yamato to make sure we don't break nightly because of incorrect reference images.

**Review by simon-engelbrecht-soerensen — APPROVED** [review]
Works as intended.
Have not found any issues with boat attack/polygon farm.
But as Elvar said, checking that it runs on the outlier platforms is probably a good idea 👍

**Review by ellioman — APPROVED** [review]
Looks good.But we'll need to wait until 10.1 comes out and fix the changelog as this won't be in the 10.1 package release.

**Comment by thomas-zeng** [comment]
Looked into the PR and PR looks good. The failed XR test catches an XR issue related to camera stacking. Please turn off the XR compat bit for this test. XR team work on next PR to fix the XR issue and re-enabled the test. Thanks!
image

**Review by thomas-zeng — APPROVED** [review]

**Comment by phi-lira** [comment]
ABV was passing before merging master. Only HDRP tests were failing which are unrelated to this PR.

**Pull request merged**
