### PR TITLE
[7.x.x][case 1251402] Fixed an issue where gamma correction was being applied twice for Google VR on iOS devices when FXAA was enabled

### PR DESCRIPTION
**Pull request by todds-unity**
### Purpose of this PR
Fixed an issue where gamma correction was being applied twice for Google VR on iOS devices when FXAA was enabled. [case 1251402](https://issuetracker.unity3d.com/issues/metal-urp-ios-google-vr-ios-white-filter-appears-when-using-fxaa-plus-post-processing-plus-single-pass-stereo-rendering-mode)

### Testing status
Manually tested the change on local mobile devices.

### CODE REVIEW

**Comment by thomas-zeng** [comment]
Note: the linear colorspace check is already landed in master in https://github.com/Unity-Technologies/Graphics/pull/22

**Review by thomas-zeng — APPROVED** [review]
LGTM. Thanks!

**Review by DiannaUnity — APPROVED** [review]
Version 2019.4.8f1 (60781d942082)
Wed, 05 Aug 2020 14:08:36 GMT
Branch: 2019.4/staging

Before fix; the sky and ground is lighter, skybox looks more grey
image



After fix; the scene becomes darker and matches the scene viewer
image

Confirmed that the fix works on iPhone XS.

**Comment by phi-lira** [comment]
@todds-unity where is the PR to master? we need to land it on master first then backport to other versions.

**Comment by phi-lira** [comment]
Updated on this PR?

**Review by eh-unity — APPROVED** [review]
Looks like this is entirely contained in XR-side (under defines). LGTM.

**Pull request closed without merging**
