### PR TITLE
[HDRP] Revert cookie field area light

### PR DESCRIPTION
**Pull request by alelievr**
### Purpose of this PR
Revert https://github.com/Unity-Technologies/Graphics/pull/5885 due to drag and drop bug in the new cookie field

Please note that this issue is also in the 2022.1 release.

---
### Testing status

Created an area light and dropped a 2D texture in the cookie field
image

### CODE REVIEW

**Review by RemyUnity — APPROVED** [review]
lgtm

**Review by alex-vazquez — APPROVED** [review]
Thanks!

**Comment by adrien-de-tocqueville** [comment]
Hey, i have a fogbug related to that, i was about to make a trunk PR to fix it, should i cancel ?

**Review by martint-unity — APPROVED** [review]
LGTM

**Comment by adrien-de-tocqueville** [comment]
I have made the trunk PR to fix the root issue, it is interesting to backport this one, but I don't  think it's needed for master
https://github.cds.internal.unity3d.com/unity/unity/pull/6711

**Comment by sebastienlagarde** [comment]
close as it will be fix by C++ PR of Adrien https://github.cds.internal.unity3d.com/unity/unity/pull/6711

**Pull request closed without merging**
