### PR TITLE
Enable iOS URP tests

### PR DESCRIPTION
**Pull request by tomzig16**
### Purpose of this PR
This PR enables URP tests for iOS. Yamato will have an additional option to run iPhone_Metal tests.
I have filtered out around 15 iOS tests that were blocking us, but every disabled test is tracked and I am working with Liutauras on fixing them. 
Result correctness was compared with other platforms. Main references are Android, D3D11 standalone (playmode) and OSX Metal (playmode)

---
### Testing status

**Manual Tests**:
- Ran tests locally
- Yamato tests

**Automated Tests**: 
Yamato iPhone tests

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/ios%252Ftomaszi%252Fenable-urp-tests

Any test projects to go with this to help reviewers?
This PR adds iPhone_Metal option to yamato. It uses the same UniversalGraphicsTests project

---
### Comments to reviewers
This PR enables iOS in nightly

### CODE REVIEW

**Comment by sophiaaar** [comment]
awesome. is there a reason for not including ios in the nightly yet?

**Comment by tomzig16** [comment]
> awesome. is there a reason for not including ios in the nightly yet?

Yes, unfortunately we do not have enough hardware at the time of making this PR. Bokken team is doing some testing + adding more devices so they left us only 3 iOS devices for now. However, they promised to enable 20 iOS devices soon, which will be more than enough for nightly and probably ABV but because of limited physical access to the datacenter (due to pandemic) no concrete ETA was given. 
I am keeping my eye on device availability + I am in a close contact with the team, so as soon as devices are ready I will be pushing it to nightly :)

**Comment by sophiaaar** [comment]
cc @kivistikliis for awareness

**Comment by tomzig16** [comment]
> Any idea what's canceling the task on the iOS metal pipeline? We should get the pipeline running smoothly before trying to land this [Broken test run link](https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/ios%252Ftomaszi%252Fenable-urp-tests/.yamato%252Fupm-ci-universal.yml%2523Universal_iPhone_Metal_fast-trunk/2039098/job/(log:Execution))

No idea. I am investigating that right now. The only thing I am sure about is that it comes from the bokken side. Same commit a night before was successful: https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/ios%252Ftomaszi%252Fenable-urp-tests/.yamato%252Fupm-ci-universal.yml%2523Universal_iPhone_Metal_fast-trunk/2026605/job

**Comment by tomzig16** [comment]
iOS builds are green again. cc @sophiaaar @JessAtUnity 
Although I saw several failures on Android side on newest master as there were new tests added. I will merge master here too and see how those new tests behave on iOS.

**Comment by tomzig16** [comment]
Adding comment here for visibility - latest commit added iOS tests to the nightly

**Pull request merged**
