### PR TITLE
Universal/implement camera extension

### PR DESCRIPTION
**Pull request by RSlysz**
### Purpose of this PR
Use the Camera extension mechanism and deprecate the UniversalAdditionalCameraData.

**This currently require custom build** based on ono branch graphics/camera-extensible-by-interface-list
This branch will become a PR soon. For now, we want to be sure all works fine on Universal side.

image

The legacy UniversalAdditionalCameraData is kept but tagged obsolete. Every public property/method redirect on the extension. This is to keep user script working while they have not fixed their code to directly use the extension.

---
### Testing status

**Current Graphic Tests status:**
Everything is green except 5 tests using the Camera Stacking. For thoses, it is required to save the scene after the data have migrated prior launching the test for it to be green. Same goes if you load thoses scene. Only the base camera is displayed unless you enter play mode. This need to be debugged before this PR land.
*It seams to be caused because for some reason the base camera have awakened and thus migrated. But the layer camera have not migrated yet when entering the RenderCameraStack*

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [x] C# and shader warnings (supress shader cache to see them)

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

**Yamato**:
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/universal%252Fimplement-camera-extension/.yamato%252Fall-universal.yml%2523All_Universal_CUSTOM-REVISION/2821737/job

---
### Comments to reviewers
Currently, there is a breaking error in GraphicTest project:
`Library\PackageCache\com.unity.xr.legacyinputhelpers@2.1.4\Editor\MenuUtils.cs(120,93): error CS0618: 'UniversalAdditionalCameraData' is obsolete: 'Use UniversalCameraExtension instead.'`
This is due to changing UniversalAdditionalCameraData to obsolete now that it is not needed anymore. But com.unity.xr.legacyinputhelpers reference it and this create a warnings. As it is a dependency at some point in the UniversalGraphicTest, the warning appears. But as all warnings here, it is converted to a persistent error that prevent launching the test runner.
So for now, just comment the obsolete attribute on this class if you want to test.

**Compatible with tip (53f91790eb60) of C++ branch.**

### CODE REVIEW

**Comment by martint-unity** [comment]
Is this PR still valid? or have there been many more changes lately? @RSlysz

**Comment by RSlysz** [comment]
@martint-unity It is still valide. I fixed friday the last known serialization issue in Unity. No change needed on this side. Now all graphic test are green, even the Camera stacking one.

Though the C++ PR activating the extension will wait a little more as we need to add some more authoring requirement. Other than this, the work for URP is pretty finished.

**Comment by phi-lira** [comment]
What's the status update on this PR?

**Comment by RSlysz** [comment]
At time it was done, Yamato remained green for URP. Though, it should be redone later, the same way, as at the moment trunk is still not ready.

As I got absolutely no feedback from URP side and the change are what we should still do, I'm still open to any feedback :)

**Review by phi-lira — CHANGES_REQUESTED** [review]
This PR is old and have lots of conflicts. Please re-request review when ready to be reviewed.

**Comment by Nzollner** [comment]
@martint-unity and I looked through the PR.

Here are some comments:
* The new variables using the class ```UniversalCameraExstension``` should not use the old names such as ```additionalCameraData``` which were previously used for the ```UniversalAdditionalCameraData``` class.
* For the ```UniversalAdditionalCameraData``` obsolete description instead of "Keeped for migration only, use UniversalCameraExtension" we would prefer "For migration only, use UniversalCameraExtension".
* We would also like to split the ```UniversalCameraExstension``` class into a new file called UniversalCameraExstension.cs.
* Wo would prefer to use an upgrader for migration instead of an awake function which will give the user more control.

Here are some questions:
* Why doesn't the ```UniversalCameraExstension``` contain ```DisallowMultipleComponent```, is it because it is defined in the base class?
* What is ```UniversalCameraExstension```'s member variable ```Version``` used for?
* What is ```camerahandler``` used at L. 226 in UniversalAdditionalCameraData.cs?
* What is the reason for the undo action when migrating from ```UniversalAdditionalCameraDatav to ```UniversalCameraExstension```? We thought it could confuse the user if no clear interaction from the user causes the migration of the data with added undo actions. This will leave the user with undo actions that the user doesn't know about.
* Why is the ```UniversalRenderPipelineCameraEditor``` class no longer using ```CustomEditorForRenderPipeline``` attribute but instead the CustomEditor attribute?
* Why are calls such as ```OnEnable``` changed to protected instead of public?

**Comment by RSlysz** [comment]
Thanks a lot for the allotted time folks! I really appreciate it.
I agree with your remarks and will take them into acount while redoing this PR in near future onto latest version of URP.

Here is some clarification:

> Wo would prefer to use an upgrader for migration instead of an awake function which will give the user more control.

Can you provide an exemple of that? I am not sure to see exactly what you want. (I am open to suggestion)
If you talk about APIUpgrader that is put into the attribute, I need to check if this is possible this way. I was not aware of this at time when I wrote this and it is limited in some cases. Let me figure out if I can do better. Nice point.
In HD side, we have such an upgrade system so it was logical to use it. But I'm not sure you need it on Universal. I hope Serialization team will be able to deliver a nice framework at some point to migrate everything.

> Why doesn't the UniversalCameraExstension contain DisallowMultipleComponent, is it because it is defined in the base class?

This attribute only affects MonoBehaviour. Camera.Extension per design cannot be multiple of same type onto the Camera so only one or no UniversalCameraExstension, only one or no HDCameraExtension.

> What is UniversalCameraExstension's member variable Version used for?

This was to prepare potential pugrade later. I was not fully aware of what system do you use to upgrade a component. I'm open to suggestion.

> What is camerahandler used at L. 226 in UniversalAdditionalCameraData.cs?

camerahandler is a property available on each Camera.Extension to access the Camera which this Extension is onto. 

> What is the reason for the undo action when migrating from UniversalAdditionalCameraDatav to UniversalCameraExstension```? We thought it could confuse the user if no clear interaction from the user causes the migration of the data with added undo actions. This will leave the user with undo actions that the user doesn't know about.

I don't see any change with Undo in what I have done. Can you point me out where this is? AFAIK I should not have to deal with undo anywhere while migrating data...

> Why is the UniversalRenderPipelineCameraEditor class no longer using CustomEditorForRenderPipeline attribute but instead the CustomEditor attribute?

This is part of the changes done with the refactor. This will be used each time you want do display the Inspector for the UniversalRenderPipeline. With the way it is done in the refactor, the editor is based on CameraEditor.ExtensionEditor and don't target a MonoBehaviour anymore. There is no point to filter on RenderPipeline as we can want to display Universal information when in HD for a multi pipeline project. So I modified the [CustomEditor] to be applicable to the CameraEditor.ExtensionEditor child types and there is at top of the component a Selector that allow user to chose which Extension to modify.

Here is a screenshot on the figma design discussed with UX 
image
Changing the selector will let user display the inspector of another extension in multiple pipeline project.

All resources on the refactor are in this document and links into it https://docs.google.com/document/d/1VaNrpqdcneiAEaOLPDFxSN35oZH5kfSeIkynY_6QGvg/edit?usp=sharing

> Why are calls such as OnEnable changed to protected instead of public?

As we are not on a standard Editor, they are grabbed using inheritance onto the base class.
Lifecycle hooks for the Runtime part is done as for MonoBehaviour but in the Editor it was more complex to achieve and using inheritance was fitting in this case. And we want to be able to call OnEnable/OnDisable when switching from one active Extension to another one (changing the selector). This is handled onto the CameraEditor in trunk and was less costly this way. The other way to do that is to go back onto the C++ level when switching pipeline to grab hooks in the method cache that will call them onto the C# side, so 2 more transfer between C++ and C#. I believe inheritance is best solution here.

**Comment by Nzollner** [comment]
Thank you for the answers.

The undo action is located at: L. 714 in UniversalAdditionalCameraData.cs.

And an example on what I mean by and upgrader can be seen at L. 1064 in UniversalRenderPipelineAsset.cs using the ```OnAfterDeserialize``` instead of awake. This also include how versioning is handled in ```UniversalRenderPipelineAsset```.

**Comment by RSlysz** [comment]
> The undo action is located at: L. 714 in UniversalAdditionalCameraData.cs.

This was an attempt to let user in control but We don't do it in HDRP usually. I can remove the undo part, sure.

> And an example on what I mean by and upgrader can be seen at L. 1064 in UniversalRenderPipelineAsset.cs using the OnAfterDeserialize instead of awake. This also include how versioning is handled in UniversalRenderPipelineAsset.

Ok the upgrader is not actually an entity or a framework existing it is just the upgrading code right? In HDRP, there is a small migration framework that you can find for instance in [here](https://github.com/Unity-Technologies/Graphics/blob/master/com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Camera/HDAdditionalCameraData.Migration.cs) if you are curious.

OnAfterDeserialize() can only be used to modify data into your container (MonoBehaviour). Here we are moving data from it to outside it. We cannot use this lifecycle hook to do so. We can do it in Awake() because as there is a [RequiredComponent(typeof(Camera))] onto the UniversalAdditionalCameraData, we are sure the camera comes sooner in the sibling list so it is loaded when we do the Awake of the UniversalAdditionalCameraData. It is the sooner available hook point to do the migration (AFAIK).

**Comment by RSlysz** [comment]
By the way @martint-unity @Nzollner , If I remember well, we should not use EditorApplication.delayCall inside OnAfterDeserialize (as done in UniversalRenderPipelineAsset). Check with Serialization team but I'm pretty sure this is not good.

**Comment by RSlysz** [comment]
This PR need to be redone on tip of Master.

**Comment by RSlysz** [comment]
Don't delete the branche. I'll need the commit to port it on Master. I'll delete it once done.

**Pull request closed without merging**
