### PR TITLE
Fixed an error message trigerred when a mesh has more than 32 sub-meshes (case 1274508).

### PR DESCRIPTION
**Pull request by anisunity**
https://fogbugz.unity3d.com/f/cases/1274508/

If the mesh has more than 32 submeshes, the default flags are used for 33+ and all meshes will be included in ray tracing, but no more exceptions in the console. 32+ submeshes is a bad pattern anyway.

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]

**Comment by remi-chapelain** [comment]
To clarify the description, if you have a mesh with more than 32 submeshes, some parameters (like double sided, alpha clipping threshold) are not guaranteed to be passed to RTX effects for **ALL submeshes** materials in the mesh, not only the submeshes that have an index > 31. 

While this PR prevent from throwing an error, I don't really like the fact that now it is silently failing and there's no indications that you broke a limit and nothing to explain the inconsistencies of some materials parameters not being passed to RTX effects. 

Since we can't really spam the console at runtime with a warning, one solution @anisunity proposed would be to integrate a check in the process "check for RTX errors" render pipeline menu to display ONE warning if the number of submeshes is > 32 in the scene ?

**Review by remi-chapelain — COMMENTED** [review]
To clarify the description, if you have a mesh with more than 32 submeshes, some parameters (like double sided, alpha clipping threshold) are not guaranteed to be passed to RTX effects for ALL submeshes materials in the mesh, not only the submeshes that have an index > 31.

While this PR prevent from throwing an error, I don't really like the fact that now it is silently failing and there's no indications that you broke a limit and nothing to explain the inconsistencies of some materials parameters not being passed to RTX effects.

Since we can't really spam the console at runtime with a warning, one solution @anisunity proposed would be to integrate a check in the process "check for RTX errors" render pipeline menu to display ONE warning if the number of submeshes is > 32 in the scene ?

**Comment by anisunity** [comment]
i'll add the warning when running the check

**Comment by anisunity** [comment]
Added the warning message

**Pull request merged**
