### PR TITLE
Add initial PS5 support to the Graphics Repo

### PR DESCRIPTION
**Pull request by robinb-u3d**
### Purpose of this PR
This PR adds support for the PlayStation 5 Platform to the packages in the Graphics Repo. 

---
### Testing status
- Local testing on PS5 with the HDRP template project.

- BLOCKED - Engine bug fix required before landing this.

---
### Comments to reviewers
@sambickley can you run this through the PS5 and report test status back here to give us an up to date testing report.

### CODE REVIEW

**Comment by robinb-u3d** [comment]
com.unity.postprocessing may need extra care as at the moment this will break on Unity versions that do not have PS5 support due to the build target enums not being available. I suspect the best approach here will be to #if check the Unity version and then downgrade the version as support lands.

**Review by Chman — APPROVED** [review]

**Comment by robinb-u3d** [comment]
This requires a fix on the engine side to stop other platforms trying to include the PS5 header and failing.

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
@sambickley any update on this one?
@robinb-u3d : what does it mean: BLOCKED - Engine bug fix required before landing this. ?

**Comment by robinb-u3d** [comment]
Closing PR till the new year as it needs some engine fixes and a full test pass that will now not get done till then before we can look at getting this merged in.

**Pull request closed without merging**
