### PR TITLE
Fix VT Feedback buffer

### PR DESCRIPTION
**Pull request by zeroyao**
# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [x] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [x] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- ~[ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).~ No documentation change is necessary.
- ~[ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.~ Adding a graphics test for checking the VT feedback buffer might be possible, but is difficult to do. For the scope of this PR it doesn't feel necessary.

---
### Purpose of this PR
Fix VT feedback buffer values by correctly initialize BuiltinData.vtPackedFeedback to (1,1,1,1) for cases either InitBuiltinData function is called or ZERO_INITIALIZE. Fix for ShaderGraph too.

Previously the value is zero initialized which actually is a valid tile ID ({0,0,0} for tileset 0). Correcting it is important for the underlying VT code to correctly prioritize tile requests coming from manually managed procedural VT stacks.

---
### Testing status
Manually tested with SG shaders and HDRP Lit shader, in HDRP Test project plus the Environment test project.

### CODE REVIEW

**Comment by zeroyao** [comment]
@sebastienlagarde Hello! What is the current process for backporting PRs? Will your team pick it up or should I do it myself? I need to backport all the way to 8.0.0 as this version is used by 2020.3 editor. I don't see a backport label for 8.0 though?

**Review by debaetsd — COMMENTED** [review]
LGTM

**Review by GraphineCharles — APPROVED** [review]
Good for the VT change of 0,0,0,0 to 1,1,1,1.  Difficult for me to judge if the changes will catch all situations where the struct is initialized by hdrp.

**Comment by zeroyao** [comment]
> Good for the VT change of 0,0,0,0 to 1,1,1,1. Difficult for me to judge if the changes will catch all situations where the struct is initialized by hdrp.

Yup that was the majority of the effort to find out all the places. It's really hard to centralize as there are different situations this struct is used. And I guess not really future proof. Having a graphics tests that checks out what's being written to the VT feedback buffer sounds unviable either as you'll basically need to have all shaders now and future in the test. Just adding the initialization code probably is the best we can do now. Hopefully there is little chance in the future that a new handwritten shader will be added to HDRP, so that for the majority of the situations SG coverage is good enough.

**Review by cdxntchou — APPROVED** [review]
Looks good!

**Review by jonaskhalil — APPROVED** [review]
Nothing to add, looks okay for as far as I can tell ...

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
Note to self: Require C++ PR landed in 21.2 and 21.1.
For 20.3: https://ono.unity3d.com/unity/unity/pull-request/128235/_/2020.3/graphics/granite/env-improvements

**Pull request merged**
