### PR TITLE
[VFX] SDF Baker + bounds helper tool

### PR DESCRIPTION
**Pull request by julienf-unity**
### Purpose of this PR
- New tool to help set VFX Bounds https://jira.unity3d.com/browse/GVFXG-18
- New tool : Signed Distance Field baker. https://jira.unity3d.com/browse/GVFXG-60

---
### Testing status
QA pass + GFX tests for both features

### CODE REVIEW

**Review by VladNeykov — APPROVED** [review]
SDF Baker [QA pass](https://docs.google.com/document/d/1GYAzBy8zk4feoahSzt7PdM5w2HP6VSjaJypVNk_oen4/edit#)
Bounds Helper [QA pass](https://docs.google.com/document/d/1M2zV7tgx7Yz3NAW9NVR8oZCFaFzOcrnRzolc1hnq0VA/edit)

**Comment by PaulDemeulenaere** [comment]
For reference :
- Bound helper PR : https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/201
- SDK Bake PR : https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/186
I'm checking there isn't any unexpected change

Also, running nightly VFX on Yamato :
- HDRP : https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/vfx%252Fstaging/.yamato%252Fall-vfx_hdrp.yml%2523Nightly_VFX_HDRP_trunk/6774996/job
- URP : https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/vfx%252Fstaging/.yamato%252Fall-vfx_urp.yml%2523Nightly_VFX_URP_trunk/6775003/job

About internal status, everything is 🔴 (due to unrelated changes) : https://yamato.cds.internal.unity3d.com/jobs/339-ScriptableRenderPipelinePrivate/tree/master/.yamato%252Fall-vfx_urp.yml%2523PR_VFX_URP_trunk/6772371/job/pipeline
We will have to update several screenshot anyway.

**Comment by PaulDemeulenaere** [comment]
There is missing documentation : 
```
The following APIs are missing documentation: Missing Doc on UnityEditor.VFX.BoundsSettingMode
Missing Doc on UnityEditor.VFX.BoundsSettingMode.Recorded
Missing Doc on UnityEditor.VFX.BoundsSettingMode.Manual
Missing Doc on UnityEditor.VFX.BoundsSettingMode.Automatic
Missing Doc on UnityEditor.SdfBakerPreview
Missing Doc on UnityEditor.SdfBakerPreview.mesh
Missing Doc on UnityEditor.SdfBakerPreview.sizeBoxReference
Missing Doc on UnityEditor.SdfBakerPreview.actualSizeBox
Missing Doc on UnityEditor.SdfBakerPreview.centerBox
Missing Doc on UnityEditor.SdfBakerPreview.orthographic
Missing Doc on System.Void UnityEditor.SdfBakerPreview::.ctor(Mesh)
Missing Doc on System.Void UnityEditor.SdfBakerPreview::Dispose()
Missing Doc on System.Void UnityEditor.SdfBakerPreview::OnPreviewGUI(Rect, GUIStyle)
Missing Doc on System.Void UnityEditor.SdfBakerPreview::OnPreviewSettings()
Missing Doc on static System.String UnityEditor.SdfBakerPreview::GetInfoString(Mesh)
Missing Doc on UnityEditor.Experimental.VFX.SDF.PreviewChoice
Missing Doc on UnityEditor.Experimental.VFX.SDF.PreviewChoice.None
Missing Doc on UnityEditor.Experimental.VFX.SDF.PreviewChoice.Mesh
Missing Doc on UnityEditor.Experimental.VFX.SDF.PreviewChoice.Texture
Missing Doc on UnityEditor.Experimental.VFX.SDF.PreviewChoice.MeshAndTexture
Missing Doc on UnityEditor.Experimental.VFX.SDF.ModelSource
Missing Doc on UnityEditor.Experimental.VFX.SDF.ModelSource.Mesh
Missing Doc on UnityEditor.Experimental.VFX.SDF.ModelSource.MeshPrefab
Missing Doc on SdfBakerSettingsEditor
Missing Doc on System.Void SdfBakerSettingsEditor::OnInspectorGUI()
Missing Doc on UnityEditor.Experimental.VFX.SDF.SDFBakeTool
Missing Doc on System.Void UnityEditor.Experimental.VFX.SDF.SDFBakeTool::OnGUI()
Missing Doc on System.Void UnityEditor.Experimental.VFX.SDF.SDFBakeTool::OnEnable()
Missing Doc on System.Void UnityEditor.Experimental.VFX.SDF.SDFBakeTool::OnDisable()
Missing Doc on System.Void UnityEditor.Experimental.VFX.SDF.SDFBakeTool::FitBoxToMesh()
Missing Doc on System.Void UnityEditor.Experimental.VFX.SDF.SDFBakeTool::FitCubeToMesh()
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.m_Mesh
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.m_textureVoxel
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.m_textureVoxelBis
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.m_DistanceTexture
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.m_bufferVoxel
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.m_computeShader
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.m_maxResolution
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.m_dimX
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.m_dimY
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.m_dimZ
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.m_MaxExtent
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.m_SdfOffset
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.m_DefaultPath
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.nTriangles
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.m_SizeBox
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.m_Center
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.m_Cmd
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.m_OwnsCommandBuffer
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.kMaxGridSize
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.SdfTexture
Missing Doc on System.Void UnityEngine.VFX.SDF.MeshToSDFBaker::InitMeshFromList(System.Collections.Generic.List<Mesh>, System.Collections.Generic.List<Matrix4x4>)
Missing Doc on Vector3Int UnityEngine.VFX.SDF.MeshToSDFBaker::GetGridSize()
Missing Doc on Vector3 UnityEngine.VFX.SDF.MeshToSDFBaker::GetActualBoxSize()
Missing Doc on System.Void UnityEngine.VFX.SDF.MeshToSDFBaker::.ctor(Vector3, Vector3, System.Int32, Mesh, System.Int32, System.Single, System.Single, CommandBuffer)
Missing Doc on System.Void UnityEngine.VFX.SDF.MeshToSDFBaker::.ctor(Vector3, Vector3, System.Int32, System.Collections.Generic.List<Mesh>, System.Collections.Generic.List<Matrix4x4>, System.Int32, System.Single, System.Single, CommandBuffer)
Missing Doc on System.Void UnityEngine.VFX.SDF.MeshToSDFBaker::Finalize()
Missing Doc on System.Void UnityEngine.VFX.SDF.MeshToSDFBaker::Reinit(Vector3, Vector3, System.Int32, Mesh, System.Int32, System.Single, System.Single)
Missing Doc on System.Void UnityEngine.VFX.SDF.MeshToSDFBaker::Reinit(Vector3, Vector3, System.Int32, System.Collections.Generic.List<Mesh>, System.Collections.Generic.List<Matrix4x4>, System.Int32, System.Single, System.Single)
Missing Doc on System.Void UnityEngine.VFX.SDF.MeshToSDFBaker::Init()
Missing Doc on System.Void UnityEngine.VFX.SDF.MeshToSDFBaker::BakeSDF()
Missing Doc on System.Void UnityEngine.VFX.SDF.MeshToSDFBaker::ClearRenderTexturesAndBuffers()
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.RayMap
Missing Doc on System.Void UnityEngine.VFX.SDF.MeshToSDFBaker::ReleaseBuffersAndTextures()
Missing Doc on System.Void UnityEngine.VFX.SDF.MeshToSDFBaker::Cleanup()
Missing Doc on System.Void UnityEngine.VFX.SDF.MeshToSDFBaker::CreateGraphicsBufferIfNeeded(GraphicsBuffer, System.Int32, System.Int32)
Missing Doc on System.Void UnityEngine.VFX.SDF.MeshToSDFBaker::ReleaseGraphicsBuffer(GraphicsBuffer)
Missing Doc on System.Void UnityEngine.VFX.SDF.MeshToSDFBaker::CreateRenderTextureIfNeeded(RenderTexture, RenderTextureDescriptor)
Missing Doc on System.Void UnityEngine.VFX.SDF.MeshToSDFBaker::ReleaseRenderTexture(RenderTexture)
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Triangle
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Triangle.a
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Triangle.b
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Triangle.c
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.inBucketSum
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.blockSums
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.finalSum
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.toTextureNormalized
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.copyTextures
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.jfa
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.distanceTransform
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.copyBuffers
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.generateRayMapLocal
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.rayMapScanX
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.rayMapScanY
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.rayMapScanZ
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.signPass6Rays
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.signPassNeighbors
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.toBlockSumBuffer
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.clearTexturesAndBuffers
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.copyToBuffer
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.generateTrianglesUV
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.conservativeRasterization
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.chooseDirectionTriangleOnly
Missing Doc on UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels.surfaceClosing
Missing Doc on System.Void UnityEngine.VFX.SDF.MeshToSDFBaker.Kernels::.ctor(ComputeShader)
UnityEngine.Debug:Log (object)
DocChecker:FindMissingDocs () (at Assets/FindMissingDocs/Editor/DocChecker.cs:204)
DocChecker:GenerateDocumentation () (at Assets/FindMissingDocs/Editor/DocChecker.cs:139)
DocChecker:OnGUI () (at Assets/FindMissingDocs/Editor/DocChecker.cs:100)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at G:/Unity/Dev/Modules/IMGUI/GUIUtility.cs:189)
```

**Review by PaulDemeulenaere — APPROVED** [review]
- Image reference fixed at https://github.com/Unity-Technologies/Graphics/pull/4501/commits/2eaf0dd7949f41533492d74c1761e4e2c0c0ef68
- Missing API doc fixed at https://github.com/Unity-Technologies/Graphics/pull/4501/commits/03d0b7bd44ddfd556c217595d9cc04def5fb2116
LGTM 🟢

**Pull request merged**
