### PR TITLE
Hdrp/samples/new material ball

### PR DESCRIPTION
**Pull request by SeanPuller**
### Update Material Samples with new Material ball

- Update to new material ball (provided by Cyril)
- Also updated Transparent material (textures provided by Remi)
- Moved the material ball fbx from HDRP package to Core so it can be utilized by URP
- remove old material ball
- update scenes with new assets
image

Unity_ZCYkNSYFHi
Unity_GWZwjJg2eK
Unity_wQed4ByNXv
Unity_GCnPv1bRAD

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]

**Review by remi-chapelain — COMMENTED** [review]
Just a few quick comments: 

- I wonder if we should disable SSR in the sample ? It gives this glitchy vibes on very reflective material, especially that the default quality level is medium, there's a lot of artefact.

https://user-images.githubusercontent.com/57442369/153831284-13f3a387-76b2-40f0-8d03-2f752a5454af.mp4

- About the mat1/mat2/mat3 that are now in com.unity.render-pipelines.core\Runtime\RenderPipelineResources\Mesh, is it good that we keep them in core since these material are only compatible with HDRP (HDRP/Lit) ?

image

**Review by remi-chapelain — CHANGES_REQUESTED** [review]
Let's also update the image [here](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@14.0/manual/HDRP-Sample-Content.html) in the doc as well :)

**Review by remi-chapelain — CHANGES_REQUESTED** [review]
Reviewed the latest changes, looks good to me: 

Quick remaining things: 
- Doc [image](https://github.com/Unity-Technologies/Graphics/blob/master/com.unity.render-pipelines.high-definition/Documentation~/Images/MaterialSamples.png) still needs an update
- StainedGlass normal map import setting is not set to normal map, and it should be set to the materials using it (at least 3)

**Comment by SeanPuller** [comment]
> Let's also update the image [here](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@14.0/manual/HDRP-Sample-Content.html) in the doc as well :)

done

**Comment by SeanPuller** [comment]
> Reviewed the latest changes, looks good to me:
> 
> Quick remaining things:
> 
> * Doc [image](https://github.com/Unity-Technologies/Graphics/blob/master/com.unity.render-pipelines.high-definition/Documentation~/Images/MaterialSamples.png) still needs an update
> * StainedGlass normal map import setting is not set to normal map, and it should be set to the materials using it (at least 3)

Done

**Review by remi-chapelain — APPROVED** [review]
Go for merge ! ✔️

**Pull request merged**
