### PR TITLE
DX12 raytracing & IET updates for the HDRP template

### PR DESCRIPTION
**Pull request by pierre-unity**
### Purpose of this PR
1. The project has been switched to DX12 to allow for raytracing to be enabled easily.

2. Two new HDRP assets and corresponding quality levels have been created for raytracing, called "Very High" and "Ultra"
image

3. The IET has been updated to reflect recent changes, and the images showing the former material ball have been updated
image

4. A new 3rd person character control has been added by Motiejus (the old one still exists in the hierarchy)
image

5. Added "Additional properties" page for the IET
image

6. Fixed wrong position for the collision proxy of the lounge chair
image

7. Added missing prefab edition scene
image

8. The default low/medium/high values for SSR and RTAO have been retuned to offer better results out of the box

9. Lowered the handrails.
image

---
### Testing status
No particular testing done so far.

---
### Comments to reviewers
When enabling raytracing, some bugs might be visible, these are not directly related to this PR but already exists.
For instance, this flickering in the 3rd room: https://jira.unity3d.com/browse/UUM-7911
Feel free to add more bugs related to raytracing.

### CODE REVIEW

**Comment by remi-chapelain** [comment]
Very nice improvements ! 👏 
I have a few comments: 
- Is it expected that by default DXR Activated is not checked by the wizard just after opening the project ? 
image
- Is it possible to offset by only a little the spotlight so that they appear when using the pathtracer ? The culling must be a little different and when the camera is close they just disappear when using the pathtracer (see [video1](https://unity.gyazo.com/54b6a39fe0636e9417bd7d29b004a558) [video2](https://unity.gyazo.com/f6752a9bc4c41f50d5586b0a5ea64f17))
This is also true for spotlights inside the corridor (see [video](https://unity.gyazo.com/8179fa09aefb0fd5d1fd917bac09e49a))
- In Raytracing we should probably disable the receive motion occluder parameter to remove noise from the 3rd person controler (see [video](https://unity.gyazo.com/a9a793603b35da2a8e48e7903372ddba))
- RTGI fallbacking on Reflection probe on the top of the room1 creates some lights artifacts that can be solved by just increasing the radius of one of the probe (see [video](https://unity.gyazo.com/58afe2796268b2c4a11962c2f044aef0))
- Since there is 10% clear coat on the "SandblastMetal_Mat" (the baseboards), The Ray Traced Reflection are on the clear coat smooth layer and are calculated only to contribute at 10%. Even if it's subtle, I would suggest removing clear coat at all so that the RTR are calculated for the base layer and not for the 10% clear coat.
- Directional fallback intensity should be at 1 outside and 0 inside (and blend nicely around the stairs) this leads to darkened reflection on the ROOM1 (see [video](https://unity.gyazo.com/0fceb1f8e48ce0d293c90efe138ef913))
- There seems to be an issue with RTR. There shouldn't be the peter paning like this (I'll make a bug)
image


The last ones are pretty subjective feedback and suggestion so I don't expect them to be "fixed" specifically, but still want to share them:
- I know it's probably common, but I'm really disturbed by the shoulder offset of 1 of the character. Maybe it's just me, but since the camera is "far away", I, personnally, really would prefer the character to be centered. :)
- Now that we have a nice 3rd person controller that can jump, could we also use it for the FPS (with a camera distance of 0 or something) to have one controller to rule them all ? Instead of having one complex and one very simple with different collider ?
- How about making the helmet front more metallic to showcase a little more how RTR can look ? :p
image

**Comment by iM0ve** [comment]
This is how it looks after my last commit. I updated the textures (saved 1mb of space and fixed some things), adjusted the camera position.

Close up
Unity_APSUvEfDtZ

Starting position
Unity_BqNdhpCHmD

Rtx
rtx

**Comment by pierre-unity** [comment]
Ready for review again, all known remaining issues have been fixed.

**Review by sebastienlagarde — APPROVED** [review]

**Comment by remi-chapelain** [comment]
To me there's two slight things remaining, that are only really visible in the debug modes so I won't block anything for it. 
It's more for the sake of it: 
- For the same reasons of RTGI, we could disable Receive Motion Rejection for the RTAO. ([video](https://unity.gyazo.com/a02924289784f7ed5bfb7a9277ca0f25))
- Since RTGI ray miss fallbacks on reflection probe and sky, in the entrance of the room2, there's this big reflection probe (ReflectionProbe Room 1 Exit) that have a small blend distance for its size and it shows when looking at the debug mode as well. 
It could be easily fixed by just increasing the blend distance to 5 or more.

**Review by remi-chapelain — APPROVED** [review]

**Review by sebastienlagarde — APPROVED** [review]

**Pull request merged**
