### PR TITLE
Fixed undo in gradient picker (blackboard and graph)

### PR DESCRIPTION
**Pull request by julienamsellem**
### Purpose of this PR
https://fogbugz.unity3d.com/f/cases/1261595/

This bug fix works in relation with with this PR but there's no code dependency
https://ono.unity3d.com/unity/unity/pull-request/128017/_/graphics/vfx/fix/1261595-undo-gradient-preset-change

### CODE REVIEW

**Comment by VitaSkruibyte** [comment]
Done a bit of testing on this, here are some observations.

Good things first: 
The issue with undo where gradient keys disappear is fixed when using properties in blackboard, inline nodes, blocks (color over lifetime, Set Color Random from Gradient), Color Mapping - Gradient Mapped setting.

Newly issues found or newly found issues for visibility:

**Comment by VitaSkruibyte** [comment]
Done a bit of testing on this, here are some observations.

Good things first:
The issue with undo where gradient keys disappear is fixed when using properties in blackboard, inline nodes, blocks (color over lifetime, Set Color Random from Gradient), Color Mapping - Gradient Mapped setting.

Issues that are still present or newly found issues for visibility:

**Comment by VitaSkruibyte** [comment]
Done a bit of testing, here are the observations and what was tested:

Tested:
- Blackboard properties, Color Mapping property, inline nodes, properties in blackboard, various blocks that contain gradient editor
-  Edited gradients in the Gradient window (used keys, dragged them, performed undo actions, used color picker, switched between gradient etc)
- Checked connected/disconnected nodes + created several simple effects to see if gradients look fine

**Good things first**: Primary issue is no longer reproducible with blackboard properties, Color Mapping - Gradient Mapped Outputs, inline nodes. Issue where we discussed that undo can't be done in Blackboard when inline node is edited and undo action is performed is also fixed! 🎉

**Newly found issues or existing ones that could be fixed within this PR:**

**1. Error _'Assertion failed on expression: 'didInsert'_' is thrown to the console when Gradient Window is being opened**

SC7AekRRyU

**2. NRE is thrown to the console when editing choosing color in the color wheel (this one might require a bit of effort when choosing a color in the color wheel)**
baONtjdpfe
Few lines of the error:
```
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.GradientEditor.ShowSwatchArray (UnityEngine.Rect position, System.Collections.Generic.List`1[T] swatches, System.Boolean isAlpha) (at C:/buildslave/unity/build/Editor/Mono/GUI/GradientEditor.cs:400)
UnityEditor.GradientEditor.OnGUI (UnityEngine.Rect position) (at C:/buildslave/unity/build/Editor/Mono/GUI/GradientEditor.cs:159)
UnityEditor.GradientPicker.OnGUI () (at C:/buildslave/unity/build/Editor/Mono/GUI/GradientPicker.cs:228)
UnityEditor.HostView.OldOnGUI () (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:266)
```

**3.  _[Not caused by this PR, but would be cool to have this fixed]_ Gradient keys disappear when selecting a color in the color wheel**
goWTVOVeRN

**4. _[Not caused by this PR and not our area (I believe this one can be left as is unless you have some bandwidth and want to make users happy as this issue is a bit annoying]_ In the Inspector Gradient window does not update when undoing actions**
AQiKDy9Cnb

So far that's it what I managed to find, if I find anything else will jot down here. If you need any reproduction clarification, feel free to slack me

**Review by iTris666 — APPROVED** [review]

**Review by VitaSkruibyte — APPROVED** [review]
All the PR related issues were fixed, couldn't find any other outstanding behavior. Thank you for the fix!

**Review by kroatoa — APPROVED** [review]

**Pull request merged**
