### PR TITLE
Fixed the transparent cutoff not working properly in semi-transparent  and color shadows (case 1340234).

### PR DESCRIPTION
**Pull request by anisunity**
https://fogbugz.unity3d.com/f/cases/1340234/

Testing status
Added a test to cover the issue.
DXR test are green locally.

### CODE REVIEW

**Review by remi-chapelain — APPROVED** [review]
Has been quickly pair tested and new test should cover the usage without issue.

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
unsure if it come from the PR but after few re-run I still not get a green DXR: https://yamato-artifactviewer.prd.cds.internal.unity3d.com/e07609e1-67eb-402b-985b-6e80d915cf7d%2Flogs%2FTestProjects%2FHDRP_DXR_Tests%2Ftest-results/TestReportV1.html.  I re-run once again to be sure.

**Comment by sebastienlagarde** [comment]
> unsure if it come from the PR but after few re-run I still not get a green DXR: https://yamato-artifactviewer.prd.cds.internal.unity3d.com/e07609e1-67eb-402b-985b-6e80d915cf7d%2Flogs%2FTestProjects%2FHDRP_DXR_Tests%2Ftest-results/TestReportV1.html. I re-run once again to be sure.

yup 100% failing

**Review by remi-chapelain — APPROVED** [review]
Updated the test screenshot, 
DXR PR Job is 🟢 on yamato now.

**Pull request merged**
