### PR TITLE
Added support for volumetric clouds in planar reflections.

### PR DESCRIPTION
**Pull request by anisunity**
Previously the clouds didnt not appear in the planar reflections. This PR makes them works. The process was a bit more complex than expected, but its working. I also updated the documentation to remove the previously declared limitation.

image

Testing status
Tested with a planar reflection at different smoothness levels and different cloud presets.

### CODE REVIEW

**Review by JordanL8 — APPROVED** [review]

**Review by remi-chapelain — APPROVED** [review]
Need to not forget to increase the far plane and enable exposure control in the planar settings but otherwise, tested with multiple range of planar / roughness / shader, result is fine ! ✔️ 

https://user-images.githubusercontent.com/57442369/109518519-994e3300-7aaa-11eb-8076-2aa360219336.mp4

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
@anisunity : There is formatting issue. (I can help). And also can you update current volumetric cloud test by adding a planar reflection in it? thanks

**Comment by anisunity** [comment]
Doing the changes you asked for

**Comment by anisunity** [comment]
Fixed the formatting and updated a test (will need to update a screenshot)

**Comment by anisunity** [comment]
Updates screenshots

**Comment by sebastienlagarde** [comment]
@anisunity volumetric cloud shadow test cause gc alloc:
System.Exception : Memory allocation test failed, 5 allocations detected. Steps to find where your allocation is:

**Comment by anisunity** [comment]
Fixed

**Pull request merged**
