### PR TITLE
Narrow asset search to .asset files when upgrading ForwardRendererData into UniversalRendererData.

### PR DESCRIPTION
**Pull request by kaychang-unity**
---
### Purpose of this PR
This improves the search through assets of type ForwardRendererData and UniversalRenderPipelineAsset and should reduce upgrade time to UniversalRendererData.

This PR requires another Ono PR to land first in trunk (https://ono.unity3d.com/unity/unity/pull-request/123977/_/asset-database/find-assets-optimisation).

---
### Testing status
Ran UniversalGraphicsTests_Lighting locally and confirmed ForwardRendererData are still correctly found and upgraded to UniversalRendererData.

### CODE REVIEW

**Review by phi-lira — APPROVED** [review]

**Review by simon-engelbrecht-soerensen — APPROVED** [review]

**Comment by phi-lira** [comment]
@kaychang-unity let me know when PR to trunk lands so we merge this one.

**Comment by theo-pnv** [comment]
Hi everyone, the trunk PR was merged this weekend. Are we ready to merge this one into master? It is needed to resume the srp2core PRs.

**Comment by phi-lira** [comment]
Ready to be merged, just waiting ABV.

**Comment by kaychang-unity** [comment]
I forgot master must be merged again first in order for Yamato to run against latest trunk. re-running ABV one more time.

**Comment by kaychang-unity** [comment]
It looks like pinned revision of trunkfor today is still set before the trunk PR merge. I suppose it should be fine tomorrow. I ran Yamato ABV with custom revision of trunk (the latest revision in Ono is af5e3dc5f881) and relevant [job are passing](https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/universal%252Fpostprocessor-improvement/.yamato%252F_abv.yml%2523all_project_ci_CUSTOM-REVISION/6388118/job/pipeline).

The only job that crashes is URPUpdate_Top_Asset_Store on Win_DX11_playmode_mono_Linear, which also fails in [master branch ABV](https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252F_abv.yml%2523all_project_ci_trunk/6386992/job/pipeline).

**Pull request merged**
