### PR TITLE
Universal Staging

### PR DESCRIPTION
**Pull request by phi-lira**
### Purpose of this PR
Staging branch to land following PRs:
- Enable Depth Priming on Vulkan w/ MSAA (#4699) …
- Urp/fix to add tooltip of ss-shadows (#5034) …
- ShadowCaster now using varyings normalWS for shader graph (#5527) …
- Add Shadow and Additional light variant stripping (#5544) …
- adaptive performance foldout ui issue (#5820) …
- Updated link to the Enlighten documentation (#5928)
- Fixed typo in API name (#5854) 
- Fix regression in screen position when using XR (#5867)

### CODE REVIEW

**Comment by phi-lira** [comment]
@cdxntchou there were some shader graph reference images changes from this PR. Are those what you mean?
 I had to kick out that PR form the batch anyway as it introduced a failure in tests.
  https://github.com/Unity-Technologies/Graphics/pull/4769/

**Comment by cdxntchou** [comment]
Ah, I see, that PR #4769 added missing reference images back on Aug 6th, but those images have already been added to master in #5428 on Sep 21.  Can probably just revert the ShaderGraph reference images from the PR.

**Review by cdxntchou — APPROVED** [review]
ShaderGraph code looks good

**Review by ernestasKupciunas — APPROVED** [review]
Looks good! No issues related to the staging branch were found.
Testing doc: https://docs.google.com/document/d/1eiHufY0BUgxQ_Kz9pICSMorP15WKpb4MpYJ4V_ySnJo/edit?usp=sharing

**Comment by phi-lira** [comment]
Build URP_PostPro on iPhone_Metal_il2cpp failing on master two days ago. 🔴 
ShaderGraph on Android_Vulkan_Standalone_il2cpp_Linear 🔴 
Build URP_Performance_BoatAttack on iPhone_Metal_il2cpp_Linear failing on master 🔴 
Build URP_Performance_LostCrypt on iPhone_Metal_il2cpp_Linear failing on master 🔴

**Pull request merged**
