### PR TITLE
[VFX] Staging to master

### PR DESCRIPTION
**Pull request by PaulDemeulenaere**
---
### Purpose of this PR
Batch of changes from the `vfx/staging` branches
- Motion vectors enabled for particle strips ▶️ [#251](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/251)
- Fixed Collision with Depth Buffer when using Orthographic camera [Case 1309958](https://issuetracker.unity3d.com/product/unity/issues/guid/1309958/) ▶️ [#239](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/239)
- Fix culling of point output [Case 1225764](https://issuetracker.unity3d.com/product/unity/issues/guid/1225764/) ▶️ [#135](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/135)
- Compilation issue when normal is used in shadergraph for opacity with unlit output ▶️ [#256](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/256)
- Fix Exception on trying to invert a degenerate TRS matrix [Case 1307068](https://issuetracker.unity3d.com/product/unity/issues/guid/1307068/) ▶️ [#252](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/252)
- Fix IsFrontFace shader graph node for VFX. ▶️[#257](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/257)
- Fix crash when loading SDF Baker settings holding a mesh prefab [Case 1343898](https://issuetracker.unity3d.com/product/unity/issues/guid/1343898/) ▶️ [#264](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/264)
- Exception using gizmo on exposed properties [Case 1340818](https://issuetracker.unity3d.com/product/unity/issues/guid/1340818/) ▶️[#260](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/260)
- GPU hang on some initialize dispatch during dichotomy (platform specific) ▶️[#261](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/261)
- Minor doc update ▶️ [#265](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/265)
- Add shader formatting for Infinity and NaN in float ▶️ [#259](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/259)
- Transform Shape V2 🎉 ▶️ [#258](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/258)
-  Add a debug preference view for "Multithread update enabled" ▶️ [#271](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/271)

TODO :
- [x] Wait for the merge of https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/258
- [x] Reorder changelog
- [x] Rebuild all vfx
- [x] Wait for the merge in trunk from https://ono.unity3d.com/unity/unity/pull-request/128819/_/2021.2/vfx/fix/1309958-collide-with-depth-orthographic (the package 12.x.x is still targeting 2021.2 & trunk)
- [x] Bump package minimal revision to 2021.2.0b6.3179_da480e1687cb
- [x] Merge with master (when pinned revision has been updated)
- [x] Wait for `2021.2.0b6` to be available on [saihai](https://saihai.hq.unity3d.com/history/) (required for the [General Checks](https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/vfx%252Fstaging/.yamato%252F_editor_priming.yml%2523editor%253Apriming%253Atest_min_editor%253AWin/7871637/job) verification)
- [x] Relaunch Yamato with 21.2 (VFX + General Checks)
- [x] Wait for all 🟢 & Merge

Bonus :
- [x] Apply formatting (at https://github.com/Unity-Technologies/Graphics/pull/5155/commits/24cbf56b2f80d40719c7cfdaf82b38d1e3b80fa3)
- [x] Wait for all 🟢 & Merge
---
### Testing status
Yamato 🟢 
And also uploading reference image for internal platform : https://github.cds.internal.unity3d.com/unity/ScriptableRenderPipelinePrivate/pull/217
Known issue with SkinSDF : https://fogbugz.unity3d.com/f/cases/1351595/

---
### Comments to reviewers
~~There is a known sanitize issue https://fogbugz.unity3d.com/f/cases/1352832/ but it only makes the graph a bit messy after sanitization, there isn't any loss of data, it's an UX issue if you are using exposed shape. (update) The [fix](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/268) is in progress.~~ 
Fixed at https://github.com/Unity-Technologies/Graphics/pull/5155/commits/ddea81cd3b1f042d9c9c41476fc3f485b62331d1

### CODE REVIEW

**Review by gabrieldelacruz — APPROVED** [review]
Everything seems fine on my side

**Comment by PaulDemeulenaere** [comment]
The changes in URP are only related to the package.json bump : https://github.com/Unity-Technologies/Graphics/pull/5155/commits/c9de5de0cfbe4bde333e0ada215c439f92ef613c

**Comment by PaulDemeulenaere** [comment]
@julienf-unity We have to wait for Sahai to be able to merge `vfx/staging` because the [General Checks](https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/vfx%252Fstaging/.yamato%252F_abv.yml%2523General_Checks_2021.2/7871650/job/pipeline) only used final version of each beta. In our case, we have to wait for the release of 21.2b6 (see https://github.com/Unity-Technologies/Graphics/commit/c9de5de0cfbe4bde333e0ada215c439f92ef613c)
See also this [conversation](https://unity.slack.com/archives/G1BTWN88Z/p1627481800058900)

**Comment by PaulDemeulenaere** [comment]
Ready to be merged @julienf-unity 🎉

**Review by ernestasKupciunas — APPROVED** [review]
Approving without testing because this is just a batch of bugfixes from the internal vfx/ staging branch. All the bugfixes were approved by the qa-gfx-vfx team.

**Comment by PaulDemeulenaere** [comment]
Ready to be merged @julienf-unity 🎉(bis 😅)

**Review by julienf-unity — APPROVED** [review]

**Pull request merged**
