### PR TITLE
[2021.2][XR] Decals

### PR DESCRIPTION
**Pull request by lukaschod**
### Purpose of this PR
Enable decals on XR.

---
### Testing status
INC

---
### Comments to reviewers
This is follow up PR of https://github.com/Unity-Technologies/Graphics/pull/3926 that will enable decals support on XR.

### CODE REVIEW

**Review by fabien-unity — APPROVED** [review]

**Review by phi-lira — APPROVED** [review]

**Review by phi-lira — APPROVED** [review]

**Review by erikabar — APPROVED** [review]

**Review by JasonCostanza — CHANGES_REQUESTED** [review]
After realizing there was huge confusion on branches... I completed the following configs on XR platforms:

Version 2021.2.0a17 (96ee4da88f82)
Branch: trunk

HL2
OpenXR 1.2.0 + WMR OXR 0.9.2
SRP 12.0.0 PR branch (this PR)
https://fogbugz.unity3d.com/f/cases/1335166/

WMR
OpenXR 1.2.0 + WMR OXR 0.9.2
SRP 12.0.0 PR branch (this PR)
https://fogbugz.unity3d.com/f/cases/1335166/

PS4VR
1.5.0 PS4 Render Pipe
SRP 12.0.0 PR branch (this PR)
https://fogbugz.unity3d.com/f/cases/1335166/
https://fogbugz.unity3d.com/f/cases/1335164/

For the above bugs, I would not recommend merging these changes without targeted bug fixes addressing these issues.

**Review by amaestas13 — CHANGES_REQUESTED** [review]
Tested on Quest and Quest 2

Overall the pr seems good. 

However performance is not good on vulkan.  droping into the 40s from 72 in a simple scene. 

Quest 2 would drop significant fps even with just a few decals.  This was especially apparent in multipass on vulkan when the setting "Optimize Buffer Discards" was disabled. 

I also experienced the flashing which @JasonCostanza reported but that seemed to go away when removing the normal map from the brick wall material.  I think this bug is unrelated to the decal system.

**Review by amaestas13 — APPROVED** [review]
Ran additional testing. 

Performance bug previously reported due to another issue and not this pr. 

However performance is still not the greatest overall on mobile vr but this varies by how a user implements the decal and how much of the screen it takes up. More of an issue in multipass. 

Overall good no oculus specific issues seen. Tested with Quest and Quest 2 native and link. Tested GLES and Vulkan with all supported stereo render modes.

**Review by JasonCostanza — APPROVED** [review]
Version: 2021.2.0a18.git.4293293
Revision: trunk 4182adfbc8b7
Built: Sun, 16 May 2021 07:07:00 GMT

URP:
commit bc0c1206f02f3a58f76fd1623918a8729551cc37 (HEAD -> universal/decal-xr, origin/universal/decal-xr)

demo project: 
commit 84997754d58f082069b1f476ca7c128071b8256e (HEAD -> master, origin/master, origin/HEAD)

Both HL2 and WMR HMD's perform well and display all the decals as I would expect to see. The pink cube still appears but I have in slack that this is by design and not an issue. I think this is good enough to send out. I verified release players on both Arm64 and x64 for respective headsets.

**Pull request merged**
