### PR TITLE
ClearFlag.Depth does not clear stencil anymore

### PR DESCRIPTION
**Pull request by kaychang-unity**
### Purpose of this PR
This adjusts ClearFlag usage so that we explicitly declare when we want to clear depthStencil instead of deph or stencil only.
ClearFlag.Depth does not implicitly clear stencil anymore and code has been fixed around that.

---
### Testing status
Ran UniversalGraphicsTests, HDRP_Tests, Yamato.

---
### Comments to reviewers
This PR should land after the maching Ono PR lands (https://ono.unity3d.com/unity/unity/pull-request/119517/_/graphics/commandbuffer-clear-stencil).

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
@kaychang-unity what is next step?

**Comment by kaychang-unity** [comment]
I was busy working on another unrelated task. I will continue working on the trunk PR side shortly, as soon as it is approved/lands, the github PR can land.

**Comment by sebastienlagarde** [comment]
Oh I forget, be sure to add an upgrade guide in both URP and HDRP to tell to users what's change

**Comment by kaychang-unity** [comment]
@sebastienlagarde  How/where do I add an upgrade guide?

**Comment by sebastienlagarde** [comment]
> @sebastienlagarde How/where do I add an upgrade guide?

Each SRP ahve a file like this in documentation folder: https://github.com/Unity-Technologies/Graphics/blob/master/com.unity.render-pipelines.high-definition/Documentation~/Upgrading-from-2021.1-to-2021.2.md  

you need to add what's change.

Example: https://github.com/Unity-Technologies/Graphics/blob/master/com.unity.render-pipelines.high-definition/Documentation~/Upgrading-from-2019.3-to-2020.1.md

**Comment by kaychang-unity** [comment]
@sebastienlagarde I updated the upgrade guide. The change is now small due to the behaviour of `CommandBuffer.ClearRenderTarget(bool, bool, Color, float)` not changing.

**Comment by sebastienlagarde** [comment]
Perfect, thanks a lot all good.
Oh last point. In the past we where suppose to bump min version (with the version where the C++ PR will land), but wondering what we do with SRP2Core now.  Anyway @phi-lira if you can validate :)

**Review by phi-lira — APPROVED** [review]

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
PR is ready, now need to get better Yamato, the C++ PR need to land.

**Comment by sebastienlagarde** [comment]
And thus you will need to udpate the min version in various package.json

**Comment by kaychang-unity** [comment]
@sebastienlagarde I've been stuck the last few days on Yamato and Katana failures. I still don't get why all my Yamato jobs fail ...
Regarding the min version in various package, what does this value be? It's currently "version": "12.0.0".

**Comment by sebastienlagarde** [comment]
Hey, any update on this one?

**Comment by kaychang-unity** [comment]
I ran Yamato SRP ABV on this 10 days ago but it looked like it was testing against a pinned revision of trunk, instead of latest trunk, which is needed in order to pass.

**Comment by kaychang-unity** [comment]
Got latest and rerunning Yamato again. 4 jobs still failing (rerunning them again in case it's an instability).

**Pull request merged**
