### PR TITLE
Use color temperature in the player for Enlighten real-time GI

### PR DESCRIPTION
**Pull request by KEngelstoft**
### Purpose of this PR
Fixes Correlated Color Temperature not being applied in Player builds for Enlighten real-time GI lights (case 1370438).

### Testing status
Tested locally on Windows 10 using the repro from the case in editor and standalone player:
1. Download and open CornellBox project. Use an appropriate branch for your RP of choice.
2. Open CornellBox scene
3. Select either the Directional Light, Spotlight, or Point Light game object
4. Make sure that it is using any color temperature value
5. Set its mode to Realtime
6. Enable Realtime GI in the Lighting window and bake
7. Build a standalone build
8. Notice that the light's color is white, regardless of the color temperature setting

I have tested editor and standalone player using BiRP, URP and HDRP.

Screenshot of the editor showing a light source with a low color temperature and a white color filter https://drive.google.com/file/d/1qdFfk63dUQPjpbzIionGfTHFwezCI0bm/view?usp=sharing.

Screenshot of a standalone player build of the same scene in BiRP https://drive.google.com/file/d/1bp0l8R_2phwegRWuIZuEH2KKE0BM-hOG/view?usp=sharing.

Screenshot of a standalone player build of the sample scene in URP with a realtime GI light with color temperature https://drive.google.com/file/d/1DLnEyRDdSsWX0M2mvU89llI8cklTNDnh/view?usp=sharing 

Screenshot of a standalone player build of the sample scene in HDRP with a realtime GI light with color temperature https://drive.google.com/file/d/1ik9LgFBkrFY2sjqYWUiMw64QXmF_n9WO/view?usp=sharing

Suggestions for manual testing: HDRP and URP sanity checks for lighting and realtime GI and baked GI.

### Comments to reviewers
Native code PR for BiRP https://ono.unity3d.com/unity/unity/pull-request/136092/_/lighting/bugfix/1370438

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
Hey, I suppose this need to be backported up to 21.2 right? thanks

**Comment by KEngelstoft** [comment]
> Hey, I suppose this need to be backported up to 21.2 right? thanks

Yes please.

**Comment by sebastienlagarde** [comment]
> > Hey, I suppose this need to be backported up to 21.2 right? thanks
> 
> Yes please.

ok I can take care of it, if you can provide C++ backport PR link here, thanks

**Review by radishface — APPROVED** [review]
I have verified the fix in:
2022.1.0a17.2383.lighting/bugfix/1370438.2
Revision: lighting/bugfix/1370438 d840211da104
Built: Thu, 25 Nov 2021 09:52:45 GMT

**Comment by sebastienlagarde** [comment]
@KEngelstoft  so the PR landed in trunk, do you have a link on the 22.1 and 21.2 version? can you post it here so I can track for the backport, thanks

**Comment by KEngelstoft** [comment]
> @KEngelstoft so the PR landed in trunk, do you have a link on the 22.1 and 21.2 version? can you post it here so I can track for the backport, thanks

@sebastienlagarde The native side backports are tracked in Fogbugz: 
2021.2: https://fogbugz.unity3d.com/f/cases/1370445
2022.1: https://fogbugz.unity3d.com/f/cases/1384718
Both cases are assigned to the SE back porting service and hasn't reached the PR stage yet.

**Comment by sebastienlagarde** [comment]
22.1 https://ono.unity3d.com/unity/unity/pull-request/136852/_/2022.1/lighting/bugfix/1370438
21.2: https://ono.unity3d.com/unity/unity/pull-request/136850/_/2021.2/lighting/bugfix/1370438

**Comment by radishface** [comment]
@sebastienlagarde, has this fix been backported to 2021.2 and 2022.1 yet? I have tried verifying it in a public 2021.2 build, but the fix was not present there. Thanks.

**Comment by KEngelstoft** [comment]
https://ono.unity3d.com/unity/unity/pull-request/136850/_/2021.2/lighting/bugfix/1370438 landed in 2021.2/staging at 2021.2.8f1.4206_8b5a9ba59c0b.

22.1 didn't land yet.

**Pull request merged**
