### PR TITLE
[ON HOLD - DO NOT MERGE] Separate multiplier for ambient probe and Sky reflection

### PR DESCRIPTION
**Pull request by FrancescoC-unity**
This PR introduces two new fileds in the indirect lighting controller 

image

Namely to scale ambient probe separately (**note** it will not work when the ambient probe is sampled through old tetra probes as no way to know what is ambient probe and what not there) and sky fallback reflections. 

Discussed this with @pierre-unity  as first step in this direction, more complext separated tuning will require further discussions. 

I updated the screenshot for the already existing test, but will kick yamato now.

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]

**Review by iM0ve — CHANGES_REQUESTED** [review]
Hello, please update whats tested section. Also what else its worth checking besides the Indirect controller override or it shouldnt affect anything else?

**Review by JulienIgnace-Unity — APPROVED** [review]

**Comment by FrancescoC-unity** [comment]
> Hello, please update whats tested section. Also what else its worth checking besides the Indirect controller override or it shouldnt affect anything else?

I changed the test :-) 

I tested looking at water/clouds/fog with ambient probe affecting them and moving the changes. 
I also checked the sky reflection probe being scaled by the factor.

**Review by iM0ve — CHANGES_REQUESTED** [review]
The feature does work as expected, but we are still iterating on the tooltip and maybe the name of the Ambient Probe Multiplier parameter.

https://user-images.githubusercontent.com/36502659/146540625-04879ead-b2e1-481e-abc0-c20ee7eaa5bd.mov

**Comment by sebastienlagarde** [comment]
talk with Pierre Yves, close for now

**Pull request closed without merging**
