### PR TITLE
Fixed LightProbes to have gamma correct when using gamma color space

### PR DESCRIPTION
**Pull request by lukaschod**
# **Please read;**
## **PR Workflow for the Graphics repository:**
* **All PRs must be opened as draft initially**
* Reviewers can be added while the PR is still in draft
* The PR can be marked as “Ready for Review” once the reviewers have confirmed that **no more changes are needed**
* Tests will start automatically after the PR is marked as “Ready for Review”
* **Do not use [skip ci]** - this can break some of our tooling
* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [x] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ]  Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Fix for case https://fogbugz.unity3d.com/f/cases/1268911/.

---
### Testing status

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally
- [x] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)
- Other: 

**Automated Tests**: Can not really add automation as we are currently testing linear color space only. Part of discussion is here https://unity.slack.com/archives/C89KFUUCT/p1596718321327600?thread_ts=1596617214.309600&cid=C89KFUUCT.

**Yamato**: https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/universal%252Fbugfix%252Flight-probes-gamma-space

**Test Project**: Added in the case https://fogbugz.unity3d.com/f/cases/1268911/.
Linear
image
Gamma before fix
image
Gamma after fix
image

---
### Comments to reviewers
As we always had incorrect LightProbe contribution in gamma space, this fix will change the look of current projects. Can we do something to make this easier for users?

### CODE REVIEW

**Review by pbbastian — CHANGES_REQUESTED** [review]
Code looks good. I think this makes sense to land even if it changes existing projects, but we should land it in a new major version. That also means it shouldn't be backported.

Since this is a behavior change, can you add something to the "Changed" section in the change log? Keep the bug fix note in fixed as well though.

**Comment by phi-lira** [comment]
I agree with Peter, imo we can still land this for 10.x as is preview as long as we land for 10.1. Please add changed in the section as well and `ready-to-merge` tag when ABV is green.

**Comment by lukaschod** [comment]
> Code looks good. I think this makes sense to land even if it changes existing projects, but we should land it in a new major version. That also means it shouldn't be backported.
> 
> Since this is a behavior change, can you add something to the "Changed" section in the change log? Keep the bug fix note in fixed as well though.

Added changed entry, will try to land into 10.1 if not will post-pone it to next major.

**Comment by lukaschod** [comment]
So as I understand we are still in 10.1.x preview, maybe we can land it?

**Review by pbbastian — APPROVED** [review]

**Pull request merged**
