### PR TITLE
Motion vector support for Custom post processing effects

### PR DESCRIPTION
**Pull request by Aydindeveloper**
> > Note to self: Need to recreate the PR, can't trigger Yamato on it
> 
> for future PR's by community, is there a way to add that trigger ability so that you folks don't have to create PRs over and over? :)

I am not the expert for this one but I don't think so. We are still happy to accept community PR even if we need to recreate them.

### CODE REVIEW

**Comment by merpheus-dev** [comment]
@sebastienlagarde no review or assignment for approval on this?

**Comment by sebastienlagarde** [comment]
Hi, first thanks for your contribution and for making a PR. This is currently under evaluation and we will see if we proceed with your way or a different one but we indeed want to provide access to those motion vector. Our current evaluation is about the lifetime of the RT.

**Review by JulienIgnace-Unity — APPROVED** [review]

**Review by JulienIgnace-Unity — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
Note to self: Need to recreate the PR, can't trigger Yamato on it

**Comment by merpheus-dev** [comment]
> Note to self: Need to recreate the PR, can't trigger Yamato on it

for future PR's by community, is there a way to add that trigger ability so that you folks don't have to create PRs over and over :)

**Comment by sebastienlagarde** [comment]
repalce by https://github.com/Unity-Technologies/Graphics/pull/4837

**Pull request closed without merging**
