### PR TITLE
Fixes warning about missing unit in VFXContext.uss 

### PR DESCRIPTION
**Pull request by kevinmv**
### Purpose of this PR
com.unity.visualeffectgraph generates a warning when opening projects due to the VFXContext.uss margin-bottom and width properties not listing their size in pixel units (we don't specify any unit at all).

---
### Testing status
Re-opened a project and confirmed no warnings were generated (the dots/monorepo also fails CI if warnings are generated when opening projects)

### CODE REVIEW

**Review by julienamsellem — APPROVED** [review]
I never saw such a warning, but this fix is not gonna harm anyway :)

**Comment by kevinmv** [comment]
> I never saw such a warning, but this fix is not gonna harm anyway :)

Thanks!

Is it fine to merge this? CI fails since this branch hasn't merged in master and thus is no longer compatible with trunk. But for this 2 char change, if you're ok with it would be simpler than making a new branch (as others are using this branch until this change is merged in)

**Comment by julienamsellem** [comment]
> Is it fine to merge this? CI fails since this branch hasn't merged in master and thus is no longer compatible with trunk. But for this 2 char change, if you're ok with it would be simpler than making a new branch (as others are using this branch until this change is merged in)

Yep, I don't see any risk, you can merge safely :)

**Comment by kevinmv** [comment]
> > Is it fine to merge this? CI fails since this branch hasn't merged in master and thus is no longer compatible with trunk. But for this 2 char change, if you're ok with it would be simpler than making a new branch (as others are using this branch until this change is merged in)
> 
> Yep, I don't see any risk, you can merge safely :)

Thanks! :)

**Pull request merged**
