### PR TITLE
Add new API to CachedShadowManager  and fix WouldFitInAtlas

### PR DESCRIPTION
**Pull request by FrancescoC-unity**
This PR introduces a couple of things: 

**New public API**

 - A new WouldFitInAtlas that takes directly a light. 
 - A LightHasBeenPlacedInAtlas to verify if a light has found its placement in the cached shadow atlas. 

**Fixes**
- Would fit in atlas would previously would wrongly return true even if only one face of a point light shadow fit in the atlas. 

EDIT: 

Added even more API:

- LightHasBeenPlaceAndRenderedAtLeastOnce needed as light OnDemand don't render automatically upon placement so they might contain stale data and the user might want to know about it.

### CODE REVIEW

**Comment by FrancescoC-unity** [comment]
Note: there might be a slight issue with the new API, please don't merge I'll have to do a small pass on Monday.

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
@FrancescoC-unity guess we should update the documentation about sahdow caching as well to talk about this new feature

**Comment by FrancescoC-unity** [comment]
Yes, will add the docs when I do a small pass on it (likely Wednesday as it coincide with a meeting I will have)

**Comment by sebastienlagarde** [comment]
I have remove the QA on this PR as it is not something we can easily test. It was tested by Bornfire for validation instead.

**Pull request merged**
