### PR TITLE
Hd/fix pivot size ratio percistency through 0

### PR DESCRIPTION
**Pull request by RSlysz**
### Purpose of this PR
Fix https://fogbugz.unity3d.com/f/cases/1308338/
Also set default pivot to (0, 0, 0) (must be a miss in the refactor) as otherwise the vertex snapping cannot work.
Also discovered and fixed a recently introduced multi-edition issue when changing size in Inspector.

razpJYvW4p

---
### Testing status
Manually tested:
- ratio is kept when changing the size to 0 and go back to another value through Inspector
- saved ratio is reset when pivot is changed in Inspector
- saved ratio is reset when pivot is changed in the edit mode
- tested multi-edition: when multi editing several DecalProjector's Inspector's Size, they all rescale around their own pivot point.

Note: saved ratio is not kept when Editor is destructed (the fix is worth only for the Inspector lifetime but it cover all problematic workflow with the issue above)

---

### CODE REVIEW

**Comment by RSlysz** [comment]
Realized there is something odd with multi edition and tweaking inspector size (both before and after PR). Enquiring more information from @SeanPuller on slack on the matter to know the best way to solve this (or not) and integrate it here.

**Review by sebastienlagarde — APPROVED** [review]

**Comment by RSlysz** [comment]
Tomas found a flaw in my initialization logic in case of multi-edition. This need to be fixed.

**Review by fredericv-unity3d — APPROVED** [review]

**Review by TomasKiniulis — APPROVED** [review]
After the fixes PR seems good!
What I've checked:
- Not encountering any issues with projection update
- Confirmed that adjusting Projection Depth with different multiple selected object values does update input box with the same value when changed
- No GUI errors occur when adjusting pivot
- Multi-editing decals with mismatching Projection Depth do adjust values from their individual pivots now

PR unrelated issue found: https://fogbugz.unity3d.com/f/cases/1317105/

**Comment by sebastienlagarde** [comment]
Note: fix for PR: https://github.com/Unity-Technologies/Graphics/pull/3001 (2021.1)

**Pull request merged**
