### PR TITLE
Added a way to check the normals through the material views.

### PR DESCRIPTION
**Pull request by anisunity**
After working on multiple bugs that envolved datasets with wrong geometry normals or normal maps, we've decided to go for a debug mode that tells the user that his normals are broken.

https://fogbugz.unity3d.com/f/cases/1267816
https://fogbugz.unity3d.com/f/cases/1263744

image

Testing status
Tested with the dataset that comes from the repro (the dino), works for all modes except Gbuffer where the surface is considered invalid.

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]
Good, could you add a changelog and also in the documentaitno for debug windows / debug view mode that when it is red it mean it is not normalized? thanks

**Comment by sebastienlagarde** [comment]
And trigger Yamato :)

**Comment by anisunity** [comment]
Changelog done and yamato triggered

**Comment by anisunity** [comment]
Doc updated aswell

**Review by JordanL8 — APPROVED** [review]

**Review by remi-chapelain — APPROVED** [review]
To complete the testing done by @anisunity with imported meshes, I tested creating a procedural mesh and assigned it intentionnally broken normals to see if the debug mode showed red color. ✔️

**Pull request merged**
