### PR TITLE
Smoother decal angle fade

### PR DESCRIPTION
**Pull request by adrien-de-tocqueville**
### Purpose of this PR

1. Change the two angle fade sliders to a single min max slider.
image

2. Fix https://fogbugz.unity3d.com/f/cases/1288165
Double sided was not taken into account by the depth prepass

3. Change the decal projector angle fading equation to look smoother with wide ranges starting a low values
It uses actually less instructions than before

First images are 0° - 180° range, second is 0° - 90°
For start angles above 90° the results are similar
Before            |  After
:-------------------------:|:-------------------------:
image |  image
image | image

---
### Testing status

Tested the repro package for the fogbugz
Tested various angles on a sphere for the angle fading

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
Something is incorrect in the PR, there is part of the decal that stay show: 

image

**Comment by adrien-de-tocqueville** [comment]
It was like that on the previous screenshot i didn't modify the test. It is the projector of the bottom row that is too high on y axis and affects the meshes of the top row, but it's not a problem

**Comment by sebastienlagarde** [comment]
> It was like that on the previous screenshot i didn't modify the test. It is the projector of the bottom row that is too high on y axis and affects the meshes of the top row, but it's not a problem

good to know! :), I should have made a better test

**Comment by sebastienlagarde** [comment]
@RemyUnity checked that the slider and double sided worked as expected on my side, will merge for 10.2 package

**Pull request merged**
