### PR TITLE
Srp workflows - Debug panel system to core

### PR DESCRIPTION
**Pull request by alex-vazquez**
### Purpose of this PR
https://jira.unity3d.com/browse/XPIPELINE-264

Moving all Debug Panel framework to Core in order to be able to implement the Volumes Panel on URP.

---
### Testing status
Testing the URP debug panels work in the same way

---
### Comments to reviewers
Simply doing a templated class with common functinality for URP and HDRP and move all the interfaces to Core.

### CODE REVIEW

**Review by RSlysz — APPROVED** [review]
test

**Review by RSlysz — APPROVED** [review]
LGTM

**Review by fredericv-unity3d — APPROVED** [review]
I do not want to block the PR but there are somethings that can be improved on the framework itself.

**Comment by alex-vazquez** [comment]
@Unity-Technologies/gfx-qa-urp  Please do a smoke test to the Rendering Debugger in
- Standalone build.
- Editor.

**Review by martint-unity — APPROVED** [review]
LGTM, need QA to verify that everything works the same way before and after this change.

**Review by erikabar — APPROVED** [review]
everything is working the same way as it was before the changes. there are some issues unrelated to this PR that I will report

**Pull request merged**
