### PR TITLE
Added an initial version of under water rendering for the water system.

### PR DESCRIPTION
**Pull request by anisunity**
This PR is the next iteration of the water system, the major feature that it includes is underwater rendering.
It also fixes and improves previously existing behaviors such as:
- Decals (they were disabled on the previous version)
- Better blending for the caustics.
- Scattering height function has been improved.

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]

**Review by remi-chapelain — CHANGES_REQUESTED** [review]
Found a few things that can be split into three categories:

**1. Things that will be fixed later. (UI/UX Docs stuff)**
- Missing warning to add a collider when enabling underwater with non infinite mode [video](https://unity.gyazo.com/a9034aa374395123478c67cd8bd553fa)
- Not even sure we need an input field about it, we could force having the collider on the object directly (same as volumes)
- SSR doesn't seem to fallback properly on reflection probe underwater (docs needs to be updated)

**2. Things that can be fixed now.** 
- Missing "in meters" in the transition size tooltips.
- Reword proposition for "View Distance Multiplier" variable and tooltips
--- Variable name should be:  Maximum Absorbtion Distance Multiplier
--- "Sets the multiplier for the Maximum Absorbtion Distance underwater. A value of 0.5 means you will see half as far underwater." 


**3. Things that are known and WIP (not sure if they will be fixed in this PR)**
- Even with 0m in transition size, the "underwater" threshold seems to be always a bit above the water. Regardless of the agitation of the water
- Artefacts showing when crossing the surface for a few centimeters. (More visible when crossing vertically rather than a grazing angle [video](https://unity.gyazo.com/c2223c0b91caa2b2a8388f2009b5be93)

**Comment by anisunity** [comment]
New under water test
image
Modified the previously existing test
image

**Comment by anisunity** [comment]
Relaunching the yamato tests to update the screenshots

**Review by remi-chapelain — APPROVED** [review]
I've noted a few things in the feedback document [here](https://docs.google.com/document/d/1iXAKdWKFNIZ4PNqyHOXitbXr93zZIebHNmLrAZGRr10/edit#) that does not directly relates to the PR but should be looked at some point. 

Ready to merge ✔️

**Pull request merged**
