### PR TITLE
Improvements to HDRP reflection and refraction documentation - backport

### PR DESCRIPTION
**Pull request by markg-unity**
Documentation only.

Backport of https://github.cds.internal.unity3d.com/unity/unity/pull/17298 (which Alix Michel and Rémi Chapelain reviewed).

### CODE REVIEW

**Comment by jiaozi158** [comment]
Hi, I found that the Thickness information for Thin Refraction Model is wrong.

It should be **5cm** rather than **5mm**. (It's set to 0.05 in shader codes)

[Thin refraction model](https://github.com/Unity-Technologies/Graphics/blob/5816fd03c02c7339c554271ee6a308475ea76aa3/com.unity.render-pipelines.high-definition/Documentation~/refraction-models.md#thin-refraction-model)
Thickness

As this is a coming documentation, I think it is meaningful to correct it.

Thanks for the great documentation!

**Comment by AlixMi** [comment]
> Hi, I found that the Thickness information for Thin Refraction Model is wrong.
> 
> It should be **5cm** rather than **5mm**. (It's set to 0.05 in shader codes, and written as 5cm in [HDRP's current docs](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@14.0/manual/Refraction-in-HDRP.html#RefractionModel))
> 
> [Thin refraction model](https://github.com/Unity-Technologies/Graphics/blob/5816fd03c02c7339c554271ee6a308475ea76aa3/com.unity.render-pipelines.high-definition/Documentation~/refraction-models.md#thin-refraction-model) Thickness
> 
> As this is a coming documentation, I think it is meaningful to correct it.
> 
> Thanks for the great documentation!

Hi, the HDRP Lit shader define the distance as 0.005 :

```
#if HAS_REFRACTION
    // Note that this option is referred as "Box" in the UI, we are keeping _REFRACTION_PLANE as shader define to avoid complication with already created materials.
    #if defined(_REFRACTION_PLANE)
    #define REFRACTION_MODEL(V, posInputs, bsdfData) RefractionModelBox(V, posInputs.positionWS, bsdfData.normalWS, bsdfData.ior, bsdfData.thickness)
    #elif defined(_REFRACTION_SPHERE)
    #define REFRACTION_MODEL(V, posInputs, bsdfData) RefractionModelSphere(V, posInputs.positionWS, bsdfData.normalWS, bsdfData.ior, bsdfData.thickness)
    #elif defined(_REFRACTION_THIN)
    #define REFRACTION_THIN_DISTANCE 0.005
    #define REFRACTION_MODEL(V, posInputs, bsdfData) RefractionModelBox(V, posInputs.positionWS, bsdfData.normalWS, bsdfData.ior, bsdfData.thickness)
    #endif
#endif
```

It is in millimeters, that's why we are correcting the documentation. If you see shader codes that says 0.05, please provides the files to look at.

Thank you

**Comment by jiaozi158** [comment]
Oops, maybe I didn't see it.

I checked it in HDRP 12 and it's indeed 5mm.
Thickness

Thank you very much for explanation!

**Comment by sebastienlagarde** [comment]
we will not backport this documentation for 20.3 as it doesn't fit with current state of it in this version

**Pull request closed without merging**
