### PR TITLE
Universal/light cookies improvements2

### PR DESCRIPTION
**Pull request by eh-unity**
### Purpose of this PR
More light cookie tests.
More light cookie code quality improvements.
Fixes a light cookie bug (case 1344938) when last light cookie is disabled/removed.
Fixes a light cookie bug (case 1349073) where shadergraph was missing cookies in player build.

---
### Testing status
Ran foundation tests locally on Mac.

---

### CODE REVIEW

**Review by svens-unity — APPROVED** [review]

**Comment by eh-unity** [comment]
iPhone test failures seem unrelated.
Android test failures reproed locally and need to be looked in more detail.

**Review by phi-lira — APPROVED** [review]

**Review by erikabar — APPROVED** [review]
Looks good, verified issue 1344938

**Comment by eh-unity** [comment]
Added another fix. Just flipped shadergraph cookie keyword from "shader_feature" to "multi_compile", so it doesn't get stripped in player builds.
Added a test case for that too.
It's such simple change that I don't think extra QA is needed if the tests pass.

**Comment by eh-unity** [comment]
Looks like it's green and the errors are unrelated to this PR and LightCookies. Seems like bunch of instability errors and 2D (unrelated to light cookies).
Merging.

**Pull request merged**
