### PR TITLE
Universal/fix depth prepass to grass

### PR DESCRIPTION
**Pull request by Seongdae**
### Checklist for PR maker
- [x] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [x] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [x] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Fix an issue where depth and depth/normal of grass isn't rendered to depth texture

---
### Testing status

**Manual Tests**: What did you do?
- Create a new project and scene
- Add Terrain
- Brush detail texture
- Add SSAO renderer feature
- Play and run frame debugger
- Move to depth prepass
- There is no depth prepass for grass

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/universal%252Ffix_depthPrepassToGrass

### CODE REVIEW

**Comment by Seongdae** [comment]
> Loaded up the test scene 035_Shader_Terrain and Depth does not line up with the forward pass.
> image
> image

**Comment by Seongdae** [comment]
Applied changes requested from @Verasl

**Review by Verasl — APPROVED** [review]
LGTM depth offset fixed in latest commit, should this be backported? if so make sure you add the correct backport tags and start the backport PRs

**Review by cinight — APPROVED** [review]
Depth & Normal Prepass
Depth Prepass
working fine

**Comment by phi-lira** [comment]
What's the status on this PR? Please add `ready-to-merge` tag when all reviewers approved and ABV is green and I'll merge it.

**Comment by phi-lira** [comment]
`Universal_Stereo on Win__Standalone` not caused by this PR and already fixed in master as of today. Reunning the other failed jobs.

**Comment by Seongdae** [comment]
@phi-lira as you told I tagged 'ready-to-merge' and ABV is green now. What should I do the next for merging?

**Comment by ROBYER1** [comment]
@phi-lira Is there a backport of this for 9.0.0? I requested it through @thomas-zeng he mentioned he would make a note to @thomas-zeng to backport it to there for this special case.

**Comment by Seongdae** [comment]
@ROBYER1 let me handle it as soon as possible. Now I'm working on another jobs.

**Pull request merged**
