### PR TITLE
Fix white flash on camera cuts with volumetric 

### PR DESCRIPTION
**Pull request by FrancescoC-unity**
Fix for https://fogbugz.unity3d.com/f/cases/1270283/ 

The issue stems from the fact that the reprojection uses _previous_ frame exposure, so not only we need to wait for reprojection data to be valid but also the previous exposure needs to be valid. 

What did I test: The repro case both scrubbing and in play mode + I verified that reprojection still happens after the two frames we skip it (by checking in debugger :P )

### CODE REVIEW

**Review by TomasKiniulis — CHANGES_REQUESTED** [review]
Hey @FrancescoC-unity! Please give a short description of what was tested and what additional testing is needed

**Comment by FrancescoC-unity** [comment]
> Hey @FrancescoC-unity! Please give a short description of what was tested and what additional testing is needed

Done!

**Comment by TomasKiniulis** [comment]
> > Hey @FrancescoC-unity! Please give a short description of what was tested and what additional testing is needed
> 
> Done!

Thanks!

**Review by TomasKiniulis — APPROVED** [review]
Checked with @iM0ve since he already looked into the issue. Testing status is sufficient. Approving!

**Pull request merged**
