### PR TITLE
Fixed SimpleLit smoothness input

### PR DESCRIPTION
**Pull request by Nzollner**
### Purpose of this PR
Link to FogBugz case: https://fogbugz.unity3d.com/f/cases/1318659/
This PR fixes simple lit not using smoothness and changing alpha when "Smoothness Source" is set to "Specular Alpha".
The Smoothness value isn't handled the same way as for the lit shader is SimpleLitInput.hlsl. 
Removed changes to Base Color from smoothness slider in SimpleLitGui.hlsl

The SimpleLit material now uses the same albedo color as the Lit material.

---
### Testing status
Describe what manual/automated tests were performed for this PR.

Manually tested on windows then using Fogbugs given project.

Tested for Each universal test project on windows.

Should have automated testing from nightly.
---
### Comments to reviewers
Notes for the reviewers you have assigned.
I change how objects using simple lit is rendered for their specular highlight

### CODE REVIEW

**Comment by Nzollner** [comment]
Nightly is currently failing on master but this PR needs to pass on nightly because of changes to the SimpleLit shader

**Review by erikabar — APPROVED** [review]
it doesn't need additional testing from QA because developer already covered it.

**Review by Verasl — CHANGES_REQUESTED** [review]
Late to look at this sorry, but it looks like by doing this we would need a Material upgrader as before the value was being read from color.a or specular.a the value get's lost as it `_Smoothness` does not currently exist.

**Comment by Nzollner** [comment]
This solution comes with its own set of challenges. I will instead close the Fogbugz case by design since we want the simple lit to be as barebone as possible.

**Pull request closed without merging**
