### PR TITLE
Fixed error in SSGI when disabling decals (case 1365521).

### PR DESCRIPTION
**Pull request by anisunity**
The SSGI was using a texture it had already bound, but under and other identifier. Already fixed in master and more recent versions

### CODE REVIEW

**Review by iM0ve — CHANGES_REQUESTED** [review]
Hello, 
If this requires qa to verify - please describe what testing was already made or any tips what to test.
Or if its only for awareness - let us know in the description.
Thank you

**Review by sebastienlagarde — APPROVED** [review]
>@AnisB  does it only happen on 10.x? do we need to forward port on master?
answer yes

**Comment by sebastienlagarde** [comment]
Note: this will be for 10.8 package (so in a month)

**Comment by anisunity** [comment]
Only for QA awareness.

**Review by iM0ve — APPROVED** [review]
Thanks

**Pull request merged**
