### PR TITLE
Improved volumetric clouds presets

### PR DESCRIPTION
**Pull request by pierre-unity**
### Purpose of this PR

1. Updates for all the presets for the clouds: sparse, cloudy, overcast, stormy

2. The base frequency of the erosion has been increased slightly to reduce blockiness

3. The lut has been updated accordingly too (automatically generated with Photoshop actions), this improves the Advanced mode as well
image
image
image

4. "StormClouds" has been replaced by "Stormy" to make it more consistent with the other names for the presets

5. Sigma and shaping/erosion logic have been updated

6. Erosion max distance has been increased, to provide more micro details at very long range

7. Minor tooltips updates (adding "in meters" when needed, and clarify tooltip for the bottom altitude)

---
### Comments to reviewers

Tests will be broken, as images are now out of date because the presets have been changed.

### CODE REVIEW

**Comment by anisunity** [comment]
Already discussed with @pierre-unity fine by me, just needs to update screenshots

**Review by sebastienlagarde — APPROVED** [review]

**Review by anisunity — APPROVED** [review]
Content is approved, I merged master into it as it needs the planar reflection PR to be merged first. I'll update the screenshots afterwards

**Comment by anisunity** [comment]
I updated the tests scenes for a better coverage. I noted an issue with cloud shadows and planar that i'll fix in a seperate PR

**Comment by anisunity** [comment]
Updated the screenshots and merged master into the branch

**Pull request merged**
