### PR TITLE
[20.3][XR][URP] Fog is shifted in the right eye when Deferred rendering path is used with Single Pass Instanced render mode

### PR DESCRIPTION
**Pull request by thomas-zeng**
# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [x] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
master URP git PR: https://github.com/Unity-Technologies/Graphics/pull/6842/
Backport request Jira: https://jira.unity3d.com/browse/UUM-10266

---
### Testing status
- QA

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by ellioman — APPROVED** [review]

**Comment by thomas-zeng** [comment]
iphone failure(UniversalGraphicsTests.049_Lighting_Mixed_Subtractive) is not relevant to this PR.

**Comment by thomas-zeng** [comment]
Hi @ryanhy-unity , could you help verify this fix for XR platforms such as Quest? Thanks!

**Review by ernestasKupciunas — APPROVED** [review]
Looks good. Approving without testing.

**Review by ryanhy-unity — APPROVED** [review]
Verified bug fixed using user test project and Mock HMD on DX11 and Vulkan for windows.
Also verified no regressions in multipass with this.

Halo tested Quest as well using multipass and multiview and GLES3 and Vulkan, everything looked good there too.

Automated SRP tests have been kicked off I see, if those show no regressions as well I think this is good to go.

**Pull request merged**
