### PR TITLE
[XPipeline]Top level menu common sections and priorities

### PR DESCRIPTION
**Pull request by alex-vazquez**
### Purpose of this PR
Definition of Sections and Priorities to be used in my following PRs

---
### Testing status
Testing compilation and usage of the definitions

### CODE REVIEW

**Review by RSlysz — APPROVED** [review]
Though, I am still not convince that we should scope things in Priorities, but only a part of the fields.

**Comment by alex-vazquez** [comment]
@RSlysz , I will follow this [documentation](https://confluence.unity3d.com/pages/viewpage.action?spaceKey=DEV&title=Obsolete+API+updaters#ObsoleteAPIupdaters-Suggested%22path%22toobsolescence) to remove the priorities that are not scoped, at the end we will only have the scoped ones.

**Comment by alex-vazquez** [comment]
@jenniferd-unity , I am waiting for this PR to be merged in order to fix the other PR comments. :)

**Review by TomasKiniulis — APPROVED** [review]
This looks good. Checking template does not introduce any PR related errors or warnings

**Review by jenniferd-unity — APPROVED** [review]

**Pull request merged**
