### PR TITLE
[XPipeline] Lazy init + clean up of CoreEditorStyles

### PR DESCRIPTION
**Pull request by alex-vazquez**
---
### Purpose of this PR
Lazy initialization of all the styles in order to be able to obtain the icons from a UIToolkit context.

All the calls to Editor.Styles are restricted to the method `OnGUI`, from UIToolkit window this is not further possible so we defer the initialization of those styles to the first call to obtaining the style, That call must be on OnGUI context.

Use case the development of Converters from @martint-unity

---
### Testing status
Check that the styles are correct, nothing is broken

---
### Comments to reviewers
Needed by @martin-unity3d

### CODE REVIEW

**Review by jenniferd-unity — APPROVED** [review]
I am approving the change because code functionality seems correct but I do not understand use case or why Martin needs it. Could we clarify the PR description maybe?

**Review by martint-unity — APPROVED** [review]
LGTM
Need to have a quick QA pass on it.

**Comment by alex-vazquez** [comment]
@Unity-Technologies/gfx-qa-urp could you do a pass on this PR, open some inspectors and windows, and see that everything is working fine

**Review by erikabar — APPROVED** [review]
LGTM

**Pull request merged**
