### PR TITLE
Fix to render depth or depth/normal of waving grass

### PR DESCRIPTION
**Pull request by Seongdae**
### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Fix to render depth of waving grass in depth prepass
 - In opaque pass billboard offset was applied
 - But, those offset wasn't added to depth and depth/normal prepass
 - In case of billboard grass, the vertex result was not the same between opaque and prepasses

---
### Testing status
Add new terrain
Add detail billboard grass
Bush detail where you want to check

---
### Comments to reviewers
It wasn't working to draw depth of waving billboard grass to depth texture

### CODE REVIEW

**Review by ellioman — CHANGES_REQUESTED** [review]
I'm not 100% sure what the bug is that this PR is trying to fix. Would be nice to get that info in the description.

With a PR that got introduced today, we now have a `WavingGrassDepthNormalsPass.hlsl` file with the DepthNormals passes, which also need to be looked at.

In the same PR, four test scenes were added in the Terrain Project to test depth & normals (Forward & Deferred). Can we expand on that and include some testing for this in order to avoid any breakages in the future?

**Comment by Seongdae** [comment]
@ellioman Thanks for letting me know about `WavingGrassDepthNormalsPass.hlsl` added, I updated and merged from master to my branch.

In case of detail checked as billboard, depth prepass of waving grass didn't work and I tried frame debugger to check if the prepass worked. the prepass was called but depth didn't appear in depth texture.(depth normal is also the same)

`TerrainBillboardGrass(v.vertex, v.tangent.xy)` was applied in opaque pass before but depth prepasses didn't have it.
So I added `TerrainBillboardGrass(v.vertex, v.tangent.xy)` to vertex stage of depth and depth/normal pass then the result appeared in the frame debugger and the those work well in screen space features(ambient occlusion and shadow)

here are the comparison

[before adding `TerrainBillboardGrass(v.vertex, v.tangent.xy)`]
image

[after adding `TerrainBillboardGrass(v.vertex, v.tangent.xy)`]
image

**Comment by phi-lira** [comment]
Adding @russoh for terrain awareness

**Comment by russoh** [comment]
I'll loop in terrain team for a review, would be good to have somebody from the team, look over this.

**Comment by spaceburp** [comment]
would it be possible to cover what Elvar brought up regarding tests?

> In the same PR, four test scenes were added in the Terrain Project to test depth & normals (Forward & Deferred). Can we expand on that and include some testing for this in order to avoid any breakages in the future?

**Review by russoh — COMMENTED** [review]
The changes logically look sane to me, but I agree with other sentiments that we should probably add a test that would fail an image comparison if those changes were subsequently stripped out again. Also, do we have any larger terrain + grass demos that can be used to validate against?

**Comment by phi-lira** [comment]
@Seongdae please ping reviewers for another look.

**Comment by Seongdae** [comment]
Should I handle the tests of terrain and does it allow me to add scenes for comparing with detail shadows?

**Comment by phi-lira** [comment]
@Seongdae yes, please add tests, ping @ellioman or @russoh for help.

**Comment by ellioman** [comment]
What's the status on this PR @Seongdae ?
Regarding the test discussion, there is now two tests scenes for the DepthNormals that you can check and verify:
- 201_DepthNormalsDeferred
- 201_DepthNormalsForward

**Comment by Seongdae** [comment]
@ellioman this is to fix depth/normals of billboard grass, but there is no billboard grass in the test scenes you told me. Should I add billboard grass to the scenes?

**Comment by ellioman** [comment]
> @ellioman this is to fix depth/normals of billboard grass, but there is no billboard grass in the test scenes you told me. Should I add billboard grass to the scenes?

@Seongdae 
Yes, I think that's a good idea. Those scenes should be testing as much as possible Terrain related. So if you can structure the scene with the billboards as well, then that's perfect. 👍

**Comment by Seongdae** [comment]
Checked it in the terrain test scenes @ellioman told me, and also update the reference images now. I'm waiting for Yamato, but there seem to be an issues in the current test environment.

**Comment by Seongdae** [comment]
The tests related to Terrain were passed now.

**Review by ellioman — APPROVED** [review]

**Review by ellioman — APPROVED** [review]

**Pull request merged**
