### PR TITLE
Stripping shader variants per renderer

### PR DESCRIPTION
**Pull request by lukaschod**
### Purpose of this PR
Changing shader variant stripping to be done per renderer features instead of combined renderer features. This should eleminate some of not needed variants.

---
### Testing status
Compare build time before and after.

**Windows**
***Lighting***
Before 8588 (3:10h execution)
After 3988 (1:38h execution)

***Foundation***
Before 6489 (2:40h execution)
After 3888 (1:40h execution)

***Post Process***
Before 431 (0:23h execution)
After 206 (0:14h execution)

**iPhone**
***Lighting***
Before 13623 (4:38h execution)
After 2376 (2:14h execution)

***Foundation***
Before 12267 (3:63h execution)
After 2295 (0:57h execution)

***Post Process***
Before 333 (0:20h execution)
After 270 (0:21h execution)

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by lukaschod** [comment]
Waiting for tests to finish to compare results, if there is speed up

**Review by pbbastian — APPROVED** [review]
This looks good!

Suggestion for follow-up PR: We should have a `ShaderFeatures` per URP-asset & renderer combination, as a decent amount of the features are decided based on the renderer. But that will also require some changes to the logic in `GetSupportedShaderFeatures(UniversalRenderPipelineAsset)`

**Review by ellioman — APPROVED** [review]

**Review by phi-lira — APPROVED** [review]

**Comment by lukaschod** [comment]
Fails on master too:
URPUpdate_Top_Asset_Store on Win_DX11_playmode_mono_Linear on version trunk 
URP_Foundation on Android_OpenGLES3_Standalone_cache_il2cpp_Linear
URP_Foundation on Win_Vulkan_playmode_cache_mono_Linear
URP_Lighting on Android_OpenGLES3_Standalone_cache_il2cpp_Linear on version
URP_Lighting on iPhone_Metal_Standalone_cache_il2cpp_Linear
URP_Terrain on Android_OpenGLES3_Standalone_cache_il2cpp_Linear
URP_Terrain on iPhone_Metal_Standalone_cache_il2cpp_Linear
URP_Terrain on Android_OpenGLES3_Standalone_cache_il2cpp_Linear
URP_Terrain on iPhone_Metal_Standalone_cache_il2cpp_Linear
Source https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Fall-universal_split.yml%2523Nightly_Universal_Split_trunk/6989449/job/dependencies

**Review by erikabar — APPROVED** [review]
Build time improved by around 7%, it's still slow (the project I tested used to build within an hour and now build time is around 6hours), but it's better compared to master. Also tested visual correctness, all scenes are rendered correctly. test doc: https://docs.google.com/document/d/1gA5jm_aFQhodi-Lq1-3Hpxr1cooh7YUG5GXxi2TpT9E/edit#

**Comment by lukaschod** [comment]
Seems like only terrrain slightly slower, but others much faster. So I am merging

**Pull request merged**
