### PR TITLE
[2021.2][SG] Backport of fix to exceptions being thrown on undo-ing adding inputs to a category 

### PR DESCRIPTION
**Pull request by Nightmask3**
### Purpose of this PR
Backport of PR: #5818

Fixes bug: https://fogbugz.unity3d.com/f/cases/1348910/ in the 2021.2 branch

### CODE REVIEW

**Review by jessebarker — APPROVED** [review]
LGTM

**Comment by Nightmask3** [comment]
image

The one failure seems (OSX_Metal_playmode) seems to be a false positive test failure, think it can be ignored

**Review by bencloward — APPROVED** [review]
Tested this in 2021.2 and it's working correctly.  Nice!

**Comment by jessebarker** [comment]
> image
> 
> The one failure seems (OSX_Metal_playmode) seems to be a false positive test failure, think it can be ignored

Indeed, the editor exited with a weird error code (139 - text file busy, which is likely to be an issue with the logging itself).

**Pull request merged**
