### PR TITLE
Apply fixup for normals that are provided in OS or WS (instead of TS), when rendering double-sided, according to face + mirror vs. flip. 

### PR DESCRIPTION
**Pull request by russoh**
# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [x] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR

When normals are provided in tangent space, GetNormalWS would correctly flip resolved normals, according to use of double-sided + backface + normal mode. For normals dropped off to the master node in object space or world space, this flip was not being applied, and would have to be solved explicitly inside a Shader Graph by performing this manually with a custom function node. This PR fixes that issue.

Additionally non-surface gradient normals dropped off in object space or world space should also flip correctly. There is one use case that (still) doesn't work - reading an object space normal map, transforming that explicitly to tangent space, and dropping that off in tangent space to the master node - that was funky before, and still doesn't work, so avoid that edge case.

This change is being made to support a host of other changes in Shader Graph to better support Surface Gradients. More info here: https://github.cds.internal.unity3d.com/unity/surfgrad-examples

And here: https://docs.google.com/document/d/1XeUfc2MauivBYx82V68c_u2aQBZJxt2h9VRVu9yemGY/edit

---
### Testing status

https://github.cds.internal.unity3d.com/unity/surfgrad-examples

The "basic" example in this project has had the manual fixup nodes removed, and now works correctly by default with double-sided enabled/disabled, using world space normals dropoff, using mirror/flip for normals mode on the material.

Have compared normal modes in HD Lit, against Surface Gradient versions, and basic Shader Graph examples not using surface gradient.

---
### Comments to reviewers

For testing, use instructions here for getting the compatible build: https://github.cds.internal.unity3d.com/unity/surfgrad-examples/blob/master/README.md

I modified the SpeedTree 8 shader to remove the manual flipping of the normal, since that is now done at handoff to master node, automatically. I did not change the test image associated with the SpeedTree8 test, since this result of this change should generate the same output as before.

### CODE REVIEW

**Review by mmikk — APPROVED** [review]
This looks perfect!

**Comment by russoh** [comment]
Tests passed here: https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/sg%252Fsurfgrad%252Fdsnormalfix/.yamato%252Fall-hdrp.yml%2523PR_HDRP_trunk/6478426/job

And here:
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/sg%252Fsurfgrad%252Fdsnormalfix/.yamato%252Fall-shadergraph.yml%2523PR_ShaderGraph_trunk/6478047/job

**Review by nerites — APPROVED** [review]
Checked ST8 shadergraph and modified normal transformation subshadergraph to work with these changes! Thanks!

**Comment by sebastienlagarde** [comment]
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/sg%252Fsurfgrad%252Fdsnormalfix/.yamato%252Fall-hdrp.yml%2523PR_HDRP_CUSTOM-REVISION/6598499/job

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
Added @Unity-Technologies/gfx-qa-hdrp for validation before merging

**Comment by sebastienlagarde** [comment]
custom revision is green: https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/sg%252Fsurfgrad%252Fdsnormalfix/.yamato%252Fall-hdrp.yml%2523PR_HDRP_CUSTOM-REVISION/6598499/job/pipeline

**Review by TomasKiniulis — APPROVED** [review]
Tested HDRP Object Space and World Space normals with various material types. Normals change correctly now according to Double Sided mode. Also checked on VFX graph.

Object Space DP modes master:
https://user-images.githubusercontent.com/50582134/117001568-30be4500-aceb-11eb-83ce-1cbac24c7a13.mp4
Object Space DP modes PR:
https://user-images.githubusercontent.com/50582134/117001630-42075180-aceb-11eb-8853-6c711524b474.mp4

World Space DP modes master:
https://user-images.githubusercontent.com/50582134/117001716-58ada880-aceb-11eb-9435-00c608947337.mp4
World Space DP modes PR:
https://user-images.githubusercontent.com/50582134/117001734-6105e380-aceb-11eb-8d10-6bfcfbbe69a7.mp4

Object Space DP modes on VFX:
https://user-images.githubusercontent.com/50582134/117001886-8f83be80-aceb-11eb-911e-b327b5aa9e66.mp4

**Pull request merged**
