### PR TITLE
2021.1/universal/deferred soft shadow variant fix

### PR DESCRIPTION
**Pull request by kaychang-unity**
---
### Purpose of this PR
_SHADOW_SOFT variant did not always used multi_compile_fragment option.
Backport from master branch: https://github.com/Unity-Technologies/Graphics/pull/5056

### CODE REVIEW

**Comment by kaychang-unity** [comment]
PR URP on 2021.1 all green!

**Review by eh-unity — APPROVED** [review]
LGTM.

**Review by nigeljw-unity — APPROVED** [review]
LGTM

**Review by erikabar — APPROVED** [review]
approved without testing as the change is not big

**Pull request merged**
