### PR TITLE
Fixed gles2 shaders compilation.

### PR DESCRIPTION
**Pull request by kaychang-unity**
---
### Purpose of this PR
Fixed GLES2 shader compilation issues (Android, GLES2 platform).

---
### Testing status

**Manual Tests**: What did you do?
- [ X ] Opened test project + Run graphic tests locally
- [ X ] Built a player

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

**Yamato**: (Select your branch):
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/universal%252Ffix-gles2

---

### CODE REVIEW

**Comment by kaychang-unity** [comment]
For XR code change: it is not possible to guard `#pragma multi_compile` with platform `#define` because the preprocessor runs after the custom Unity `#pragma` are processed. Instead, we have to implement fallback shaders (subshader blocks with `#pragma only_renderer` and `#pragma exclude_renderer` keywords).

**Review by phi-lira — APPROVED** [review]

**Review by erikabar — APPROVED** [review]
verified the fix for GLES2 shaders compilation errors

**Comment by fabien-unity** [comment]
As discussed over Slack, the fix for XROcclusionMesh is handled here: https://github.com/Unity-Technologies/Graphics/pull/1960
I'd suggest to either remove the changes from this PR, or wait for it to land.

**Comment by kaychang-unity** [comment]
@erikabar I copied the fixes from #1960 into this branch.

**Comment by kaychang-unity** [comment]
I'm ok with waiting for #1690 to land, then land this PR.

**Comment by kaychang-unity** [comment]
Changed of plan, #1960 was closed, this PR supersedes it.

**Comment by kaychang-unity** [comment]
@phi-lira Do you want to merge in master?
It only fixes GLES2 compilation errors (tested locally).
The currently failures on Yamato look to be the same as master (not introduced by this PR, which does change test results).

**Comment by kaychang-unity** [comment]
Incorrect pass order from previous commit (that's a different branch code). Rerunning Yamato again...

**Comment by phi-lira** [comment]
Ok. Waiting for yamato to finish.

**Comment by phi-lira** [comment]
Yamato failures are fixed in master.

**Pull request merged**
