### PR TITLE
Decal small fixes

### PR DESCRIPTION
**Pull request by lukaschod**
### Purpose of this PR
- Updating vulkan decal reference images as it regressed.
- Changing HDRP Decal Projector component path name with HDRP
- Changing URP Decal Projector component path name with URP

---
### Testing status
Describe what manual/automated tests were performed for this PR

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by phi-lira — APPROVED** [review]

**Review by jenniferd-unity — CHANGES_REQUESTED** [review]
Could we confirm the path?
I understood we wanted "URP Decal Projector" without a submenu.

Also could you explain what you tested?

**Comment by TheoWong-pixel** [comment]
Yes, if possible we would like to avoid a sub menu and just have the prefix. If the plan is to merge the two decal projectors together it keeps this menu location relatively the same and also menus with only one items are not encouraged as it makes the users work harder to get to the content.

**Review by TheoWong-pixel — APPROVED** [review]

**Review by jenniferd-unity — APPROVED** [review]
Thanks

**Comment by lukaschod** [comment]
As this is UI and reference image changes. Will skip tests. Merging

**Pull request merged**
