### PR TITLE
Add bounding sphere support to the SS AABB generation pass

### PR DESCRIPTION
**Pull request by EvgeniiG**
### Purpose of this PR
See title + comments in code. TLDR: tighter bounding boxes for lights using bounding spheres.
Also made bounding spheres a little tighter for certain light types.
Bonus: fix https://fogbugz.unity3d.com/f/cases/1283644/

---
### Testing status
Ran the graphics tests locally, tested manually a little bit (again, using the scenes in the graphics tests).

Yamato: https://yamato.cds.internal.unity3d.com/job/3875925

---
### Comments to reviewers
We should do more exhaustive manual testing to make sure lights don't disappear when they are in tricky configurations (camera inside the light, light behind the camera, etc) as well as with advanced camera configurations (tilt-shift, oblique near plane, orthographic, etc).

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
Adding Francesco as he have made this fix: https://github.com/Unity-Technologies/Graphics/pull/2231/

**Review by FrancescoC-unity — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
For QA: automated testing is working. As it is something that need to be validated in a lot of different situation, I suggest to merge this PR and we will see during the QA test week with upgrading of projects if we get any new issue.

**Review by JMargevics — COMMENTED** [review]
Hey, I think smoke test sufficiently covered it, We've checked spaceship, amalienburg, template, planar reflections with out FTP scene. In addition I've tried to cover tricky situation like Evgenii mentioned. No regressions were found functionally and performance-wise ✅

**Comment by EvgeniiG** [comment]
Thank you, Jans.

**Pull request merged**
