### PR TITLE
Fix 1299233 ies resize bug

### PR DESCRIPTION
**Pull request by skhiat**
Fix:
https://fogbugz.unity3d.com/f/cases/1299233/ (cf. Video)
image
Repro bug:
To see Atlas Display Cookie Atlas (make sure Clear Cookie Atlas is *NOT* checked)
1. Change IES Size to 64
2. Change IES Size to 512
Notice when clear cookie atlas we don't have the issue.

This PR fix this issue.
Make sure that don't break the others features of the Atlas (for example Animated RenderTexture).
NZueNdZniI

### CODE REVIEW

**Review by sebastienlagarde — COMMENTED** [review]
you miss changelog

**Comment by skhiat** [comment]
> you miss changelog

[Fixed]

**Review by sebastienlagarde — APPROVED** [review]

**Review by iM0ve — APPROVED** [review]
All good from my side.

Tested:
* That when IES doesnt fit in the cookie atlas, it will no longer be rendered
* When IES doesnt fit the atlas an error now will be shown (during play and without)
* Checked render texture cookie still works as before
* Verified that regular spotlight cookie textures still work

Light no longer rendered and error
https://user-images.githubusercontent.com/36502659/104615282-c5942880-5691-11eb-8060-b6f493b75c1e.mp4

Animated cookie texture works
https://user-images.githubusercontent.com/36502659/104615289-c6c55580-5691-11eb-9d5c-e369a40c9287.mp4

Spotlight cookie texture works
https://user-images.githubusercontent.com/36502659/104615291-c75dec00-5691-11eb-955a-86b68dff16cf.mp4

**Comment by sebastienlagarde** [comment]
This Pr have been reverted as it was causing gc alloc

**Pull request merged**
