### PR TITLE
Fixed Shadow Matte not appearing in ray tracing effects (case 1364005).

### PR DESCRIPTION
**Pull request by anisunity**
image
https://fogbugz.unity3d.com/f/cases/1364005/

This PR makes the ray traced effect receive the shadow matte on unlit shaders (reflection, gi and recursive ray tracing).
This also removes the dithering for ray tracing.
Fixes a very very bad behavior that was using the binormal as a normal in the shadow matte.

Testing status
Issue doesn't repro on the dataset of the user anymore.
Modifed one of the tests to cover this new behavior.

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]

**Comment by patrickp-unity3d** [comment]
Awesome, thank you!

**Comment by sebastienlagarde** [comment]
yamato green waiting QA approval

**Review by remi-chapelain — APPROVED** [review]
Pair tested ✔️ 
3 tests have been added to check shadow matte tint, shadow matte light type support  in Ray Traced Reflections

**Comment by remi-chapelain** [comment]
Tests are green locally ✔️ 
Launched [yamato DXR tests](https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Ffix-1364005/.yamato%252Fall-hdrp_dxr.yml%2523PR_HDRP_DXR_trunk/9791667/job).

**Comment by anisunity** [comment]
Did the formatting manually

**Comment by patrickp-unity3d** [comment]
Hi! Is the transparent shadow matte picked up by raytracing effects, or only the opaque shadow matte? I've tried in latest 2021.2 and the transparent shadow matte doesn't appear to be picked up.
@sebastienlagarde @anisunity

**Comment by remi-chapelain** [comment]
No, transparents are not included in the reflections, whether you use classic SSR or RayTraced Reflections.

**Comment by patrickp-unity3d** [comment]
Ok, thanks for confirming 👍

**Pull request merged**
