### PR TITLE
[10.x.x] Fix Redirect Node to work with CFN

### PR DESCRIPTION
**Pull request by marctem**
# Purpose of this PR
Fix bug with CustomFunctionNode not working with redirect node inputs. https://fogbugz.unity3d.com/f/cases/1235999/
Also fixed existing redirect node automated test to actually catch this bug in the first place.

# Testing status
## Manual Tests
Tried redirect node with all CFN input types as well as Subgraph inputs (bug did not repro there but just to be sure)

## Automated Tests
The redirect node test previously checked the node for errors but did not actually try to compile the shader - which is where this error was reported.

### CODE REVIEW

**Review by Nightmask3 — APPROVED** [review]

**Comment by ZbignevM** [comment]
Verified that the changes in this PR fix the bug.

Although, there are some sides changes to the behaviour of the CFN after these changes:

1. Previously if I had Input of Matrix4 (worked this some other Matrices and Vectors too), I could output any smaller Matrix or Vector. It didn't throw errors and worked (ex. Vector1 would be 1st value of Matrix)
Now it throws errors about concretization and truncation.

2. The visual indication of error in the node doesn't seem to be consistent. Now Matrix4 would showcase the error in node (tiled magenta/black), but Matrix3 would provide correct visualization even though saving the asset would still throw the error

**Comment by alindmanUnity** [comment]
Hey Z, could you give some more details on how you're getting those new states? I'm seeing the exact same behavior on master as on this branch for both of the points you mentioned. 
I'm also only seeing that Vector 2, 3, and 4 throw truncation errors when casting from a larger matrix to a smaller value. Vector 1 and all other matrix types compile. 
I'm also not seeing the error behavior you're describing. All of the error states are consistent with when errors appear in the console, and saving the asset doesn't have any errors in itself. Only the shader has compilation issues.

**Comment by ZbignevM** [comment]
Investigated more and realized I had different inputs in the previous version, so the behavior of error handling doesn't change, it was always like it.

How to get it:
1. Add an input of Vector1 in CFN
2. Create Vector1 and attach it to that input
3. Change input type in CFN to Matrix4
4. You'll see errors & warnings in the console and visual indication of node being incorrect in the preview
5. Change input type in CFN to Matrix3 
6. You'll see now that no errors are thrown and the preview looks correct 
If you try saving the asset it will only throw an error on that point
nZsO98tGmp

**Review by ZbignevM — APPROVED** [review]
Fixes the bug. Concerns found are not related to this PR (present previously too).

**Review by cdxntchou — APPROVED** [review]

**Comment by marctem** [comment]
HD Failures match trunk, merging.

**Pull request merged**
