### PR TITLE
[Backport][2019.4 / 7.x.x] Fix for Opaque Texture + MSAA being rendered black on old Apple GPUs 

### PR DESCRIPTION
**Pull request by manuele-bonanno**
Backport of [this PR](https://github.com/Unity-Technologies/Graphics/pull/2863)

### Purpose of this PR
fix for [ISS case 1315879](https://fogbugz.unity3d.com/f/cases/1315879).

new API SystemInfo.supportsStoreAndResolveAction (bump to 2019.4.23f1 min required version) [PR](https://ono.unity3d.com/unity/unity/pull-request/121664/_/2019.4/platforms/mobile/store_and_resolve_action_api).

Older Apple GPUs don't support ResolveAndStore store actions. Because of this we fall back to a Resolve store action, which discards the multisampled RT contents. Any following Load load action will then load a discarded RT, resulting in a black texture.

Because of this we need to disable MSAA when performing a separate Opaque Texture pass on hardware without StoreAndResolve support (i.e. Apple GPUs <= A8).

---
### Testing status
Tested locally using the fogbugz issue repro project.

**Before**:
image

**After**:
image

### CODE REVIEW

**Review by ellioman — APPROVED** [review]

**Comment by manuele-bonanno** [comment]
the test failures are VFX and HDRP related, so not relevant to this PR

**Review by marctem — APPROVED** [review]
Clearing SG code lock from version bump.

**Review by robertas-unity — APPROVED** [review]
Tested the fix using the project attached in fogbugz report - looks good.
Tested with iPhone 6

Unity version used:
Version 2019.4.24f1 (4e106a1d61c6)
Sat, 20 Mar 2021 15:28:53 GMT
Branch: 2019.4/staging

**Comment by ellioman** [comment]
Yamato issues not related to this PR.

**Pull request merged**
