### PR TITLE
Fix issues with bloom sampling outside 

### PR DESCRIPTION
**Pull request by FrancescoC-unity**
Fix for https://fogbugz.unity3d.com/f/cases/1277645/

This fixes issues around guardbands and bloom. 

There were a couple of issues:
 - some borders were rejected when shouldn't. 
 - In upsample the clamp was not generous enough. 
 - The clamping was not done upon sampling the high res texture. 
 - The UV clamping for the low res version was using the wrong texel size. 

I also removed the guardbands clear as I think it could be hiding bugs that can be fixed by clamping accordingly the UVs. 

**What have I tested**: Checked repro case, tried various bloom parameters and rescaled the view a fair lot.

### CODE REVIEW

**Comment by JulienIgnace-Unity** [comment]
Did you check the graphics tests locally? I suspect this may slightly change some screenshots maybe?

**Comment by FrancescoC-unity** [comment]
> Did you check the graphics tests locally? I suspect this may slightly change some screenshots maybe?

First half then apparently unity crashed :D ( I thought it was done ), running them now agian.

**Review by iM0ve — APPROVED** [review]
The black bars are significantly reduced, however they are still visible slightly when Scattering is set to 1. In real projects with realistic scattering it should not be visible.

bars

Functional bloom settings test

Screen Shot 2020-09-18 at 13 26 45

**Whats tested:**
* Resizing editor views
* Resizing whole editor window
* Checking that bloom parameters still work
* Build player on mac to see if any issues occur

**Review by JulienIgnace-Unity — APPROVED** [review]

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Ffix-bloom-side-black/.yamato%252Fall-hdrp.yml%2523All_HDRP_trunk/3611012/job/pipeline

**Pull request merged**
