### PR TITLE
Universal bugfix multiediting fix lights

### PR DESCRIPTION
**Pull request by martint-unity**
Purpose of this PR
Fixes the multi editing issue in this fb case
https://fogbugz.unity3d.com/f/cases/1289620/

Testing status
Created several cameras and tested this property locally.

### CODE REVIEW

**Comment by martint-unity** [comment]
Still have the issues @simon-engelbrecht-soerensen showed here
https://github.cds.internal.unity3d.com/unity/Graphics/pull/2992
the ui doesnt update properly... will work on that.

**Comment by Verasl** [comment]
Are these changes supposed to work between light types? like having a spot and a point light selected at the same time? In this case, currently the bias settings are not even visible.

**Comment by martint-unity** [comment]
Still have the issues @simon-engelbrecht-soerensen showed here
https://github.cds.internal.unity3d.com/unity/Graphics/pull/2992
the ui doesnt update properly... will work on that.
I will not do that in this PR. We should make another bug-report for that. Since it looks like it is more involved than I initialy thought.
@Verasl I Don't think they should work between light types.

**Review by Verasl — APPROVED** [review]
LGTM

**Review by simon-engelbrecht-soerensen — APPROVED** [review]
Works as expected!

**Review by simon-engelbrecht-soerensen — APPROVED** [review]
lgtm

**Comment by phi-lira** [comment]
Failures not related to this PR.

**Pull request merged**
