### PR TITLE
[Draft] [11.x] Fix view direction for URP

### PR DESCRIPTION
**Pull request by marctem**
*Summary:*
Fix for https://fogbugz.unity3d.com/f/cases/1217639/

Manually Tested:
- That the bug no longer reproduces
- That the other spaces seem fine in URP

Technical Risk: 0.1/4
Halo Effect: 2/4 - I looked around but didn't see this effecting anything else

*Automation:*
BROKEN! That's why I'm leaving this as draft.

Note from Zack: Test should fail, I'll grab those generated shaders and put them in test project (as I can't trust my own home machine to produce usable images)

So we need new test images for the changed behavior.

*Docs*
We also need an upgrade guide

### CODE REVIEW

**Comment by phi-lira** [comment]
What's missing for this one?

**Comment by phi-lira** [comment]
@marctem @alindmanUnity what's status on this PR?

**Comment by alindmanUnity** [comment]
> @marctem @alindmanUnity what's status on this PR?

Updated test images and upgrade guide docs, as it changes previous behavior

**Comment by phi-lira** [comment]
Please resolve merge conflicts and change PR to review/run ABV. LGTM.

**Comment by phi-lira** [comment]
@alindmanUnity what's the status on this PR?

**Comment by phi-lira** [comment]
Is this PR waiting for branchoff?

**Comment by alindmanUnity** [comment]
we're going to close this PR for now, in favor of a bug tracker and JIRA ticket. we want to investigate if we can leverage the new upgrading system for a better user experience

**Pull request closed without merging**
