### PR TITLE
[HDRP] Improves robustness of detail normal mapping when scale = 0 (and not using surface gradients)

### PR DESCRIPTION
**Pull request by eturquin**
This PR addresses: https://fogbugz.unity3d.com/f/cases/1399548/

**Before:**
Using some detail maps with null scale resulted in null normals.

**Now:**
Null scale will produce a "neutral" normal, as expected.

**Note:**
We could consider normalizing the detailNormal in a more general way, rather than in this specific use-case, but I went for the minimal amount of changes and risks of unwanted side-effects.

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]

**Review by RemyUnity — APPROVED** [review]
LGTM

**Comment by remi-chapelain** [comment]
While this is still a slight improvement for the case where the detail map scale is zero , I don't really think this fixes the issue overall because on some cases when having both normal and detail map, it's still enough for some reasons to flip the normal onto the other hemisphere :|

https://user-images.githubusercontent.com/57442369/152398657-adf0cffb-d69c-4094-ab50-4d94c58e6d18.mp4

I don't know if we can do anything about it while keeping the function (UnpackNormalAG) that infer the Z coordinate of the normal from the XY but wanted to highlight that !

**Comment by sebastienlagarde** [comment]
any update?

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
discussed with Remi, we will merge the PR, waiting for Yamato

**Review by remi-chapelain — APPROVED** [review]
The fix is still an improvement so we will merge. 

While this does not really fully fix the problem, it has been decided to discuss and maybe find a way to use surface gradient in the future rather than trying to fix the way normal map are blended right now.

**Pull request merged**
