### PR TITLE
Vertex ID, Instance ID, and Stereo Eye Index ShaderGraph nodes for URP and HDRP

### PR DESCRIPTION
**Pull request by esmelusina**
### Purpose of this PR
Provides users the ability to access VertexID (in the vertex stage), InstanceID, and Stereo Eye Index through ShaderGraph nodes.

---
### Testing status
Graphics tests will come, post-haste, in a follow-up PR to avoid added blocking and to take advantage of an incoming refactor to our testing process. Manual tests by QA and stakeholders in the meantime.

---
### Comments to reviewers
A few very minor changes to ShaderGraph's implementation by HDRP and URP to properly expose VertexID. If you are from one of those teams, feel free to review those changes specifically.

### CODE REVIEW

**Review by elizabeth-legros — APPROVED** [review]

**Review by LandonTownsendUnity — APPROVED** [review]
Tested Vertex ID for all available master nodes (except VFX, which it won't work in because it is vertex stage exclusive).
Was able to confirm the behavior for instance ID.
Tested eye ID in both URP and HDRP.

**Review by ellioman — APPROVED** [review]

**Review by joshua-davis — APPROVED** [review]

**Review by marctem — APPROVED** [review]
Re-approving to clear code lock.

**Comment by kroatoa** [comment]
For the testing status, can you clarify how what is being blocked? 
How are you tracking the work for adding the missing tests?

**Review by kroatoa — COMMENTED** [review]
setting review status

**Comment by esmelusina** [comment]
> For the testing status, can you clarify how what is being blocked?
> How are you tracking the work for adding the missing tests?

My team is tracking in Jira and it is an internal team block.
Task for improved node testing framework: [GSG-245]
Task for testing these nodes: [GSG-332]

Graphics test reference images cannot be merged, so effectively only one team member can work on them at a time. They also have to be modified across all tested platforms. The GSG-245 task intends to decouple this relationship and reformat our tests in a non-blocking manner. GSG-245 and GSG-332 are both planned for our current sprint and well in advance of the 21.2 freeze.

These node implementations were previously fully tested in another PR (#2937), but was closed and simplified due to test blocks.

**Review by kroatoa — APPROVED** [review]
Thank you for the clarification.

**Comment by RR7** [comment]
any chance the vertex ID can go into HDRP 10?

**Pull request merged**
