### PR TITLE
[ShaderGraph] Add "Sprite" option to Main Preview, use as default for Sprite subtargets

### PR DESCRIPTION
**Pull request by dhsavell**
### Purpose of this PR

This PR introduces a "Sprite" preview mode (a quad that can't be rotated). Additionally, Sprite is now used as the default preview for Universal sprite subtargets. FogBugz case: https://fogbugz.unity3d.com/f/cases/1343708/

---
#### Sprite Preview

- Open a Shader Graph asset and enable the Main Preview if not already visible
- Observe that the preview mesh can be zoomed and rotated as normal
- Right-click on the Main Preview and select Sprite
- Observe that the resulting preview quad can be zoomed, but not rotated
- Select a different mesh and see that zoom/rotate functionality is restored

https://user-images.githubusercontent.com/10332426/121578273-7fe94b00-c9f8-11eb-8211-b8a68eb5c938.mp4

(Around 5s the menu gets cut off -- the sprite option was selected). Additionally, try saving and re-opening a graph with the Sprite preview mode. Note that the fixed orientation is preserved.

#### Sprite as Default for URP Sprite Subtargets

- Create a new URP Lit or Unlit graph. Observe that the standard sphere preview is used.
- Create a new URP Sprite Lit, Sprite Unlit, or Sprite Custom Lit graph. Observe that the new sprite preview is used.
- In the new Sprite graph, change the material to a non-sprite one (Lit, Unlit, or Decal) using the Graph Settings tab in the Graph Inspector. Observe that the preview changes to a sphere.
  - Change the material back to Sprite Lit/Unlit and observe that the preview changes to a sprite.
- Change the Main Preview mesh manually through its context menu, and notice that the user's choice is honored regardless of material.
  - Save, close, and reopen the graph and see that the user choice persists.

https://user-images.githubusercontent.com/10332426/121958195-6a925a80-cd31-11eb-9f63-8517170544b1.mp4

#### Multiple Targets

- Create a shader graph with a Universal sprite target and arbitrary HD target (none of the HD materials use the sprite preview).
- Without changing the Main Preview mesh, switch between HD/Universal pipelines and observe that the preview updates to match the active target's preference.

https://user-images.githubusercontent.com/10332426/123983576-f93de300-d991-11eb-8bf0-608a9f997943.mp4

- As with above, if the user selects a custom mesh, it is used over the default in all cases.

https://user-images.githubusercontent.com/10332426/123984703-d9f38580-d992-11eb-966a-6dea6ed73418.mp4

#### Sprite Orientation

- Observe that sprite preview is oriented as expected using the test graph below.

image

#### Vertex Animation

- Observe that vertex position is reflected in the sprite preview below.

image

#### Yamato

Failed jobs have corresponding failures on master:

- [URP_Lighting on iPhone_Metal_Standalone_il2cpp_Linear on version 2021.2](https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Furp_lighting-iphone-metal.yml%2523URP_Lighting_iPhone_Metal_Standalone_il2cpp_Linear_2021.2/7463895/job)
- [URP_Terrain on iPhone_Metal_Standalone_il2cpp_Linear on version 2021.2](https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Furp_terrain-iphone-metal.yml%2523URP_Terrain_iPhone_Metal_Standalone_il2cpp_Linear_2021.2/7463897/job)

### CODE REVIEW

**Review by esmelusina — APPROVED** [review]
Did some manual testing, looks good.

Adding a note for other reviewers: We don't currently document the actual list of options available for the master preview. The scope of this change isn't to correct that gap, so we don't expect this to have any docs additions.

**Comment by dhsavell** [comment]
@esmelusina and I discussed this a little more and decided to do everything -- both adding the Sprite option and making it the default for sprite (sub)targets -- in one PR. Reverting to a draft until all of that is ready.

**Review by pbbastian — APPROVED** [review]

**Comment by LandonTownsendUnity** [comment]
Can you test the following things:
1. What happens if you use multiple targets, like HDRP and URP, with this feature? If you have an HDRP target and switch the URP material to sprite, are there any errors?
2. If you render a sprite using this feature, does the sprite appear facing the correct way in the preview? (It would be helpful to have an image of this as this is probably the most important thing to test)
3. Does vertex animation (changing vertex positions) work on the sprite preview?

**Review by LandonTownsendUnity — APPROVED** [review]
Thank you for testing those things, approving!

**Pull request merged**
