### PR TITLE
[UniversalGraphicsTest] New MSAA Graphics test

### PR DESCRIPTION
**Pull request by manuele-bonanno**
---
### Purpose of this PR
Added new MSAA test: 146_MSAA_RenderToBackbuffer to test scenarios where the final MSAA resolve is done without any extra post processing/intermediate passes enabled. On some platforms (Vulkan/Metal) this results in an implicit resolve directly to the backbuffer and there wasn't any test coverage

image

---
### Testing status
ran tests locally + all graphics test on each platform on Yamato: ABV, iPhone, Android Vulkan, Android GLES3

---

### CODE REVIEW

**Comment by manuele-bonanno** [comment]
all the tests failed do not involve the specific test added by this PR

**Comment by manuele-bonanno** [comment]
closing PR temporarily to verify something

**Comment by manuele-bonanno** [comment]
fixed the camera test settings and updated the reference images again

**Comment by manuele-bonanno** [comment]
the test 146 passed on all platforms

**Review by ellioman — APPROVED** [review]

**Review by phi-lira — APPROVED** [review]

**Comment by phi-lira** [comment]
VFX Test failure: Known issue because we are running against Unity 2021.1.a5 (fixed in a6)
 XR issue, Test 072 should be disabled, it's being addressed in other PR.

**Comment by phi-lira** [comment]
Android Failures not related to this PR as well.

**Pull request merged**
