### PR TITLE
Hdrp: Move packing and dots instancing code to right location

### PR DESCRIPTION
**Pull request by sebastienlagarde**
# Purpose of this PR

This PR is just moving code to their "correct" location.

# Testing status

## Links
**Yamato**: (Select your branch) https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics
> Any test projects or documents to go with this to help reviewers?

# Comments to reviewers
> Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
Yamato is green for the code move (the red part are due to different issue).

**Comment by JussiKnuuttila** [comment]
Code changes look good to me, I didn't find the Hybrid CI in Yamato so I queued that to run.

**Comment by sebastienlagarde** [comment]
> I'll quickly test this locally as well to make sure there are no problems with ObjectToWorld. I remember there were some problems when this code was originally written, which is why the macros were originally in a weird place in the code.

Thanks, 

you can find the Yamato for Hybrid here: https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Fupm-ci-abv.yml%2523all_project_ci_nightly_2020.1/2167305/job/pipeline

**Comment by sebastienlagarde** [comment]
Replace by this PR: https://github.com/Unity-Technologies/Graphics/pull/442

**Pull request closed without merging**
