### PR TITLE
[VFX/Test] Add exclusion solution for specific target

### PR DESCRIPTION
**Pull request by PaulDemeulenaere**
### Purpose of this PR
1. Exclude known platform issue with the TestCaseFilter
- https://jira.unity3d.com/browse/URP-723
- https://fogbugz.unity3d.com/f/cases/1273379/

*URP*
image

*HDRP*
image

2. Avoid instability : https://jira.unity3d.com/browse/URP-713
image
image

=> Disabling sorting at 0df79e6f1ca2c83ffaf358340c8a5642c65c7a57
image

---
### Testing status
Yamato 
- [Public](https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/vfx%252Ftest%252Fadd-platform-filter) 🟢 
- [Internal](https://yamato.cds.internal.unity3d.com/jobs/339-ScriptableRenderPipelinePrivate/tree/vfx%252Ftest%252Fadd-platform-filter) ⌛ 

---
### Comments to reviewers
The OSXPlayer reference image wasn't up to date, I've taken the opportunity of this PR to update them. These change are backportable to 2021.1 as well.

### CODE REVIEW

**Comment by PaulDemeulenaere** [comment]
@julienf-unity I'm struggling to retrieve all image reference for NDA platform, I will move this to "Ready for review" once this [PR](https://github.cds.internal.unity3d.com/unity/ScriptableRenderPipelinePrivate/pull/73) is ready

**Comment by PaulDemeulenaere** [comment]
Remark from @theo-pnv : It would be nice to also exclude depth issue on X1 since this PR will be backported in 21.1.

**Comment by PaulDemeulenaere** [comment]
> Remark from @theo-pnv : It would be nice to also exclude depth issue on X1 since this PR will be backported in 21.1.

image
Resolve at https://github.com/Unity-Technologies/Graphics/pull/3369/commits/631e90b5101b4a85e778101438a413993f966931

**Review by julienf-unity — APPROVED** [review]

**Comment by PaulDemeulenaere** [comment]
I'm merging https://github.cds.internal.unity3d.com/unity/ScriptableRenderPipelinePrivate/pull/73 synchronously

**Pull request merged**
