### PR TITLE
Add test for DXR alembic support

### PR DESCRIPTION
**Pull request by nerites**
# **Please read;**
## **PR Workflow for the Graphics repository:**
* **All PRs must be opened as draft initially**
* Reviewers can be added while the PR is still in draft
* The PR can be marked as “Ready for Review” once the reviewers have confirmed that **no more changes are needed**
* Tests will start automatically after the PR is marked as “Ready for Review”
* **Do not use [skip ci]** - this can break some of our tooling
* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [x] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [x] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?
Adding test coverage for alembic meshes in DXR. Takes a snapshot on frame 5 of a sphere whose mesh is replaced each frame using a script written by @IonutNedelcuUnity, such that there is no need to depend on the alembic package. 

---
### Testing status
Generated reference images on Yamato. It looks like standalone player build is failing, but only because of the security permissions popup not being handled properly on the VM.

---
### Comments to reviewers
Do we need changelog updates for changes to the text projects?

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
redirect to HDRP/staging as this is where we develop stuff for hdrp

**Comment by sebastienlagarde** [comment]
I get an error in Yamato with this PR
1:14:09.293 INF] Compiler
	severity: Error
	message: Assets\Scenes\6000_VertexFormats\ProceduralMesh\ProceduralMesh.cs(7,7): error CS0101: The namespace '<global namespace>' already contains a definition for 'ProceduralMesh'

on 2020.2. Does this PR expect a C++ changed not yet landed in 2020.2 ?

**Comment by nerites** [comment]
> 
> 
> I get an error in Yamato with this PR
> 1:14:09.293 INF] Compiler
> severity: Error
> message: Assets\Scenes\6000_VertexFormats\ProceduralMesh\ProceduralMesh.cs(7,7): error CS0101: The namespace '' already contains a definition for 'ProceduralMesh'
> 
> on 2020.2. Does this PR expect a C++ changed not yet landed in 2020.2 ?
> 
> Edit: ah no, this PR conflict with another test already added by @IonutNedelcuUnity iirc

Thanks for finding this! I'll pull trunk and clean up the conflict.

**Comment by sebastienlagarde** [comment]
@nerites is it the expected result of the test: https://yamato-artifactviewer.prd.cds.internal.unity3d.com/d1d92e3d-3e36-47e5-b4d5-3089c145a250%2Flogs%2FTestProjects%2FHDRP_DXR_Tests%2Ftest-results/Assets/ActualImages/Linear/WindowsEditor/Direct3D12/None/6001_Alembic.png  it is really weird :)

**Comment by nerites** [comment]
> 
> 
> @nerites is it the expected result of the test: https://yamato-artifactviewer.prd.cds.internal.unity3d.com/d1d92e3d-3e36-47e5-b4d5-3089c145a250%2Flogs%2FTestProjects%2FHDRP_DXR_Tests%2Ftest-results/Assets/ActualImages/Linear/WindowsEditor/Direct3D12/None/6001_Alembic.png it is really weird :)

Yes; I can probably tilt the camera up a bit more to match Ionut's test though ':)

**Comment by sebastienlagarde** [comment]
@tian-unity your test is non deterministic. Local run are not consistent, neither on Yamato. Anything you can do about it?
https://yamato-artifactviewer.prd.cds.internal.unity3d.com/607a1c13-13ca-448f-8327-4ee71e9c4500%2Flogs%2FTestProjects%2FHDRP_DXR_Tests%2Ftest-results/TestReportV1.html

We have a Alembic test in HDRP Test and we don't have this issue, maybe take a look at it. IIRC it was added by @TomasKiniulis

**Comment by nerites** [comment]
> 
> 
> @tian-unity your test is non deterministic. Local run are not consistent, neither on Yamato. Anything you can do about it?
> https://yamato-artifactviewer.prd.cds.internal.unity3d.com/607a1c13-13ca-448f-8327-4ee71e9c4500%2Flogs%2FTestProjects%2FHDRP_DXR_Tests%2Ftest-results/TestReportV1.html
> 
> We have a Alembic test in HDRP Test and we don't have this issue, maybe take a look at it. IIRC it was added by @TomasKiniulis

That's odd, I thought I was getting deterministic results before making the camera transform change by using the wait N frames functionality. I'll investigate today.

**Comment by TomasKiniulis** [comment]
> We have a Alembic test in HDRP Test and we don't have this issue, maybe take a look at it. IIRC it was added by @TomasKiniulis

Was added by @JMargevics some time ago https://github.com/Unity-Technologies/Graphics/pull/1582

**Comment by sebastienlagarde** [comment]
Yamato give another result. Maybe try to update with shots from Yamato and retrigger it

**Comment by sebastienlagarde** [comment]
guess we will have a difference between local test and yamato test, but that yamato test should be always the same?

**Comment by sebastienlagarde** [comment]
Hey, you have increase the XR scale to 1.5 and it fail from a very small gap:


  Expected: less than or equal to 0.000149999993f
  But was:  0.00150095485f

But the result currently don't match at all, there is really a problem, it really looks like non deterministic:
https://yamato-artifactviewer.prd.cds.internal.unity3d.com/b0049d49-a72e-40cd-9e29-2ca496f6ac81%2Flogs%2FTestProjects%2FHDRP_DXR_Tests%2Ftest-results/TestReportV1.html

**Comment by nerites** [comment]
> 
> 
> Hey, you have increase the XR scale to 1.5 and it fail from a very small gap:
> 
> Expected: less than or equal to 0.000149999993f
> But was: 0.00150095485f
> 
> But the result currently don't match at all, there is really a problem, it really looks like non deterministic:
> https://yamato-artifactviewer.prd.cds.internal.unity3d.com/b0049d49-a72e-40cd-9e29-2ca496f6ac81%2Flogs%2FTestProjects%2FHDRP_DXR_Tests%2Ftest-results/TestReportV1.html

I'm checking with @fabien about anything I should look out for for XR testing with waitframes.

**Comment by nerites** [comment]
When I run locally, the image produced matches the reference images I have, and does not look like the image Yamato produces for XR.

**Comment by nerites** [comment]
Ah sorry, you were right! There was some nondeterminism in the geometry script (taking a sin of framecount and rounding) and converting it to simply increment resolution by one per frame seemed to fix it. The remaining failure is because of the windows defender popup causing a standalone build failure.

**Comment by sebastienlagarde** [comment]
good, thanks for doing this test!

**Comment by sebastienlagarde** [comment]
and yes, standalone DXR player don't work

**Comment by remi-chapelain** [comment]
Out of curiosity I tried adding an alembic animated mesh using the alembic package and something happens in the reflections but the animation is still not properly reflected with it. 
ccd25e3f2cd7cd8e3a801d0dade6cddd

**Comment by remi-chapelain** [comment]
As @IonutNedelcuUnity pointed out, just need to have Dynamic Geometry as Raytracing mode, now everything behaves as expected 
ba88a1c31671be6deb27380fdf328742

**Pull request merged**
