### PR TITLE
Vfx/feature/linear gradient

### PR DESCRIPTION
**Pull request by iTris666**
# Purpose of this PR

C# side of the c++ linear gradient PR. must be merged once the C++ arrives. 10.x.x only.

# Testing status

## Links
**Yamato**: (Select your branch) https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/vfx%252Ffeature%252Flinear-gradient
> Any test projects or documents to go with this to help reviewers?

# Comments to reviewers
> Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by sophiaaar** [comment]
VFX_LWRP reference images need updating too

**Comment by PaulDemeulenaere** [comment]
- All VFX_LWRP CI trunk is green 🍏 
- VFXMain on Win_DX11_Standalone failed : 
=> subtle difference for `ShadergraphSampleScene`
image
image
image

=> `24_MotionVector ` didn't render anything 😨
image
image
image

Is this something you already observed @sebastienlagarde ? The `master` branch seems to not have these issue, either with 24_MotionVector or ShaderGraphSampleScene :
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Fvfxmain-win-dx11.yml%2523VFXMain_Win_DX11_Standalone_CUSTOM-REVISION/2369631/job/artifacts

**Comment by PaulDemeulenaere** [comment]
Update : I missed this message https://unity.slack.com/archives/CFZERNTS7/p1590928922358500
Last working trunk was 79865bcf096d.
Running a _ABV at custom revision here : https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/vfx%252Ffeature%252Flinear-gradient/.yamato%252F_abv.yml%2523all_project_ci_CUSTOM-REVISION/2376422/job

**Comment by julienf-unity** [comment]
Both these failures are not related to this branch (happen also on 9.x). Motion vector test failure is probably on HDRP and issue with motion vector debug view. As for the shader graph test issue, I have no idea yet.

**Comment by PaulDemeulenaere** [comment]
The run on custom C++ revision : https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/vfx%252Ffeature%252Flinear-gradient/.yamato%252F_abv.yml%2523all_project_ci_CUSTOM-REVISION/2376422/job/pipeline
- 🍏 on HDRP
- 🍏 on LWRP
image

**Pull request merged**
