### PR TITLE
Fixed range fields for depth of field

### PR DESCRIPTION
**Pull request by adrien-de-tocqueville**
### Purpose of this PR

https://fogbugz.unity3d.com/f/cases/1376609/

Added checks to prevent far being lower than near and the other way around

dof-range

---
### Testing status

see the gif aboce

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by RemyUnity — CHANGES_REQUESTED** [review]
Looking at your video capture, it's nice that the **end** value of a range can't be smaller than the **start** value, but is it expected that the **start** of **_near_** can be bellow the **end** of **_far_** ?

**Comment by adrien-de-tocqueville** [comment]
> Looking at your video capture, it's nice that the **end** value of a range can't be smaller than the **start** value, but is it expected that the **start** of **_near_** can be higher than the **end** (and **start**) of **_far_** ?

i don't know, @pmavridis does it make sense ?

**Comment by JulienIgnace-Unity** [comment]
I guess it does make sense. Probably harmless to do it too.

**Comment by adrien-de-tocqueville** [comment]
yeah so i checked it's done anyway when preparing parameters for rendering so no issue.
Added necessary checks so that all orders are respected but only checking overriden parameters

**Review by pmavridis — APPROVED** [review]

**Comment by pmavridis** [comment]
>  is it expected that the start of near can be higher than the end (and start) of far ?
I think that preventing this in the UI makes it clear for the users how to use the feature (overlapping near/far ranges does not make much sense in practice), so it's good that we have added the extra check in the code. The PR looks good to me now.

**Review by RemyUnity — APPROVED** [review]
Tested and everything seems to work fine :)

**Review by sebastienlagarde — APPROVED** [review]

**Pull request merged**
