### PR TITLE
Dcc/3dsmax2021 physical material

### PR DESCRIPTION
**Pull request by Thomasch-unity3d**
### Purpose of this PR

Fixes case [1293576](https://fogbugz.unity3d.com/f/cases/1293576/), 3DsMax 2021 changes the way Physical Materials are exported to FBX and they are not properly handled by our AssetPostprocessors, this PR fixes that.
Also fixes case [1307234 ](https://fogbugz.unity3d.com/f/cases/1307234/) where the emissive property of AutodeskInteractive materials are overriden by the inspector due to a property keyword conflict ( EmissionColor )
Finally, fixes case [1295747](https://fogbugz.unity3d.com/f/cases/1295747/), imported transparent materials won't cast shadows anymore.

---
### Testing status
Tested manually :
- Tested FBX files with various material property combinations made in 3DsMax 2021 and 3DsMax 2020.
- Created AutodeskInteractive material and changed the Emission color value.
- Tested FBX and Sketchup files files with transparent materials.

Additional QA TBD by Etienne : Look for potential regressions with Autodesk Interactive materials and Material imports from FBX and SKP files.

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
Hey, I expect this need to be backported on 2020.2?

**Comment by sebastienlagarde** [comment]
@Thomasch-unity3d is your current PR fixing this issue as well: https://fogbugz.unity3d.com/f/cases/1307234/ could you check? thanks

**Comment by Thomasch-unity3d** [comment]
Hey, yes that'll need to be backported and yes commit #2 fixes 1307234, I'll assign it to myself.

**Review by phi-lira — CHANGES_REQUESTED** [review]
Missing changelog entry. Ideally you could add the link to the issues you are fixing.

**Review by remi-chapelain — CHANGES_REQUESTED** [review]
Hey @Thomasch-unity3d, before QA can take a look at this, can you please fix the formatting of the PR ? Meaning : 
- Removing the PR Checklist
- Include backlinks for fixed fogbugz
- Detail a bit more in depth what you tested manually
Thanks a lot ! ❤️

**Review by phi-lira — APPROVED** [review]

**Review by remi-chapelain — APPROVED** [review]
Testing seemed sufficient on the repro case.  
Out of curiosity, I still tested various combinations of Physical Material with 3dsMax 2020/2021. 
Also tested how well textures and transparent material imported with latest Sketchup pro. ✔️ 

image


As far as I tested, no new regressions have been introduced in the 3ds Max 2021 export pipeline. ✔️

Some issues about clear coat not being exported and/or imported properly is happening but same thing happens in 3DSMax 2020, so no regression here. 
Is this something we should care about ?

**Pull request merged**
