### PR TITLE
Port DoF to Render graph

### PR DESCRIPTION
**Pull request by FrancescoC-unity**
Ported both DoF modes to render graph. 

I re-enabled all physical camera + DoF tests for render graph and they all pass locally. 

Note the new DoF mode is broken currently so couldn't fully test (Pavlos has a fix ready soon I think), but both render graph and non rendergraph break in exactly the same way :-)  So I am fairly confident. 

Yamato running https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Fport-dof-to-rendergraph/.yamato%252Fall-hdrp.yml%2523All_HDRP_fast-trunk/2865571/job/pipeline

### CODE REVIEW

**Comment by FrancescoC-unity** [comment]
Note: This is ready for review, is draft just for process sake

**Comment by sebastienlagarde** [comment]
For HDRP staging you don't care about draft, it is only for master, you can create your PR as usual

**Comment by FrancescoC-unity** [comment]
> For HDRP staging you don't care about draft, it is only for master, you can create your PR as usual

👍  Good to know, we should probably disable the github bot then

**Comment by FrancescoC-unity** [comment]
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Fport-dof-to-rendergraph/.yamato%252Fall-hdrp.yml%2523All_HDRP_fast-trunk/2865571/job/pipeline

DX and Rendergraph tests passed, a vulkan and osx job failed with stuff that looks very unrelated, but I kicked them again

**Comment by FrancescoC-unity** [comment]
The failing yamato jobs passed once re-run https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Fport-dof-to-rendergraph/.yamato%252Fhdrp-win-vulkan.yml%2523HDRP_Win_Vulkan_playmode_XR_fast-trunk/2866204/job 

and https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Fport-dof-to-rendergraph/.yamato%252Fhdrp-osx-metal.yml%2523HDRP_OSX_Metal_playmode_fast-trunk/2866203/job

**Pull request merged**
