### PR TITLE
Migrate Hair, Fabric sample graphs into HDRP Resources

### PR DESCRIPTION
**Pull request by johnpars**
### Purpose of this PR
This PR migrates the **hair** and **fabric (silk, cotton, wool)** shadergraph samples from the Material Samples into the HDRP Resources. It allows a user to access a starting point/template for hair or fabric from the main shader menu:

ShaderMenu

image

**The material samples for fabric and hair were updated to point to the new location of the graphs:** 
MaterialSample3

**The relevant subgraphs were also moved to the HDRP Resources, and are now located here in the node list:**
Subgraph

---
### Testing status
- Tested locally on two machines. 
- No warnings or errors are observed when importing the sample.
- Checked to confirm parity with the original materials prior to the change.
- Made a build (Windows x64, Mono).

---
### Comments to reviewers
~

### CODE REVIEW

**Comment by johnpars** [comment]
FYI to reviewers, we are currently drafting the supplementary documentation that adds Cotton/Wool, Silk, and Hair to the shader list documentation, so this PR will remain WIP until that is done.

**Comment by johnpars** [comment]
Yamato: https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Fmigrate-hair-fabric-sg

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
For QA, this will be tested with the 10.2 package test week

**Comment by remi-chapelain** [comment]
Tested during 10.2 smoke testing ✔️

**Pull request merged**
