### PR TITLE
SRP Workflows - Volume Debug Panel for URP

### PR DESCRIPTION
**Pull request by alex-vazquez**
---
### Purpose of this PR
https://jira.unity3d.com/browse/XPIPELINE-264

This PR is including the Volume Debug Panel into Core and is being used on URP.

---
### Testing status
- Tested the Volume Debug Panel on Editor and on Runtime.
- Test that the volume components are being filtered by each pipeline.
HDRP
image
URP
image
- Parameters are being updated.
- Values are correct.
- Check unit tests are green
image

### CODE REVIEW

**Review by JulienIgnace-Unity — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
hey, what's the status of this PR?

**Review by arttu-peltonen — APPROVED** [review]
Sorry, I had forgotten this review was waiting on me. It was pending our debug display discussion as I wanted some clarity on which debugdisplay concepts/APIs we want to make common between URP and HDRP. Following that discussion, I think we agreed that we can start with this PR and iterate on the shared API in Core in the future to make it better (and not have to worry too much about breaking changes). So I'm fine with going forward with this.

**Comment by alex-vazquez** [comment]
@Unity-Technologies/gfx-qa-hdrp  could you do a quick smoke test on the Volumes Debug Panel?

**Review by JMargevics — APPROVED** [review]
Quickly checked on HDRP side. Found no (new) regressions with Volume Debug panel ✔👍

**Comment by ernestasKupciunas** [comment]
I have found 4 issues during the testing.

- **Only some mesh is rendered when any of the component is selected:**
Steps to reproduce:
1. Enter Play mode
2. Select any of the PP component: Component >> Post Processing>> Bloom
Screenshot 2021-11-16 at 16 17 15
*************************************************************************************************************

- **Getting outofrangeexception when Playmode is active, camera is set as Main Camera, and exit the Playmode:**
Steps to reproduce:
1. Enter Play mode
2. Select component: Post Processing>> Bloom
3. Select Camera >> Main Camera
4. Exit Play mode
_IndexOutOfRangeException: Index was outside the bounds of the array.
UnityEditor.Rendering.DebugUIDrawerEnumField.OnGUI (UnityEngine.Rendering.DebugUI+Widget widget, UnityEditor.Rendering.DebugState state) (at /Users/ernestask/Downloads/Graphics/com.unity.render-pipelines.core/Editor/Debugging/DebugUIDrawer.Builtins.cs:331)_
Screenshot 2021-11-16 at 16 06 49
*************************************************************************************************************

- **Getting nullreference when Play mode is active, camera is set to Editor Camera:**
_NullReferenceException: Object reference not set to an instance of an object
UnityEngine.Rendering.DebugDisplaySettingsVolume+WidgetFactory.CreateVolumeTable (UnityEngine.Rendering.DebugDisplaySettingsVolume data) (at /Users/ernestask/Downloads/Graphics/com.unity.render-pipelines.core/Runtime/Debugging/DebugDisplaySettingsVolumes.cs:202)
Steps to reproduce:_
1. Enter Play mode
2. Select component: Post Processing>> Bloom
3. Select Camera >> Editor Camera
Screenshot 2021-11-16 at 16 07 32
*************************************************************************************************************

- **Main Camera is only available when entering Playmode** (HDRP it is always available, so I think we should make it consistent between 2rendering pipelines):
Screenshot 2021-11-16 at 16 10 00
*************************************************************************************************************

Tested using:
2022.1.0a16.2270
Revision: trunk 2562102a0d34
Built: Fri, 12 Nov 2021 08:07:22 GMT

Device under testing:
MacBook Pro (16-inch, 2021), CPU: Apple M1 Max, Memory: 64 GB, macOS: Monterey 12.0

**Comment by arttu-peltonen** [comment]
> Only some mesh is rendered when any of the component is selected:
@ernestasKupciunas does this only happen on MacOS with Metal? Looks very similar to this known issue:  https://fogbugz.unity3d.com/f/cases/1374226/ (happens when any Rendering Debugger mode is activated)

**Comment by alex-vazquez** [comment]
@ernestasKupciunas Fixed issues 2 and 3, other issues will be tackled in another PR as they are not related with the work done in this PR

**Comment by ernestasKupciunas** [comment]
@arttu-peltonen indeed this is the same issue. Removing Normal map from the material renders the object with no issues. 

@alex-vazquez issue No. 2(outOfRangeException) is still reproducible.

**Comment by ernestasKupciunas** [comment]
While verifying the latest changes, 2 additional issues appeared which I think should be addressed:

- **MissingReferenceException** once I try to use Editor's camera after the play mode
Steps to reproduce:
Enter Play mode
Select component: PP >> Bloom
Select camera: Main Camera
Exit Play mode (notice that camera will fall back to the Editor camera)
Select Camera as None
Select Editor Camera
you will get the exception: MissingReferenceException: The object of type 'Volume' has been destroyed but you are still trying to access it.

- **Editor Crash** when the editor is restarted and trying to use Volume Debug panel (not happen with HDRP)
Steps to reproduce:
Select component: PP >> Bloom
Select camera: Editor Camera
Quit Unity
Open Unity
Select component: PP >> Bloom

I have sent additional info with videos to @alex-vazquez via slack

**Review by ernestasKupciunas — APPROVED** [review]
Looks good. All mentioned issues are fixed.
I have also reported a crash bug: https://fogbugz.unity3d.com/f/cases/1382770/ (Editor crash that was mentioned above)

**Review by Nzollner — APPROVED** [review]
LGTM

**Pull request merged**
