### PR TITLE
7.x.x/universal/backport/speedtreegi

### PR DESCRIPTION
**Pull request by jpg-unity**
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

Backport of https://github.com/Unity-Technologies/Graphics/pull/720

---
### Testing status
Describe what manual/automated tests were performed for this PR

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by nerites** [comment]
Kicked off Yamato here: https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/7.x.x%252Funiversal%252Fbackport%252Fspeedtreegi/.yamato%252F_abv.yml%2523all_project_ci_2019.4/5404534/job

**Comment by nerites** [comment]
There are some image failures in Universal on OSX_Metal_Standalone_mono_Linear:
UniversalGraphicsTests.009_AdditionalLightsShadows
UniversalGraphicsTests.010_AdditionalLightsSorted

Rerunning doesn't change anything, however no images are generated:
https://yamato-artifactviewer.prd.cds.internal.unity3d.com/67d688be-1830-4bb1-9869-c7f9eec12d39%2Flogs%2FTestProjects%2FUniversalGraphicsTest%2Ftest-results%2Ftest-results/TestReportV1.html

I am unsure how to begin fixing this. Will post in Universal slack chat for help.

**Review by phi-lira — APPROVED** [review]

**Comment by phi-lira** [comment]
While looking for PRs that need backport to 7.x I discovered this PR. Do you still plan to land it?

**Comment by spaceburp** [comment]
> While looking for PRs that need backport to 7.x I discovered this PR. Do you still plan to land it?

i'll be working on landing this

**Review by erikabar — APPROVED** [review]
Looks good, approving

**Review by ghost — APPROVED** [review]
SSS hookup looks good! Approving!

**Pull request merged**
