### PR TITLE
Avoid dynamic allocation in GBufferPass.Configure().

### PR DESCRIPTION
**Pull request by kaychang-unity**
---
### Purpose of this PR
Removed dynamic allocation inside GBufferPass.Configure().

---
### Testing status
Ran UniversalGraphicsTest locally.

---

### CODE REVIEW

**Comment by kaychang-unity** [comment]
@jonuuukas After checking the code, I realized the original logic was not completely incorrect. The Lighting buffer graphics format is actually not known by DeferredLights (it could be R11G11B10, R16G16B16A16) and GraphicsFormat.None will be returned by DeferredLights.GetGbufferFormat(3). Is that an issue?

**Review by ellioman — APPROVED** [review]
Looks good. Tested on my branch that has deferred scenes and no errors 👍

**Review by jonuuukas — APPROVED** [review]
This is not an issue at the moment - tested it on RenderPass-enabled Deferred renderer and everything is fine as there is currently a workaround for GraphicsFormat.None that is provided by the gBufferFormat array in the MRT setup of renderPass attachments. The workaround might be faulty though and we'll fix it before making the RenderPass API public. What would be the correct way to get the actual format of the gbufferLighting attachment?

**Comment by kaychang-unity** [comment]
The gbufferLighting texture is the camera color target, so I suppose you can access it as `cameraData.cameraTargetDescriptor.graphicsFormat`.

**Pull request merged**
