### PR TITLE
[XPipeline]Fix Decal Shader Graph menu

### PR DESCRIPTION
**Pull request by alex-vazquez**
---
### Purpose of this PR
https://fogbugz.unity3d.com/f/cases/1335634/

image

---
### Testing status
Check that the menus are correctly sorted.

### CODE REVIEW

**Comment by jenniferd-unity** [comment]
Could you explain "Other packages, for instance testing package, relies that the Shader Option is at position 83" ?

**Comment by alex-vazquez** [comment]
@jenniferd-unity , Check the updated PR description

**Review by CertifiedRice — APPROVED** [review]

**Review by phi-lira — APPROVED** [review]

**Review by joshua-davis — COMMENTED** [review]
I already have a PR in flight to fix this: https://github.cds.internal.unity3d.com/unity/unity/pull/4304/commits/e48fa46d68a021063007f32c28965d16bf1292f6
We should chat about this

**Review by jenniferd-unity — APPROVED** [review]

**Review by jenniferd-unity — APPROVED** [review]

**Review by lukaschod — APPROVED** [review]
Looks good, I saw HDRP has a bit different layout. Maybe we should align on that?

**Review by simon-engelbrecht-soerensen — APPROVED** [review]
Looks good to me!

**Pull request merged**
