### PR TITLE
[2021.1] Add SpeedTree8 shadergraph to HD and Universal

### PR DESCRIPTION
**Pull request by nerites**
# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [x] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [x] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [x] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [x] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Backport of https://github.com/Unity-Technologies/Graphics/pull/3911
10.x.x PR: https://github.com/Unity-Technologies/Graphics/pull/3861/

---
### Testing status
Opened with 2021.1/staging and confirmed shadergraphs work. Need QA pass technically

---

### CODE REVIEW

**Review by ValGrimm-U3D — APPROVED** [review]
Thanks for responding to my many questions and suggestions, fine to merge.  👍

**Review by fabien-unity — APPROVED** [review]

**Review by elizabeth-legros — APPROVED** [review]

**Review by JMargevics — APPROVED** [review]
Same comments as with other backport. All issues discussed, approving ✅

**Review by ellioman — APPROVED** [review]

**Review by erikabar — CHANGES_REQUESTED** [review]
we do not have QA bandwidth right now, we will test this after feature cutoff.

**Review by erikabar — APPROVED** [review]
Tested with a scene with a few SpeedTrees with SpeedTree8_PBRLit shadergraph, everything works as expected in the Editor and Standalone build. Also tested Wind Zone, Terrain Tree painting, interaction with Spot, Point, Directional lights - no issues found. 
There is one issue on Metal - 4 warnings are thrown in the shadergraph: 
image

**Pull request merged**
