### PR TITLE
[ShaderGraph] [2022.1] [Ruby] Fix regression in screen position when using XR

### PR DESCRIPTION
**Pull request by cdxntchou**
### Purpose of this PR

Fix for regression introduced by:
+ https://github.com/Unity-Technologies/Graphics/pull/5428

Bug https://fogbugz.unity3d.com/f/cases/1369450/

This PR does not include fixes for Built-in or HDRP, but I will create a separate PR for those, want to unblock URP tests first.

The issue is that `_ScreenParams` is _NOT_ the render target resolution when XR is enabled -- it is the resolution of the current camera render target (i.e. the final combined image) but the render targets we actually render the shaders to are per eye and of a different resolution.

Unfortunately, there doesn't appear to be any way to access the "current render target" resolution (would require a trunk change  to add it).  So for the time being I've just reverted the code to use the less accurate projection method of calculating screen position when XR is active.

This PR also fixes another bug where the new screen position code was not taking inverted Y projections into account.

See example failure:
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Funiversal_stereo-win.yml%2523Universal_Stereo_Win_Standalone_mono_Linear_trunk/9048767/job/artifacts
Test: 126_SampleDepth is failing because it is not sampling the depth buffer from the correct screen space location

Now passes!
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/sg%252Ffix%252F1369450/.yamato%252Funiversal_stereo-win.yml%2523Universal_Stereo_Win_Standalone_mono_Linear_trunk/9108989/job

---
### Testing status
Describe what manual/automated tests were performed for this PR

Tested locally : scene vs. game view, XR Mock HMD, and URP test.

Yamato:

ShaderGraph PR: 🟡 -- same failures as master
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/sg%252Ffix%252F1369450/.yamato%252Fall-shadergraph.yml%2523PR_ShaderGraph_trunk/9090840/job/pipeline

master:  3ab2be147edd9ecac2d169c2791984e4924eb678
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Fall-shadergraph.yml%2523PR_ShaderGraph_trunk/9089368/job/pipeline

PR URP: 🟡 -- matches master
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/sg%252Ffix%252F1369450/.yamato%252Fall-urp.yml%2523PR_URP_trunk/9111636/job/pipeline

master:  3ab2be147edd9ecac2d169c2791984e4924eb678
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Fall-urp.yml%2523PR_URP_trunk/9089372/job/pipeline

failures:
Build URP_Foundation on iPhone_Metal_il2cpp_Linear_Standalone_build_Player on version trunk -- non-test-related failure on both 🟡
Build URP_Foundation on Linux_Vulkan_mono_Linear_Standalone_build_Player on version trunk -- non-test-related failure on both 🟡
Build ShaderGraph on Linux_Vulkan_mono_Linear_Standalone_build_Player on version trunk -- non-test-related failure on both 🟡
Build ShaderGraph on iPhone_Metal_il2cpp_Linear_Standalone_build_Player on version trunk -- non-test-related failure on both 🟡

URP_Lighting on Android_Vulkan_Standalone_il2cpp_Linear on version trunk -- green on re-run 🟢
URP_Lighting on Android_OpenGLES3_Standalone_il2cpp_Linear on version trunk -- same 1 test failed 🟡 
URP_Terrain on Android_OpenGLES3_Standalone_il2cpp_Linear on version trunk -- non-test-related failure on both 🟡
URP_Foundation on OSX_Metal_playmode_mono_Linear on version trunk -- green on re-run 🟢
URP_Foundation on Android_OpenGLES3_Standalone_il2cpp_Linear on version trunk -- same 2 tests failed 🟡
URP_Foundation on Win_DX12_Standalone_XR_mono_Linear on version trunk -- same 1 test failed 🟡
URP_Foundation on Win_DX11_playmode_XR_mono_Linear on version trunk -- same 1 test failed 🟡
URP_Foundation on Win_DX11_Standalone_XR_mono_Linear on version trunk -- same 1 test failed 🟡
URP_PostPro on Android_Vulkan_Standalone_il2cpp_Linear on version trunk -- same 2 tests failed 🟡 
URP_PostPro on Android_OpenGLES3_Standalone_il2cpp_Linear on version trunk -- same 1 test failed 🟡
URP_PostPro on Linux_Vulkan_Standalone_mono_Linear on version trunk -- same 2 tests failed 🟡
URP_PostPro on Win_Vulkan_Standalone_mono_Linear on version trunk -- same 2 tests failed 🟡
URP_PostPro on Win_DX11_playmode_XR_mono_Linear on version trunk -- green on re-run 🟢  

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by jessebarker — APPROVED** [review]
LGTM (should still get URP approval)

**Comment by cdxntchou** [comment]
This is ready to merge as soon as it gets review approval

**Review by pbbastian — APPROVED** [review]
LGTM :)

**Review by jessebarker — APPROVED** [review]
LGTM

**Comment by phi-lira** [comment]
Are the failures in yamato expected issues?

**Pull request merged**
