### PR TITLE
FinalPostProcessing, AfterRendering -> AfterRenderingPostProcessing

### PR DESCRIPTION
**Pull request by eh-unity**
Changes to pass order from this:
PostProcess
UserPass_AfterRenderingPostProcessing
UserPass_AfterRendering
CapturePass
FinalPost
FinalBlitPass

to:
PostProcess
UserPass_AfterRenderingPostProcessing
FinalPost (stable sort)
UserPass_AfterRendering
CapturePass (stable sort)
FinalBlitPass

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [x] Have you updated the changelog? Each package has a `CHANGELOG.md` file.

---
### Purpose of this PR
Bug fix, avoid applying FXAA (in FinalPost) on top of user ui.

---
### Testing status
Run tests locally.

---
### Comments to reviewers
Notes for the reviewers you have assigned.
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/universal%252Ffix-after-rendering-user-renderpasses

Backport 2021.1: https://github.com/Unity-Technologies/Graphics/pull/3760

### CODE REVIEW

**Review by phi-lira — APPROVED** [review]
LGTM.

**Comment by phi-lira** [comment]
LGTM. Adding mobile QA as we need to test custom render passes and post. Universal Rendering Examples is a good test.

**Comment by eh-unity** [comment]
I had to redo the fix as the underlying code got moved/refactored, so perhaps a re-review is in order.

**Review by phi-lira — APPROVED** [review]

**Review by ValentinHume — APPROVED** [review]
Looks good

**Comment by eh-unity** [comment]
Only failure seems to be an unrelated error.

**Pull request merged**
