### PR TITLE
2d/pixel perfect improvements

### PR DESCRIPTION
**Pull request by unity-cchu**
# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [x] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [x] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).

---
### Purpose of this PR
To improve the usability of Pixel Perfect. This does not add new functionality but rather improves existing functionality.

---
### Testing status
I have run it through automated test scenes setup and made sure they upgrade properly.

### CODE REVIEW

**Review by UnityPaul — APPROVED** [review]

**Comment by BoonKiangTan** [comment]
Fixes verified on branch:

Version: 2021.2.0a10.1508
Revision: trunk b8c2bb7e8b36
Built: Tue, 16 Mar 2021 16:54:50 GMT
Package branch: 2d/Pixel-Perfect-Improvements (4b8a97412d)

- Verified Camera Projection and the Camera Size properties are disabled in Camera component if URP Pixel Perfect Camera component is added (Verified warning box appears to inform users)
- Verified Pixel Perfect Camera error message in inspector if no SRP/non-2D URP asset is added to Project Settings > Graphics
- Verified “Windowbox” Crop Frame mode visual artifacts are fixed (Black bars appear around camera view when Windowbox is selected)
- “Letterbox” Crop Frame issue, and by extension, Windowbox and Stretchfill resolution issues are fixed

**Review by BoonKiangTan — APPROVED** [review]

**Review by simon-engelbrecht-soerensen — APPROVED** [review]

**Review by phi-lira — APPROVED** [review]

**Comment by phi-lira** [comment]
LGTM. @TheoWong-pixel could review UX.

**Comment by TheoWong-pixel** [comment]
Wnat to clarify that it is a warning box or Info box? I believe in @Xiangtingsu's design it is supposed to be a info box which i agree with.

**Comment by unity-cchu** [comment]
image

image

**Comment by unity-cchu** [comment]
image
image

**Review by Xiangtingsu — APPROVED** [review]

**Review by TheoWong-pixel — APPROVED** [review]

**Pull request merged**
