### PR TITLE
[WIP][URP][HDRP] Add SpeedTree8 shadergraph and update material upgraders

### PR DESCRIPTION
**Pull request by nerites**
# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [x] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [x] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Adding SpeedTree8 support (including material upgrader) to HDRP, and updating URP to use the new PBRLit SpeedTree8 shadergraph.
I've updated the URP tests to use the new SpeedTree8 shadergraph as well.

I still need to make a SpeedTree8 test scene for HDRP, but I wanted to start getting code reviews first. 

I'm leaving this PR as a draft until this trunk PR merges: https://ono.unity3d.com/unity/unity/pull-request/120356/_/graphics/terrain/speedtreesrp

---
### Testing status
I made three projects (Builtin, HDRP, URP) and tested the following:
- Importing a new speedtree8 asset (created by @xiaoxicici) and verified that correct shaders were applied to all LODs
- (SRPs only) Manually set builtin SpeedTree8 shaders to asset and verified that material upgraders applied the correct shaders to all LODs

SRP test project updates:
- Updated SpeedTree8 assets in UniversalTestProject
- HDRP test project update IP

Rerunning SRP ABV on custom Editor branch:
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/terrain%252Fspeedtreesg/.yamato%252F_abv.yml%2523all_project_ci_CUSTOM-REVISION/5245690/job

---
### Comments to reviewers
Should the shadergraphs be a part of RenderPipelineResources or RenderPipelineEditorResources? They don't need to be grabbed from resources outside of Editor/importing, however I noticed that when I moved them to RenderPipelineEditorResources I would get path errors because it would attempt to load them from the project Packages directory instead of my local Graphics repo.

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]
Approve for the HDRP part

**Comment by sebastienlagarde** [comment]
You should ask for a QA to validate the SpeedTree shader graph part (or maybe an artist?)

**Comment by xiaoxicici** [comment]
> You should ask for a QA to validate the SpeedTree shader graph part (or maybe an artist?)

Yes! I'm testing this change.

**Comment by nerites** [comment]
More recent PR: https://github.com/Unity-Technologies/Graphics/pull/3713

**Pull request closed without merging**
