### PR TITLE
Fix Iris normal disabled on eyes graphic tests

### PR DESCRIPTION
**Pull request by remi-chapelain**
### Purpose of this PR
Since Iris Normal has been exposed in Eye Shader graph and is disabled by default, this PR re-enable the iris normal checkbox in the Eye Shader Graph for the two eyes tests in HDRP & DXR automated graphic tests. 
79f9a5d9b86fa1af2441bcc5e2251b7a

Also, looking into this made me find that the IrisNormal was nor imported properly as a normal map leading to unwanted results. this PR also fixes this. 

**Test in DXR test project**
d4f635b79ce96ce5af78381a830c7ed4

**Test in HDRP test project**
78c76d0bbe96ac65aeb51194854d44d8

---
### Testing status

 Both tests pass locally ✔️ 

---
### Comments to reviewers
Yamato link for All HDRP_DXR : https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Ffix-eyes-graphic-tests/.yamato%252Fall-hdrp_dxr.yml%2523All_HDRP_DXR_trunk/4361042/job
Yamato link for All HDRP : https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Ffix-eyes-graphic-tests/.yamato%252Fall-hdrp.yml%2523All_HDRP_trunk/4374950/job

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
screenshots need to be updated in the test.

**Comment by remi-chapelain** [comment]
Updated the screenshots according to last yamato launch
Relaunched yamato and updated the links in the PR description

**Comment by remi-chapelain** [comment]
Test now pass properly on yamato even though on the HDRP side. 
Just noticed that the test 1101_Unlit_Smooth_Distortion is using IrisNormal that was not properly imported as a normal map for a distortion test so it failed too... need to update those.

**Comment by remi-chapelain** [comment]
Looks like all test are passing now. ✔️

**Pull request merged**
