### PR TITLE
Fixed UI alignment of framesettings

### PR DESCRIPTION
**Pull request by adrien-de-tocqueville**
Fix for https://fogbugz.unity3d.com/f/cases/1260513/

The background of framesettings headers in HDRP Default Settings was not correclty aligned.

before:
before

after:
after

That's maybe not the cleanest way to fix this but didn't find any other way

### Test Status

The other places in which it is drawn have not changed (Project Settings window and inspectors)

### CODE REVIEW

**Review by RSlysz — APPROVED** [review]
This is drawn at several location.
I see hardcoded spacing here. Please try the following location:
- in Camera's Inspector
- in HDRP Default settings

**Review by RSlysz — COMMENTED** [review]
edit review: wrongly approved

**Review by RSlysz — CHANGES_REQUESTED** [review]
Check the two displayed cases

**Review by RSlysz — APPROVED** [review]
Checked with Adrien. Both location have been tested

**Review by sebastienlagarde — APPROVED** [review]

**Pull request merged**
