### PR TITLE
Fixed the fogbugz case 1343418

### PR DESCRIPTION
**Pull request by thomas-zeng**
---
### Purpose of this PR
- This PR backports #3357 to 10.x.x/release
- Fogbugz case: https://fogbugz.unity3d.com/f/cases/1343418/

---
### Testing status
- QA
- ABV

---
### Comments to reviewers
- None

### CODE REVIEW

**Review by ellioman — APPROVED** [review]

**Review by ellioman — APPROVED** [review]

**Comment by thomas-zeng** [comment]
Hi @ryanhy-unity,
Could you review this backport PR when you have time? Thanks :)!

**Review by ryanhy-unity — COMMENTED** [review]
I no longer see the error but the Mock HMD is still showing a black screen on Android phones (Samsung S20 and Pixel 5 tested).  So, is this fixed, was it expected to fix the black screen?

**Comment by thomas-zeng** [comment]
Hi @ryanhy-unity,

Thanks for testing! The black screen using MockHMD on Quest is actually expected. This is because we disable mirror view when running on Android to avoid the mirrorview blit(Mirrorview doesn't make sense when running on Quest). This causes the black screen when running on android phones. 
See code: https://github.com/Unity-Technologies/Graphics/blob/ae30d11fe71a7b2445f40518c750b0468a272899/com.unity.render-pipelines.universal/Runtime/XR/XRSystem.cs#L367

**Review by ryanhy-unity — APPROVED** [review]
ok, given the black screen is expected and the errors are gone I'd say this is looking good.

**Pull request merged**
