### PR TITLE
Platform/graphics/fix urp test failures 1

### PR DESCRIPTION
**Pull request by tijutv**
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?
Fixing URP graphics tests

---
### Testing status
Describe what manual/automated tests were performed for this PR
Automated tests
---
### Comments to reviewers
Cases 1305591 and 1300373

### CODE REVIEW

**Comment by svens-unity** [comment]
Checked hoarder and all tests are passing.

Windows Vulkan Playmode only runs on nightly, kicked off a run [for foundation here](https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/platform%252Fgraphics%252Ffix_urp_test_failures_1/.yamato%252Furp_foundation-win-vulkan.yml%2523URP_Foundation_Win_Vulkan_playmode_cache_mono_Linear_trunk/6310151/job/full-pipeline) and [terrain here](https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/platform%252Fgraphics%252Ffix_urp_test_failures_1/.yamato%252Furp_terrain-win-vulkan.yml%2523URP_Terrain_Win_Vulkan_playmode_cache_mono_Linear_trunk/6311315/job).

Linux Vulkan Playmode only runs on nightly, kicked off a run [for foundation here](https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/platform%252Fgraphics%252Ffix_urp_test_failures_1/.yamato%252Furp_foundation-linux-vulkan.yml%2523URP_Foundation_Linux_Vulkan_playmode_cache_mono_Linear_trunk/6310219/job) and [terrain here](https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/platform%252Fgraphics%252Ffix_urp_test_failures_1/.yamato%252Furp_terrain-linux-vulkan.yml%2523URP_Terrain_Linux_Vulkan_playmode_cache_mono_Linear_trunk/6311300/job).

**Comment by svens-unity** [comment]
Is there a fogbugz case missing? 035 isn't mentioned in either report. 
Why are we changing the reference images on Linux vulkan for 026 the report states the test was only failing on Windows.
In the case of 038 we only change the linux image but the test was failing on windows?

**Comment by tijutv** [comment]
I changed the images for all the tests that I was working with as there were minor differences. I brought it up in the urp channel that updating all images for all platforms/APIs is not the correct way to have reference images. We should be running for all the platforms/APIs separately and updating those images as there are driver differences for each Platform/API combination. So I wasn't looking at the bugs, I was just trying to make sure that all Vulkan and DX12 bugs added in the test filter were running correctly without issues.

**Comment by tijutv** [comment]
035 wasn't part of the bug assigned to me but it was closed with https://fogbugz.unity3d.com/f/cases/1304675/, but it was still in the TestFilters and wasn't running. I just enabled it. Let me know if there's some reason to keep it disabled - maybe in that case the bug should be updated.

**Review by svens-unity — APPROVED** [review]
Sounds good 👍 Thanks for resolving these issues.

**Review by ellioman — APPROVED** [review]

**Pull request merged**
