### PR TITLE
[RPW][1386964]Fix undo for DebugUI.Enum fields on the rendering debugger.

### PR DESCRIPTION
**Pull request by alex-vazquez**
### Purpose of this PR

Fix https://fogbugz.unity3d.com/f/cases/1386964/

- Improving debug names on the undo stack

image

---
### Testing status
Test that Undo/Redo is working for Enum fields on the rendering debugger.

---
### Comments to reviewers
Serialization issue, the index where not being correctly set for enum fields after a serialization.

### CODE REVIEW

**Review by arttu-peltonen — APPROVED** [review]
Another enum index issue :) nice work!

**Review by JulienIgnace-Unity — APPROVED** [review]

**Review by JMargevics — APPROVED** [review]
Find a semi-related issue of UI not playing nicely when changing multiple enum fields but undoing only once. Reported it.

Otherwise undoing enum fields does work correctly now and Undo history shows correct names. All good from my side 🟢👍

**Comment by sebastienlagarde** [comment]
PR seems to miss some doc but otherwise ready to go?

**Comment by alex-vazquez** [comment]
@sebastienlagarde , missing docs are not from this PR, merging. Thanks

**Pull request merged**
