### PR TITLE
Make sure serialization of exposure modes is consistent between HDRP versions

### PR DESCRIPTION
**Pull request by pmavridis**
### Purpose of this PR
https://fogbugz.unity3d.com/f/cases/1261385/

The problem was that the new "AutomaticHistogram" exposure mode was added in the middle of the enum that was defining the available exposure modes. At the same time our serialization for the volume profiles just saves the integer number that corresponds to the exposure mode. 

This means that the value 3 in the volume profile that was serialized like this:
image
would mean different things between the two HDRP versions.

A solution is to use an explicit numbering in the Enum that is compatible with 8.x (this also keeps the same visual ordering in the UI).

---

### Testing status
- Problem does not repro anymore
- All tests are green (which means we are not testing all exposure modes...)

### CODE REVIEW

**Comment by FrancescoC-unity** [comment]
(From vacation, so likely will not able to follow up :P ) 
The problem in doing so is that it will then break stuff with project that used the 10.x package. Instead what we need is a migration path, either for the old case or if we keep this change for this change. 

I am a bit leaning towards migrating the old case as visually having Automatic, Physical camera, Automatic Histogram is a bit odd looking (prefer to have the automatic close to each other) 


And yes, we lack a bit of exposure testing. Needs to be added, but the automatic case last time we tried was not super stable. We shall try again.

**Comment by pmavridis** [comment]
(Apologies for tagging you on vacation, it was mostly for visibility, please ignore this until you return :) )  

> The problem in doing so is that it will then break stuff with project that used the 10.x package or 9.x with automatic histogram already in. Instead what we need is a migration path, either for the old case or if we keep this change for this change.

Unfortunately I don't think a migration path is possible, because the volume profiles for old projects (either 8.x or 9.x) were all saved at an implied "serializedVersion: 0", so even if we introduce version 1 now, we cannot really know if "m_Value:3" at version 0 corresponds to the old or new enum. I briefly discussed this with @JulienIgnace-Unity and we could not think a solution, but if you have any ideas, please let us know.

This indeed will break some projects created with HDRP 9.x, but this was a preview package, and I think not breaking the 8.x projects has higher priority (and changing the order of a public enum can break old projects in many ways, if they were using the enum to index to an array for example).

**Comment by FrancescoC-unity** [comment]
I have the feeling there might be a solution, but don't have the chance to give it proper thought from here :D 

In any case, I am fine with moving enum order, but then please let's keep the visual order as is (custom enum drawer, we do it in other places). 

Also, the default settings now use histogram by default I think (@Chman  changed it IIRC), so you need to update that too I think. 

Worth also checking the template and any "recent" (as modified for >=9.x) project we ship to make sure we don't break them

**Comment by Chman** [comment]
Yep, defaults were changed in #948.

**Comment by pmavridis** [comment]
To fix the visual ordering, I have ordered the Enum as before (so the two automatic values are grouped together in the C# file too, as suggested by Francesco), but the numeric values are set explicitly in a way that is compatible with HDRP 8.x.

image

Also updated the defaults for the outdoor scenes (I guess this is what you meant by defaults, I don't see anything else relevant in  #948). I tested this by creating a new HDRP outdoors scene, but @Unity-Technologies/gfx-qa-hdrp please test this a bit more.

**Comment by sebastienlagarde** [comment]
Given how this problem will affect scene, and given that we release  10.x very soon, this PR should be merge so we avoid to have lot of conflict.

**Comment by sebastienlagarde** [comment]
And FYI, it is indeed breaking our standalone test :)

**Pull request merged**
