### PR TITLE
Fix procedural sky with orthographic camera

### PR DESCRIPTION
**Pull request by EvgeniiG**
### Purpose of this PR
Fix case https://fogbugz.unity3d.com/f/cases/resolve/1278013/

---
### Testing status

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)
- Other: Manually tested the procedural sky in a simple scenario.

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

**Yamato**: (Select your branch):
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Ffix-orthographic-sky/.yamato%252F_abv.yml%2523all_project_ci_trunk

Any test projects to go with this to help reviewers?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by JulienIgnace-Unity — APPROVED** [review]

**Review by TomasKiniulis — COMMENTED** [review]
@EvgeniiG it fixes the case submitted issue, but Orthographic projection just displays the Sky in a solid color now. Which is different from what it used to be or what is now in Legacy and URP. Could the fix be done while still keeping the old way of sky displayed?

Attaching comparison results:
**PR Orthographic**
image
**PR Perspective**
image
**8.1.0 Orthographic**
image
**8.1.0 Perspective**
image
**Legacy Orthographic**
image

**Comment by EvgeniiG** [comment]
> @EvgeniiG it fixes the case submitted issue, but Orthographic projection just displays the Sky in a solid color now. Which is different from what it used to be or what is now in Legacy and URP. Could the fix be done while still keeping the old way of sky displayed?

The new way of rendering the sky is correct.
Recall what orthographic projection is - you have the same single view direction for all pixels of the screen. The skybox is very far away, so all pixels end up looking at the same skybox texel.

**Comment by TomasKiniulis** [comment]
> > @EvgeniiG it fixes the case submitted issue, but Orthographic projection just displays the Sky in a solid color now. Which is different from what it used to be or what is now in Legacy and URP. Could the fix be done while still keeping the old way of sky displayed?
> 
> The new way of rendering the sky is correct.
> 
> Recall what orthographic projection is - you have the same single view direction for all pixels of the screen. The skybox is very far away, so the difference in pixel positions does not matter, and all pixels end up looking at the same skybox texel.

Ah right, wish it was the same between all pipelines, but that makes sense

**Review by TomasKiniulis — APPROVED** [review]

**Comment by JulienIgnace-Unity** [comment]
Even though it might be mathematically correct, as it stands, it makes the sky in ortho more or less unusable anyway. I think it would be worth exploring other possibilities and see if we can get a usable result.

**Comment by sebastienlagarde** [comment]
Close as we used the fixed deliver in this PR instead: https://github.com/Unity-Technologies/Graphics/pull/2955

**Pull request closed without merging**
