### PR TITLE
[ShaderGraph] Fix softlock dropping an unknown property type into graph

### PR DESCRIPTION
**Pull request by cdxntchou**
### Purpose of this PR

Fix for https://fogbugz.unity3d.com/f/cases/1288887/
Using an unknown property type to create property nodes results in corrupted results, softlocking the graph.
This PR disallows creating these types of nodes.

Backported to 10.x:  https://github.com/Unity-Technologies/Graphics/pull/2468

---
### Testing status
Tested with diffusion property in URP only project:
dragging property to graph is now disallowed
create node menu: doesn't list unknown property types

tested it works if HDRP present

ABV:
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/sg%252Ffix%252Fdrop-unknown-field/.yamato%252F_abv.yml%2523all_project_ci_trunk/4106458/job/pipeline

master ABV (5144b4c):
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252F_abv.yml%2523all_project_ci_trunk/4085447/job/pipeline

Failures:
Build Universal on Win_DX11_mono_Linear_Player on version trunk -- both failed build in same way
Universal on Win_DX11_playmode_mono_Linear on version trunk -- both failed build in same way
Universal on Win_DX11_playmode_XR_mono_Linear on version trunk -- both failed build in same way
Universal on OSX_Metal_playmode_mono_Linear on version trunk -- both failed build in same way
VFX_HDRP on Win_DX11_playmode_mono_Linear on version trunk -- both failed same test
VFX_HDRP on Win_DX11_playmode_XR_mono_Linear on version trunk -- both failed same test

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by LandonTownsendUnity — CHANGES_REQUESTED** [review]
Please add a note in the description that https://github.com/Unity-Technologies/Graphics/pull/2484 must be merged first, and make sure this PR does not merge first as it will make master throw compile errors if it is.

**Comment by LandonTownsendUnity** [comment]
After merging in https://github.com/Unity-Technologies/Graphics/pull/2433 this PR successfully fixes the bug. After merge dependency notes are added to description I will approve.

**Comment by cdxntchou** [comment]
I merged in #2433, so the ordering should be solved now  :D

**Review by LandonTownsendUnity — APPROVED** [review]
Dependent PR has been merged.

**Review by elizabeth-legros — APPROVED** [review]

**Pull request merged**
