### PR TITLE
Lowering the bokeh depth of field post processing number of full precision floats

### PR DESCRIPTION
**Pull request by manuele-bonanno**
### Purpose of this PR
URP's bokeh depth of field post processing shader has a high float to half ratio.
Reducing the float precision to half as discussed with Apple.

---
### Testing status
local and Yamato

---
### Comments to reviewers

Before:
bokeh_dof_blur_before_patch

After:
bokeh_dof_blur_after_patch

### CODE REVIEW

**Comment by manuele-bonanno** [comment]
the failed URP tests are also failing on master and don't seem related to this PR

**Review by ellioman — APPROVED** [review]

**Comment by sambickley** [comment]
Adding myself for platform-specific tests:

- [ ] [ShaderGraph](https://yamato.cds.internal.unity3d.com/job/5258038)
- [ ] [Universal](https://yamato.cds.internal.unity3d.com/job/5258040)
- [ ] [VFX_URP](https://yamato.cds.internal.unity3d.com/job/5258042)

**Review by sambickley — APPROVED** [review]
Ran the following test suites for Switch:
- [ShaderGraph](https://yamato.cds.internal.unity3d.com/job/5258038)
- [Universal](https://yamato.cds.internal.unity3d.com/job/5276475)
- [VFX_URP](https://yamato.cds.internal.unity3d.com/job/5274454)

And found that the VFX_URP and ShaderGraph both pass 100%. Universal suite has failures, however they look to be the [exact same failures as are happening in master](https://yamato.cds.internal.unity3d.com/job/5267635) and so I see no regressions in existing behaviour that would suggest there's an issue.

**Review by erikabar — APPROVED** [review]
Tested with UniversalRenderingExamples project, no issues found.

**Review by aleksandrasdzikia — APPROVED** [review]
Tested with Universal Rendering Examples and URP Template. Found no issues regarding this PR only before reported ones. Could not find any difference on performance.

**Comment by ellioman** [comment]
Last commit was for changelog so I stopped the Yamato job.

**Pull request merged**
