### PR TITLE
Fix nullref from material preview in ShaderGraph while play mode [1274148]

### PR DESCRIPTION
**Pull request by alelievr**
### Purpose of this PR
Fixed case https://fogbugz.unity3d.com/f/cases/1274148/

Related discussion: https://github.com/Unity-Technologies/Graphics/pull/1073/files#r452405814

---
### Testing status
I tested manually with the repro steps of the bug report for the issue is fixed.

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]

**Review by remi-chapelain — APPROVED** [review]
I tested with the original repro case (with the HDRP Compositor) and it fixes the issue there.

**Comment by marctem** [comment]
This fix concerns me because according to the discussion on the original PR, the "Destroy" line should be removed once a low-level change is made in core Unity. I'm worried that whoever does that change will also remove the "new Material" part and not realize they should instead move it back into a "if(mat == null)" block. I'm willing to approve this PR to fix the urgent crash issue, but I think the only solution we can make is to add a note in the comment about how to fix it once but core issue is addressed?

**Comment by alelievr** [comment]
If the `if(mat == null)` is not added back when the fix lands, then the preview will just be broken and throw nullrefs in the console I think? 
But I can re-add the commented condition with another comment that explains what should be done when we remove the destroy if you want.

**Comment by alelievr** [comment]
I replaced 
```CSharp
CoreUtils.Destroy(shaderData.mat);
```
by
```CSharp
Object.DestroyImmediate(shaderData.mat);
```

and re-added the null check because it is valid if we destroy the material with `DestroyImmediate`

**Comment by sebastienlagarde** [comment]
@marctem can you review and attribute a shader graph QA for validation (we are low on QA this week) ? thanks

**Review by remi-chapelain — APPROVED** [review]

**Review by elizabeth-legros — APPROVED** [review]

**Pull request merged**
