### PR TITLE
- Fixed edges and ghosting appearing on shadow matte due to the shadow being black outside the range of the light (case 1371441).

### PR DESCRIPTION
**Pull request by anisunity**
https://fogbugz.unity3d.com/f/cases/1371441/
For Lit materials, having black outside of the range doesn't cause any trouble. but it does for shadow matte. This sets the shadow to white if outside of the range, but keeps black if not visible by the light (back face) for point and spot. 

Testing status
Added a test, but trunk is currently broken, so i cannot regenerate the new screenshot so i disabled it for now.
image

### CODE REVIEW

**Review by RemyUnity — APPROVED** [review]
Thank you for the comparison screenshots, LGTM !

**Comment by anisunity** [comment]
test are working now, I am gonna fix the spot and enable the tests

**Comment by anisunity** [comment]
fixed the second issue reported by @remi-chapelain and added a test for it 
image

**Comment by anisunity** [comment]
I'll update the screenshots locally and rebase before merging

**Comment by anisunity** [comment]
Added test scene, updated screenshots and launched the tests

**Review by sebastienlagarde — APPROVED** [review]

**Pull request merged**
