### PR TITLE
Occlusion culling for shadow maps

### PR DESCRIPTION
**Pull request by ApoorvaJ**
### Purpose of this PR

This PR doesn't directly add occlusion culling for shadow maps, but it paves the way to do so. We make the following changes:

### 1. Set `ShadowSplitData.cullingMatrix` and `ShadowSplitData.cullingNearPlane`.

This only needs to be done in HDRP because unlike URP, it doesn't call the engine functions `ComputeSpotShadowMatricesAndCullingPrimitives()` or `ComputePointShadowMatricesAndCullingPrimitives()`.

---
### Testing status

I have manually tested this with the following permutations, making sure that occlusion culling buffers look correct:
```
                    | HDRP | URP |
--------------------+------+-----|
Spot light          |    x |   x | All shapes. HDRP's box shape is a special case, because it is an ortho point light. I've validated that it works.
Point light         |    x |   x |
Directional light   |    x |   x |
Area light          |    x |     | URP doesn't support real-time area lights
Perspective camera  |    x |   x |
Orthographic camera |    x |   x | HDRP doesn't support ortho cameras apparently, but occlusion culling still works fine
```

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by bobvodka — APPROVED** [review]

**Review by Marc-Vanaclocha — APPROVED** [review]
testing has been done manually in URP and HRDP, coverage is small, addition of data and looks fine

**Review by nigeljw-unity — COMMENTED** [review]
LGTM: Including the incoming conversion to projection type enum instead of bool

**Review by sebastienlagarde — APPROVED** [review]
this need a changelog

**Comment by ApoorvaJ** [comment]
> this need a changelog

Since I simplified the engine change quite a bit, now the diff is miniscule. Not adding a changelog for now; do let me know if  you still want me to follow up with one though.

**Pull request merged**
