### PR TITLE
XPipeline - Sharing styles across Light Inspectors

### PR DESCRIPTION
**Pull request by alex-vazquez**
### Purpose of this PR

Improving light inspectors across SRP's. Sharing styles between pipelines.

---
### Testing status
Check the tooltips and labels

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by arttu-peltonen — APPROVED** [review]

**Review by martint-unity — APPROVED** [review]
Nice one!

**Comment by alex-vazquez** [comment]
@Unity-Technologies/gfx-qa-urp , please have a quick look at the tooltips and the labels of the light temperature

**Comment by RemyUnity** [comment]
Shouldn't this be mentioned in the changelog ?

**Comment by alex-vazquez** [comment]
@RemyUnity ,  I am missing my last PR where I will put all the changelog for this.

**Review by JMargevics — APPROVED** [review]
Hey! Checked labels and tooltips on both HDRP and URP lights. All tooltips and labels appear correctly. Saw no issues with light temperature section either. ✔

**Review by simon-engelbrecht-soerensen — APPROVED** [review]
LGTM

**Pull request merged**
