### PR TITLE
[ShaderGraph] [10.3] [bugfix 1291760] Shader graph inspector window behavior fixes

### PR DESCRIPTION
**Pull request by Nightmask3**
### Purpose of this PR:

Backport of #2675 

Wanted to make sure these fixes were in 2020.2 as they make a major difference to the usability of the graph inspector and the graph.

Fixes bugs (these were already closed as the fix is merged into 11.x):

https://fogbugz.unity3d.com/f/cases/1291760/

https://fogbugz.unity3d.com/f/cases/1257036/

https://fogbugz.unity3d.com/f/cases/1291760/

Also fixes this currently open bug: https://fogbugz.unity3d.com/f/cases/1296982/

---
### Testing status:

Performed all the same tests as on the original PR, everything checked out.

---
### Comments to reviewers

@cdxntchou This also includes your fix to the TabbedView and InspectorView to make sure the bug you fixed recently with the unhandled UI elements exception doesn't crop back up in 10.3 as this PR includes the code that surfaced the unhandled exception.

### CODE REVIEW

**Review by cdxntchou — APPROVED** [review]

**Review by LandonTownsendUnity — APPROVED** [review]
Tested it a bit, looks good!

**Comment by Nightmask3** [comment]
image

HDRP on OSX Metal failure is consistent with master. Can be ignored. Re-running other test failures.

**Comment by Nightmask3** [comment]
image

The tests for HDRP on Linux_Vulkan_mono_Linear_Standalone_build_Player keep failing without any clear reason as to why, given that this passes on master Im hoping this is just a bokken/yamato error that can be ignored.

**Comment by Nightmask3** [comment]
The HDRP on Win_DX12_playmode_XR_mono_Linear test has also thrown failure consistently during testing.

image

Comparing the same test run on master, it looks like the only reason master succeeds is because its skipping those last 6 tests that make the test fail? 🤔 something weird happening here for sure

**Comment by Nightmask3** [comment]
Last failure to account for, HDRP on Linux_Vulkan_playmode_mono_Linear , is also consistent with master, some sort of memory allocation issue:

image

**Pull request merged**
