### PR TITLE
Shader Graph: Change the shared template directory to an array [Skip CI]

### PR DESCRIPTION
**Pull request by sebastienlagarde**
### Purpose of this PR

This PR change the current shared template directory from a single element to an array.
This allow to HDRP shader graph master node to reference multiple folder for the $(include) directly in the template file that is used to generate the code. Allowing to share more code.

Test: Tested locally for HDRP that it worked and checked generated code. But if Yamato is green it mean that the change work correctly

---
### Testing status

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)
- Other: 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Fadd-folder-to-shader-graph/.yamato%252F_abv.yml%2523all_project_ci_fast-trunk/2547410/job/pipeline

Any test projects to go with this to help reviewers?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by marctem** [comment]
The way it's implemented now the first location in the array takes priority. That'll be an explicit contract once this is public API and my expectation was that lower strings would override higher ones, in case anyone wants to build this array programatically or something. Either way works, but we'll need to document it eventually.

**Comment by sebastienlagarde** [comment]
> The way it's implemented now the first location in the array takes priority. That'll be an explicit contract once this is public API and my expectation was that lower strings would override higher ones, in case anyone wants to build this array programatically or something. Either way works, but we'll need to document it eventually.

Indeed I haven't consider any priority here as I expect usage to be for different file. but fair enough, I will swap the order :)

**Comment by sebastienlagarde** [comment]
> > The way it's implemented now the first location in the array takes priority. That'll be an explicit contract once this is public API and my expectation was that lower strings would override higher ones, in case anyone wants to build this array programatically or something. Either way works, but we'll need to document it eventually.
> 
> Indeed I haven't consider any priority here as I expect usage to be for different file. but fair enough, I will swap the order :)

Done
ead731b3ec4bf7d9a55463a9a0e49abb8b6ef372

**Comment by sebastienlagarde** [comment]
Yamato is green

**Pull request merged**
