### PR TITLE
[7.x.x] Fixed a case where overlay camera with output texture caused base camera not to render to screen

### PR DESCRIPTION
**Pull request by lukaschod**
### Purpose of this PR
Backport https://github.com/Unity-Technologies/Graphics/pull/2539.

---
### Testing status
Describe what manual/automated tests were performed for this PR

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by ellioman — APPROVED** [review]

**Review by phi-lira — CHANGES_REQUESTED** [review]
This PR has a compiler error. Running tests locally should catch the issue.

**Review by phi-lira — APPROVED** [review]

**Comment by phi-lira** [comment]
Rerunning failed test.

**Comment by lukaschod** [comment]
Failures also happens on 7.x.x https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/7.x.x%252Frelease/.yamato%252Funiversal-osx-metal.yml%2523Universal_OSX_Metal_playmode_mono_Linear_fast-2019.4/4943683/job

**Comment by phi-lira** [comment]
Validation tests are known issue not related to this PR. 
 Also OSX tests are failing on known issue in 2D renderer.

**Pull request merged**
