### PR TITLE
Fix Unlit shader SRP Batcher compatibility on OpenGLES/OpenGLCore

### PR DESCRIPTION
**Pull request by skerys**
### Purpose of this PR
The URP Unlit shader is not SRP Batcher compatible on OpenGLES/OpenGLCore due to differing properties in Unlit Shader properties and Unlit Pass input cbuffer. This PR restore SRP Batcher compatibility for the Unlit shader by adding obsolete/unused shader properties(_Glossiness and _Metallic).

Fix for: https://fogbugz.unity3d.com/f/cases/1263720/

---
### Testing status

**Manual Tests**: 
Tested manually on the repro project.

**Yamato**: (Select your branch):
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/universal%252Ffix-unlit-srp-batcher-compatibility-opengl

### CODE REVIEW

**Comment by marton-unity** [comment]
@Unity-Technologies/mobile-qa please do a performance check with this on a project which uses Unlit shader. (ask Liutauras if finding a good project needs clarification)

**Review by phi-lira — APPROVED** [review]

**Comment by Verasl** [comment]
Am I crazy but why does unlit need metallic and glossiness? shouldnt we remove them from teh cbuffer pass if they are there? what are they used for if the user doesnt set them anyway?

**Review by aleksandrasdzikia — APPROVED** [review]
Tested and it works as expected. No more performance tests were required to be run as the code was changed to not affect the performance. Other than that, everything seems to be fine.

**Review by Verasl — APPROVED** [review]
LGTM

**Review by phi-lira — APPROVED** [review]

**Comment by phi-lira** [comment]
LGTM. Missing changelog entry. Please add.

**Comment by phi-lira** [comment]
ABV was green before.

**Pull request merged**
