### PR TITLE
[11.x.x] Fixing NullReferenceException with Lift Gamma Gain & upgrading URP Package

### PR DESCRIPTION
**Pull request by ellioman**
# Purpose of this PR
Fixes issue [#1283588](https://issuetracker.unity3d.com/issues/argumentnullexception-is-thrown-when-upgrading-urp-package-and-volume-with-lift-gamma-gain-is-focused-in-inspector)

The solution is to simply create the material in OnGUI instead of in the constructor, like is done it other places.

# What has been tested?
Upgraded the project between 8.2.0 and a version containing the changes in this PR.

# Yamato
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/universal%252Fbugfix-1283588

### CODE REVIEW

**Review by erikabar — APPROVED** [review]
Verified case 1283588
Also checked all the rest Post Processing Volume overrides, upgrading from 8.2 to this branch in 2021.1 and upgrading from 2020.1 + 8.2 to 2021.1 + this branch

**Review by phi-lira — APPROVED** [review]

**Comment by phi-lira** [comment]
Are any of those shaders used at runtime?

**Review by martint-unity — APPROVED** [review]
LGTM

**Comment by phi-lira** [comment]
merging to stage branch

**Pull request merged**
