### PR TITLE
Added the possibility to have multiple POM node in a ShaderGraph

### PR DESCRIPTION
**Pull request by alelievr**
### Purpose of this PR
Added the possibility to have multiple POM node in a ShaderGraph
image

Also moved the POM node to the ShaderGraph package

---
### Testing status (What I tested)
- Created a graph with two POM node sleeping between the two results with a slider, works as expected
- Also tested that it still works with one POM node and the standard Lit shader
- Ran HDRP tests locally, all green
- Upgraded some graphs to check if the migration from HD POM to SG POM works correctly.

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
Can you move this node to Shader graph library at the same time (and thus target master) ? (cc @lukaschod  fYI). Thanks

**Comment by alindmanUnity** [comment]
is this node cross compatible with universal? @phi-lira

**Comment by alindmanUnity** [comment]
is this going to collide with this PR? https://github.com/Unity-Technologies/Graphics/pull/1234

**Comment by lukaschod** [comment]
@alindmanUnity Requested to merge this PR into mine https://github.com/Unity-Technologies/Graphics/pull/1234, so I guess this one can be closed now.

**Comment by alindmanUnity** [comment]
going to close as it the changes here are already present in master, feel free to poke me if we've missed something

**Pull request closed without merging**
