### PR TITLE
Added support for screen space shadows (directional and point, no area) for shadow matte unlit shader graph.

### PR DESCRIPTION
**Pull request by anisunity**
Added support for screen space shadows (direction and point) for the unlit shader graph shadow matte.

Testing status
Added two new tests to cover this use case.
This shoudn't affect anything outside of these tests.

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]
Please add the feature in the what's new for 12.0 page. Thanks

**Comment by sebastienlagarde** [comment]
Formatting is incorrect

**Review by remi-chapelain — COMMENTED** [review]
Expected that Unlit shadow matte (on the left) only get semi transparent ray traced shadow but don't get color like the lit on the right ? 

image

**Comment by anisunity** [comment]
Color shadow fixed and formatting fixed

**Comment by anisunity** [comment]
My shadow change broke a test

**Review by remi-chapelain — APPROVED** [review]
Thanks for adding the colored shadow setup to the 712 test ✔️

**Comment by sebastienlagarde** [comment]
Ping on this PR: missing update of What's new and there is one test failing (the added one)

**Comment by anisunity** [comment]
The added test is not the one failing. It is an other one that fails. I pushed a fix that should make everything green (does locally at least)

**Pull request merged**
