### PR TITLE
[HDRP][Path Tracing] Sky settings now properly taken into account when using recorder

### PR DESCRIPTION
**Pull request by eturquin**
Addresses: https://fogbugz.unity3d.com/f/cases/1340507

Before: When recording (using the recorder package) in path tracing mode, sky settings would be ignored (sky was always set to clear color).
Now: Settings are properly taken into account.

This has been tested on the HDRP template (which was the scene used as an example in the accompanying ticket).

### CODE REVIEW

**Review by remi-chapelain — APPROVED** [review]
I'm trusting what has already been tested. ✔️ 
Will be tested in exploratory testing phase later this week using the bugfix branch.

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
@eturquin can you run Yamato DXR for this change? If there is no change in test, it mean we should add one test :)

**Comment by eturquin** [comment]
> @eturquin can you run Yamato DXR for this change? If there is no change in test, it mean we should add one test :)

The issue was only when using recorder, I'm not sure how we could test that?

**Comment by sebastienlagarde** [comment]
> > @eturquin can you run Yamato DXR for this change? If there is no change in test, it mean we should add one test :)
> 
> The issue was only when using recorder, I'm not sure how we could test that?

ah ok, fine thne

**Pull request merged**
