### PR TITLE
Move resolver resize logic to HDRP

### PR DESCRIPTION
**Pull request by robin-demoor**
# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [x] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [x] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [x] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
We currently perform the resolver resizing logic of the RTHandles in the engine itself. To make VT SRP agnostic we want to perform as little logic in the engine and move that to HDRP itself so users can make their own VT system without having to mimic/use the RTHandles system. This logic will be removed from core once this PR has landed.
---
### Testing status
Describe what manual/automated tests were performed for this PR

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
Hey, it miss a changelog, also if I understand correctly it is also related to a C++ change? do you have a link for the PR? thanks

**Comment by robin-demoor** [comment]
I will add a changelog and this is the ono PR https://ono.unity3d.com/unity/unity/pull-request/121456/_/graphics/vt-resolver-update-size

This PR will have to land before we land the ono one.

**Comment by RemyUnity** [comment]
So, this PR doesn't introduce any change from user perspective ?
Should QA check test here, or pay a particular attention ?

**Comment by robin-demoor** [comment]
This PR itself doesn't change anything. The trunk PR that follows will change the behavior for people who have a custom pipeline with Virtual Texturing.

I tested locally with scripts that resize everything to a few random both valid and invalid sizes and that seemed to work/log what is expected. I don't think there is much extra to test for.

**Comment by robin-demoor** [comment]
Closing PR for now as it is blocked by https://fogbugz.unity3d.com/f/cases/1306556/

**Comment by RemyUnity** [comment]
> I tested locally with scripts that resize everything to a few random both valid and invalid sizes and that seemed to work/log what is expected. I don't think there is much extra to test for.

Thanks ! Next time remember to add this information directly in the PR description :)

**Review by RemyUnity — APPROVED** [review]

**Review by JulienIgnace-Unity — COMMENTED** [review]
I'm not sure I understand the purpose of this PR.
What was on the C++ side that is going to be removed?
If I understand the PR description it seems that there was some logic based on the RTHandle system behavior? Is that correct?
The width and height that we passed to the resolver UpdateSize function were just the current viewport size so I'm not sure where the RTHandle specific part is here. I'm probably just missing something though :)
Is this the part where we just ensure that the resolver size can only grow?  (cf CalculateResolverDimensions). Isn't that a behavior that you'd want regardless of using RTHandle or not? (I assume that by having it only grow, it avoids reallocation of internal buffers when switching between cameras with different resolution).

**Comment by robin-demoor** [comment]
@JulienIgnace-Unity The issue is that we were doing this "not downsizing" in Unity Engine and had complaints from people that the resolver was not the size they requested because they didn't know this logic was happening. (Someone was implementing Virtual Texturing in URP) That is why we chose to make the engine side as low-level as possible and we don't want to perform this logic without people knowing.  So we moved the logic to HDRP and the engine side now just accepts whatever width/height you give it.  TLDR; Nothing changes for people using HDRP this is just a change for people implementing VT elsewhere.

(trunk PR: https://ono.unity3d.com/unity/unity/pull-request/121456/_/graphics/vt-resolver-update-size)

**Review by JulienIgnace-Unity — APPROVED** [review]

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
Why is there change of universal  shader graph in this PR ?

**Comment by JulienIgnace-Unity** [comment]
> Why is there change of universal shader graph in this PR ?

There was a merge mistake that broke the PR and I redid the merge. Don't know why it got there. It's just a case change for .shadergraph though so probably not an issue.

**Comment by robin-demoor** [comment]
I made a mistake when merging in master which Julien Ignace helped fix but the end result still has these 2 files with a change in case. The .ShaderGraph at the end is not .shadergraph

**Comment by sebastienlagarde** [comment]
> I made a mistake when merging in master which Julien Ignace helped fix but the end result still has these 2 files with a change in case. The .ShaderGraph at the end is now .shadergraph

ok got it, it is currently the githook system who have automatically fixed it

**Review by hdb-unity — APPROVED** [review]
Not tested locally (based on earlier discussion in this PR).

Checking changes to UniversalGraphicsTest

Functionally, don't think it will cause an issue...

If possible, can you restore the filename as it is in master so it won't make any changes when merged?

**Comment by sebastienlagarde** [comment]
Tried to fix the shader graph files issue but don't work. It shouldn't be a problem in practice, the files are unchanged.

**Pull request merged**
