### PR TITLE
Fixed the fade in mode of the clouds not impacting the volumetric clouds shadows (case 1381652).

### PR DESCRIPTION
**Pull request by anisunity**
https://fogbugz.unity3d.com/f/cases/1381652/
The Fade In mode and parameters were not affecting the volumetric clouds shadows which could lead to visual inconsistencies.
This PR fixes the issues and now it visually matches.

https://user-images.githubusercontent.com/42026998/145033137-3b56debd-9317-4b40-9a14-8f4e9395193b.mp4

Testing Status:
Tried with the different parameters combinations and seems to work fine now.

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]

**Comment by anisunity** [comment]
This changes the results of the standalone clouds tests, will need to update the 5 screenshots

**Review by RemyUnity — CHANGES_REQUESTED** [review]
I can still reproduce the issue mentioned in the FB case (testing on Metal).

**Comment by anisunity** [comment]
@RemyUnity you'll need to show me

**Review by RemyUnity — APPROVED** [review]
I misinterpreted the issue and what was shows in the repro, fix confirmed.

**Comment by anisunity** [comment]
Updated the screenshots and relaunched the tests

**Pull request merged**
