### PR TITLE
Embed instead of copying locally the config package

### PR DESCRIPTION
**Pull request by fredericv-unity3d**
### Purpose of this PR
Fixes [case 1276518](https://fogbugz.unity3d.com/f/cases/1276518/)

If you are using Collaborate as source control and installed the HDRP config package locally, the config package won't be checked in the source control.

This PR fixes the issue in two stages:
* The HDRP Wizard now embed the package instead of copying locally. (It means it is copied by the package manager in the `Packages`  folder, which is versioned by collaborate).
   With this, new use will be correct.
* Added an entry in the `Known-Issue.md` file for the FAQ, so users previously facing the issue know they can copy themselves the folder.

---
### Testing status
Manual testing:
1. Embedded the package with the HDRP wizard
2. > Checked that a copy of the package is now in the `Packages` folder.

---
### Comments to reviewers
QA: It would be nice to check that this is also working on non windows OS, just to be sure.

Doc: I added a section in the Known Issue that needs your review it would be nice if you can look at it.

### CODE REVIEW

**Comment by remi-chapelain** [comment]
Hey @fredericv-unity3d , could you rename the PR relative to what it's about instead of the case number and/or provide a quick explanation below the "Purpose of the PR". This will helps others understand the issue you're trying to solve without having to click on the fogbugz (which is not public) ! Thanks a lot <3

**Comment by fredericv-unity3d** [comment]
@remi-chapelain I added the explanation of the bug, also you may want to check the file `Known-Issues.md` as I provided detailed information about the issue and the workaround

**Comment by sebastienlagarde** [comment]
Please run Yamato and check with doc tools to be sure it is allowed to have a .py file in it. thanks

**Comment by fredericv-unity3d** [comment]
I generated the documentation locally with the doctool and it succeeded with no error.

Regarding Yamato, I started a job as requested.

**Comment by JordanL8** [comment]
Hey, can we put the python file in https://github.com/Unity-Technologies/Graphics/tree/master/Tools instead? If not, the document currently points to Packages/com.unity.render-pipelines.high-definition-config/Documentation~/tools/local_package_collab.py, but the python file is currently in the main HDRP Documentation~ folder.

**Comment by fredericv-unity3d** [comment]
@JordanL8 My intent was to put the file next to the workaround description so at ` com.unity.render-pipelines.high-definition/Documentation~/tools/local_package_collab.py`.

The location `master/Tools` is for tools involving all projects in this repo, I find it too global for an HDRP issue. Also. HDRP don't have any folder currently for such tools.
It makes more sense to me the place where it is now, but you may want to create a new folder like `com.unity.render-pipelines.high-definition/Tools~`? (it should not appear in Unity 's assets).

**Comment by fredericv-unity3d** [comment]
>If not, the document currently points to Packages/com.unity.render-pipelines.high-definition-config/Documentation~/tools/local_package_collab.py, but the python file is currently in the main HDRP Documentation~ folder.

I am confused as the location of the python file is `com.unity.render-pipelines.high-definition/Documentation~/tools/local_package_collab.py` which is not the main HDRP documentation folder, but a child folder. Maybe I missed something?

**Comment by JordanL8** [comment]
Yeah I know the python file is currently in HDRP/docs/tools, but the known issues page says 
> 1. Run the utility script bundled in hdrp: `Packages/com.unity.render-pipelines.high-definition-config/Documentation~/tools/local_package_collab.py -p <PATH_TO_YOUR_UNITY_PROJECT>`
on line 28 and 33.

I was wondering whether the doc was wrong or if the file itself was in the wrong place. I guess the doc is wrong. I'd prefer it if it could go in a top-level Tools folder like : com.unity.render-pipelines.high-definition/Tools~, but I'm unsure if this is allowed for packages? This is unprecedented in docs so I'll see what the rest of the docs team have to say about the possibility of it going in a tools folder under the Documentation~ folder. One quick question is why is this a python script and not a menu option? Is it not possible to replicate this functionality as a menu option in the editor?.

**Review by JMargevics — APPROVED** [review]
I've tested the scripted workaround on **Windows -> Windows** and on **Windows -> Mac.** In both way it worked and i've managed to pull the HDRP config with disabled area lights ✅

(The way Collab works with SRP packages is extremely rough though 😶)

**Review by JulienIgnace-Unity — APPROVED** [review]

**Comment by JordanL8** [comment]
I'll review the document now, but I'm still not entirely keen on where the script is.
> but you may want to create a new folder like com.unity.render-pipelines.high-definition/Tools~? (it should not appear in Unity 's assets).
If this is allowed, I'd much prefer it. @JulienIgnace-Unity/@sebastienlagarde what are your thoughts?

**Comment by JordanL8** [comment]
I reviewed the docs last week. I just want to know for sure whether this can go anywhere else other than the docs folder before I approve it

**Comment by JordanL8** [comment]
Perfect! Thanks very much! 🙂

**Comment by fredericv-unity3d** [comment]
@JordanL8 I implemented a cleaner workaround, it does not involve additional python file. Although, can you review the update of the `Known-Issues.md` file?

**Comment by JordanL8** [comment]
Great! I'll have a look now

**Review by JordanL8 — APPROVED** [review]

**Comment by JordanL8** [comment]
Looks good, just made some minor changes. 🟢

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
waiting for @JMargevics

**Review by JMargevics — APPROVED** [review]
Sorry, missed this PR. Gave it a pass and tried syncing area light changes in config between two computers. Worked well 👍 Will give it another try when the PR is merged and SRP is shipped with Unity. 

https://user-images.githubusercontent.com/50581102/112504146-2c217b00-8d94-11eb-8a6f-3bf4dc5c398b.mp4

**Pull request merged**
