### PR TITLE
[10.x.x] AxF UI improvements

### PR DESCRIPTION
**Pull request by slunity**
### Purpose of this PR

Add some discussed improvements for the UI: add some tooltips (note for some field types Unity editor doesn't show them, this is a known issue), separate the main mapping / tiling configuration that the user is expected to change from all the other AxF material configuration. Add headers as a mnemonic for the purpose of the 4 vector "tiling/offset" entries beside each map.
Remove the BTF main BRDF mode display and fix a compilation issue when it was selected.

See screenshot below:

AxF-new-ui

---
### Checklist for PR maker
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [x]  Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).

---
### Testing status

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally
- [ ] Checked new UI names with UX convention
(todo)

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics
(todo)

---
### Comments to reviewers

Didn't run Yamato manually yet. Waiting for approval of changes.

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
Nice improvement, thanks for the PR!

**Comment by sebastienlagarde** [comment]
@slunity The PR don't compile:
there is an error with AxfMainSurfaceInputsUIBlock. Have you miss to submit a file?
I reverted the PR on staging, you will need to redo it.

**Comment by slunity** [comment]
> @slunity The PR don't compile:
> there is an error with AxfMainSurfaceInputsUIBlock. Have you miss to submit a file?
> I reverted the PR on staging, you will need to redo it.

Compiles here? Let me double check

**Comment by slunity** [comment]
> @slunity The PR don't compile:
> there is an error with AxfMainSurfaceInputsUIBlock. Have you miss to submit a file?
> I reverted the PR on staging, you will need to redo it.
Sorry about that: 
https://github.com/Unity-Technologies/Graphics/pull/1902

**Pull request merged**
