### PR TITLE
Makes sure quaternion is normalized and valid before converting to ma…

### PR DESCRIPTION
**Pull request by eturquin**
Added a quaternion normalization for the mirrorRotation, before converting to matrix.
Without it we were getting warnings about invalid, null quaternions.
(see https://fogbugz.unity3d.com/f/cases/1182022)

Note: this should probably be backported to packages 7 and 8.

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
Please add a changelog. Thanks

**Comment by sebastienlagarde** [comment]
>Note: this should probably be backported to packages 7 and 8.
you can use label for this

**Comment by eturquin** [comment]
Changelog updated.

**Comment by sebastienlagarde** [comment]
Yamato is green

**Comment by JMargevics** [comment]
hPZXYUscEm
Semi unrelated question: is resetting working correctly? When you reset the probe, a second gizmo handle appears and preview disappears until we deselect.

**Pull request merged**
