### PR TITLE
[9.x.x][Shader Graph] Fix Custom Function node reorderable list

### PR DESCRIPTION
**Pull request by alindmanUnity**
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?
Fixing a regression in ReorderableSlotList where replacing slot types stopped working, causing null references when renaming a slot of the same type. 

---
### Testing status

**Manual Tests**: What did you do?
Created new custom function nodes and subgraph output nodes and renamed the slots. Reordered slots, added, and removed slots to ensure no new regressions are introduced. 
Previous custom function nodes maintain consistent behavior. 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics

Any test projects to go with this to help reviewers?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by LandonTownsendUnity** [comment]
Things I'd like you to test:
1. Rename a slot that has additional slots after it on both input and output, then rename one of the other slots
2. Rename a slot that has additional slots before it on both input and output, then rename one of the other slots
3. Reorder slots and then immediately rename one of the slots
4. Remove a slot and then immediately rename a slot
5. Rename a slot immediately after adding that slot

That's all I can think of that you didn't already test. Once you've tested these things I'll approve.

**Comment by alindmanUnity** [comment]
> Things I'd like you to test:
> 
> 1. Rename a slot that has additional slots after it on both input and output, then rename one of the other slots
> 2. Rename a slot that has additional slots before it on both input and output, then rename one of the other slots
> 3. Reorder slots and then immediately rename one of the slots
> 4. Remove a slot and then immediately rename a slot
> 5. Rename a slot immediately after adding that slot
> 
> That's all I can think of that you didn't already test. Once you've tested these things I'll approve.

manually tested all cases. Fix resolves issues in all cases given. 

New issue was found that reproduces in master, custom function node actions error in undo, think it's related to preview manager. filing a separate bug.

**Review by ghost — APPROVED** [review]
I'll let the undo bug get fixed in a separate PR. Approving.

**Review by marctem — CHANGES_REQUESTED** [review]
I don't like duplicating the whole AddSlot function like this, it's a recipe for missed bugs in the future. Could you add a bool to the original function about whether to re-use an existing instance or not instead?

**Review by marctem — APPROVED** [review]
Much simpler.

**Review by Nightmask3 — APPROVED** [review]

**Pull request merged**
