### PR TITLE
Add VFX_URP on Win_DX11_playmode_XR to Yamato

### PR DESCRIPTION
**Pull request by fabien-unity**
---
### Purpose of this PR
Enable Yamato job to ensure VFX Graph is always working with URP + XR

---
### Testing status
Test run results : https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/universal%252Fxr%252Fadd-vfx-tests/.yamato%252Fvfx_urp-win-dx11.yml%2523VFX_URP_Win_DX11_playmode_XR_trunk/3725216/job

### CODE REVIEW

**Review by thomas-zeng — APPROVED** [review]

**Comment by DennisDeRykeUnity** [comment]
@fabien-unity I see that VFXGraphicsTests.008_AssetBundle passed in recent trunk for non-XR VFX URP Playmode tests, but it is ignored for your dev branch due to “Test scene is not compatible with XR and will be skipped.”  

In this PR I do not see any changes to the settings file for this scene.  Was it already toggled off by another PR?  

And do you know whether it is toggled off due to an unsupported XR feature, or a bug?

**Comment by fabien-unity** [comment]
@DennisDeRykeUnity indeed, it was already disabled from the HDRP_TestSettings on the scene (documented here: https://confluence.unity3d.com/display/XG/SRP+regression+tests)
We still need to investigate the source of the problem.

**Review by DennisDeRykeUnity — APPROVED** [review]
I ran "All VFX_URP CI - trunk" and "All VFX_URP CI - 2020.2" and both are green for this PR.  

A side effect of these config changes is that now some XR pipelines are added to vfx_urp_osx_metal.yml and vfx-urp-osx-opengl.core.  These are extraneous because we do not need to test XR on Mac at this time.  Their presence does not hurt anything because we have not added them to any jobs, but I will try to remove them in a later PR.

**Comment by DennisDeRykeUnity** [comment]
@fabien-unity I copied your dev branch then added two lines in the file below.  This prevents the extraneous Mac XR pipelines that I mentioned in my previous comment, as well as some unused Mac XR pipelines that are already in master.  You may wish to make these changes in your own dev branch to avoid clutter in the Yamato UI and Graphics repo YaML files.  

https://github.com/Unity-Technologies/Graphics/blob/universal/xr/add-vfx-tests_dennisd/.yamato/config/__shared.metafile

**Comment by sophiaaar** [comment]
do we need xr for osx?

**Comment by fabien-unity** [comment]
Closing this PR as it will required some rework after https://github.com/Unity-Technologies/Graphics/pull/2812 is merged.

**Pull request closed without merging**
