### PR TITLE
[ShaderGraph] [2022.1/Ruby] Adding anisotropic option

### PR DESCRIPTION
**Pull request by cdxntchou**
### Purpose of this PR

Fix for: https://fogbugz.unity3d.com/f/cases/1367540/

Backports:
2022.1: https://github.com/Unity-Technologies/Graphics/pull/5657
2021.2: https://github.com/Unity-Technologies/Graphics/pull/5801

Adding anisotropic option to the Sampler State node:
image

Docs ticket: https://jira.unity3d.com/browse/GSG-591

---
### Testing status
Before: (no anisotropic)
image

After: (x16)
image

Added yamato test to test inline anisotropic sampler state node:
image

Yamato:

Nightly ShaderGraph on Trunk: 🟢
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/sg%252Fadd%252Fanisotropic/.yamato%252Fall-shadergraph.yml%2523Nightly_ShaderGraph_trunk/8832664/job/pipeline

* Note that the OSX metal results on the anisotropic sampling test are incorrect, but it appears to just be from the integrated GPUs on the farm machines not supporting anisotropic.  Running on a "real" OSX machine locally, the results look correct.

Console PR and Tests: 🟡 -- failures match master
https://github.cds.internal.unity3d.com/unity/ScriptableRenderPipelinePrivate/pull/244

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by alindmanUnity — CHANGES_REQUESTED** [review]
Notes:
- Move the aniso setting to the node inspector, so the setting is visible when the node is selected
- Rename the setting to something easily searchable, ie "Anisotropy Filering", and the options to recognizable settings ie "x2, x4" etc
- Cross check the setting name against any existing anisotropy settings (for example, on the texture assets) and when in doubt reuse the options for consistency. 
- Keep the default option consistent with the current node behavior.

**Comment by cdxntchou** [comment]
> 
> 
> Notes:
> 
>     * Move the aniso setting to the node inspector, so the setting is visible when the node is selected
> 
>     * Rename the setting to something easily searchable, ie "Anisotropy Filering", and the options to recognizable settings ie "x2, x4" etc
> 
>     * Cross check the setting name against any existing anisotropy settings (for example, on the texture assets) and when in doubt reuse the options for consistency.
> 
>     * Keep the default option consistent with the current node behavior.

Moved the control to the node inspector, renamed it to "Anisotropic Filtering", with options "None, x2, x4, x8, x16".
Default was already "None", including when upgrading from older graphs.

**Review by alindmanUnity — APPROVED** [review]
approving with the UX changes

**Comment by jessebarker** [comment]
Quick comment on the test results (just to clarify the author's comment), the Intel integrated GPUs in our macOS test farm agents do not support this (and several other features, especially for HDRP), but an AMD or Apple Silicon GPU does support this (hopefully adding more agents in the future will help this).

**Review by jessebarker — APPROVED** [review]
LGTM

**Pull request merged**
