### PR TITLE
[11.x.x] Re-enabled Metal MacOS implicit MSAA resolve

### PR DESCRIPTION
**Pull request by manuele-bonanno**
### Purpose of this PR

Implicit MSAA resolve (store resolve action) was temporarily disabled on MacOS waiting for a backbuffer AA fix landing in trunk. This PR reenables it, improving performance on Metal/MacOS by removing the unnecessary ResolveAA intermediate pass

Trunk PR: https://ono.unity3d.com/unity/unity/pull-request/115516/_/platforms/metal/case_1289045_macos_backbuffer_msaa#comment-901793

---
### Testing status
Tested in the UniversalGraphicTest 146 in editor and MacStandalone to make sure the MSAA to backbuffer works fine

### CODE REVIEW

**Review by ellioman — APPROVED** [review]

**Comment by manuele-bonanno** [comment]
all URP tests passed, the failures are not relevant to my changes and mostly HDRP

**Comment by phi-lira** [comment]
Do we need to bump minimum version of package to point to the Unity trunk version that contains the fix?

**Comment by manuele-bonanno** [comment]
> Do we need to bump minimum version of package to point to the Unity trunk version that contains the fix?

no, the trunk fix landed in 0a6. The current minimum version is 0a7

**Review by cinight — APPROVED** [review]
lgtm

**Comment by ellioman** [comment]
The failures on Yamato were not caused by this PR and is therefore safe to land.

**Pull request merged**
