### PR TITLE
[URP 2D] Fix inconsistent normals

### PR DESCRIPTION
**Pull request by rainsing**
### Purpose of this PR
Fixed inconsistencies in sprite normal map rendering.

---
### Testing status
Manual QA testing and ABV.

---
### Comments to reviewers
NA

### CODE REVIEW

**Review by unity-cchu — APPROVED** [review]

**Review by unity-cchu — APPROVED** [review]

**Comment by BoonKiangTan** [comment]
Fix verified on branch:

Version: 2021.1.0a8.1475
Revision: trunk 824e91d155c5
Built: Tue, 24 Nov 2020 17:23:34 GMT
Branch: 2d/fix-inconsistent-normals (a7bd30642f)

- Verified 2D point light shines on the sprite in 2D, point light appears flat and not skewed on the rotated surface
- Verified adding new Sorting layer to sprite and light's target sorting layer, no issues found

**Review by BoonKiangTan — APPROVED** [review]

**Comment by rainsing** [comment]
The test failures were also happening on master.

**Review by eh-unity — APPROVED** [review]
Looks like this is contained in 2D-side completely. LGTM.

**Comment by phi-lira** [comment]
Hard to look due to many failures. We fixed several yamato failures this past week. Could you merge master and rerun tests?

**Pull request merged**
