### PR TITLE
PBR Sky renderer now shares its internal precomputation table between different instances.

### PR DESCRIPTION
**Pull request by JulienIgnace-Unity**
### Purpose of this PR
Currently the Physically Based Sky Renderer has precomputation tables that are not shared between cameras using the same sky. This leads to a big overhead of GPU memory. In order to fix that, the PBR sky renderer now caches these tables internally to be shared between instances of the renderer (one renderer per camera).

Also:
- Removed duplicated hash code probably due to a bad merge.
- Added a debug visualizer for HDCamera object.

---
### Testing status

**Manual Tests**: What did you do?
- Tested a complex scene with one PBR sky and multiple realtime probes and cameras. Tested via the debugger and memory profiler that only one set of precomputed tables were allocated.
- Tested the same scene with multiple different PBR sky and checked that the right number of precomputed tables were allocated.
- Tested that making a new set or setting the sky to none properly deallocated the tables.
@Unity-Technologies/gfx-qa-hdrp those tests + automated tests should be enough.

- [x] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)

### CODE REVIEW

**Comment by EvgeniiG** [comment]
I feel like the current system has become too convoluted.

What happens when someone else goes ahead and implements another sky model that involves precomputation? Wouldn't they have to re-do all the work?

Why can't we just do a simple thing and build a hash table (like std::set) of sky objects (using their type and properties) every frame?

If you want to separate a sky object into logic and data (Sky Renderer and Sky Properties, or whatever you want to call them), any precomputed data should live within the data component (Sky Properties) rather than the logic component (Sky Renderer).

I am sure this works, but perhaps there is a better way.

**Comment by JulienIgnace-Unity** [comment]
> I feel like the current system has become too convoluted.
> 
> What happens when someone else implements another sky model that involves precomputation? Wouldn't they have to re-do all the work?
> 
> Why can't we just do a simple thing and build a hash table (like std::set) of sky objects (using their type and properties) every frame? Then Update and Render them?
> 
> If you want to separate a sky object into logic and state (Sky Renderer and Sky Properties, or whatever you want to call them), any precomputed data should live within the state component (Sky Properties) rather than the logic component (Sky Renderer).
> 
> I am sure the current implementation works, but perhaps there is a better way.

In practice, what we do is almost what you suggest. The SkyRendering context contains all the result (aka Reflection Cubemap + AmbientProbe) that we want to share between skies/cameras and is saved by the sky parameters hash.
Historically the renderer was just that, an entity that just does the logic of rendering with no attached state and so it was shared as well (there wasn't need to have more than one instance).
The issue that was brought by the PBR sky is that its precomputation hash is not the same as the "generic" one from the sky parameter. This is why it cannot be shared under the same hashcode. This was actually the issue that caused the PBR sky to slow down when directional light changed orientation, because this information is included in the hash and changes the look of the sky so we need to recompute reflection cubemap and ambient probe on change. The unfortunate side effect was the recomputation of PBR sky tables even though it wasn't actually needed. This is the reason why the renderer was split from the context containing the result texture.
At this point there was two choices: Adding another layer of formalization on top of the rest of the sky manager, making it even more complicated than it already is, or consider that renderer specific data must be handled by the renderer itself. I chose the second solution because it did not put more strain on the already complicated system.
We have documentation about how to write a custom sky renderer so I will put a section in there to explain in details this kind of cases. I think this is currently the best we can do.

**Comment by sebastienlagarde** [comment]
@JulienIgnace-Unity Please add the doc :)

**Comment by JulienIgnace-Unity** [comment]
@sebastienlagarde doc done.

**Comment by sebastienlagarde** [comment]
Merged to get this fix in 7.4.0

**Comment by TomasKiniulis** [comment]
Checked on 7.x.x/release with multiple cameras & PBR Skies modifying properites. InScatteredIrradiance tables are indeed no longer once per camera when using the same sky parameters. 
Test scene
image (4)
Before pr:
image (5)
With pr:
image (6)

**Pull request merged**
