### PR TITLE
Vfx/fix/1340654 multiline tooltip output properties

### PR DESCRIPTION
**Pull request by julienamsellem**
### Purpose of this PR
https://fogbugz.unity3d.com/f/cases/1340654/

When a tooltip in a subgraph output property spans on multiple lines text cannot be selected properly
OutputTooltip

---
### Testing status
Only tested the scenario described in the fogbugz

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by VitaSkruibyte** [comment]
Tested:

- VFX Graph, Subgraph, Subgraph Block, Subgraph block operator
- Selecting text, selecting text using shortcuts, copy-paste selected text, insert some text, delete text. 

Everything seems good, but there's one weirdo that we need to shutdown 🔪:

**Comment by VitaSkruibyte** [comment]
Tested:

- VFX Graph, Subgraph, Subgraph Block, Subgraph block operator
- Selecting text, selecting text using shortcuts, copy-paste selected text, insert some text, delete text. 

Everything seems good, but there are some weirdos that we need to shutdown 🔪.

**Comment by VitaSkruibyte** [comment]
Looking good! Tested:
VFX Graph, Subgraph, Subgraph Block, Subgraph block operator
Selecting text, selecting text using shortcuts, copy-paste selected text, insert some text, delete text. 🟢

**Review by VitaSkruibyte — APPROVED** [review]

**Review by iTris666 — APPROVED** [review]
lgtm

**Pull request merged**
