### PR TITLE
[diedsoon] Transparent QoF (part 2): RemapAlpha, Node Scene Depth Difference, 

### PR DESCRIPTION
**Pull request by skhiat**
Remap Transparent Channel of the BaseColor/Color texture for {Lit, Unlit, LayeredLit, LitTesselation, LayeredLitTesselation}
Lit:
image

Unlit:
image

LayeredLit:
image

LitTesselation:
image

LayeredLitTesselation:
image

Add Scene Depth Difference for 3 format: {Linear01, Raw, Eye}:
image

Approved by UX - Maddelena

UX review notes: changes the order of parameters

https://jira.unity3d.com/browse/HDRP-1600
https://jira.unity3d.com/browse/HDRP-1602
https://jira.unity3d.com/browse/HDRP-1603

### CODE REVIEW

**Review by sebastienlagarde — COMMENTED** [review]
This PR have been built on top of the other PR, so it include 2 change. (for reviewvers)

**Review by remi-chapelain — CHANGES_REQUESTED** [review]
Double checked the remapping sliders on all compatible shaders ✔️ 

~The new node works well but users may benefit from understanding how the node is made. Maybe it can be interesting to have it a subgraph since it's mostly subtracting SceneDepth and Pixeldepth ?~
**EDIT: Not possible since we can't do enum as input in subgraph.** 


Also there's no documentation so we should document it. 
And adding a test using the node in the shadergraph project would be great ! :)

**Comment by skhiat** [comment]
> Can you separate SG specific changes into a separate PR? It doesn't seem like the alpha remapping for HDRP and SceneDepthDifference need to be coupled.

checkout the PR here:
https://github.com/Unity-Technologies/Graphics/pull/6467

**Comment by esmelusina** [comment]
Can this be closed?

**Comment by skhiat** [comment]
> Can this be closed?

I'll close them when we merge the other linked one:
https://github.com/Unity-Technologies/Graphics/pull/7013
https://github.com/Unity-Technologies/Graphics/pull/6924

**Pull request closed without merging**
