### PR TITLE
SetInt and GetInt -> SetFloat and GetFloat [21.1]

### PR DESCRIPTION
**Pull request by aleks01010101**
This PR removes the deprecation warnings produced by HDRP and URP code.

# **Please read;**
## **PR Workflow for the Graphics repository:**
* **All PRs must be opened as draft initially**
* Reviewers can be added while the PR is still in draft
* The PR can be marked as “Ready for Review” once the reviewers have confirmed that **no more changes are needed**
* Tests will start automatically after the PR is marked as “Ready for Review”
* **Do not use [skip ci]** - this can break some of our tooling
* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [x] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Trunk will soon have Material.SetInt, Material.GetInt, Shader.SetGlobalInt, Shader.GetGlobalInt, MaterialPropertyBlock.SetInt and MaterialPropertyBlock.GetInt deprecated.
This PR removes warnings found using the template scenes.
Int type in ShaderLab is just an alias to Float, so this PR shouldn't change anything.

---
### Testing status
Describe what manual/automated tests were performed for this PR
Manual testing on both templates.

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by ellioman — APPROVED** [review]

**Comment by ellioman** [comment]
I'm adding @Unity-Technologies/gfx-qa-foundation as a reviewer.
Can you do some light testing so we're 100% sure nothing has regressed?
- Test opaque/transparent with our main shaders Lit/SimpleLit/Particles/etc
- Test transparent blending modes alpha/premultiply/additive/multiply
- Test transparent doesn't write to depth
- Test opaque writes to depth
- Test deferred lighting

**Comment by sebastienlagarde** [comment]
>Int type in ShaderLab is just an alias to Float, so this PR shouldn't change anything.
Do we really want to do this? If we have used SetInt etc... it was in the hope that one day we will support int. not that we will deprecated its support :). Is it harder to remove SetInt or make it work?

**Comment by sebastienlagarde** [comment]
launching an ABV to see the current impact of such change

**Comment by aleks01010101** [comment]
> > Int type in ShaderLab is just an alias to Float, so this PR shouldn't change anything.
> 
> Do we really want to do this? If we have used SetInt etc... it was in the hope that one day we will support int. not that we will deprecated its support :). Is it harder to remove SetInt or make it work?
> 
> I am worried because we code in the past like SSS that have workaround this limitation and maybe other place and I am afraid that such a change could cause issue in HDRP.

There's a new Integer type (together with SetInteger/GetInteger API) that uses ints under the hood.
We decided to go the deprecation way for this, as changing Int storage to int would break too many projects.

**Comment by JulienIgnace-Unity** [comment]
I'm not sure I understand either. Is the new Integer API not available yet? Can't we move to it instead of moving this to float (and only on the C# side) then back to integer later?

**Comment by sebastienlagarde** [comment]
> I'm not sure I understand either. Is the new Integer API not available yet? Can't we move to it instead of moving this to float (and only on the C# side) then back to integer later?

Let's have a chat, I already talk with Aleksander

**Comment by fra-frassineti-unity** [comment]
I have already started some URP tests and I've just noticed the discussion going on. Are there any updates on the discussion? If not, should I put the testing on hold?

**Comment by aleks01010101** [comment]
> I have already started some URP tests and I've just noticed the discussion going on. Are there any updates on the discussion? If not, should I put the testing on hold?

I'm checking with Felipe

**Comment by aleks01010101** [comment]
> I have already started some URP tests and I've just noticed the discussion going on. Are there any updates on the discussion? If not, should I put the testing on hold?

Please continue with testing :)
I'll check with Kay as well, he might be interested in making the right things for deferred right off

**Comment by aleks01010101** [comment]
@kaychang-unity you might be interested in this - would you like to update the code to use Integers where applicable instead?

**Comment by kaychang-unity** [comment]
@aleks01010101 Thanks for the heads-up. I didn't know setInt() was actually setFloat() under the hood!
So, SetInteger() will be the new way to correctly set int values, correct?
I would like to use SetInteger() when the shaderLab file declares int, to keep it coherent for users reading the code.

**Comment by aleks01010101** [comment]
> So, SetInteger() will be the new way to correctly set int values, correct?
Yes!


> I would like to use SetInteger() when the shaderLab file declares int, to keep it coherent for users reading the code.

Int still maps to Float. I introduced Integer type for Shader Lab recently - this one is backed by real integers.

**Comment by kaychang-unity** [comment]
@aleks01010101 I see! In that case, could you fix StencilDeferred.shader to use the new Integer property instead of Int? TileDeferred.shader has been removed from master branch, I'll fix it on my side.

**Comment by aleks01010101** [comment]
> @aleks01010101 I see! In that case, could you fix StencilDeferred.shader to use the new Integer property instead of Int? TileDeferred.shader has been removed from master branch, I'll fix it on my side.

I could, I'm just not sure I'm up to chasing potential bugs that could come up from doing this right now :)
Do you have bandwidth to do that?

**Comment by kaychang-unity** [comment]
Ok, I can indeed see a long process with QA.
For URP deferred renderer, leave the code as it is, I will fix it using Integer type in the future, or the next time I touch the files.

**Comment by aleks01010101** [comment]
> For URP deferred renderer, leave the code as it is, I will fix it using Integer type in the future, or the next time I touch the files.

Great, thank you!

**Review by fra-frassineti-unity — APPROVED** [review]
Since today is my last day at Unity and my tests did not cover all the scenarios I was asked to test, I'm approving the PR (I did not found any issue with what I tested). I'm re-assigning @Unity-Technologies/gfx-qa-foundation so that they can finish the remaining tests.

**What I tested (URP only)**:
- Test opaque/transparent with main shaders Lit/SimpleLit/Particles/Unlit
- Test transparent blending modes alpha/premultiply/additive/multiply
- Test transparent doesn't write to depth
- Test opaque writes to depth

**What I did not test**:
- Deferred Lighting
- All of the above for HDRP

**Test Document**:
https://docs.google.com/document/d/14nEuJGXk3QWqdKroFKt1khkyawFDSt-Kj0J3FjjIdjk/edit?usp=sharing

**Review by cinight — APPROVED** [review]
Tested with UniversalRenderingExamples with Forward & Deferred, HybridURPSamples editor & player. all good.

And automated test _ABV for SRP repository - 2020.2 in this PR is green.

**Pull request merged**
