### PR TITLE
moving some Bokeh DoF calculations from GPU to CPU

### PR DESCRIPTION
**Pull request by manuele-bonanno**
### Purpose of this PR
These optimizations were discussed with Apple, and move work from the GPU to the CPU.

The improvement with this PR on iPhone SE (1334 x 750 res) iOS 14:

Before patch:

Bokeh Blur shader GPU Time: ~2.14 ms

After patch:

Bokeh Blur shader GPU Time: ~1.56 ms

Around ~0.55 ms+ gain in GPU time (and around ~80 mil ALU instructions shaved from the Bokeh Blur Shader)

---
### Testing status
Local testing in Editor and iOS device.
Yamato ABV

---
### Comments to reviewers

Before: 
before_patch_alu_instructions

After:
after_patch_alu_instructions_new

### CODE REVIEW

**Review by phi-lira — APPROVED** [review]
LGTM. Maybe add changelog mentioning that performance of Bokeh DOF was improved.

**Comment by phi-lira** [comment]
@Unity-Technologies/gfx-qa-urp please test that this PR doens't regress dynamic scaling or render pipeline asset scale. Drop a message to me if you need help.

**Review by erikabar — APPROVED** [review]
Tested visual correctness on macOS and Windows with UniversalRenderingExamples project. No PR issues found.

**Review by aleksandrasdzikia — APPROVED** [review]
Looks good. Tested visual correctness and performance. No issues found.

**Pull request merged**
