### PR TITLE
Hair Documentation Pass

### PR DESCRIPTION
**Pull request by johnpars**
### Purpose of this PR
This PR adds updated documentation for the upcoming hair Physical model.

Section explaining the two models.
image
image
image

Section explaining geometry type.
image

Section explaining hair in path tracing. 
image

One additional change was to the nomenclature of the Hair "material types". They are now:
- Kajiya-Kay -> **Approximate**
- Marschner -> **Physical**

---
### Testing status
I built the docs with the DocTools and verified everything was formatted correctly.

### CODE REVIEW

**Comment by johnpars** [comment]
Adding images shortly

**Comment by merpheus-dev** [comment]
It is a convenient simplification! Although, I would propose putting a side note somewhere to describe what Basic and Physical would refer to as their hair shading model.
Along with that, the term "Basic" might get a bit misleading for the general audience.

**Comment by johnpars** [comment]
Thanks @merpheus-dev, I will incorporate this feeback!

**Comment by johnpars** [comment]
We decided to switch the nomenclature to **Approximate / Physical** for both the **Material Type** and the **Scattering Mode** for consistency.

**Comment by merpheus-dev** [comment]
Awesome!

**Comment by johnpars** [comment]
@sebastienlagarde yamato is now green - I forgot to update the reference image for OSX in the previous PR. It has been updated and the test re-ran.

**Comment by sebastienlagarde** [comment]
@Vic-Cooper merging this PR as it include change in the feature that need to be in 21.2. Could you do a correction pass in a separate PR? thanks

**Pull request merged**
