### PR TITLE
New DXR HDRP test for testing SNorm16 vertex format support in ray tracing shaders

### PR DESCRIPTION
**Pull request by IonutNedelcuUnity**
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

Added a DXR test 6000_VertexFormats after fixing https://fogbugz.unity3d.com/f/cases/1263936/ 

The test creates a mesh from C# that uses the following formats for its vertex attributes:
Position - Float32 
Color - UNorm8
Tex Coord - Float16
Normal - SNorm16

The actual support for SNorm16 vertex formats is in UnityRayTracingMeshUtils.cginc and it was merged in trunk at eb03bc43ebc2 (2020.2.0b1.2894).

---
### Testing status

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally
- [x] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [x] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)
- Other: 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)
Reference image:
6000_VertexFormats

Player output:
HDRP_DXR_Tests_2020-08-20_11-15-58

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics

Any test projects to go with this to help reviewers?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by remi-chapelain — APPROVED** [review]
Verified that all supported VertexAttributeFormat was tested. 
- Float ✔️ 
- Float16 ✔️ 
- UNorm8 ✔️ 
- SNorm16 ✔️ 
- UNorm16 🔴 
There's VertexAttributeFormat.UNorm16 that is not tested in the test but as @IonutNedelcuUnity , can't find a proper use case for it. 

Also, launched yamato with the proper revision to be sure that the test pass on it
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Fraytracing%252Fgfx_test_6000/.yamato%252Fall-hdrp_dxr.yml%2523All_HDRP_DXR_CUSTOM-REVISION/3187194/job

**Comment by IonutNedelcuUnity** [comment]
The branch with the new vertex format support was merged to trunk in 2020.2.0b1.2894 on eb03bc43ebc2

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
Yamato is failing: https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Fraytracing%252Fgfx_test_6000/.yamato%252Fall-hdrp_dxr.yml%2523All_HDRP_DXR_fast-trunk/3471249/job/pipeline @IonutNedelcuUnity any thought?

**Comment by sebastienlagarde** [comment]
All green, but need to wait that Yamato pinned master move to a more recent revision to not break...

**Comment by remi-chapelain** [comment]
Shouldn't really happen since the [ONO PR](https://ono.unity3d.com/unity/unity/pull-request/110532/_/graphics/raytracing/1263936) this PR depends on have been merged a while ago but it's the only difference between my yamato launch (that were 🟢 ) on Aug 20, 2020 is that I triggered it with custom revision "0be7e687e224"

**Pull request merged**
