### PR TITLE
Fixed how the 'unsaved changes' prompt is handled

### PR DESCRIPTION
**Pull request by joshua-davis**
This fixes double prompts on close and also weird issues from closing and re-opening the editor window, such as docking changes. [1319623]

Fix for https://fogbugz.unity3d.com/f/cases/1319623/

# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [x] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
ShaderGraph did hacks to try and display a "you have unsaved changes, do you want to save?" message. This caused issues such as double prompts for close, incorrect docking positions, etc... This change changes ShaderGraph to use the actual mechanism for this expected by EditorWindow.

---
### Testing status
- [x] Change a graph and see the correct title change (has a '*')
- [x] Undo a graph change so it's not modified and see a correct title change (no '*')
- [x] Change a graph and save it. The title correctly changes (no '*')
- [x] Change a graph and save as to another file. The old graph's title doesn't change.

For all of the below cases modify a graph and check the three choices of "Save", "Discard", and "Cancel" to verify:
- [x] Docked Tab Closed via "..." -> "Close"
  - [x] Save correctly closes the file and saves the changes
  - [x] Cancel doesn't close the tab or change the file on disc.
  - [x] Discard closes the tab and doesn't change the file on disc. (Currently double prompts, see comments)
- [x] Docked Tab via middle mouse click  (requires a somewhat up-to-date editor change to work)
  - [x] Save correctly closes the file and saves the changes
  - [x] Cancel doesn't close the tab or change the file on disc.
  - [x] Discard closes the tab and doesn't change the file on disc. (Currently double prompts, see comments)
- [x] Docked tab. Try to close the entire editor
  - [x] Save correctly saves the changes and the editor closes
  - [x] Cancel stops the editor from closing and the file doesn't change
  - [x] Discard doesn't change the file on disc and the editor closes
- [x] Docked tab. right click tab and choose "Reload Window"
  - [x] Save correctly saves the changes and the editor closes
  - [x] Cancel produces two windows,  one old and one new (this is how it works without the change and currently can't be fixed)  
  - [x] Discard doesn't change the file on disc and window is reloaded
- [x] Undocked Tab closed via the 'x' button:
  - [x] Save correctly closes the file and saves the changes
  - [x] Cancel doesn't close the tab or change the file on disc.
    - [x] The window position doesn't change either.
  - [x] Discard closes the tab and doesn't change the file on disc. (Currently double prompts, see comments)
- [x] Undocked Tab closed via the '..." -> "Close option" (do all 3 options)
- [x] Undocked Tab closed via middle click (do all 3 options)
- [x] Undocked Tab via "Reload Window"
  - [x] This should have the same behavior as a docked window except the docking will screw up with cancel (the old tab will be where the floating window is and the properly modified tab will now be docked).
- [x] Docked Tab. Switch tabs (game, scene, etc...). Click the "..." and choose maximize. 
  - [x] Verify the three options (this change also ends up improving https://fogbugz.unity3d.com/f/cases/1316104/)

---
### Comments to reviewers
As this changes the behavior on editor or tab close, let me know if I missed any other important cases. I tried to make sure I hit everywhere that handled modifications.

This change mostly fixes all behavior, but there's a known case that can't be worked around properly in the expected workflow (tab reload). To support this case the old behavior is left as a fallback. This has the unfortunate side effect of double prompting on "Discard" which can also lead to some slightly strange effects if you discard then cancel (just window docking). A bug has been filed on the editor to fix this side of things (https://fogbugz.unity3d.com/f/cases/1325912), but as this fixes a lot of behavior and has minimal side-effects I've deemed it better than the old behavior.

### CODE REVIEW

**Review by Nightmask3 — CHANGES_REQUESTED** [review]
Ran into an interesting edge case where trying to close the shader graph window by middle-mouse clicking on the shader graph window tab would instantly close the window without any prompt to save/discard changes. 
This also happens if there are actual changes made to the graph, so the changes made would then be lost.

Other than that, it looks like the bug itself has definitely been resolved, could not repro the re-docking behavior mentioned in the bug.

**Comment by Nightmask3** [comment]
> Ran into an interesting edge case where trying to close the shader graph window by middle-mouse clicking on the shader graph window tab would instantly close the window without any prompt to save/discard changes.
> This also happens if there are actual changes made to the graph, so the changes made would then be lost.
> 
> Other than that, it looks like the bug itself has definitely been resolved, could not repro the re-docking behavior mentioned in the bug.

Can no longer repro this case, approving!

**Review by Nightmask3 — APPROVED** [review]
looks good to me! Definitely some messy stuff here in the windowing framework that makes it less than ideal to handle but a decent compromise, and the code is better now than it was before. Do what we can 🤷

**Review by jessebarker — APPROVED** [review]
LGTM

**Review by ghost — CHANGES_REQUESTED** [review]
Closing a shadergraph with changes to it and choosing "discard" now opens a new dialog identical to the old one except now "discard" is replaced with "discard changes". This doesn't seem like correct behavior.

**Review by ghost — APPROVED** [review]
Sorry, I missed the notes to reviewers. Aside from the problem that is known I don't see any issues. Hopefully an editor PR can fix that.

**Pull request merged**
