### PR TITLE
Enable XR Standalone Universal tests for Fabien's single-eye-stereo mechanism

### PR DESCRIPTION
**Pull request by DennisDeRykeUnity**
---
### Purpose of this PR
Fabien’s single-eye-stereo tests already run in Playmode on Yamato as part of the Graphics repo test projects.  This PR adds single-eye-stereo Standalone tests for Universal.  

These are pipelines with _XR in their names.  These reuse the non-stereo reference images rather than generating left-eye-right-eye pairs. 

---
### Testing status
My Yamato config changed pipelines for Universal PR and Universal Nightly pipelines.  Here are jobs for these pipelines, comparing:
- Graphics master commit 3f0ec4b 
- tests/xr/urp_standalone_dennisd commit 688610e

I verified that all pipelines for master are also still present for my dev branch, and that every pipeline that failed for my dev branch also failed for master except this one which is re-running now: 
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/tests%252Fxr%252Furp_standalone_dennisd/.yamato%252Funiversal-linux-vulkan.yml%2523Universal_Linux_Vulkan_playmode_cache_mono_Linear_trunk/5176136/job

I verified that my branch adds URP XR Standalone pipelines for DX11 and DX12 to “Universal PR Job - trunk” and “Nightly Universal - trunk” and they passed. 

* master: Universal PR Job - trunk
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Fall-universal.yml%2523PR_Universal_trunk/5159602/job

* dev branch: Universal PR Job - trunk
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/tests%252Fxr%252Furp_standalone_dennisd/.yamato%252Fall-universal.yml%2523PR_Universal_trunk/5159841/job/pipeline

* master: Nightly Universal - trunk
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Fall-universal.yml%2523Nightly_Universal_trunk/5159625/job/pipeline

* dev branch: Nightly Universal - trunk
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/tests%252Fxr%252Furp_standalone_dennisd/.yamato%252Fall-universal.yml%2523Nightly_Universal_trunk/5159844/job/pipeline

---
### Comments to reviewers
I am still not a Raumel guru yet, so if you see any problems with my PR definitely let me know. I hope to enable more XR standalone tests going forward, for Android, HDRP, etc.  If run times become onerous we can discuss.  Thanks!

### CODE REVIEW

**Review by fabien-unity — APPROVED** [review]
Great!
I've confirmed in the execution logs the XR render path is indeed activated.

**Review by sophiaaar — APPROVED** [review]

**Comment by DennisDeRykeUnity** [comment]
@sophiaaar Since you and Fabien have approved, can you go ahead and merge this?  Or am I supposed to merge it myself?  (Not sure if I have permissions on your repo...)

**Comment by DennisDeRykeUnity** [comment]
I added the ready-to-merge label since I heard that is the next step in order to get this merged.  
Please advise if further actions are needed from me on this PR.   Thanks!

**Comment by kivistikliis** [comment]
We've updated the yml system, the ruamel lives outside of the repo now (i.e. you need a local checkout of that repo) and this brought some changes in how commands are defined, especially for Universal due to the screen resolution requirement. To enable Standalone cache XR, you can copy the normal [Standalone cache](https://github.com/Unity-Technologies/Graphics/blob/master/.yamato/config/universal.metafile#L74), rename it, and add xr flags [here ](https://github.com/Unity-Technologies/Graphics/blob/master/.yamato/config/universal.metafile#L83) and [here ](https://github.com/Unity-Technologies/Graphics/blob/master/.yamato/config/universal.metafile#L89). Ping us if you need help with this :)

**Comment by DennisDeRykeUnity** [comment]
I am closing this PR.  I hope to launch a PR based off my new branch tests/xr/urp_standalone_dennisd_2 where I started from today's latest master and made the changes recommended above by @kivistikliis in addition to a few more lines in the config file to exclude XR from a few platforms.

**Pull request closed without merging**
