### PR TITLE
Use correct index for light shadow

### PR DESCRIPTION
**Pull request by adrien-de-tocqueville**
### Purpose of this PR

fix https://fogbugz.unity3d.com/f/cases/1387209/

Fix is pretty straightforward, wrong index was used to sample the shadowdata array (I guess the name `_DirectionalShadowIndex` is slightly misleading as it's the index of the directional casting shadow in the `_DirectionalLightDatas`  array and not it's index in `shadowDatas` array

---
### Testing status

Tested on the repro project.
For QA, I don't recomend doing it if you want to verify because the FPS sample project is very long to open. It's probably a better idea to try to reproduce it with multiple lights casting shadows on a custom project

### CODE REVIEW

**Comment by FrancescoC-unity** [comment]
LGTM, but adding @AnisB as he did the screen space stuff -- I am pretty certain the change is good, but worth a double check from him.

**Comment by adrien-de-tocqueville** [comment]
Ah thanks, you were the recommended reviewer for some reason

**Review by FrancescoC-unity — APPROVED** [review]

**Comment by FrancescoC-unity** [comment]
> Ah thanks, you were the recommended reviewer for some reason

I think because I was the last one doing a bug fix around those, _I think_ :D

**Review by remi-chapelain — CHANGES_REQUESTED** [review]
Double checke raytraced shadows on DXR_Tests to be sure since they all use Screen Space Shadows and here's the result:
image

**Review by remi-chapelain — APPROVED** [review]
Must have done a mistake when running the tests. 
Retried and got an all green (like @adrien-de-tocqueville). 
Approving ✔️

**Review by sebastienlagarde — APPROVED** [review]

**Review by anisunity — APPROVED** [review]
lgtm

**Pull request merged**
