### PR TITLE
[2021.2+] Support undo of Global Settings assignation - case 1342987

### PR DESCRIPTION
**Pull request by jenniferd-unity**
---
### Purpose of this PR
The HDRP or URP Global Settings could have been changed by script, undo/redo (case 1342987), or file update - file versioning, let us make sure we display the correct one. The recording in the Undo stack is done from the C++ PR listed below.
In a Player, we do not need to worry about those changes as we only support loading Global Settings from the Graphics Settings.
image

Fogbugz 2022.1: https://fogbugz.unity3d.com/f/cases/1342987/
Fogbugz 2021.2: https://fogbugz.unity3d.com/f/cases/1348159/

C++ PR: https://github.cds.internal.unity3d.com/unity/unity/pull/4993

---
### Testing status
Tested on Windows the ability to change the Global Settings assignation in the menus.
Also added 2 regression tests for this behavior: one in HDRP_Tests, the other one in UniversalGraphicsTest_Foundation - both in the new GlobalSettings tests section

Note: if we undo towards a None Global Settings, the rendered frame may still re-assign a Global Settings so not to break rendering.

---
### Comments to reviewers
This PR needs to land after C++ PR support (ono: https://ono.unity3d.com/unity/unity/pull-request/129515/_/graphics/srp/1342987-global-settings-undo-support)
--> C++ PR landed in  2021.2.0b6 and 2022.1.0a4

### CODE REVIEW

**Review by RSlysz — APPROVED** [review]
looks good

**Comment by jenniferd-unity** [comment]
C++ PR landed in  2021.2.0b6 and 2022.1.0a4

**Review by RemyUnity — APPROVED** [review]
I tried the repro steps in HDRP and URP, as well as changing the assigned asset.
LGTM !

**Review by ernestasKupciunas — APPROVED** [review]
Tested both rendering pipelines: HDRP and UPR. Works like a charm. Undo and Redo works as intended with the Global settings in the global settings menu (HDRP and URP assets). Also, Undo/ Redo react respectively in all places (tested on Lights GameoObjects and URP specific assets) once the Global settings are changed.

ezgif com-gif-maker (1)
ezgif com-gif-maker


Unity used for testing:
Version: 2022.1.0a5.673 Personal
Revision: trunk 141e928f4280
Built: Tue, 03 Aug 2021 10:02:00 GMT

Platform:
MacBook Pro (15-inch, 2017), 2,8 GHz Quad-Core Intel Core i7, 16 GB 2133 MHz LPDDR3, Radeon Pro 555 2 GB, macOS Big Sur 11.5.1 (20G80).

**Pull request merged**
