### PR TITLE
Misc fixes of rendergraph errors when disabling opaque objects

### PR DESCRIPTION
**Pull request by FrancescoC-unity**
Some of the issues were genuine (did not check with MSAA in first PR), some other confuse on why I did not repro before, but anyway here all seems fine again.

### CODE REVIEW

**Comment by FrancescoC-unity** [comment]
Note: not ready yet.

**Review by JulienIgnace-Unity — APPROVED** [review]

**Review by remi-chapelain — CHANGES_REQUESTED** [review]
With the latest fix, when you disable the SSR, you can disable opaque objects and motions vectors on custom frame settings. 
BUT I took a broader look with all the ray tracing effects (RTAO, RTGI, RTR, RR, RTSSS & Shadows with those two frame setting)
With the latest commit issue still happening on my side on DX12 when disabling opaque objects on custom frame settings with : 
**RTR on Performance**
image
**RTR on Quality**
image
**SSR**
image
**Recursive Rendering**
image
**RT Directionnal Shadow**
image
**RT Point/Spot Light Shadows**
image
**RT Area Light Shadows**
image


AND, it's also happens when disabling Motion Vectors on custom frame settings : 
**RTR Quality** 
image
**RTR Perf**
image
**SSGI**
image
**RTGI Quality**
image
**RTGI Perf**
image
**RTAO**
image
**RT SubSurfScattering**
image
**RT Directional Shadows**
image
**RT Area Light Shadows**
image

**Comment by FrancescoC-unity** [comment]
Ok, so a pass over the ray tracing passes is needed, good to know will do tomorrow first thing. Thanks for the thorough check!

**Review by JulienIgnace-Unity — CHANGES_REQUESTED** [review]
Under review again with all new changes :)

**Comment by remi-chapelain** [comment]
After countless back & forth, I did a thorough test with all the ray traced effects with most of the custom frame settings in forward and deferred. Everything seems to be fixed now ✔️

**Review by remi-chapelain — APPROVED** [review]

**Review by remi-chapelain — CHANGES_REQUESTED** [review]
After further check, found another error while modify Default Frame settings :|
It works fine in custom frame settings, but any modification in Default Frame Settings triggers that error : https://unity.gyazo.com/da2ebb7be74bdcdaf92f0b44426a30aa

image

**Comment by FrancescoC-unity** [comment]
> After further check, found another error while modify Default Frame settings :|
> It works fine in custom frame settings, but any modification in Default Frame Settings triggers that error : https://unity.gyazo.com/da2ebb7be74bdcdaf92f0b44426a30aa
> 
> image

I don't seem to be able to repro this :-(

**Review by remi-chapelain — APPROVED** [review]
Tried on a new project and can't seem to repro either on this branch. 
So, re-approving this rollercoaster of a PR ✔️

**Review by sebastienlagarde — APPROVED** [review]

**Pull request merged**
