### PR TITLE
Adding Test Shaders and Textures to ShadergraphPlayground Project

### PR DESCRIPTION
**Pull request by bencloward**
This PR includes the following test content
Shaders
AllShaderNodes - a shader that has all of the shader nodes arranged by category
MigrationGroupes - a shader that has all of the shader nodes arranged by migration groups. These correspond with the Jira tasks for migrating the node groups.
TestAltitudeMask
TestCameraDistanceMask
TestColorToGrayscale
TestFaceNormal
TestLevels
TestSphereMap
TestTriplanrDirectionMasks
TestUVFlowMap
TestUVInteriorCubemap
TestUVLatLong
TestUVTriplanar

Textures - used in the test shaders
013-weg-naast-wei-ldri
cobblestones_d
cobblestones_n
flowmap
Ground_Albedo
interior_cube_sample
latlong_test
matcap_chrome
test_texture
windows_d

HDRP Support
added HDRP packages to the manifest.json file

I also added several files related to adding HDRP support and general project settings files that were generated when I opened the project.

### CODE REVIEW

**Comment by bencloward** [comment]
Xiaoxi helped me complete the process of adding support for HDRP to the project.  In the process, several new files were generated - which I added to the PR.  So HDRP is now completely functional in the project.

**Comment by esmelusina** [comment]
Something about the changes in graphic settings borks the preview compilation in the GTF migration work.

Can you merge in the current state of master, and then check Windows->Shaders->ShaderGraph and add like, the Lerp node and make sure it shows up black by default and not pink (shader compilation error)?

image

image

I'm not sure what's going on exactly just yet, but it looks like the HDRP configuration or something in the project settings is not letting us compile the preview images with URP (and we don't support HDRP previews for nodes juuuust yet).

**Comment by bencloward** [comment]
I merged sg2-staging-master to my branch this morning.  All my node
previews still show up as pink.  I also switched the project settings so
that the Scriptable Render Pipeline Settings is set to use the URPAsset
instead of the HDRP, but the previews in SG2 still show up as pink.

Can you think of anything else I should try?

-Ben

**Comment by bencloward** [comment]
My latest commit fixes the preview so it's working again.

**Comment by esmelusina** [comment]
Okay! Looks good-- preview works and the previews for test projects look good too.

**Pull request merged**
