### PR TITLE
[ShaderGraph] [URP] Additive blending should fade with alpha

### PR DESCRIPTION
**Pull request by cdxntchou**
### Purpose of this PR
Fix for https://fogbugz.unity3d.com/f/cases/1270344/

When a lit transparent is set to additive blend mode, the alpha value did not do anything.
Now it is multiplied into the addition, so that alpha 0 results in no change.

This PR fixes via a blend mode adjustment.   Verified with @eh-unity that this is a good approach.

---
### Testing status
Describe what manual/automated tests were performed for this PR

Tested against repro case in editor.. verified fades with alpha, zero is completely transparent and one is equivalent to old behavior.

ABV:
ShaderGraph CI:  https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/sg%252Ffix%252F1270344/.yamato%252Fall-shadergraph.yml%2523All_ShaderGraph_trunk/4006408/job/pipeline

succeeded

Universal CI:  https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/sg%252Ffix%252F1270344/.yamato%252Fall-universal.yml%2523All_Universal_trunk/4006423/job/pipeline

failed, but matches master failures.

master ABV:

https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252F_abv.yml%2523all_project_ci_trunk/3948082/job

failures:
Universal_Hybrid on OSX_Metal_playmode_mono_apiNet2_Linear on version trunk -- both failed (non-test failure)
Build Universal on Win_DX11_mono_apiNet2_Linear_Player on version trunk -- both failed (non-test failure)
Universal on OSX_Metal_playmode_mono_apiNet2_Linear on version trunk -- both failed (non-test failure)
Universal on Win_DX11_playmode_XR_mono_apiNet2_Linear on version trunk -- both failed (non-test failure)
Universal on Win_DX11_playmode_mono_apiNet2_Linear on version trunk -- both failed (non-test failure)

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by ellioman** [comment]
Replacing myself with @eh-unity as he's been working with blend modes recently.

**Comment by LandonTownsendUnity** [comment]
Does this bug also happen for unlit shaders? I'd like to fix it there too if so

**Review by LandonTownsendUnity — APPROVED** [review]
I checked and the bug does not repro for unlit. Good to see this is being fixed. Approving.

**Review by eh-unity — APPROVED** [review]
This change appears to be compatible with the Blending/Preserve specular fix.

**Pull request merged**
