### PR TITLE
[ShaderGraph] [2022.1] [Ruby] Fix screen position behaviors

### PR DESCRIPTION
**Pull request by cdxntchou**
### Purpose of this PR
Proper Fix for: https://fogbugz.unity3d.com/f/cases/1369450/

### MUST LAND AFTER (and remove changes from merged):
- #6114

Original fix PR here (that just unblocked Universal Tests, but didn't properly fix the whole issue): #5867

This addresses a number of additional platforms and render pipelines, adds a standard for pixel position (origin in upper left), and also adds some tests.

This PR ensures that "Default" Screen Position and Pixel Position work identically across:
* Render Pipelines
* Graphics APIs
* Shader Stages
* XR / non-XR
* projection flipped / normal

Specific changes:
* Cannot use $conditional: and #if preprocessor commands on the same lines, as they interfere.
* Moved all of the flip calculations to Pixel Position, so that pixel position is now consistent across all platforms and projections.
* Standardized Pixel Position to place the origin in the upper left
* Copied all of the relevant code to HDRP and Built-in platforms.
* Added a node test verifying that Screen Position matches the expected behavior (relative to raw Screen Position / clip space)
* Added a node test verifying that Pixel Position matches the expected behavior (relative to raw Screen Position / clip space)
* Updated Dither node tests in the Artistic Nodes scene to be more deterministic
* Cleaned up XR special case (using fixes from #6114)
* Fixed VFX generated code to use the same logic

Console Reference Image PR:
https://github.cds.internal.unity3d.com/unity/ScriptableRenderPipelinePrivate/pull/306

---
### Testing status
Added automatic editor tests to verify that screen position and pixel position produce the expected result relative to raw clip position, in both the pixel and vertex shaders.

Manually tested that ScreenPosition and PixelPosition always have consistent origins in both vertex and fragment stages, and the sample depth and sample scene nodes operate as expected, and that the _ScreenParams return the correct value.
- [x] URP - PC with D3D11, Vulkan and OpenGL
- [x] URP XR - PC with D3D11, OpenGL
- [x] HDRP - PC with D3D11, Vulkan and D3D12
- [x] HDRP XR - PC with D3D11, Vulkan, and D3D12
- [x] Builtin - PC with D3D11, Vulkan and OpenGL
- [x] VFX in HDRP with D3D12
- [ ] URP renderscale -- this PR does not fix the handling of render scale in URP.  This will be fixed in a follow up PR.

image

Note:  The double UV flip introduced in this PR caused the dither node tests (in the Artistic Nodes scene) to change.  But it is because those tests were extremely sensitive to screen position (output was heavily dependent on the least significant bits).  I updated the Dither node test -- the new tests are more robust, and won't change results based on lowest bit discrepancies (or device/platform vagaries).

image

Yamato:

Nightly ShaderGraph: 🟢
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/sg%252Ffix%252Fscreen-position2/.yamato%252Fall-shadergraph.yml%2523Nightly_ShaderGraph_trunk/9504802/job/pipeline

PR ShaderGraph (with latest test updates): 🟢
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/sg%252Ffix%252Fscreen-position2/.yamato%252Fall-shadergraph.yml%2523PR_ShaderGraph_trunk/9576253/job/pipeline

PR HDRP: 🟢
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/sg%252Ffix%252Fscreen-position2/.yamato%252Fall-hdrp.yml%2523PR_HDRP_trunk/9594824/job/pipeline

PR URP: 🟢
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/sg%252Ffix%252Fscreen-position2/.yamato%252Fall-urp.yml%2523PR_URP_trunk/9598485/job/pipeline

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by jessebarker — APPROVED** [review]
LGTM

**Review by joshua-davis — CHANGES_REQUESTED** [review]
Current PR looks good, but it seems like the vertex and tessellation templates also need updating

**Review by joshua-davis — APPROVED** [review]

**Review by ellioman — APPROVED** [review]

**Review by VitaVFX — APPROVED** [review]
Seems to look good on VFX side. Checked Screen Position behavior and compared VFX with regular primitives that have SG assigned. Tests included:
- Vertex Stack, Fragment Stack with various particle outputs (Output Mesh, Quad, etc)
- DX11 (HDRP and URP), DX12, Vulkan (URP only)
- New and old (URP only) SG integrations
- MockHMD (URP)
- SG Scene from our VFX QA FTP project, checked if everything remains in the same places (URP)

**Review by PaulDemeulenaere — APPROVED** [review]
Looks good to me from the VFX side.
Thanks for the update.
N.B.: I think it could appropriate to have some helper function in core to factorize these implementation.

**Review by phi-lira — APPROVED** [review]
Looked at yamato. Seems good coverage.

**Review by JMargevics — APPROVED** [review]
I ran included PixelPosition graphs, dithered SGs and checked material samples on HDRP, 

- Tested on DX11, DX12, Vulkan, PS4 
- Tested all DRS upscale filters 
- Thanks @remi-chapelain for checking DLSS

No issues or regressions seen. Looks good to me! 👍✔

**Comment by BogomilP** [comment]
Does this, by any chance, offer a fix for this Issue:
https://issuetracker.unity3d.com/is...position-node-does-not-work-when-xr-is-active

My team has been trying to get HDRP VR Render Texture Portals to work in HDRP which both use the ScreenPosition Node.
Even after successfully implementing the changes from this commit we still cant get it to work.

**Pull request merged**
