### PR TITLE
[7.x.x] [VFX] ShaderGraph loosing reference while updating

### PR DESCRIPTION
**Pull request by PaulDemeulenaere**
### Purpose of this PR
Fix [issue](https://fogbugz.unity3d.com/f/cases/1297186/) using change from https://github.cds.internal.unity3d.com/unity/vfx-graph/pull/188

1. Use the same approach than 8.x.x (or greater) package to avoid shaderGraph reference lost.
2. Improve the solution using explicit `GetOrRefreshShaderGraphObject` instead of `RefreshShaderGraph` which wasn't called for every shaderGraph access.

---
### Testing status
Loading spaceship project switching package from `7.4.1` to local package & also the minimal repro (using this [trunk](https://ono.unity3d.com/unity/unity/pull-request/117486/_/2019.4/graphics/vfx/assets-priority) revision, landed in 2019.4.17f1_667c8606c536)
- https://drive.google.com/file/d/1A3C6Krrs_jfYtOCgI8pspUShhummSiKW/view?usp=sharing

---
### Comments to reviewers
See also https://unity.slack.com/archives/CM6VCD9C7/p1607013268001500
For code synchronisation, see : https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/185

### CODE REVIEW

**Comment by PaulDemeulenaere** [comment]
@vlad We should check this only when a `7.5.3` is schedule, we are looking for bug like this : https://fogbugz.unity3d.com/f/cases/1284439
ezgif com-gif-maker (5)

To switch package like the package manager does, the best way to simulate it is modifying replacing this line :
> "com.unity.render-pipelines.high-definition" : "7.4.1"

by

> "com.unity.render-pipelines.core": "file:../../../SRP/com.unity.render-pipelines.core",
"com.unity.render-pipelines.high-definition": "file:../../../SRP/com.unity.render-pipelines.high-definition",
"com.unity.render-pipelines.high-definition-config": "file:../../../SRP/com.unity.render-pipelines.high-definition-config",
"com.unity.visualeffectgraph": "file:../../../SRP/com.unity.visualeffectgraph",

**Review by VitaSkruibyte — APPROVED** [review]
Test Doc: [https://docs.google.com/document/d/1EpR_1Ye9W-Nkyw-sS9QpTriZhyRM-KbFmIIEpqZUCWA/edit](url)

**Summary**

[HDRP, URP] Minimal repro project:
- Regular VFX (checked if nodes, properties (exposed/not exposed), VFX SubGraph operator lose connection, Output properties stay the same, ShaderGraph reference loss)
- VFX Subgraph (checked if nodes, properties (exposed/not exposed), VFX SubGraph operator lose connection, Output properties stay the same, ShaderGraph reference loss)

Spaceship Demo:
- ShaderGraph reference loss in VFX Graph
- If effects look as expected in Editor and Standalone (DX 11)

**Comment by julienf-unity** [comment]
I guess we want to merge that for 7.5.3

**Comment by PaulDemeulenaere** [comment]
> I guess we want to merge that for 7.5.3

Yes, it has been verified and the change are pretty safe : it uses the behavior from 8.x.x+ to avoid any incorrect reference while compiling/opening the VisualEffectGraph.

I'm merging & running Yamato one more time.

**Comment by PaulDemeulenaere** [comment]
@julienf-unity Ready to merge, this [internal PR](https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/185) will help to avoid code divergence.

**Review by julienf-unity — APPROVED** [review]

**Pull request merged**
