### PR TITLE
Vfx/fix/1367447 improve inspector preview

### PR DESCRIPTION
**Pull request by julienamsellem**
### Purpose of this PR
https://fogbugz.unity3d.com/f/cases/1367447

When a VFX asset is selected the whole editor hits a frame rate drop.
Uploading 2021-11-18 08-53-18.mp4…

After investigation it appeared that this slow down was mainly due to the VFX preview. See capture below:
BHdjx9k9KO

To improve performances a new toggle button is available in the preview title bar to enable/disable animation.
By default it's disable so that when a VFX asset is selected there's no frame rate drop.
You can see in the capture below that the CPU usage is quite stable even after selecting the asset.
QSWGoKlt8g

---
### Testing status
Tested many VFX asset selection in the project browser (using the Visual Effect Asset filter) and also selecting the asset by clicking in the void in the VFX graph window.
The goal is to keep the CPU usage at the same level as before selecting the asset (when it's not animated).

---
### Comments to reviewers
The state of the "animate" toggle is kept between each asset selection.
Depending on the VFX asset if the preview is not animated it can be empty when there's no prewarm or if the start event is custom.

### CODE REVIEW

**Review by julienf-unity — COMMENTED** [review]
I tested the branch. Looks good but a few remarks:
- preview refresh should be triggered upon preview window modification as well (resize, dock, convert to floating window...) because as soon as the dimensions are changed without refresh, render is streched until next refresh
- When animated preview is on, all other render windows are being refreshed as well (scene and game view). This should not be the case

**Comment by julienf-unity** [comment]
Also the play state seems to be kept when switching vfx. Not sure this is the best, I would probably reset to pause when selecting a vfx? Plus this would be more consistent with material preview

**Comment by julienf-unity** [comment]
Zoom with the wheel does not trigger a refresh as well

**Comment by VitaVFX** [comment]
Hi! Here's the [Test Doc](https://docs.google.com/document/d/1PuI_aQeC5wF8N5En5OBAPDWw6FqJNlc7-aktPm9m_ig/edit), dropped some performance questions to clarify things out. A bit down in the doc logged some issues.

**Review by VitaVFX — APPROVED** [review]
Looks good, all the raised concerns were taken into account. Thank you for fixing this! 🟢  [Test doc](https://docs.google.com/document/d/1PuI_aQeC5wF8N5En5OBAPDWw6FqJNlc7-aktPm9m_ig/edit)

**Pull request closed without merging**
