### PR TITLE
Fix virtualtexturing lowquality bias clamping

### PR DESCRIPTION
**Pull request by NicoLeyman**
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?
This PR clamps the sampled LOD to a valid range when sampling a virtual texture with low quality and a non 0 mip bias.

---
### Testing status

**Manual Tests**:
- Manually inspected previously broken test scene to verifiy the fix works.

**Automated Tests**:
- Added a new sample shader/material/ball to the Virtual Texturing scene to automate testing in the future. (locally the tests couldnt find the reference images, I have updated them however).

### CODE REVIEW

**Review by GraphineCharles — APPROVED** [review]
Looks good

**Comment by sebastienlagarde** [comment]
Hey, so @NicoLeyman you need to update the reference screenshots for the other platforms (linux, vulkan etc...). Also I am not sure why VFX is failing , guess it is an instability unrelated to your change, at your next Yamato run I expect it will pass.

**Comment by sebastienlagarde** [comment]
Hey @NicoLeyman I have check your Yamato result. It is a bit hard to read as there is failure currently due to trunk (standalone of HDRP / URP + 3 VFX test), failure because you don't have the latest master (playmoide hdrp mac), , but looks like there is also instability (hdrp vulkan VR). And the last one is Hybrid which I am not sure where it come from.

Given all this mess. I will suggest that you merged latest master and re-run Yamato. Then you should get a result like this one: https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Fstaging/.yamato%252F_abv.yml%2523all_project_ci_fast-trunk/3383810/job/pipeline .

Let do this as a sanity check before merging. THanks

**Comment by NicoLeyman** [comment]
Merged master as requested. Fingers crossed Yamato returns a greener result this time around.

**Pull request merged**
