### PR TITLE
[8.x.x] [VFX] Fix Shadow compilation

### PR DESCRIPTION
**Pull request by PaulDemeulenaere**
Manual backport of https://github.cds.internal.unity3d.com/unity/vfx-graphics/pull/77

Actually, squash of https://github.com/Unity-Technologies/Graphics/pull/1719

Require merge of https://github.com/Unity-Technologies/Graphics/pull/1704 before

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
Ping , it is all green, should be merge?

**Comment by PaulDemeulenaere** [comment]
> Ping , it is all green, should be merge?

We need this before : https://github.com/Unity-Technologies/Graphics/pull/1704

**Comment by PaulDemeulenaere** [comment]
Ready to merged @julienf-unity it adds a test 
image

Fix this case https://issuetracker.unity3d.com/product/unity/issues/guid/1259511/ & other inconsistency with shaderGraph integration.

**Comment by PaulDemeulenaere** [comment]
All green @julienf-unity 🟢  If it's not too late, it's ready to be merged.

**Review by julienf-unity — APPROVED** [review]

**Pull request merged**
