### PR TITLE
[Fogbugz 1341576] Memory leaks when the player is paused, and the user changes pipeline…

### PR DESCRIPTION
**Pull request by kecho**
### Purpose of this PR
Toggling any pipeline settings while having the player paused causes memory leaks on the GPU resources.
Fogbugz: https://fogbugz.unity3d.com/f/cases/1341576/
Fixed by detecting if we are paused and using the correct API to delete render target objects.

---
### Testing status
Followed the use case in the fogbogz:
* Tested also on dx11, vulkan and dx12 on PC
* Checked that I didnt crash
* Checked task manager, GPU memory usage and saw that GPU memory is now flat.

### CODE REVIEW

**Review by FrancescoC-unity — APPROVED** [review]

**Review by iM0ve — APPROVED** [review]
Looks safe

**Review by hknielsen — APPROVED** [review]
From my point of view this LGTM, but I think personally I would still see if it was possible to cover with some test

**Comment by kecho** [comment]
> From my point of view this LGTM, but I think personally I would still see if it was possible to cover with some test

Thanks for your review. Will instruct QA to do further testing.

**Comment by kecho** [comment]
@iM0ve the bug is ready for some further testing:
* Do some stress testing on live editing while editor is played (on windows migth suffice).
* Add / remove objects, play unplay, try to see if we hit a crash.
* Try the usecase of playing and pausing, play pause multiple times while the editor is updating
* Test with multiple viewports
* Test with vulkan and dx11. Let me know if you find out anything else. If it looks solid @sebastienlagarde and you agree then I think we can ship this?

**Review by sebastienlagarde — APPROVED** [review]

**Review by TomasKiniulis — COMMENTED** [review]
Tested Dx11 and Vulkan editing objects in playmode paused, unpaused, or going back to editmode. I get no leaks or crashes anymore. 

Adding assets in edit mode, playmode paused/unpaused:

https://user-images.githubusercontent.com/50582134/122027701-01afee80-cdd4-11eb-9ecc-2c8ed5b0a63a.mp4

Removing objects in editor playmode paused/unpaused:

https://user-images.githubusercontent.com/50582134/122027842-2015ea00-cdd4-11eb-8c45-646f2fe0fb55.mp4

Edit: Below occurs in master:
~However, toggling asset options like Low res Transparency in paused playmode sometimes ends up with a warning in console:
`Releasing render texture that is set to be RenderTexture.active!
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
`~
~@kecho any idea if this can be resolved? Can't repro this in master, since it involves a lot of spam clicking and master almost immediately crashes.~

~Releasing Render Texture Warnings:~

https://user-images.githubusercontent.com/50582134/122028070-55bad300-cdd4-11eb-9527-b076db43a437.mp4

**Review by TomasKiniulis — APPROVED** [review]

**Pull request merged**
