### PR TITLE
[VFX] 2021.1 backports

### PR DESCRIPTION
**Pull request by julienf-unity**
### Purpose of this PR
2021.1 backport fixes + some doc update

Fixes:
- Target GameObject attach button does not allow attaching a valid VFX if the last selection was invalid. [Case 1312178](https://issuetracker.unity3d.com/product/unity/issues/guid/1312178/)
- Deleting flow edge between Init and Update throw an invalid opeation exception [Case 1315593](https://issuetracker.unity3d.com/product/unity/issues/guid/1315593/)
- Regression with some settings not always triggering a recompilation [Case 1322844](https://issuetracker.unity3d.com/product/unity/issues/guid/1322844/)
- Having more than five GPU Event output leads to "unexpected token 'if" at compilation [Case 1323434](https://issuetracker.unity3d.com/product/unity/issues/guid/1323434/)
- Deleted properties still show up in the inspector [Case 1320952](https://issuetracker.unity3d.com/product/unity/issues/guid/1320952/)
- Exception in VFXFilterWindow if search field is empty [Case 1235269](https://issuetracker.unity3d.com/product/unity/issues/guid/1235269/)
- Fixed null reference exception when exposing Camera type in VFX graph [Case 1315582](https://issuetracker.unity3d.com/product/unity/issues/guid/1315582/)
- Fixed VFX with output mesh being always reimported [Case 1309753](https://issuetracker.unity3d.com/product/unity/issues/guid/1309753/)
- Modified state in the VFX tab has now a correct state
- Motion Vector map sampling for flipbooks were not using correct mips
- Remove unexpected expression in spawn context evaluation [Case 1318412](https://issuetracker.unity3d.com/product/unity/issues/guid/1318412/)
- Fix incorrect buffer type for strips
- Compilation issue when normal is used in shadergraph for opacity with unlit output

---
### Testing status
Tested locally (VFX gfx + editor tests)

---
### Comments to reviewers
@gabrieldelacruz This only requires a double check on modified files.
@Unity-Technologies/gfx-qa-vfx There are some fixes in importer there, so some tests pass making sure there's no issue regarding this is required

### CODE REVIEW

**Review by gabrieldelacruz — APPROVED** [review]
Looks good! Thanks!

**Review by VladNeykov — CHANGES_REQUESTED** [review]
Hi, found some issues, most I think have explanations, but camera buffers are breaking with this PR. More in the [Test Doc](https://docs.google.com/document/d/133fyeueRCzagKebEa0RSNR9XSFy3xJyzbO4nEz_phIM/edit?usp=sharing)

**Comment by gabrieldelacruz** [comment]
> Hi, found some issues, most I think have explanations, but camera buffers are breaking with this PR. More in the [Test Doc](https://docs.google.com/document/d/133fyeueRCzagKebEa0RSNR9XSFy3xJyzbO4nEz_phIM/edit?usp=sharing)

If I understood correctly, this PR targets 2021.1/staging, and there are no camera buffers in that version.
I see in the document that the version of the editor used was 2021.2.0b6.3225. That one may have the C++ changes for camera buffers, but it would require the C# changes that are not present in this branch.

**Comment by VladNeykov** [comment]
> > Hi, found some issues, most I think have explanations, but camera buffers are breaking with this PR. More in the [Test Doc](https://docs.google.com/document/d/133fyeueRCzagKebEa0RSNR9XSFy3xJyzbO4nEz_phIM/edit?usp=sharing)
> 
> If I understood correctly, this PR targets 2021.1/staging, and there are no camera buffers in that version.
> I see in the document that the version of the editor used was 2021.2.0b6.3225. That one may have the C++ changes for camera buffers, but it would require the C# changes that are not present in this branch.

Oh! [facepalm] You're completely right, I read it as 2021.2, that makes a lot of sense. Can't wait till we introduce a "3" or above in the numbering. Thanks, will re-run the smoke test in the proper version

**Review by VladNeykov — APPROVED** [review]
My bad on the first round, wrong version.
Ran FTP, no PR-specific issues found.

**Pull request merged**
