### PR TITLE
[Shader Graph] Fix Window Layout bugs

### PR DESCRIPTION
**Pull request by alindmanUnity**
---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

- Fixed a bug where the Main Preview window was no longer a square aspect ratio. [1257053](https://issuetracker.unity3d.com/product/unity/issues/guid/1257053/)
- Fixed a bug where the size of the Graph Inspector would not save properly. [1257084](https://issuetracker.unity3d.com/product/unity/issues/guid/1257084/)
- Increased the default size of the Graph Inspector to not cut off target settings. 

Broken behavior: 
brokenWindowLayout

Fixed behavior: 
fixedWindowLayout

---
### Testing status

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)
- Other: 
manually tested new graph creation and reloading existing graphs to confirm new window layouts persist. 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics

Any test projects to go with this to help reviewers?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by elizabeth-legros — APPROVED** [review]

**Comment by LandonTownsendUnity** [comment]
Main preview can now be shrunk down to nothing, at which point it is impossible to get it back without deleting the usersettings folder
mainpreviewdeletebug

**Review by ghost — CHANGES_REQUESTED** [review]
Fix Main Preview scaling bug

**Comment by alindmanUnity** [comment]
> Fix Main Preview scaling bug

looks like this is present on master, could you please confirm?

**Review by ghost — APPROVED** [review]
Tested both docked and undocked mode. After the preview resize bug was fixed, I was not able to create any "irreversible" scenarios by resizing the windows. They were always resizeable again after closing and reopening shadergraph. Aside from that, no bugs found either.

**Pull request merged**
