### PR TITLE
New node position when created by dragging a port connector is improved

### PR DESCRIPTION
**Pull request by julienamsellem**
### Purpose of this PR
https://fogbugz.unity3d.com/f/cases/1365292/

When creating a new node by dragging a connector from another node the newly created node was unexpectedly placed (the top left corner of the node was aligned with the mouse position)

With this PR the newly created node is placed so that the connect port position is aligned with the mouse position.

[Before]
YsfsOeCA7u

[After]
nENksCgNh5

---
### Testing status
Tests:
- Create a new operator node from another operator
- Create a new operator node from a context block

---
### Comments to reviewers
The fix will not prevent nodes from overlapping.
If you want to check consistency, you should see a similar behavior with Shader Graph.

### CODE REVIEW

**Comment by MarieGuff** [comment]
Tested and approved on 2021.2.0a15 (37767e16dc73)

**Review by MarieGuff — APPROVED** [review]

**Review by PaulDemeulenaere — APPROVED** [review]
This PR is still draft but I'm assuming it's ready to be reviewed.
The change is pretty straightforward, it looks good to me, let me know if you are doing massive change before merge. 🟢

**Comment by VladNeykov** [comment]
Removed **gfx-qa** (not used, so we never saw this PR) and added **gfx-qa-vfx**.  
Vita or I will take a look.

**Comment by VitaVFX** [comment]
When copy pasting it seems to position nodes in the center of graph. I think it would make sense to paste nodes/blocks based on cursor position to fasten node creation processs. Are we in scope of this PR?
Unity_3LgcNRKotH

**Test results:**

- Dragging from node/block/context - couldn't notice any overlapping or randomly positioned nodes.
- Creating floating nodes/contexts to see if there is any outstanding behavior.
- Tried all combinations above with VFX Graph, Subgraph Operators.

**Review by VitaVFX — APPROVED** [review]
My favourite feature, I mean it :) Thank you for addressing this!
Unity_LZp4szHIb7


Test results:
- Copy pasting/duplicating nodes/contexts, whole systems/multiple nodes
- A few combinations of dragging nodes

**Comment by julienamsellem** [comment]
@VitaVFX: I hope it's not gonna bite me back, but did you also check what happens when you copy/paste multiple selection? Because it added a small bit of complexity.

**Comment by VitaVFX** [comment]
Double checked this behavior based on the raised concern. Properties are positioned farther than used to be before. Tried other exotic layouts, but other than that seems good.
Unity_JxL2Qok54s

**Pull request merged**
