### PR TITLE
[10.x.x][VFX] Importer and compilation various fixes

### PR DESCRIPTION
**Pull request by julienf-unity**
### Purpose of this PR
Various fixes:
- Fix potential infinite compilation when using subgraphs (https://fogbugz.unity3d.com/f/cases/1346576/)
- Prevent out of sync serialization of VFX assets that could cause the asset to be dirtied without reason (https://fogbugz.unity3d.com/f/cases/1327805)
- Fix undetermitism in space with LocalToWorld and WorldToLocal operators (https://fogbugz.unity3d.com/f/cases/1355820/)
- Fix edit only compilation debug mode

This is a backport of  https://github.com/Unity-Technologies/Graphics/pull/5371

---
### Testing status
Tested locally

---
### Comments to reviewers
This PR is meant to be backported to partner branch.
It is high priority

### CODE REVIEW

**Review by PaulDemeulenaere — APPROVED** [review]
Same change than https://github.com/Unity-Technologies/Graphics/pull/5371#pullrequestreview-732508506 🟢

**Review by VladNeykov — COMMENTED** [review]
As discussed on slack, one of the cases ([1355820](https://fogbugz.unity3d.com/f/cases/1355820/))  still reproduces, and the FTP project has a change of behavior due to the World to Local fixes.

Otherwise, no issues found. @julienf-unity please let me know how you'd like to proceed (if the change of behavior is expected and the order of transformations should be fixed here or removed from the changelog and addressed later)

[Test doc](https://docs.google.com/document/d/1zAuJFn1Z35KsPvnwyNQh3b6dlCl_4S_W3qxzsnaNgiI/edit#)

**Review by PaulDemeulenaere — APPROVED** [review]
I double checked this change https://github.com/Unity-Technologies/Graphics/pull/5372/commits/86083d488cf3839a3e6eb534bc543c4b4c2227ba 🟢

**Review by VladNeykov — APPROVED** [review]
Looking good, no outstanding issues pertaining to this PR ([test doc](https://docs.google.com/document/d/1zAuJFn1Z35KsPvnwyNQh3b6dlCl_4S_W3qxzsnaNgiI/edit)). Thanks for the fix!

**Pull request merged**
