### PR TITLE
Added an option to render screen space global illumination in half resolution to achieve real-time compatible performance in high resolutions (case 1353727).

### PR DESCRIPTION
**Pull request by anisunity**
https://fogbugz.unity3d.com/f/cases/1353727/
A new volume parameter "Full Resolution" was added to the ray marching based GI to be able to tune down the cost of the effect a very high rendering resolutions. The cost of the effect is approximately reduced by 4 when disabling the full resolution mode.
image

Testing status
Made sure the rendering looked correct in both full resolution and half resolution modes.

### CODE REVIEW

**Comment by anisunity** [comment]
Found an issue in history buffer discarding, need to fix

**Comment by anisunity** [comment]
Fixed some issues, still some related to the temporal reprojection

**Comment by anisunity** [comment]
Fixed temporal reprojection issues 

https://user-images.githubusercontent.com/42026998/129974002-eeb5546e-cbf4-421c-929e-5483ebb0391d.mp4

**Comment by anisunity** [comment]
DXR tests are green locally

**Review by JulienIgnace-Unity — APPROVED** [review]

**Review by iM0ve — APPROVED** [review]
**Whats tested:**
* Tested the half rez feature works both in SSGI Ray marching and mixed modes
* Upgraded 2 projects to look for visual change
* Based on files changed did a quick smoke test for some parameters of :
 * Raytraced SSGI
 * Raytraced SSAO
 * Raytraced SSS
 
 **Demo:**
As expected before and after the PR there is no visual difference. When using the new feature, the image is different. When denoiser is disabled even easier to spot the resolution changes.

No SSGI
No SSGI

SSGI before PR
SSGI before PR

SSGI after PR
SSGI after PR

SSGI with reintroduced feature Full Resolution = false
SSGI half rez

No denoiser

https://user-images.githubusercontent.com/36502659/130070382-8ea67ad3-22a8-4ba7-b82d-438fbe405f42.mp4

**Pull request merged**
