### PR TITLE
Scene templates and default settings tweaks

### PR DESCRIPTION
**Pull request by Chman**
### Purpose of this PR

- Removed the old default scene system from the HDRP wizard and replaced it by scene templates (builtin feature in 2020.2). It comes with 2 scene templates for indoors and outdoors setups, with proper lighting and exposure setup (and a physical sky for outdoors to replace the old default HDRI sky) - both have a DXR variant that will only show in the template selection popup if DXR is enabled.
- Tweaked the default settings of HDRP:
  - Exposure `Mode` is now set to `Automatic (Histogram)`.
  - Exposure `Limit Min` is now set to `-4`.
  - Exposure `Limit Max` is now set to `+16`.
  - Exposure limits have been reflected on the curve remapping mode as well.
- Cleaned up the doc to remove outdated info about the default scenes.

---
### Testing status

**Manual Tests**:
Created new scenes using each available template. Note: these templates assume you have an HDRP asset setup already or that the Wizard has been ran at least once.

---
### Comments to reviewers
Adding @JordanL8 to validate the template naming scheme and descriptions (look for the four `*.scenetemplate` files). I'm not entirely sure about the naming used here but I followed the one from the two hardcoded templates used with the builtin renderer.

### CODE REVIEW

**Comment by peeweek** [comment]
> Dynamic Gradient sky is used for Ambient lighting. Not sure if better recommended workflow could be using Visual Environment:None with black camera backround. Would this make sense performance/workflow wise?

If I recall correctly, we had a lot of trouble with fog/volumetric fog when no sky was set in visual environment. (it was in 7.x package though)

**Comment by Chman** [comment]
Tweaked a few things:

- Indoors:
  - Changed the ambient mode to static.
- Outdoors:
  - Changed the ambient mode to static.
  - Exposure limit max to 14.
  - Renamed `Directional Light` to `Sun`.
  - Switched to color temperature for the sun.
  - Sun intensity to 110000 lux.

Notes:
- Regarding the wizard bug, I unfortunately cannot reproduce it on my end.
- For the Gradient Sky instead of None, see Thomas' reply. Perhaps it doesn't apply anymore, but because we don't have time to test everything at that point I'd rather play it safe.
- Adding HDRP default settings into the scene would be redundant, especially since scenes can be additively loaded.
- Moving to the PBSky is an unanimous request from all the artists here, and frankly it's miles ahead from the old default / borderline useless HDRI sky :) Eventually it would be nice for the HDRP team to find a trick to avoid this "under ground" rendering situation, but from the input we got the benefits outweigh the drawbacks in our opinion.

**Comment by Chman** [comment]
It should also be noted that I don't have any way of testing the DXR templates, any help is appreciated :)

**Comment by sebastienlagarde** [comment]
I will check DXR template.

**Comment by iM0ve** [comment]
Issues I've found were fixed or discussed. I also tested DXR its exactly the same as regular templates, but has DXR SSR instead of regular SSR. We might want to add more features, even if they are turned off by default - for discoverability.

Found one new issue with unreliable reproduction. After running DXR wizard clicking on random scenes for 10-40 seconds will end up with an error message.
[video link](https://favro.com/organization/c564ede4ed3337f7b17986b6/8ddd69383a55181bd8da3bda?card=Uni-144260)

**Comment by sebastienlagarde** [comment]
>Found one new issue with unreliable reproduction. A
@iM0ve On my version of trunk (almost latest), I don't see the behavior that you show. Can't repro. If you repro it later, it is a bug for scene template team.

On DXR I have just added disable Raytracing Settings, but there is nothing to add more.

PR is good, thanks for that!

Merging

**Pull request merged**
