### PR TITLE
camera prefab null reference fix

### PR DESCRIPTION
**Pull request by martint-unity**
---
### Purpose of this PR
Fix for this case https://fogbugz.unity3d.com/f/cases/1244430/
Removing camera component in prefab, caused a null reference.

### CODE REVIEW

**Review by ellioman — APPROVED** [review]

**Review by madsnyholm — APPROVED** [review]

**Comment by madsnyholm** [comment]
@martint-unity Have you checked if this fix also needs to by applied for HDRP?

**Comment by martint-unity** [comment]
@madsnyholm will check that now

**Review by phi-lira — APPROVED** [review]

**Comment by phi-lira** [comment]
Please add `ready-to-merge` tag when ABV is green and I'll merge it.

**Comment by martint-unity** [comment]
Don't need backport to 7 since it doesnt repro there

**Pull request merged**
