### PR TITLE
[XPipeline][HDRP]Light Editor unification

### PR DESCRIPTION
**Pull request by alex-vazquez**
---
### Purpose of this PR
- Fix indentation of additional properties
- Fix indentation of Help button
- Hide light layers

---
### Testing status
Check that [The UX](https://docs.google.com/document/d/1XlfH365Ak4xGECRSS4QYShWHfHrd6N5qfb7mrar-7Tc/edit)

---
### Comments to reviewers
Nothing big changed, some indentations, HDRP was in a good state

### CODE REVIEW

**Review by TheoWong-pixel — APPROVED** [review]

**Review by RSlysz — APPROVED** [review]
Seams ok.
Though, hiding of Light layer when not supported was not in the doc. Is this ok?

**Comment by alex-vazquez** [comment]
@RSlysz , no it wasn't in the doc, but... 
-  @TheoWong-pixel ask me to hide it on URP 
- https://unity.slack.com/archives/GHD5LADU7/p1619635835035900

Thank you :)

**Comment by RSlysz** [comment]
@TheoWong-pixel I'm sure you considered it already, but just in case of now we can not see light layer because either the additional properties are not shown or the light layer is not supported. I fear users can have hard time understanding what happens.

I add our documentation review to see if we need to clarify anything in the doc

**Comment by JordanL8** [comment]
Our current light layers entry in the Light component documentation says:
`A  mask that allows you to choose which Light Layers this Light affects. The affected Light only lights up Mesh Renderers or Terrain with a matching **Rendering Layer Mask**.<br />This property only appears when you enable [additional properties](More-Options.md) for this section.`

From reading the context, should this last bit instead say something like:
`This property only appears if:<br>&8226; Your Project supports light layers. For information on how to set up light layers, see [light layers](Light-Layers.md).<br>&8226;  You enable [additional properties](More-Options.md) for this section.`

**Comment by TheoWong-pixel** [comment]
Yes that sounds right for the documentation change. I imagine that there will be more of these sections coming up that will require a combo of actions before they are visible, which is what we want :)

**Review by JordanL8 — APPROVED** [review]

**Comment by alex-vazquez** [comment]
Awesome @Unity-Technologies/gfx-qa-hdrp team, could you do a pass on this PR, checking that the UX document for the HDRP Light Inspector look the same? Also do a little smoke test to check no regressions are introduced.

**Review by TomasKiniulis — APPROVED** [review]
No pr specific issues found. Checking all light types, Disabling light layers on/off correctly shows or hides the option in light inspector. Checking all light properties from the UX list does not affect the order and keep properties.

**Pull request merged**
