### PR TITLE
Fix faulty area light tiling

### PR DESCRIPTION
**Pull request by FrancescoC-unity**
I think this is the fix, given that the center is shifted in front of z by half a range. 

Fix for  https://fogbugz.unity3d.com/f/cases/1283644/ 

I tested the repro case and moved around, I also verified we don't over allow area lights by looking at the tile debug view.

### CODE REVIEW

**Review by remi-chapelain — APPROVED** [review]
Auto approving since this looks like a trivial fix and @FrancescoC-unity is confident that fixes the issue !

**Review by sebastienlagarde — APPROVED** [review]

**Review by EvgeniiG — CHANGES_REQUESTED** [review]
The existing code is correct. If there is indeed a problem, it is elsewhere.

**Comment by sebastienlagarde** [comment]
See PR: https://github.com/Unity-Technologies/Graphics/pull/2281

**Comment by EvgeniiG** [comment]
Fixed here: https://github.com/Unity-Technologies/Graphics/pull/2281

**Pull request closed without merging**
