### PR TITLE
HDRP - Fix indentation of quality levels on HDRP Asset

### PR DESCRIPTION
**Pull request by alex-vazquez**
---
### Purpose of this PR
Fix: https://fogbugz.unity3d.com/f/cases/1343289/

New indentation, agreed with @maddalena

image

---
### Testing status
- Test that the UI is restored in collapsed/expanded state
- Test HDRP asset on inspector view
- Test Project Settings > Quality > HDRP and see that is correctly aligned too

---
### Comments to reviewers
- Refactor of this UI has been done, there was a lot of copy pasted code;
- @remi-chapelain , could you please do a smoke test agains master and see that all the quality properties are behaving the same? see the ui on master, ui on this pr, and check that low, medium and high are stored properly, also, that the ui is the same on master and in my PR for all the sections that contain ( low, medium, high )

### CODE REVIEW

**Comment by remi-chapelain** [comment]
Added HDRP QA for awareness and because I don't have much time right now.

**Review by RSlysz — APPROVED** [review]
Way better. When we finally have a UX proof way to display those (custom inspector) we will be able to change every case easily. Thank you :)

**Review by TomasKiniulis — COMMENTED** [review]
Checked through various Lighting Quality Settings and Post-processing Quality Settings effects with Low/Medium/High settings all still works as expected and are properly aligned.

Regarding indentations, any reason why we don't indent properties inside quality levels anymore? It seems to be indented in overrides, why not keep them in the asset too?
image
In my opinion, that would keep it easier to distinct between options in quality level starting and ending.

**Review by sebastienlagarde — APPROVED** [review]

**Review by jenniferd-unity — APPROVED** [review]
Yay! amazing PR, definite improvment in our code base! thanks Alex!

**Comment by jenniferd-unity** [comment]
@maddalena could you answer @TomasKiniulis 's question about the alignment of items?

**Review by JulienIgnace-Unity — APPROVED** [review]

**Comment by TheoWong-pixel** [comment]
> Checked through various effects in Post-processing Quality Settings and Lighting Quality Settings with Low/Medium/High settings all still work as expected and are properly aligned.
> 
> Regarding indentations, any reason why properties inside quality levels are not indented anymore? It seems to be indented in overrides, why not keep them in the asset too?
> image
> In my opinion, that would keep it easier to distinct between options in quality level starting and ending.

They are slightly different, Volumes is the one that has a strange UI. I would not compare the two. The Asset one is the one we are aiming for and it aligns more with core Unity UI standards, in the coming year we are hoping to improve on the Volume one as well. Stay tuned!

**Pull request merged**
