### PR TITLE
Test fixes for PR 107417

### PR DESCRIPTION
**Pull request by DennisDeRykeUnity**
---
### Purpose of this PR
This PR modifies the package manifests of the relevant test projects to pick up an as-of-yet-unpublished version of the Graphics Test Framework.  The intention is to avoid SRP test failures on Yamato that will otherwise be introduced by Unity trunk PR 107417.

I ran my dev branch on Yamato  to compare the latest PR 107417 dev branch against its trunk parent.  Yamato links and changeset info appears below.  Feel free to merge my PR once the PR 107417 SRP ABV is green (or as green as the Trunk SRP ABV).

* TRUNK SRP ABV
Unity (trunk 73960b2166c6)
SRP (PR_107417_dennisd 1871e9e)
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/PR_107417_dennisd/.yamato%252F_abv.yml%2523all_project_ci_CUSTOM-REVISION/2432590/job

* PR 107417 SRP ABV
Unity (unity/draft#xr/remove-apis 7dce985b5fa3)
SRP (PR_107417_dennisd 1871e9e)
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/PR_107417_dennisd/.yamato%252F_abv.yml%2523all_project_ci_CUSTOM-REVISION/2432658/job

### CODE REVIEW

**Comment by DennisDeRykeUnity** [comment]
Last night my "PR 107417 SRP ABV" job had lots of dependencies that were cancelled by Yamato, so @stramit re-launched them.  Many of these passed.  For those that still failed I compared the results against both my "TRUNK SRP ABV" job and recent fast-trunk ABV on master.  

The most drastic problem I see with this PR (and by association, with PR 107417) is that the MacOSX hosts need maintenance before they can run these tests (until the latest commit of GTF gets published).  

For other pipelines within SRP ABV I only see discrepancies in a few tests when I compare: 
* PR 107417 SRP ABV (including re-launch after Yamato breakage)
* TRUNK SRP ABV
* ABV fast-trunk on recent master

Deatails appear below.  I'll take a closer look at these few discrepancies tomorrow, though I highly suspect this PR is safe to merge (along with PR 107417).  @stramit How does this look to you? 

-------------------------------------------------------------------------------------------

* VFXMain on Win_DX11_Standalone
* VFXMain on Win_DX11_playmode
Two tests failed:
- 24_MotionVector: enitely black output image
- ShadergraphSampleScene: trivial difference in output image
=> Same tests failed with same results on both TRUNK SRP ABV and master.


* HDRP on Win_Vulkan_playmode
One test failed: 
- 1215_Lit_SubSurfaceScattering: 
=> miscolored object when transmission is none
=> Same test failed on TRUNK SRP ABV and master.


* HDRP on Win_DX11_playmode_XR
28 tests failed: 
=> Same tests failed on TRUNK SRP ABV and master except 8102_Transparent: 
=> Test exceeded Timeout value of 300000ms


* HDRP on Win_DX11_playmode
27 tests failed: 
=> Same tests failed on master.
=> Same tests failed on TRUNK SRP ABV except
=> 9401_MSAAForwardOnly failed only for TRUNK SRP ABV
=> 9901_AOV_buffers failed only for PR 107417 SRP ABV


* Universal on OSX_Metal_playmode_XR
* Universal on OSX_Metal_playmode
* Universal on OSX_Metal_Standalone
com.unity.testframework.graphics: Error when executing git command. Host key verification failed.
    fatal: Could not read from remote repository.
One of the processes crashed or exited abnormally.
-------------------------------------------------------------------------------------------

**Comment by sophiaaar** [comment]
you can now use version 7.2.2-preview instead of referencing the git url :)

**Comment by sophiaaar** [comment]
i assume this PR can be closed because #771 merged?

**Comment by DennisDeRykeUnity** [comment]
@sophiaaar is correct; this PR can be closed because PR 771 has been merged.

**Pull request closed without merging**
