### PR TITLE
[HDRP][Path Tracing] Replaced recursive continuation rays with loop in ray generation

### PR DESCRIPTION
**Pull request by eturquin**
Although user-wise there should not be too much visible change (if at all), other than slightly improved performance (in the 5-10% range after early tests), this PR removes the recursion from the path tracing, with no more continuation rays shot from closesthit().

This allow us to use an arbitrary number of bounces (still caped to 10 in the UI, but could be increased to any value now), without adding to the recursion level. This also makes aspects of the code cleaner and easier to read (no more do we have to deal with different miss() functions, for instance).

This will also hopefully open the door to other optimizations, like returning a BSDFData-like payload from closesthit() and do all shading computations in the raygen(), or even return a materialID and compute BSDFData or equivalent in the raygen() too.

**TO BE TESTED:** general path tracing usage, making sure nothing is blatantly broken. 5 of the tests have changed slightly, because of a Russian roulette adjustment. Refs have been updated. Also, the old intensity clamping scheme cannot be applied anymore, without "faking" recursion, so a slightly different one is now in place, that may produce a bit more fireflies.

### CODE REVIEW

**Comment by eturquin** [comment]
Yamato currently fails with DXR tests for unrelated matters. I tried running all HDRP tests locally, and they are all green.

**Review by pmavridis — APPROVED** [review]
Looks good to me, removing recursion is definitely the right direction for the path tracer.

**Comment by remi-chapelain** [comment]
Preliminary tests shows at least three things: 
- There is somewhat more "fog" compared to master
- The process of accumulation is substantially slower (which is expected but not that much) by roughly 167% in an inside environment and 135% outside (where there's more ray miss basically)
- The noise pattern is different (which is expected) 

330a8dadba1bf3fd96178c3bcc646705

c4e58fd3450b41843275d913575ffef1

Will wait for @eturquin to come back to re-evaluate what can be done for speed and fog.

**Review by sebastienlagarde — APPROVED** [review]
@eturquin see with QA for validation, then try to merge before cutoff (with yamato validation)

**Comment by sebastienlagarde** [comment]
hmm.. need to merge master first

**Review by remi-chapelain — CHANGES_REQUESTED** [review]
For fog issue. (WIP)

**Review by remi-chapelain — APPROVED** [review]
Fog issue has been fixed, now approving ✔️
The accumulated images matches between this PR and master. ✔️ 

There's is two or three slight differences that can be noted for future reference: 
- Perf can a bit a little bit better or a little bit worse (depending on the scene and the setup)
- Intensity clamping is a bit different so there's going to be more fireflies by default (the difference is very light and can be seen only when zooming a lot)
- Noise can be a bit different

https://user-images.githubusercontent.com/57442369/155185961-e7e4525a-7346-4914-8bff-2fea7d000721.mp4

**Comment by eturquin** [comment]
In case there still is a tiny window to merge this, it is ready.

**Comment by sebastienlagarde** [comment]
replicated on provate github PR

**Pull request closed without merging**
