### PR TITLE
[VFX/X-Pipeline] Update HDRP asset

### PR DESCRIPTION
**Pull request by PaulDemeulenaere**
### Purpose of this PR
Update HDRP pipeline asset & commit the default SRP settings after changes introduced by PR : https://github.com/Unity-Technologies/Graphics/pull/3054

See also this equivalent update : https://github.com/Unity-Technologies/Graphics/pull/3995

---
### Testing status
Awaiting for Yamato ⏳ 
Running in [internal](https://yamato.cds.internal.unity3d.com/jobs/339-ScriptableRenderPipelinePrivate/tree/vfx%252Ffix%252Fmissing-hdrp-default-settings/.yamato%252Fall-vfx_hdrp.yml%2523PR_VFX_HDRP_CUSTOM-REVISION/6035148/job/full-pipeline) ⏳

### CODE REVIEW

**Review by jenniferd-unity — APPROVED** [review]

**Comment by PaulDemeulenaere** [comment]
@jenniferd-unity Looking at the test result from https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/vfx%252Ffix%252Fmissing-hdrp-default-settings/.yamato%252Fvfx_hdrp-osx-metal.yml%2523VFX_HDRP_OSX_Metal_playmode_cache_mono_Linear_trunk/6034522/job/artifacts
There is probably a settings which hasn't migrate correctly

e.g.:
006_StripAttributes
006_StripAttributes expected

009_MultiCamera
009_MultiCamera expected

**Comment by PaulDemeulenaere** [comment]
> @jenniferd-unity Looking at the test result from https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/vfx%252Ffix%252Fmissing-hdrp-default-settings/.yamato%252Fvfx_hdrp-osx-metal.yml%2523VFX_HDRP_OSX_Metal_playmode_cache_mono_Linear_trunk/6034522/job/artifacts
> There is probably a settings which hasn't migrate correctly

Fixed at https://github.com/Unity-Technologies/Graphics/pull/4017/commits/18a7940d9fdec6e7e5868d06df93e042eb5a9437

**Comment by PaulDemeulenaere** [comment]
image
Play mode runs 🟢

**Comment by PaulDemeulenaere** [comment]
Beside issue with package verification : 
```
Failed - "API Updater Configuration Validation"
```
(...)
```Validator logs:
[C# Update Tests] MoveToNamespace_UnityEngine.Rendering_MaterialQuality.cs(1,57): error CS0246: The type or namespace name 'Utilities' could not be found (are you missing a using directive or an assembly reference?)```
Nightly VFX HDRP is green 🟢 
@jenniferd-unity Can you double check my changes (and especially this one https://github.com/Unity-Technologies/Graphics/pull/4017/commits/18a7940d9fdec6e7e5868d06df93e042eb5a9437) before merge ?

**Review by jenniferd-unity — APPROVED** [review]

**Pull request merged**
