### PR TITLE
Update HDRP Template for 2020.2 [Skip CI]

### PR DESCRIPTION
**Pull request by sebastienlagarde**
### Purpose of this PR
This PR update the current HDRP template to be like:

TODO: need to update controller and text

Replace PR: https://github.com/Unity-Technologies/Graphics/pull/671 - update to latest version of master

---
### Testing status

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)
- Other: 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics

Any test projects to go with this to help reviewers?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by iM0ve** [comment]
As I understand this is not the latest version, will take a look when updated

**Comment by AQ-u3D** [comment]
I've just committed the latest updates based on prior feedback to the PR.

**Comment by iM0ve** [comment]
Can we delete the folder called Presets? Or it serves some purpose?

**Comment by sebastienlagarde** [comment]
Added FPS controller and tested various collision sceneario cases. Added box collider everywhere it was an issue. Updated the readme.asset. There is still polish to do on this template, but good to merge

**Pull request merged**
