### PR TITLE
Reconstruct worldpos docs branch

### PR DESCRIPTION
**Pull request by eh-unity**
Separated the docs from https://github.com/Unity-Technologies/Graphics/pull/2529

### CODE REVIEW

**Review by Verasl — APPROVED** [review]
LGTM and this is a nice example, in the furture we need to add a shadergraph version, but this can come later.

**Review by oleks-k — APPROVED** [review]
Edited the text and approving the changes.

**Review by erikabar — APPROVED** [review]
lgtm

**Comment by eh-unity** [comment]
Only documentation changes, no code. The code tests do not apply to his PR.

**Pull request merged**
