### PR TITLE
Added two toggles to control occluder rejection and receiver rejection for the ray traced ambient occlusion (case 1330168).

### PR DESCRIPTION
**Pull request by anisunity**
https://fogbugz.unity3d.com/f/cases/1330168/

Testing status
Pair tested with QA
DXR tests are green locally

### CODE REVIEW

**Review by CertifiedRice — APPROVED** [review]

**Comment by remi-chapelain** [comment]
Added QA for awareness :)

**Comment by anisunity** [comment]
Added the equivalent for RTGI

**Review by remi-chapelain — CHANGES_REQUESTED** [review]
The fix allows users to be able to choose between rejecting history when the occluder or receiver object is moving based on what you prefer depending on the context (more noise or more ghosting). This works great and allows more flexibility.

image
 
One concern is that this does not work in the scene view. 
This is not something introduced by the PR, before this, the latest change to reject history based on the object moving was also not reflected in scene view (I checked a few commit before). 
This is probably something we would want to be reflected in scene view to avoid confusion.

**Comment by sebastienlagarde** [comment]
Need update on this PR

**Review by remi-chapelain — APPROVED** [review]
The fact that it doesn't work in the scene view is due to the fact that we only have camera motion vectors (and not from the objects), so it's by design. 

Approving then. ✔️

**Review by sebastienlagarde — APPROVED** [review]

**Pull request merged**
