### PR TITLE
[HDRP] Adding transparency setup scenes to material sample

### PR DESCRIPTION
**Pull request by remi-chapelain**
### Purpose of this PR
Following [this (now closed) PR](https://github.com/Unity-Technologies/Graphics/pull/5707), it has been decided that it was better to include this in the material sample to avoid making the HDRP package bigger by sharing some of the materials / textures. 

133756088-929300eb-f339-4035-9a1c-eed99660d66a

Moreover, given we want to reduce the size of the Editor, the size of the material sample have been drastically reduced. 
- Initial material sample size: 69.3mb
- Merged transparency + material: 72.95mb
- Optimized new material sample: 36.27mb

What has been done mostly is converting the TGA to TIFF and reducing the size of unnecessary larger texture (2048 and 1024px). 

53e5bf93ce22c3838080f6b7f6ca4437

It's still possible to go lower (still some large textures) but at the cost of losing some quality when getting close to the materials. 

---
### Testing status
- Imported the sample in a fresh new HDRP project ✔️
- Opened all the scenes independently ✔️

---
### Comments to reviewers
Added @Vic-Cooper to have feedback on documentation and text that is inside the scene. Also I would like to know if you think it's interesting to include some of those bit in the documentation itself for redundancy.
For simplicity purpose, here's a [gdoc ](https://docs.google.com/document/d/1l2d739WxW8hmz4liTjZWDDgbn9Vjp2TMxFH6zbJZJvo/edit?usp=sharing)with all the text.

### CODE REVIEW

**Comment by Vic-Cooper** [comment]
I asked my lead @IritArkinUnity about this, and in-context text doesn't fall under our docs remit. As such, you can publish this PR without my approval. If there's new information in this scene that isn't in the docs, please [create a ticket](https://jira.unity3d.com/secure/CreateIssue.jspa?issuetype=13002&pid=28201) for this task and we can scope the docs additions into a future sprint.

**Review by iM0ve — CHANGES_REQUESTED** [review]
I reviewed the samples and listed the issues in the [doc](https://docs.google.com/document/d/1Z3OjHGciF_6M9J_77cz9wcX8G_MbSNpchO5RYfes1Bo/edit#)

**Comment by remi-chapelain** [comment]
Fixed most of the issue on the feedback document. 👍 
There's still some concerns we can't really fix because of limitations by how the samples are delivered (i.e bad HDRP asset setup etc..)

**Review by iM0ve — APPROVED** [review]
My found issues were addressed. Maybe still worth having a pass on the wording/text

**Pull request merged**
