### PR TITLE
[HDRP] Automated test scene for reflection probes and skies

### PR DESCRIPTION
**Pull request by TomasKiniulis**
### Purpose of this PR
We need a test scene checking reflection probes and settings along different skies and variations

Scene checks Planar Probes and Baked/Realtime Reflection Probes with:
- Gradient Sky
- HDRI Sky
- PBR Sky
- PBR Sky High Altitude
- Reflection probe above PBR Sky 0 Y coordinate
- Reflection probe on PBR Sky 0 Y coordinate
- Reflection probe below PBR Sky 0 Y coordinate

2212_ReflectionProbes_Skies
Unfortunately, baked probes are causing tests to fail due to this issue: https://fogbugz.unity3d.com/f/cases/1272909/

Scene is marked now with "Test Broken" object. Once the bug is fixed, tag needs to be removed from the scene, and enabled in Project Settings

Edit: since the bug was resolved as "By Design" I'm baking PBR sky probes with a delay, but I'm hitting Out Of View Frustum issues that causes test to fail: https://fogbugz.unity3d.com/f/cases/1276072/

---
**Yamato**:
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Ftests%252FrefProbes-skies/.yamato%252Fall-hdrp.yml%2523All_HDRP_trunk/3530888/job/pipeline

### CODE REVIEW

**Comment by TomasKiniulis** [comment]
@sebastianhein @RemyUnity the Out Of Frustum probe bug is fixed preventing the test scene to pass. So it should be ready to go, but a lot other test scenes are failing on Vulkan with this branch. Which works on HDRP/staging, but I don't see how my changes could affect Vulkan here.

**Comment by sebastienlagarde** [comment]
I am merging staging and relaunching Yamato.

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Ftests%252FrefProbes-skies/.yamato%252Fall-hdrp.yml%2523All_HDRP_trunk/3559314/job

**Review by RemyUnity — APPROVED** [review]
Since the two mentioned bugs are fixed now, this PR should be good to land, right ?

**Comment by sebastienlagarde** [comment]
> Since the two mentioned bugs are fixed now, this PR should be good to land, right ?

Right now the PR make vulkan explode (no idea why), thus why it is blocked

**Comment by TomasKiniulis** [comment]
I'm merging staging again and rerunning yamato, in hopes anything has changed, haven't investigated yet what makes it fail

**Comment by TomasKiniulis** [comment]
Update  on this, I can repro Vulkan failing on HDRP/staging too. The difference is that tests have to be ran twice. First all of them pass, second time running half of the same tests fail same way like on my branch. Still no idea why my branch instantly triggers same failing tests instantly though

**Pull request merged**
