### PR TITLE
HDRP Template: new material sphere and various art fixes

### PR DESCRIPTION
**Pull request by pierre-unity**
### Purpose of this PR

- Added new material sphere in Room 1 and 3, removed previous one, and updated cinematic as a result
image
image

- Removed sRGB flag on all detail maps, and tuned corresponding materials to compensate for visual change (very minor change)
image

- Tuned shadows (cascades, contact shadows, directional light biases) to maximize quality on the new material sphere, at both Medium and High quality
image

- Fixed bad normals on metal trims in room 3
image

---
### Comments to reviewers
Very minor changes, mostly artistic related.

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]
Note for myself: this PR affect default lookdev profile and default volume

**Review by iM0ve — DISMISSED** [review]
Changing the default volume breaks the tutorial(can no longer follow instructions). We should either revert the default volume or update the tutorial.

https://user-images.githubusercontent.com/36502659/153850743-ca5365a3-b1a6-42cb-840d-b6d8532427db.mov

**Comment by sebastienlagarde** [comment]
@pierre-unity please could you separate the change on the resources inside the hdrp package from the change of the template in differente PR? This week we are proceeeding to the move to private repo and your PR could be problematic, need to split it.

**Comment by pierre-unity** [comment]
Thanks, I'll do this today ASAP.

**Comment by pierre-unity** [comment]
I've reverted the change to non-template files.

I've also reverted the change to the global profile, and therefore the tutorial is working as expected again.

Ready to merge.

**Comment by sebastienlagarde** [comment]
@joeksy  / @iM0ve  template updated, can you check, thanks

**Review by iM0ve — APPROVED** [review]
The RP can land. I have found some issues that we might want to address later regarding the template but they are not introduced by this change.

What's tested:
* Scene visual with the new changes
* Some bits of tutorial
* Entering playmode
* Launching cinematics
* Creating new scenes

**Issues:**
1) Entering playmode results in "missing scripts" warnings
Unity_EAIcxZcsiU

2) Creating new indoor scene results in an overly bright image. Caused by volumetric clouds.
m5UaiyWUAA

3) Small suggestion to make it easier to use cinematics. Both parent object (Media) and child object (Cinematic timeline) are disabled. Users need to check 2 checboxes to see the cinematic, I would suggest to enable the child and keep partent disabled so its easier to access. TLDR check the checbox in the image

image

**Pull request merged**
