### PR TITLE
Changed the way volumetric clouds presets are handeled to allow for blending.

### PR DESCRIPTION
**Pull request by anisunity**
This PR changes the way presets are described for three reasons:
- Allow the user to blending between various presets.
- Start from a preset and alter it slightly.
- Improving the usage of the samples to increase the quality at equivalent cost.

This PR also changes the actual presets and alters the aplitude distortion.

https://user-images.githubusercontent.com/42026998/154358834-bb0d46d5-3a5e-43e4-ac70-44a3d62c61fd.mp4
https://user-images.githubusercontent.com/42026998/154358882-5ed4e19d-a449-4fcf-9920-a30a73328143.mp4

Testing status:
This will break the HDRP tests and Runtime tests that have clouds.
The blending and the new UI behavior for the clouds volume component is working as expected.

### CODE REVIEW

**Review by RemyUnity — APPROVED** [review]
I tested blending the cloud settings between volumes set to the different presets and a custom settings, all seemed to work properly. 🟢

**Comment by pierre-unity** [comment]
**Issue 1**
image
The default state for the volume still points at older values. We should make sure we use "cloudy" as the baseline for instance.

**Issue 2**
We can remove "Custom" from these labels, it's not really needed anymore.
image

**Issue 3 [Optional]**
I would propose we rename "Cloud Thickness" into "Altitude Range" instead. "Thickness" can be interpreted as "Density" and confuse users.
image

Apart from this, it seems to work really well, I can't find any other issues.

**Comment by pierre-unity** [comment]
https://youtu.be/R-r4UoiJbso

**Comment by pierre-unity** [comment]
Little video showing the blending in action, with different wind directions/speed.
https://user-images.githubusercontent.com/39901544/154852921-216f1526-fdec-4d81-955c-84783799ea00.mp4

**Comment by pierre-unity** [comment]
The presets are also cheaper now:

Cloudy Before/After: 0.41ms -> 0.38ms 
Overcast Before/After: 0.4ms -> 0.37ms
Stormy Before After: 0.43ms -> 0.37ms

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
@anisunity now that @pierre-unity did update, please review the PR, trigger Yamato, see with @JulienIgnace-Unity  for merging

**Review by pierre-unity — APPROVED** [review]
All good!

**Comment by sebastienlagarde** [comment]
replicated on private

**Pull request closed without merging**
