### PR TITLE
Convert XR automated tests to use MockHMD

### PR DESCRIPTION
**Pull request by fabien-unity**
### Checklist for PR maker
- [x] Have you updated the changelog? Each package has a `CHANGELOG.md` file.

---
### Purpose of this PR
- refactor XR automated tests in order to rely on MockHMD
- unlock the ability to run existing tests on standalone player builds
- edit Yamato config files

---
### Testing status
Tested locally with UniversalGraphicsTest on Win10 + Android Google Pixel 1.

Playmode + Playmode_XR
Standalone and Standalone_XR win64 d3d11 mono
Standalone and Standalone_XR android gles3 mono

---
### Comments to reviewers
Cleaner implementation of https://github.com/Unity-Technologies/Graphics/pull/2530

### CODE REVIEW

**Comment by DennisDeRykeUnity** [comment]
I compared all of today's failures for the PR 2812 dev branch against failures for today's SRP master Nightly. 
Most of the failures were identical (item 3 below), or unlikely to indicate problems specific to PR 2812 (item 2 below). 
@fabien-unity  Please advise regarding item 1 below. 

============================================
* PR 2812
- Unity (trunk ed1e382e88f9) 
- SRP (tests/xr/convert-to-mockhmd-1  d137cea)

https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/tests%252Fxr%252Fconvert-to-mockhmd-1/.yamato%252F_abv.yml%2523all_project_ci_trunk/4557224/job/pipeline
============================================
* SRP master
- Unity (trunk ed1e382e88f9)
- SRP (master 4c74a87) 

https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252F_abv.yml%2523all_project_ci_nightly_trunk/4561029/job/pipeline

============================================
1) Suspicious difference between PR 2812 and SRP master: 
- Universal on Win_DX11_playmode_XR_mono_Linear on version trunk 
  Failed for PR 2812 but passed for SRP master: 
  Renderer2DTests.BaseRendererDoesNotCreateRenderTexturesIfStackIsEmpty


2) Differences between PR 2812 and SRP master are probably trivial: 

- Build HDRP_DXR on Win_DX12_mono_Linear_Standalone_build_Player on version trunk 
  Different error messages, but both failed in the same step. 

- Build Universal on Win_DX11_mono_Linear_Standalone_build_Player on version trunk 
  Error below for PR 2812; pipeline still not finished after three hours for SRP master. 
   System.Exception: /home/bokken/build/output/Unity-Technologies/Graphics/TestProjects/UniversalGraphicsTest build failed
   at Unity.UnityTestFramework.PluginBase.EditorTestRunnerPluginBase.Build(ITestList testListFilter)
   at Unity.TestRunner.Common.TestRunnerWrapper.BuildAsync(ITestList testListFilter) in C:\build\output\unity\cds.test-platform\source\Libraries\Unity.TestRunner.Common\ITestRunner.cs:line 37
   at Unity.UnifiedTestRunner.Main.RunSuiteAsync(IKernel suiteRunnerKernel) in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 218
   at Unity.UnifiedTestRunner.Main.RunSuitesAsync() in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 178
   at Unity.UnifiedTestRunner.Main.RunAsync() in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 76

- Universal on Android_OpenGLES3_Standalone_il2cpp_Linear on version trunk
  PR 2812: 92 / 125 tests failed. 
  SRP master: 90 / 124 failed. 

- HDRP on OSX_Metal_playmode_mono_Linear on version trunk 
  PR 2812: One of the processes crashed or exited abnormally.
  SRP master: 14 / 82 tests failed. 


3) These pipelines had the same failures for both PR 2812 and Baseline: 

- HDRP_Hybrid on Win_DX11_Standalone_mono_Linear on version trunk 
  Both branches failed for same test: 
  GraphicsTests.TestLightmaps

- Build Universal on Linux_Vulkan_mono_Linear_Standalone_build_Player on version trunk 
- Build Universal on Win_Vulkan_mono_Linear_Standalone_build_Player on version trunk
  Both branches failed with the same error: 
   System.Exception: /home/bokken/build/output/Unity-Technologies/Graphics/TestProjects/UniversalGraphicsTest build failed
   at Unity.UnityTestFramework.PluginBase.EditorTestRunnerPluginBase.Build(ITestList testListFilter)
   at Unity.TestRunner.Common.TestRunnerWrapper.BuildAsync(ITestList testListFilter) in C:\build\output\unity\cds.test-platform\source\Libraries\Unity.TestRunner.Common\ITestRunner.cs:line 37
   at Unity.UnifiedTestRunner.Main.RunSuiteAsync(IKernel suiteRunnerKernel) in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 218
   at Unity.UnifiedTestRunner.Main.RunSuitesAsync() in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 178
   at Unity.UnifiedTestRunner.Main.RunAsync() in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 76

- VFX_HDRP on Win_Vulkan_Standalone_mono_Linear on version trunk 
- VFX_HDRP on Linux_Vulkan_Standalone_mono_Linear on version trunk  
  Both branches failed for same test: 
  UnityEngine.VFX.Test.VFXGraphicsTests.17_GPUEvent_Simple

- Universal on OSX_Metal_playmode_mono_Linear on version trunk
  Both branches failed for the same test: 
  UniversalGraphicsTests.103_GaussianDepthOfField


============================================

**Comment by DennisDeRykeUnity** [comment]
I compared all of yesterday's SRP ABV failures for the PR 2812 dev branch against failures for yesterday's SRP master Nightly.
Most of the failures were identical (item 3 below), or unlikely to indicate problems specific to PR 2812 (item 2 below).  
I see nothing in these results that make me suspect a breakage is introduced by this PR now that Fabien has circumvented the 2D test that failed per my 12/10/2020 comment.

----------------------------------------------------------------------------------------
* PR 2812
* Unity (trunk ed1e382e88f9) 
* SRP (tests/xr/convert-to-mockhmd-1 86bccd0)

https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/tests%252Fxr%252Fconvert-to-mockhmd-1/.yamato%252F_abv.yml%2523all_project_ci_trunk/4568810/job/pipeline

----------------------------------------------------------------------------------------
* SRP master
* Unity (trunk ed1e382e88f9)
* SRP (master 4c74a87)

https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252F_abv.yml%2523all_project_ci_nightly_trunk/4564699/job/pipeline

============================================

1. Suspicious difference between PR 2812 and SRP master:
   None.


2. Differences between PR 2812 and SRP master that are probably not introduced by PR 2812:

* Universal on Android_OpenGLES3_Standalone_il2cpp_Linear
  For PR 2812, 80/110 tests failed.  For SRP master, 91/124 tests failed.  
  Both branches have errors similar to this: 
    Error setting CPU thread affinity, errno=3, tid=4858

* Universal on OSX_Metal_playmode_mono_Linear
  PR 2812 execution log says, "FAILURE REASON: One of the processes crashed or exited abnormally."
  SRP master execution log says UniversalGraphicsTests.103_GaussianDepthOfField failed. 

* HDRP on Linux_Vulkan_playmode_mono_Linear
For both branches 0/249 tests failed, and both branches' execution logs said:
Reason(s): FAILURE REASON: One or more non-test related errors or failures occurred.


3. These pipelines had the same failures for both PR 2812 and Baseline:

* Build Universal on Win_DX11_mono_Linear_Standalone_build_Player
* Build Universal on Win_Vulkan_mono_Linear_Standalone_build_Player
* Build Universal on Linux_Vulkan_mono_Linear_Standalone_build_Player
errors: 
   System.Exception: C:\build\output\Unity-Technologies\Graphics\TestProjects\UniversalGraphicsTest build failed
   at Unity.UnityTestFramework.PluginBase.EditorTestRunnerPluginBase.Build(ITestList testListFilter)
   at Unity.TestRunner.Common.TestRunnerWrapper.BuildAsync(ITestList testListFilter) in C:\build\output\unity\cds.test-platform\source\Libraries\Unity.TestRunner.Common\ITestRunner.cs:line 37
   at Unity.UnifiedTestRunner.Main.RunSuiteAsync(IKernel suiteRunnerKernel) in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 218
   at Unity.UnifiedTestRunner.Main.RunSuitesAsync() in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 178
   at Unity.UnifiedTestRunner.Main.RunAsync() in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 76

* HDRP on OSX_Metal_playmode_mono_Linear
  The same 14/82 tests failed for both branches. 

============================================

**Comment by fabien-unity** [comment]
Note: I put a draft PR of the internal xr testing package here: https://github.com/Unity-Technologies/Graphics/pull/2810 for easier review

**Review by thomas-zeng — APPROVED** [review]

**Comment by DennisDeRykeUnity** [comment]
Repeating our experiment from the past few days, Fabien meged the latest Graphics master into his dev branch and I tried to compare results for the following pipelines.  However, SRP master seems to no longer include many of these pipelines for Nightly, so my comparison is less conclusive today. I pinged #srp-nightly-status about this. 

-----------------------------------------------------
- PR 2812
- Unity (trunk 3fda0592066d)
- SRP (tests/xr/convert-to-mockhmd-1 4ac9b3a)

-----------------------------------------------------
- SRP master
- Unity (trunk ed1e382e88f9)
- SRP (master 193a1bd)

-----------------------------------------------------
1) Xcode errors.
- ShaderGraph on OSX_Metal_playmode_mono_Linear
- Universal_Hybrid on OSX_Metal_playmode_mono_Linear
- Universal on OSX_Metal_playmode_mono_Linear
- HDRP on OSX_Metal_playmode_mono_Linear 

These pipelines all failed with the following error.  I suspect problems with Mac Yamato hosts,  so I asked about this on #devs-yamato. 
xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist

2) Terminated task.
- Universal on Android_OpenGLES3_Standalone_il2cpp_Linear

This failed for PR 2812 with the following exception.  I doubt this PR's code changes caused this, but SRP Nightly did not include this pipeline.  
System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.

3) System exception.
- Build Universal on Win_DX11_mono_Linear_Standalone_build_Player
- Build Universal on Win_DX12_mono_Linear_Standalone_build_Player
- Build Universal on Win_Vulkan_mono_Linear_Standalone_build_Player
- Build Universal on Linux_Vulkan_mono_Linear_Standalone_build_Player

PR 2812 failed with the following exception, which we have seen in my previous comments. The latest SRP Nightly did not include this pipeline.
errors:
System.Exception: C:\build\output\Unity-Technologies\Graphics\TestProjects\UniversalGraphicsTest build failed
   at Unity.UnityTestFramework.PluginBase.EditorTestRunnerPluginBase.Build(ITestList testListFilter)
   at Unity.TestRunner.Common.TestRunnerWrapper.BuildAsync(ITestList testListFilter) in C:\build\output\unity\cds.test-platform\source\Libraries\Unity.TestRunner.Common\ITestRunner.cs:line 37
   at Unity.UnifiedTestRunner.Main.RunSuiteAsync(IKernel suiteRunnerKernel) in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 218
   at Unity.UnifiedTestRunner.Main.RunSuitesAsync() in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 178
   at Unity.UnifiedTestRunner.Main.RunAsync() in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 76

**Comment by kivistikliis** [comment]
Yamato changes look good, but these new jobs should also be included in either Universal PR or Nightly jobs, otherwise they never run unless kicked off manually. I've replied in more detail in the slack thread mentioned above!

**Comment by DennisDeRykeUnity** [comment]
Here are the comparisons from yesterday's Yamato results.  I'll comment later about today's results.

------------------------------------------------
* PR 2812 
- Unity (trunk d4338e57aa6f)
- Graphics (tests/xr/convert-to-mockhmd-1 a6301c98)

_Nightly ABV against trunk: 
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/tests%252Fxr%252Fconvert-to-mockhmd-1/.yamato%252F_abv.yml%2523all_project_ci_nightly_trunk/4630958/job/pipeline

Nightly HDRP - trunk: 
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/tests%252Fxr%252Fconvert-to-mockhmd-1/.yamato%252Fall-hdrp.yml%2523Nightly_HDRP_trunk/4630957/job

------------------------------------------------
* Graphics master
- Unity (trunk d4338e57aa6f)
- Graphics (master 174a9ea)

_Nightly ABV against trunk:
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252F_abv.yml%2523all_project_ci_nightly_trunk/4620041/job/pipeline

Nightly HDRP - trunk:
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Fall-hdrp.yml%2523Nightly_HDRP_trunk/4620040/job/pipeline

------------------------------------------------
1) Suspicious behavior: 
* Build Universal on Android_Vulkan_il2cpp_Linear_Standalone_build_Player
PR 2812 failed with same System Exception as item 3 below, but master passed.

* Universal on Win_Vulkan_playmode_XR_mono_Linear
97/155 tests failed for PR 2812; for master none failed, 20 were ignored, and 145 passed. 


2) Probably not introduced by PR 2812: 
* HDRP on OSX_Metal_playmode_mono_Linear
18/233 tests failed for PR 2812, but master ran no tests due to process crash. 


3) Same behavior for PR 2812 and Graphics master:
* ShaderGraph on OSX_Metal_playmode_mono_Linear
Same test failed for both: ShaderGraphGraphicsTests.LogicNodes

* Build Smoke_Test on Win_DX11_mono_Linear_Standalone_build_Player
Same ambiguous reference error in Library\PackageCache\com.unity.xr.legacyinputhelpers@2.1.6\Editor\MenuUtils.cs

* Build Universal on Win_DX11_mono_Linear_Standalone_build_Player
* Build Universal on Win_DX12_mono_Linear_Standalone_build_Player
* Build Universal on Win_Vulkan_mono_Linear_Standalone_build_Player
* Build Universal on Linux_Vulkan_mono_Linear_Standalone_build_Player
Same error for both, we have seen this before:
System.Exception: C:\build\output\Unity-Technologies\Graphics\TestProjects\UniversalGraphicsTest build failed
   at Unity.UnityTestFramework.PluginBase.EditorTestRunnerPluginBase.Build(ITestList testListFilter)
   at Unity.TestRunner.Common.TestRunnerWrapper.BuildAsync(ITestList testListFilter) in C:\build\output\unity\cds.test-platform\source\Libraries\Unity.TestRunner.Common\ITestRunner.cs:line 37
   at Unity.UnifiedTestRunner.Main.RunSuiteAsync(IKernel suiteRunnerKernel) in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 218
   at Unity.UnifiedTestRunner.Main.RunSuitesAsync() in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 178
   at Unity.UnifiedTestRunner.Main.RunAsync() in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 76

* Universal on OSX_Metal_playmode_mono_Linear
Authentication failures for both. 

* Universal on Linux_Vulkan_playmode_mono_Linear
Same four tests failed for both.

**Comment by DennisDeRykeUnity** [comment]
Here are the latest comparisons of Yamato results for PR 2812 versus Graphics master. 

------------------------------------------------
* PR 2812 
- Unity (trunk 31233d44259e)
- Graphics (tests/xr/convert-to-mockhmd-1 945cc95)

_ABV for SRP repository (all PR jobs) - CUSTOM-REVISION:
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/tests%252Fxr%252Fconvert-to-mockhmd-1/.yamato%252F_abv.yml%2523all_project_ci_CUSTOM-REVISION/4645073/job/pipeline

------------------------------------------------
* Graphics master
- Unity (trunk 31233d44259e)
- Graphics (master 11c7c82)

_Nightly ABV against trunk: 
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252F_abv.yml%2523all_project_ci_nightly_trunk/4653094/job

------------------------------------------------
1) Suspicious discrepancies between PR 2812 and Graphics master: 

* Build Universal on Win_DX11_mono_Linear_Standalone_build_Player
This passed for master, but failed due to a familiar error:
System.Exception: C:\build\output\Unity-Technologies\Graphics\TestProjects\UniversalGraphicsTest build failed
   at Unity.UnityTestFramework.PluginBase.EditorTestRunnerPluginBase.Build(ITestList testListFilter)
   at Unity.TestRunner.Common.TestRunnerWrapper.BuildAsync(ITestList testListFilter) in C:\build\output\unity\cds.test-platform\source\Libraries\Unity.TestRunner.Common\ITestRunner.cs:line 37
   at Unity.UnifiedTestRunner.Main.RunSuiteAsync(IKernel suiteRunnerKernel) in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 218
   at Unity.UnifiedTestRunner.Main.RunSuitesAsync() in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 178
   at Unity.UnifiedTestRunner.Main.RunAsync() in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 76


2) Discrepancies versus Graphics master but probably not Fabien's fault: 

* Universal on OSX_Metal_playmode_mono_Linear
For PR 2812, 2/154 tests failed; for Graphics master no tests ran due to: 
System.IO.IOException: The file '/Users/bokken/Graphics/TestProjects/UniversalGraphicsTest/test-results/Assets/ActualImages/Linear/OSXEditor/Metal/None/AreEqual_WidthDifferentSizeImages_ThrowsAssertionException.png' already exists.

* Universal on iPhone_Metal_Standalone_il2cpp_Linear
* Universal on Android_Vulkan_Standalone_il2cpp_Linear
* Universal on Android_OpenGLES3_Standalone_il2cpp_Linear
Passed for Graphics master, but failed for PR 2812 because a process suffered abnormal termination:
 curl -s https://artifactory.internal.unity3d.com/core-automation/tools/utr-standalone/utr --output utr 


3) Same behavior for PR 2812 and Graphics master:

* ShaderGraph on OSX_Metal_playmode_mono_Linear
For both, 1/39 tests failed with same error: 
System.IO.IOException: The file '/Users/bokken/Graphics/TestProjects/ShaderGraph/test-results/Assets/ActualImages/Linear/OSXEditor/Metal/None/LogicNodes.png' already exists.

* HDRP on OSX_Metal_playmode_mono_Linear
For both, the same 26/233 tests failed.

* Build Universal on Linux_Vulkan_mono_Linear_Standalone_build_Player
* Build Universal on Win_Vulkan_mono_Linear_Standalone_build_Player
* Build Universal on Win_DX12_mono_Linear_Standalone_build_Player
Both PR 28122 and Graphics master failed with the same familiar error:
System.Exception: C:\build\output\Unity-Technologies\Graphics\TestProjects\UniversalGraphicsTest build failed
   at Unity.UnityTestFramework.PluginBase.EditorTestRunnerPluginBase.Build(ITestList testListFilter)
   at Unity.TestRunner.Common.TestRunnerWrapper.BuildAsync(ITestList testListFilter) in C:\build\output\unity\cds.test-platform\source\Libraries\Unity.TestRunner.Common\ITestRunner.cs:line 37
   at Unity.UnifiedTestRunner.Main.RunSuiteAsync(IKernel suiteRunnerKernel) in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 218
   at Unity.UnifiedTestRunner.Main.RunSuitesAsync() in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 178
   at Unity.UnifiedTestRunner.Main.RunAsync() in C:\build\output\unity\cds.test-platform\source\UnifiedTestRunner\Main.cs:line 76

**Comment by DennisDeRykeUnity** [comment]
------------------------------------------
* PR 2812
- Graphics (tests/xr/convert-to-mockhmd-1 67db283)

_Nightly ABV against trunk:
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/tests%252Fxr%252Fconvert-to-mockhmd-1/.yamato%252F_abv.yml%2523all_project_ci_nightly_trunk/4682886/job
------------------------------------------
* Graphics master
- Graphics (master b308645)

_Nightly ABV against trunk:
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252F_abv.yml%2523all_project_ci_nightly_trunk/4677332/job
------------------------------------------
1) Suspicious results: 

* Universal on Win_Vulkan_playmode_XR_mono_Linear
Seven test failed for PR 2812, only for PR 2812.  It looks like the scene is rendering twice in the screen capture: once correctly; and again with a strangely scaled viewport.  Fabien was already aware of the issue.  Thomas Z. has a PR in progress that will fix this in Unity trunk.  


2) Discrepancies versus Graphics master but probably not Fabien's fault:

* HDRP on Win_Vulkan_playmode_mono_Linear
System.IO.IOException: The file 'C:\build\output\Unity-Technologies\Graphics\TestProjects\HDRP_Tests\test-results\Assets\ActualImages\Linear\WindowsEditor\Vulkan\None\AreEqual_WidthDifferentSizeImages_ThrowsAssertionException.png' already exists.

* ShaderGraph on Linux_Vulkan_editmode_mono_Linear
Green for Graphics master, but for PR 2812 a single test failed with:
UnityEditor.ShaderGraph.UnitTests.PropertyTests.ResetPropertyReference failed with: 
System.NullReferenceException : Object reference not set to an instance of an object


3) Failed for both PR 2812 and Graphics master. 

* Universal on Win_DX11_mono_Linear_Standalone_build_Player

* Universal on OSX_Metal_playmode_mono_Linear

* Universal on iPhone_Metal_Standalone_il2cpp_Linear

* Universal on Android_Vulkan_Standalone_il2cpp_Linear

* Universal on Android_OpenGLES3_Standalone_il2cpp_Linear

* ShaderGraph on Android_Vulkan_Standalone_il2cpp_Linear

**Review by sophiaaar — APPROVED** [review]

**Comment by DennisDeRykeUnity** [comment]
(On Monday night I put another comparison of test results in the copy of this PR in our internal GitHub.  Here is my comment from Monday night, except I have excised the links to our internal systems.  If you need those URLs, check my original comment in the internal version of this PR.)

PR 2812
	•	Unity (unity/from-git#se/editor/core-business-metrics-fix-timestamp 773a5e1b5fe2)
	•	Graphics (tests/xr/convert-to-mockhmd-1 f608cad)
	•	(see internal PR for link)

Graphics Master
	•	Unity (unity/from-git#se/editor/core-business-metrics-fix-timestamp 773a5e1b5fe2)
	•	Graphics (master 7d5b400)
	•	(see internal PR for link)

To avoid the ‘Month must be in range 1-12’ bug in trunk, I am comparing the custom revisions above instead of using the latest trunk changeset. Some pipelines were still running when I compared results, and many pipelines had not finished due to infrastructure problems (item 2 below).

However, I sifted through many jobs that failed for PR 2812 (item 1 below). Most of these had identical failures for Master. A few of these failed for some other reason on Master, but I suspect such failures might be masking identical failures on Master.

The TL;DR is that among today’s valid test results I was unable to find any jobs that failed due to Fabien’s code changes.

1)	SIMILAR FAILURES FOR PR 2812 AND MASTER
Several of these failed with Vulkan shader compilation errors. Most others seem more like Yamato infrastructure issues. A few have a test that might be a legitimate failure. Most of these failed in the same manner for PR 2812 and Master, but in a few cases a build error or infrastructure issue may have masked a common failure.
	•	HDRP on Win_DX12_playmode_mono_Linear
	•	HDRP on Win_DX11_playmode_mono_Linear
	•	ShaderGraph on iPhone_Metal_Standalone_il2cpp_Linear
	•	Build Universal on Android_Vulkan_il2cpp_Linear_Standalone_build_Player
	•	HDRP on Win_DX11_playmode_XR_mono_Linear
	•	Build HDRP on Linux_Vulkan_mono_Linear_Standalone_build_Player
	•	Build ShaderGraph on Linux_Vulkan_mono_Linear_Standalone_build_Player
	•	VFX_HDRP on Win_DX11_playmode_XR_mono_Linear
	•	Universal on Win_DX11_Standalone_mono_Linear
	•	Universal on Android_OpenGLES3_Standalone_il2cpp_Linear
	•	Universal on iPhone_Metal_Standalone_il2cpp_Linear
	•	Build Universal on Win_Vulkan_mono_Linear_Standalone_build_Player
2)	INCONCLUSIVE DUE TO INFRASTRUCTURE ISSUES
		These all failed with one of the errors below. I re-launched these jobs hoping that Yamato has regained some stability.
fatal: unable to access (see internal PR for link): transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
	•	Build Universal on Linux_Vulkan_mono_Linear_Standalone_build_Player
	•	Universal on OSX_Metal_playmode_mono_Linear
	•	Universal on OSX_OpenGLCore_editmode_mono_Linear
	•	Universal_Stereo on Win__editmode_mono_Linear
	•	HDRP on OSX_Metal_playmode_mono_Linear
	•	HDRP on Linux_Vulkan_playmode_mono_Linear
	•	HDRP_DXR on Win_DX12_playmode_mono_Linear
	•	Test all packages [project context] Win
	•	ShaderGraph on OSX_Metal_playmode_mono_Linear
	•	ShaderGraph on OSX_OpenGLCore_editmode_mono_Linear
	•	Build VFX_HDRP on Win_DX12_mono_Linear_Standalone_build_Player
	•	Universal_Stereo on Win__editmode_mono_Linear

**Review by DennisDeRykeUnity — APPROVED** [review]
For the past few weeks Fabien has frequently merged master into his dev branch and ran tests on Yamato, and I have compared his results against master (see my seven previous comments above). I found a few quirks, which Fabien addressed punctually. In general, Fabien’s results have been in line with Graphics master.

Master has been red on Yamato for a long time, but I have watched Fabien's Yamato results over a span of time. I have not found evidence of any non-trivial breakage caused by Fabien’s changes, despite many hours spent looking for it.

I believe that this PR is ready to be merged.

**Review by phi-lira — APPROVED** [review]

**Pull request merged**
