### PR TITLE
Preserve depth buffer when blitting screen space reflections output back to main render buffer

### PR DESCRIPTION
**Pull request by christine-johnson**
# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Fixes rendering artifacts with screen space reflections on Apple gpus https://fogbugz.unity3d.com/f/cases/1341052/

This PR preserves the depth buffer contents when the screen space reflections output is blitted back to the main render buffer. This is needed because the depth buffer contents may be used after opaque post processing (e.g. if depth is needed in the transparent pass), and since the SSR pass currently does not preserve the depth buffer then the buffer can have garbage values. So far this has only caused artifacts on Apple gpus (iOS and M1) but it could cause issues elsewhere depending on the graphics driver.

Specifically this changes the depth buffer load action from `DontCare` to `Load`. This could have some performance implications (particularly on tile-based gpus) but there is not enough information at the time of the blit to determine if the depth buffer actually needs to be preserved. Another solution would be to not bind the depth buffer in this case since its not actually needed, but (1) the RenderTexture type does not allow for only binding the color buffer if it’s depth buffer is valid and (2) this would require manipulating the PSO which might also have performance implications.

---
### Testing status
Manually tested against https://fogbugz.unity3d.com/f/cases/1341052/ on M1 to confirm this fixes the rendering artifacts. Requesting @Unity-Technologies/mobile-qa  to verify fix for https://fogbugz.unity3d.com/f/cases/1341052/ on iOS and to verify this does not introduce significant performance regressions on mobile devices (tile-based gpus).
Requesting @Unity-Technologies/gfx-qa to verify this does not introduce any breaking changes to screen space reflections. There are no automated SSR tests due to them being unstable.

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by sebastienlagarde** [comment]
Please add a changelog, thanks

**Comment by ironext** [comment]
[Test Document](https://docs.google.com/document/d/1M_4cZTI_GlXfmGavze8wq0XY2ton5DyWjO6ZRlIiqWs/edit#heading=h.9raqpyvsgerd)

**Review by ironext — APPROVED** [review]

**Comment by christine-johnson** [comment]
@sebastienlagarde do I need to do anything else in order for this change to land?

**Comment by sebastienlagarde** [comment]
all good, merging

**Comment by sebastienlagarde** [comment]
https://unity-ci.cds.internal.unity3d.com/job/10907974/dependency-graph

**Pull request merged**
