### PR TITLE
[Universal] bugfix material post processor fixes

### PR DESCRIPTION
**Pull request by martint-unity**
---
### Purpose of this PR
When opening the latest Master UniversalGraphicsTest Project with the latest Trunk we get a null reference in our material post processor. This happens directly by just opening the project.
This fixes that.

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics

Any test projects to go with this to help reviewers?

---

### CODE REVIEW

**Review by Verasl — CHANGES_REQUESTED** [review]
Need to discuss offline as the problem is much deeper than this fix solves.

**Review by Verasl — APPROVED** [review]
LGTM

**Review by phi-lira — APPROVED** [review]

**Comment by phi-lira** [comment]
Please add `ready-to-merge` tag when ABV is green and I'll merge it.

**Comment by theo-pnv** [comment]
Hi, I have started an ABV with yesterday's pinned editor (`90b2443a8df13ecc935d91f85d723464f8a42028`) to see if we can merge this PR, as it is still needed to get rid of the MaterialPostProcessor nullref exception we have in the nigthlies.
Let's see how the ABV goes and if that is possible, let's try to merge this asap.
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/universal%252Fbugfix%252Fmaterial-post-processor-fixes/.yamato%252F_abv.yml%2523all_project_ci_CUSTOM-REVISION/3646876/job

**Pull request merged**
