### PR TITLE
[URP]Add inspector warning for ortho camera when XR providers installed

### PR DESCRIPTION
**Pull request by Tanya-Li-Unity**
# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
This PR added a camera inspector warning for URP camera editor when camera projection is set to ortho but xr providers detected in the project.
image

---
### Testing status
Editor UI changes only.
Tested in Editor with URP selected as graphics render pipeline.

---
### Comments to reviewers
This PR is a follow-up PR of previous merged PR, which is for build-in render case. https://github.cds.internal.unity3d.com/unity/unity/pull/3032
https://fogbugz.unity3d.com/f/cases/1305592

### CODE REVIEW

**Review by thomas-zeng — APPROVED** [review]
Thanks. LGTM

**Review by amaestas13 — APPROVED** [review]
Looks good.

**Comment by Tanya-Li-Unity** [comment]
just noticed that there is a URP camera inspector UI refactor PR merged today and I need to modify this PR accordingly. 
https://github.com/Unity-Technologies/Graphics/pull/4354

**Review by erikabar — APPROVED** [review]
Approving without testing from URP QA side since XR QA tested it already

**Review by ryanhy-unity — APPROVED** [review]
Verified warning in inspector and did a quick smoke test on Quest.

Ran a quick xr test on yamato too to ensure we don't run into the same issues we had when this was a warning.  Test was green there too.

**Review by phi-lira — APPROVED** [review]

**Comment by phi-lira** [comment]
@Tanya-Li-Unity Formatting job failed. You need to install / run formatter tool as described here: https://github.com/Unity-Technologies/Graphics/tree/master/Tools

Also need to fix conflict nows, drop me a message when all fixed and I'll merge it.

**Comment by phi-lira** [comment]
Question: What are the XR providers? Is that the XR Plugins installed in project?

**Review by CertifiedRice — APPROVED** [review]

**Pull request closed without merging**
