### PR TITLE
Vfx/fix/multiple windows various fixes

### PR DESCRIPTION
**Pull request by julienamsellem**
### Purpose of this PR
https://fogbugz.unity3d.com/f/cases/1382841/
https://fogbugz.unity3d.com/f/cases/1382854/

With the new multiple VFX windows features the user can have one opened VFX and the "No Asset" empty VFX graph.
In that case, if the user tries to create a new VFX from the "No Asset" window and choose the same file as an opened VFX it was opening a second window with the same VFX opened. As this is not supposed to happen there was many times when you could have error in the console then.

ywCfVqFstU
https://user-images.githubusercontent.com/85612173/143286720-8cf570d1-cf3a-41e9-86b8-3349af24fb52.mp4

**To fix this issue, now when you do so, the currently opened window is reused (and put in front) and the content is replaced by the default vfx graph.**

---
### Testing status
I tested the following scenario:
 - Create and open a brand new vfx
 - Select the following menu entry: Window->Visual Effect ->Visual Effect Graph
 - Keep both windows opened but only one tab should be visible (not sure it's mandatory)
 - In the "No asset" window click on the create button
 - Browse to choose the file of the opened VFX
 - Confirm file overwrite

---
### Comments to reviewers
There is two ways to display the "No Asset" VFX tab:
 - Through the menu Window->Visual Effect ->Visual Effect Graph (like described in the scenario above)
 - If you have a VFX opened and you delete the corresponding file
I don't think one way or the other have an influence on the bug.

### CODE REVIEW

**Comment by VitaSkruibyte** [comment]
Thanks! Issue is no longer reproducible, besides that tried various combinations of reproduction in Subgraph Blocks and Operators. There's one issue that's not caused by the PR but seems to be related:

Editor silently crashes when pasting Subgraph Operator in nested Subgraph Operator. Could this be looked into in this PR or you'd like me to log separate bug for this?

How to reproduce:
1. Create a new graph
2. Create float operator and convert it to Subgraph Operator 
3. Convert created operator to Subgraph Operator again
4. Copy the created operator
5. Enter the Subgraph
6. Paste it, Observe that error is thrown
7. Get back to the Parent Graph
8. Copy Subgraph operator again
9. Enter Subgraph Operator and paste it
10. Observe that Unity silently crashed
MBhqGcgv0J

**Comment by julienamsellem** [comment]
> Thanks! Issue is no longer reproducible, besides that tried various combinations of reproduction in Subgraph Blocks and Operators. There's one issue that's not caused by the PR but seems to be related:
> 
> Editor silently crashes when pasting Subgraph Operator in nested Subgraph Operator. Could this be looked into in this PR or you'd like me to log separate bug for this?
> 
> How to reproduce:
> 
> 1. Create a new graph
> 2. Create float operator and convert it to Subgraph Operator
> 3. Convert created operator to Subgraph Operator again
> 4. Copy the created operator
> 5. Enter the Subgraph
> 6. Paste it, Observe that error is thrown
> 7. Get back to the Parent Graph
> 8. Copy Subgraph operator again
> 9. Enter Subgraph Operator and paste it
> 10. Observe that Unity silently crashed
>     MBhqGcgv0J

I'm pretty sure this is an existing bug for which I already have a fix :)
https://github.com/Unity-Technologies/Graphics/pull/6378

**Comment by VitaSkruibyte** [comment]
Apologies Julien I am already in Friday mood, and mixed up PRs. This issue is reproducible with your mentioned bug fix :p

**Comment by VitaSkruibyte** [comment]
Double checked changes. I get NRE when following repro from this: https://fogbugz.unity3d.com/f/cases/1382841/

NullReferenceException: Object reference not set to an instance of an object
UnityEditor.VFX.UI.VFXViewWindow+<>c__DisplayClass7_0.<GetWindow>b__0 (UnityEditor.VFX.UI.VFXViewWindow x) (at C:/Users/vita.skruibyte/Documents/SRP/com.unity.visualeffectgraph/Editor/GraphView/VFXViewWindow.cs:66)
```

**Comment by VitaSkruibyte** [comment]
Double checked reproductions with various steps, PR looks great, couldn't break anything :) Thank you for fixing this so quickly!

**Review by VitaSkruibyte — APPROVED** [review]

**Review by PaulDemeulenaere — APPROVED** [review]
Only a minor change noticed.

By the way, I noticed the automatic focus from the VFX windows which could be annoying ⬇️ 

https://user-images.githubusercontent.com/22494706/144882649-f01c87cd-7780-4f39-bdc2-e481b1901600.mp4

I don't think it's related and not really an issue.

**Comment by julienamsellem** [comment]
> Only a minor change noticed.
> 
> By the way, I noticed the automatic focus from the VFX windows which could be annoying ⬇️
> 
>  _unexpected_focus.mp4 
> I don't think it's related and not really an issue.

Good catch, thanks.
It's fixed now.

**Pull request merged**
