### PR TITLE
[HDRP] Add debug button apv window

### PR DESCRIPTION
**Pull request by alelievr**
### Purpose of this PR

image

---
### Testing status
- Tested that the button works when the debug window is opened and closed.
- Tested after a domain reload (where the order of panels are different in the debug window)

### CODE REVIEW

**Review by FrancescoC-unity — APPROVED** [review]

**Review by JulienIgnace-Unity — APPROVED** [review]

**Review by iM0ve — CHANGES_REQUESTED** [review]
**Whats tested:**
* Using the button inside/outside playmode
* Using the button when Debug is closed/opened

**Issues:**
1) **FIXED Editor Window naming.** When a new window is created, its called **Unity.Editor.Rendering.Debugger** instead of **Rendering Debugger**. Would it be difficult to have the usual name?

https://user-images.githubusercontent.com/36502659/144865968-47873a55-1e80-4a6b-aa79-02fd1efe2521.mov

**2) FIXED The debug mode broke after name update.**

**Comment by alelievr** [comment]
@iM0ve Good catch! I changed a bit the window code so that it's not possible to open it without the name being set correctly

**Review by iM0ve — CHANGES_REQUESTED** [review]
Updated my review

**Comment by alelievr** [comment]
That should be fixed with the last commit

**Review by iM0ve — CHANGES_REQUESTED** [review]
I have the code change, but the issue persists. On master its working as expected.

https://user-images.githubusercontent.com/36502659/145199168-d06b8020-443a-4aaa-8359-a63d653f4a3f.mov



Here is additional error message maybe it can help:
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.Rendering.DebugWindow.UpdateWidgetStates (UnityEngine.Rendering.DebugUI+IContainer container) (at /Users/motiejus.viltrakis/Documents/Git/Graphics/com.unity.render-pipelines.core/Editor/Debugging/DebugWindow.cs:249)
UnityEditor.Rendering.DebugWindow.UpdateWidgetStates (UnityEngine.Rendering.DebugUI+IContainer container) (at /Users/motiejus.viltrakis/Documents/Git/Graphics/com.unity.render-pipelines.core/Editor/Debugging/DebugWindow.cs:266)
UnityEditor.Rendering.DebugWindow.UpdateWidgetStates () (at /Users/motiejus.viltrakis/Documents/Git/Graphics/com.unity.render-pipelines.core/Editor/Debugging/DebugWindow.cs:227)
UnityEditor.Rendering.DebugWindow.Update () (at /Users/motiejus.viltrakis/Documents/Git/Graphics/com.unity.render-pipelines.core/Editor/Debugging/DebugWindow.cs:340)
UnityEditor.HostView.SendUpdate () (at /Users/bokken/buildslave/unity/build/Editor/Mono/HostView.cs:600)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:359)

**Review by iM0ve — APPROVED** [review]
All issues fixed. Updated my review

**Review by sebastienlagarde — APPROVED** [review]

**Pull request merged**
