### PR TITLE
Hd/new-draw-api

### PR DESCRIPTION
**Pull request by JarkkoUnity**
### Purpose of this PR
Enables  motion vector rendering when using Graphics.RenderMeshInstanced()

---
### Testing status
Tested motion vectors are properly rendered for RenderMesh() and RenderMeshInstanced() with a local HDRP project

---
### Comments to reviewers
Requires landed  C++ PR #126439 ("New draw API" for 2021.2)

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]
Please add a section in upgrade guide (the document name upgrade-guide-2021-2.md) to say the change done in the shader, thanks

**Review by CertifiedRice — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
Please add changelog + upgrade guide thanks

**Comment by sebastienlagarde** [comment]
based on this PR: https://ono.unity3d.com/unity/unity/pull-request/126439/_/graphics/new-draw-api

**Comment by iM0ve** [comment]
Also please update the PR description, remove all default text, briefly explain what the PR does and what testing took place. Thank you

**Comment by sebastienlagarde** [comment]
Any update on this PR?

**Review by TomasKiniulis — CHANGES_REQUESTED** [review]
So far running into an issue where universal package added to HDRP template introduces the following errors:
image (48)

**Comment by TomasKiniulis** [comment]
The only issues that stands seems to be the Universal issue listed above. Tested RenderMesh() and RenderMeshInstanced() calls with all MotionVectorGeneration modes. HDRP/Lit, Fabric, LayeredLitTessellation, Unlit and basic SG Lit shaders, not other issues found.

**Review by sebastienlagarde — APPROVED** [review]

**Review by TomasKiniulis — APPROVED** [review]
Thanks for the fix! Switching pipelines to URP, HDRP and back to built-in works without any issues now.

**Review by phi-lira — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
Note for URP Qa: Change on urp side is just addition of those define 
#define UNITY_PREV_MATRIX_M   unity_MatrixPreviousM
#define UNITY_PREV_MATRIX_I_M unity_MatrixPreviousMI
otherwise code is share with HDRP in Core and instance file. 
HDRP QA coverage should be enough. It is not something SRP specific but SRP agnostic. 

I will merge this PR to be part of SRP to core PR happening tomorrow. If you have any comment post merge, please put it here and we will adress them. Thanks

**Comment by jessebarker** [comment]
> Note for URP Qa: Change on urp side is just addition of those define
> #define UNITY_PREV_MATRIX_M unity_MatrixPreviousM
> #define UNITY_PREV_MATRIX_I_M unity_MatrixPreviousMI
> otherwise code is share with HDRP in Core and instance file. + ABV is green (outside of iphone error coming from master)
> HDRP QA coverage should be enough. It is not something SRP specific but SRP agnostic.
> 
> I will merge this PR to be part of SRP to core PR happening tomorrow. If you have any comment post merge, please put it here and we will adress them. Thanks

This breaks BuiltIn.  Were the tests run (they don't appear in the PR details and I can't find them on yamato)?

**Pull request merged**
