### PR TITLE
Disabled specular occlusion for what we consider medium and larger scale rtao > 1.25 with a 25cm falloff interval.

### PR DESCRIPTION
**Pull request by anisunity**
Specular occlusion is currently applied on indirect specular no matter what. This PR disables specular occlsuion on RTAO for wider ambient occlusion RayLength > 1.5meters.
https://fogbugz.unity3d.com/f/cases/1304315/

Testing status
Ran the tests locally, made sure the updated screenshots made sense and tested ssao vs rtao

### CODE REVIEW

**Review by iM0ve — CHANGES_REQUESTED** [review]
The issue is fixed. However, I found one concern.

Maybe it is expected, but It seems that the Debug mode now does not match the Ambient occlusion fix. Do we have to make the change for the debug mode too? If this is intended, let me know and I will approve.

**Concern**
6lByVQ34DR

Before PR:
Before

After PR:
After

**Whats tested:**
* Tested if the issue in fb was addressed
* Debug mode
* Other areas of the scene to make sure AO is still working as intendeded

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
>Maybe it is expected, but It seems that the Debug mode now does not match the Ambient occlusion fix. Do we have to make the >change for the debug mode too? If this is intended, let me know and I will approve.
Hey, yes it is expected and in particular, the SSAO mode don't show what the specular occlusion is.

**Review by iM0ve — APPROVED** [review]
Approving since the concern I found is expected. No other issues

**Comment by sebastienlagarde** [comment]
@anisunity This PR fail on standalone 001 template, I don't understand why. For now reverted from hd/bugfix

**Comment by sebastienlagarde** [comment]
ok, fixed default value and re-integrated the PR

**Pull request merged**
