### PR TITLE
[10.x.x] Populate isDefaultViewport based on XRPass data

### PR DESCRIPTION
**Pull request by thomas-zeng**
### Checklist for PR maker
- [x] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ]  Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
* Moved cameraData XR update logic to helper function in XRSystem
* Populate isDefaultViewport for XR. This will force blit for non-default viewport case. This is required until URP supports dynamic resolution

---
### Testing status

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)
- Other: 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics

Any test projects to go with this to help reviewers?

---
### Comments to reviewers
- With this PR, URP will blit to eyeTexture respecting viewport returned by XRSDK.
- This PR removes render-direct-to-eye case when viewport is not default. This is not great for perf but we need this for correctness. Render-direct-to-eye with non-default viewport requires dynamic resolution support in URP

### CODE REVIEW

**Comment by ellioman** [comment]
Does this PR #1475 solve your issue or would you still need the `isDefaultViewport` ?

**Comment by thomas-zeng** [comment]
@ellioman PR 1475 only adds support to some postFX fx. So it does not solve the issue. When render direct to eye, postFX is always disabled.

**Comment by ellioman** [comment]
> @ellioman PR 1475 only adds support to some postFX fx. So it does not solve the issue. When render direct to eye, postFX is always disabled.

Ahh good to know. Just wanted to be sure :)

**Comment by thomas-zeng** [comment]
To QA: 
This PR fixed a case where render direct to eye texture case does not respect viewport data specified by XRSDK.

**Comment by DennisDeRykeUnity** [comment]
@thomas-zeng Three things: 

1) There is mention in case 1268163 of an Oculus provider side issue.  Until that is fixed, do I need to use RenderDoc with the repro project from case 1268163 to see how this PR fixes Unity's portion of the problem?  

2) Also please assess the likelihood of this PR breaking features on platforms other than Quest. 

3) Also please include the status of test automation that you have run for this. 

Thanks!

**Comment by thomas-zeng** [comment]
Hey @DennisDeRykeUnity,

1. Yes, until oculus fixes provider issues, the best way to check it works is through renderdoc capture.
Oculus side issues are reported here: https://fogbugz.unity3d.com/f/cases/1270117#BugEvent.1072535263

2. This PR should not break any features on other platforms. I believe it is a safe PR. It forces a blit when renderviewport scale is not 1.0f. 

3. I did local testing and with WMR/Quest link/Quest on template scene. Did not notice any issues. 
PR passed most yamato tests. Failed ones are not introduced by PR(see same issue on master, shadergraph, hdrp) https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252F_abv.yml%2523all_project_ci_nightly_trunk/3137262/job/pipeline

**Comment by thomas-zeng** [comment]
@DennisDeRykeUnity 
Is there any update on this PR?

**Review by DennisDeRykeUnity — APPROVED** [review]
Thomas has already performed the same testing that I would do.  Compliant with current guidance from management I am approving this PR without further testing on my part which would merely duplicate Thomas' effort.

**Comment by thomas-zeng** [comment]
Yamato is in a bad state and failed to update the github PR testing status. Green ABV is here: https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/universal%252Fxr%252Fforce-blit-non-deafult-viewport/.yamato%252F_abv.yml%2523all_project_ci_trunk/3508854/job/pipeline

**Comment by phi-lira** [comment]
ABV is not green. It might have been related to the yamato issues we are experiencing but still I can't merge it while red and without a reason. Please double check/re run ABV.

**Pull request merged**
