### PR TITLE
Updating base images

### PR DESCRIPTION
**Pull request by jpg-unity**
### Checklist for PR maker
- [o ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [o ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ o] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [x] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?
We need to update the base images of speedtree scenes following changes to fix cross lod fading

---
### Testing status
n/a

---
### Comments to reviewers
n/a

### CODE REVIEW

**Comment by jpg-unity** [comment]
First time I update these base images. Waiting to see if this will yield all variants of 035_Shader_TerrainShaders tests to pass (this is to address this bug https://fogbugz.unity3d.com/f/cases/1308077/)

**Comment by ellioman** [comment]
Just wanted to note that the testfilters file currently disables this test on various platforms because of this and another issue (1304675). I don't see you removing any of those filter items in this PR so you're quite likely missing out on some platforms in the Yamato job.

**Comment by jpg-unity** [comment]
Thanks for pointing that out Elvar. Ok, will make sure Yao and I sync up to
re-enable this test when he's done. Cheers!

**Comment by nigeljw-unity** [comment]
Added a yamato run for a platform where it was failing: https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/fix%252F1308077-speedtree-images/.yamato%252Funiversal-linux-vulkan.yml%2523Universal_Linux_Vulkan_playmode_cache_mono_Linear_trunk/5061292/job

**Comment by nigeljw-unity** [comment]
Do we still need this ref image update or have they already been updated in other PRs? If so, we should close this one.

**Pull request closed without merging**
