### PR TITLE
[Fogbugz # 1363291] Fix lens flare position for celestials

### PR DESCRIPTION
**Pull request by kecho**
### Purpose of this PR
Celstials lens flare was not position correctly when the camera was very far from the origin. This was caused because the relative position trick only works well when the camera is very close to a light source. If something is far enough it will incurr into small precision issues that might accumulate (due to the light position being so far away).

https://fogbugz.unity3d.com/f/cases/1363291/

Before: 
image

After:
image

---
### Testing status
Tested the fogbugz scene.

---
### Comments to reviewers
@Unity-Technologies/gfx-qa-hdrp  Change has been verified by Sean Puller

### CODE REVIEW

**Comment by Aydindeveloper** [comment]
Lens flare in URP does not work properly with Render scale.
For the solution, I applied the change in universal/decal-fixes to DoLensFlareDatadriven.

postprocess.cs

997.
void DoLensFlareDatadriven(Camera camera, CameraData camdata, CommandBuffer cmd, RenderTargetIdentifier source, bool usePanini, float paniniDistance, float paniniCropToFit)
        {
            var gpuView = camera.worldToCameraMatrix;
            var gpuNonJitteredProj = GL.GetGPUProjectionMatrix(camera.projectionMatrix, true);
            // Zero out the translation component.
            gpuView.SetColumn(3, new Vector4(0, 0, 0, 1));
            var gpuVP = gpuNonJitteredProj * camera.worldToCameraMatrix;
            float renderScale = camdata.isSceneViewCamera ? 1f : camdata.renderScale;
            float scaledCameraWidth = (float)camera.pixelRect.width * renderScale;
            float scaledCameraHeight = (float)camera.pixelRect.height * renderScale;

            LensFlareCommonSRP.DoLensFlareDataDrivenCommon(m_Materials.lensFlareDataDriven, LensFlareCommonSRP.Instance, camera, scaledCameraWidth, scaledCameraHeight,

**Comment by kecho** [comment]
> Lens flare in URP does not work properly with Render scale.
> For the solution, I applied the change in universal/decal-fixes to DoLensFlareDatadriven.
> 
> postprocess.cs
> 
> 
> void DoLensFlareDatadriven(Camera camera, CameraData camdata, CommandBuffer cmd, RenderTargetIdentifier source, bool usePanini, float paniniDistance, float paniniCropToFit)
> {
> var gpuView = camera.worldToCameraMatrix;
> var gpuNonJitteredProj = GL.GetGPUProjectionMatrix(camera.projectionMatrix, true);
> // Zero out the translation component.
> gpuView.SetColumn(3, new Vector4(0, 0, 0, 1));
> var gpuVP = gpuNonJitteredProj * camera.worldToCameraMatrix;
> float renderScale = camdata.isSceneViewCamera ? 1f : camdata.renderScale;
> float scaledCameraWidth = (float)camera.pixelRect.width * renderScale;
> float scaledCameraHeight = (float)camera.pixelRect.height * renderScale;
> 
> ```
>         LensFlareCommonSRP.DoLensFlareDataDrivenCommon(m_Materials.lensFlareDataDriven, LensFlareCommonSRP.Instance, camera, scaledCameraWidth, scaledCameraHeight,
> ```
@Aydindeveloper I believe this has been fixed already. Check this PR https://github.com/Unity-Technologies/Graphics/pull/5373
It should be available in 12.x soon

**Review by SeanPuller — APPROVED** [review]

**Comment by Aydindeveloper** [comment]
Sorry, I was referring to URP's Render Scale lens flare issues but the PR you linked seems to for HDRP

**Comment by kecho** [comment]
All tests pass, only a few fails due to unrelated issues.

**Review by sebastienlagarde — APPROVED** [review]

**Comment by kecho** [comment]
NOTE
@Unity-Technologies/gfx-qa-hdrp  Change has been reviewed by Sean Puller

**Comment by kecho** [comment]
@Aydindeveloper

> Sorry, I was referring to URP's Render Scale lens flare issues but the PR you linked seems to for HDRP

I recommend you open a bug, ill notify the URP team on our side. Cheers

**Review by JMargevics — APPROVED** [review]

**Pull request merged**
