### PR TITLE
Changed the roughness value used for screen space reflections and ray traced reflections to match environment lighting (case 1390916).

### PR DESCRIPTION
**Pull request by anisunity**
This PR alters the roughness value that is exported into the normal/roughness buffer for forward objects and that is used for screen space reflections and ray traced reflections to match the pure smooth value used for the environement lighting  (Lit Shader Only).
https://fogbugz.unity3d.com/f/cases/1390916/

Testing status:
Issue doesn't repro anymore on the fogbugz dataset
DXR tests are green locally

### CODE REVIEW

**Comment by remi-chapelain** [comment]
Could you provide the fogbugz link in the PR description ?

**Comment by anisunity** [comment]
Done

**Comment by anisunity** [comment]
Merged master and launching the tests

**Review by iM0ve — APPROVED** [review]
I have tested the PR by updating the project and comparing with master. Also checked that adjusting roughness and clear coat still works.


In the images below, focus on the reflections visible on the car's door.

Before PR:
Before

After PR:
After

Path tracer for reference:
PathTracerRef

**Review by sebastienlagarde — APPROVED** [review]

**Pull request merged**
