### PR TITLE
[Backport][2021.1] Fix Profiler errors with XR multi-pass

### PR DESCRIPTION
**Pull request by fabien-unity**
---
### Purpose of this PR
- backport #3787
- https://fogbugz.unity3d.com/f/cases/1322916/

---
### Testing status
Tested locally with repro instructions from the bug report (win10 + d3d11 + MockHMD+ multi-pass).

### CODE REVIEW

**Review by thomas-zeng — APPROVED** [review]

**Review by ellioman — APPROVED** [review]

**Comment by DennisDeRykeUnity** [comment]
"Universal_Split PR Job - 2021.1" is green except for "Universal_Hybrid on OSX_Metal_playmode_mono_Linear".  Its errors (see excerpt below) look unrelated to test failures. I relaunched this one just now, along with "_ABV for SRP repository (all PR jobs) - 2021.1".

[14:40:00.165 INF] packet_write_poll: Connection to 172.28.224.173 port 22: Operation not permitted

[14:40:00.222 INF] Process exited
[14:40:00.222 INF] lost connection

**Comment by DennisDeRykeUnity** [comment]
The parent PR on master was low risk per discussion with Fabien but backports should be tested more thoroughly.  In addition to Fabien's local tests and automation I plan to run some sanity tests on Quest.

**Review by DennisDeRykeUnity — APPROVED** [review]
I saw no regressions with these configs: 
- Unity Editor from latest 2021.1/staging (changeset 59213b4870d4)
- URP (2021.1/universal/xr/fix-perf-markers-skybox 4e0adab3e5)
- URP Template scene
- Quest
- MultiView
- both OpenGLES3, and Vulkan (Optimized Frame Pacing off to avoid known crash)

"_ABV for SRP repository (all PR jobs) - 2021.1" is green: 
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/2021.1%252Funiversal%252Fxr%252Ffix-perf-markers-skybox/.yamato%252F_abv.yml%2523all_project_ci_2021.1/6071927/job/pipeline

I approve based on these results plus observations in my previous comments.

**Review by eh-unity — APPROVED** [review]
LGTM.

**Comment by eh-unity** [comment]
Seems all green. Hybrid tests were cancelled, but this shouldn't have impact on that.

**Pull request merged**
