### PR TITLE
Universal Shadergraph automated tests

### PR DESCRIPTION
**Pull request by ghost**
# **Please read;**
## **PR Workflow for the Graphics repository:**
* **All PRs must be opened as draft initially**
* Reviewers can be added while the PR is still in draft
* The PR can be marked as “Ready for Review” once the reviewers have confirmed that **no more changes are needed**
* Tests will start automatically after the PR is marked as “Ready for Review”
* **Do not use [skip ci]** - this can break some of our tooling
* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- X Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`. - (not needed I don't think)
- ? Have you updated the changelog? Each package has a `CHANGELOG.md` file. - (not needed I don't think, will change to an X when this is confirmed)
- X  Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420). - Pretty sure automated tests don't need documentation
- X Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test. - the PR is graphics tests

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

The PR is recreating most of the Universal graphics tests (TestProjects\UniversalGraphicsTest) with all "normal" materials replaced with materials using shadergraphs, which reproduce the functionality of the original materials (as close as possible, although sometimes it's not possible to reproduce the original functionality 100%). The new tests will be in TestProjects\UniversalGraphicsTest_ShaderGraph

---
### Testing status

**Manual Tests**: What did you do?
- X Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)
- Other: 
I tested running these graphics test locally, but I don't think most of these other tests are necessary as there are no code changes in this PR.

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)
(There are too many images to add here right now.)

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics

Any test projects to go with this to help reviewers?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

NOTE: When this PR is first made, many of the tests will fail, as I am leaving the original reference images from the original tests so you can see what the differences are. Once they are approved, I can put in new reference images so the tests will pass.

### CODE REVIEW

**Comment by elizabeth-legros** [comment]
So to be clear; the purpose of this new test project is to live along side our current shadergraph test project? Will it be run with our yamato tests?

**Comment by LandonTownsendUnity** [comment]
> So to be clear; the purpose of this new test project is to live along side our current shadergraph test project? Will it be run with our yamato tests?

Yes, this is the idea, but Universal team was supposed to take the tests over, make any changes they need to, and own the tests

**Comment by hdb-unity** [comment]
Looking into a plan for best way to integrate this new test content into CI

**Comment by LandonTownsendUnity** [comment]
We're also missing shadergraph versions of most of the tests after 100, should I make those?

**Pull request closed without merging**
