### PR TITLE
[VFX] API Migration

### PR DESCRIPTION
**Pull request by PaulDemeulenaere**
---
### Purpose of this PR
Minor update from API Migration
Relative to this [C++ PR](https://ono.unity3d.com/unity/unity/pull-request/137337/_/prefabs/case1312900-expose-loadedscenecount)

---
### Testing status
Locally nothing (automatic migration)
Yamato ⏳ 

---
### Comments to reviewers
I'm anticipating the future SRP2Core preventing unexpected change in local package (cc @theo-pnv)

### CODE REVIEW

**Comment by PaulDemeulenaere** [comment]
Missing doc is about:
```Missing Doc on System.Void UnityEngine.Experimental.Rendering.ProbeVolumePerSceneData::SetBakingState(System.String)``` (not related to this PR)

**Comment by PaulDemeulenaere** [comment]
The new issue with Win_DX11_playmode_mono_Linear is related to a [trunk](https://unity.slack.com/archives/CFZERNTS7/p1642604880057100) change

**Comment by theo-pnv** [comment]
Hi, I'm not super familiar with the code, would you mind asking for another review from your team?
Please consider running the VFX_PR and General Checks pipelines also.
Thanks!

**Review by julienamsellem — APPROVED** [review]
Looks good to me.
Thanks.

**Pull request merged**
