### PR TITLE
[HDRP] Add globalmipbias scales support to grad sampling

### PR DESCRIPTION
**Pull request by slunity**
# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [x] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

Globalmipbias was not added to the abstracted GRAD texture sampling macros. The AxF material uses those, so it incidentally adds support for globalmipbias in AxF. I've noticed the required 2^bias uniform was already set by the camera code and used by virtual texturing so reused that.

For potential halo issues, I've checked if we required using the platform GRAD macro in places where the old behavior (without global mip bias) would be required: I've noticed that in VT, when the fallback code is used, even when the node has "enableGlobalMipBias" to false, since the abstracted macros are used, it will effectively still be enabled. That was there before my change. I added a fix for that.

---
### Testing status
Describe what manual/automated tests were performed for this PR

- Tested AxF.
- I used the VT testing scene to manually test my assumptions and my changes (forcing the fallback code to execute) 
- Ran all graphics tests before and after changes (no changes, some fails not related, ie already failing before)

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by kecho — APPROVED** [review]

**Comment by kecho** [comment]
Some feedback:
* Make this PR description a bit better, add  a reason for the PR and describe what changed.
* Add an entry in the CHANGELOG of the core packages explaining the extra support
* Add qa as a reviewer

**Comment by sebastienlagarde** [comment]
@slunity can you update the PR as ask by Kleber? thanks

**Comment by slunity** [comment]
> * Make this PR description a bit better, add  a reason for the PR and describe what changed.

It's in the "Purpose of this PR" section above, have I missed something ?

> * Add an entry in the CHANGELOG of the core packages explaining the extra support
> * Add qa as a reviewer

Done.

**Comment by kecho** [comment]
Hey @GraphineCharles can you do a review?
On my side I see no problems.
We now need to run also yamato tests on this PR.

**Review by sebastienlagarde — APPROVED** [review]

**Review by GraphineCharles — APPROVED** [review]

**Pull request merged**
