### PR TITLE
[VFX] Fix URP compilation with SG (& fix warning)

### PR DESCRIPTION
**Pull request by PaulDemeulenaere**
---
### Purpose of this PR
- Fix this issue : https://fogbugz.unity3d.com/f/cases/1349894/ 
- Correct wrong warning which can't be remove in URP : https://fogbugz.unity3d.com/f/cases/1343124/ (the fogbugz has been already resolved (see https://github.com/Unity-Technologies/Graphics/pull/5092) but the warning itself shouldn't be displayed on URP, this PR addresses this wrong warning condition)

---
### Testing status
About https://fogbugz.unity3d.com/f/cases/1349894/ 
Tested locally, the change is actually really minor and corresponds to a wrong copy/past of template from HDRP https://github.com/Unity-Technologies/Graphics/pull/5187/commits/6251e65af4c066934624929d99a074ba5896ec9f
image
This test will be a part of incoming SG/VFX refactor in URP.

About the warning
**HDRP** : The warning is only displayed if we are using a compatible HDRP target aside
_sg_warning_hdrp

**URP** : The warning is never displayed
_sg_warning_urp

**HDRP+URP** : The warning is displayed only if there isn't URP target
_sg_warning_urp_and_hdrp

---
### Comments to reviewers
@johnpars Did I correctly respect the initial intention behind this warning ? I also edited the message.

### CODE REVIEW

**Review by jessebarker — APPROVED** [review]
LGTM.  Message still wraps nicely within the graph inspector.

**Review by erikabar — APPROVED** [review]
Developer already tested the PR (see the description), approving without additional coverage.

**Review by johnpars — APPROVED** [review]
LGTM

**Review by VladNeykov — APPROVED** [review]
Great description, auto-approving without testing. We'll also spend more time on this in the SG URP refactor. Thanks for the fix!

**Comment by PaulDemeulenaere** [comment]
You can ignore the shaderGraph issue, it already occurs on master :
`ShaderGraph on OSX_OpenGLCore_editmode_mono_Linear on version 2021.2` 
See https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Fshadergraph-osx-openglcore.yml%2523ShaderGraph_OSX_OpenGLCore_editmode_mono_Linear_2021.2/7829715/job

**Pull request merged**
