### PR TITLE
Opt-out of builtin auto baking of ambient/reflection probe.

### PR DESCRIPTION
**Pull request by JulienIgnace-Unity**
### Purpose of this PR
Opt-out of builtin auto baking of ambient/reflection probe.
This caused some issue when baking in HDRP.
https://fogbugz.unity3d.com/f/cases/1313990/

---
### Testing status
Tested the repro step in the fogbugz case

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]

**Comment by iM0ve** [comment]
I tried to take a look at this and compare Master vs Branch. Not sure what it is fixing, on master I get exactly the same result before and after the fix. It's likely I'm doing something wrong, so maybe you could share screenshots with before and after, I could use them to evaluate and approve

Master
Unity_JQFnFquSeB

PR
Unity_5a9O0b7RTt

**Comment by JulienIgnace-Unity** [comment]
Before
image

After
image

So what we fix here is that it's not blue. Basically it just shows us that we don't run useless systems meant for builtin renderer.
The fact that it's black is still a bug but will be fixed in a C++ PR that should land soon.

**Review by iM0ve — APPROVED** [review]
Thank you for the additional info. Looks good

**Comment by sebastienlagarde** [comment]
green custom yamato: https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/hd%252Fskymanager-optout/.yamato%252Fall-hdrp.yml%2523PR_HDRP_CUSTOM-REVISION/6561500/job/pipeline

**Pull request merged**
