### PR TITLE
Fix shader warnings when switching platforms

### PR DESCRIPTION
**Pull request by FrancescoC-unity**
When switching platforms there is always _a lot a lot_ (hundreds if not collapsed) of warnings because of macro redefinition in API files. 

The solution to this is to undefine the macros that will be shortly redefined. This way no shader warnings are there anymore. 

Yamato: https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Ffix-warning-on-platform-change/.yamato%252F_abv.yml%2523all_project_ci_2021.2

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
@FrancescoC-unity do you know if it is a new thing ? Poking @aleks01010101 to be sure we don't do a mistake here :)

**Review by aleks01010101 — COMMENTED** [review]
Why do you need to include HLSLSupport.cginc in the first place?
Also, it sounds a bit odd to me that this fixes shader warnings when switching platforms.

**Comment by FrancescoC-unity** [comment]
> Why do you need to include HLSLSupport.cginc in the first place?
> Also, it sounds a bit odd to me that this fixes shader warnings when switching platforms.

This because something platform side includes said file, when switching platform to said platform, the shaders are compiled with that file and the problem ensues.

**Comment by FrancescoC-unity** [comment]
We agreed with @aleks01010101 to move this to the platform specific packages. Closing this and moving this there

**Pull request closed without merging**
