### PR TITLE
Enable XR Standalone tests for DX11 and DX12 in URP Lighting and URP PostPro

### PR DESCRIPTION
**Pull request by DennisDeRykeUnity**
---
### Purpose of this PR
This PR will enable Fabien's single-eye-stereo tests to run in Standalone mode for DX11 and DX12 using the URP Lighting and URP PostPro test projects.  This was enabled for URP Foundation in my previous PR.  

---
### Testing status
1) I verified that my PR branch includes Win_DX11_Standalone_XR_cache and Win_DX12_Standalone_XR_cache in Nightly for:
* URP Lighting
* URP Post Processing

2) I verified that my Yamato metafile changes do not accidentally remove any pipelines from Nightly for URP Foundation, URP Lighting, nor URP Post Processing. 

3) Two jobs were green for master but not for my dev branch, but rerunning these resulted in green. 

---
### Yamato Links

* Nightly URP_Foundation - trunk (master 7991604)
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Fall-urp_foundation.yml%2523Nightly_URP_Foundation_trunk/5559024/job/pipeline

* Nightly URP_Foundation - trunk (tests/xr/urp_standalone_dennisd_4 dd3ac4a) 
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/tests%252Fxr%252Furp_standalone_dennisd_4/.yamato%252Fall-urp_foundation.yml%2523Nightly_URP_Foundation_trunk/5599101/job/pipeline

* Nightly URP_Lighting - trunk (master 7991604)
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Fall-urp_lighting.yml%2523Nightly_URP_Lighting_trunk/5562002/job

* Nightly URP_Lighting - trunk (tests/xr/urp_standalone_dennisd_4 dd3ac4a) 
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/tests%252Fxr%252Furp_standalone_dennisd_4/.yamato%252Fall-urp_lighting.yml%2523Nightly_URP_Lighting_trunk/5599129/job/pipeline

* Nightly URP_PostPro - trunk (master 7991604)
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Fall-urp_postpro.yml%2523Nightly_URP_PostPro_trunk/5562005/job

* Nightly URP_PostPro - trunk (tests/xr/urp_standalone_dennisd_4 dd3ac4a) 
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/tests%252Fxr%252Furp_standalone_dennisd_4/.yamato%252Fall-urp_postpro.yml%2523Nightly_URP_PostPro_trunk/5599158/job/pipeline

### CODE REVIEW

**Comment by DennisDeRykeUnity** [comment]
@fabien-unity You may add yourself as a reviewer if you wish, but that is not necessary. These are just metafile and YML file changes, analogous to my previous PR.

**Review by sophiaaar — APPROVED** [review]

**Comment by DennisDeRykeUnity** [comment]
For my latest commit  5eaf1e3 I overwrote .yamato/script/gfx_sdet_tools_revision.txt with master to resolve my single merge conflict.  My Nightly Universal_Split trunk is green after rerunning two jobs that originally failed for non-test reasons: 

https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/tests%252Fxr%252Furp_standalone_dennisd_4/.yamato%252Fall-universal_split.yml%2523Nightly_Universal_Split_trunk/5674212/job/pipeline

https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/tests%252Fxr%252Furp_standalone_dennisd_4/.yamato%252Furp_postpro-win-dx11.yml%2523URP_PostPro_Win_DX11_Standalone_XR_cache_mono_Linear_trunk/5674454/job

https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/tests%252Fxr%252Furp_standalone_dennisd_4/.yamato%252Furp_2d-iphone-metal.yml%2523URP_2D_iPhone_Metal_Standalone_cache_il2cpp_Linear_trunk/5674453/job

**Comment by DennisDeRykeUnity** [comment]
After merging I ran Nightly Universal_Split trunk against master commit 9e1ff40 to make sure I broke nothing.  This job had seven dependencies fail for reasons that seem sporadic (process hung, job was canceled, etc.).  These seven pipelines were green upon rerunning.  Here is my Nightly followed by the seven re-runs: 

https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Fall-universal_split.yml%2523Nightly_Universal_Split_trunk/5674728/job/pipeline

https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Funiversal_stereo-win.yml%2523Universal_Stereo_Win_Standalone_cache_mono_Linear_trunk/5675941/job

https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Funiversal_hybrid-osx-metal.yml%2523Universal_Hybrid_OSX_Metal_playmode_mono_Linear_trunk/5675942/job

https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Furp_terrain-iphone-metal.yml%2523URP_Terrain_iPhone_Metal_Standalone_cache_il2cpp_Linear_trunk/5675943/job

https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Furp_lighting-android-opengles3.yml%2523URP_Lighting_Android_OpenGLES3_Standalone_cache_il2cpp_Linear_trunk/5675948/job

https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Furp_lighting-win-dx12.yml%2523URP_Lighting_Win_DX12_Standalone_XR_cache_mono_Linear_trunk/5675957/job

https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Furp_lighting-win-dx11.yml%2523URP_Lighting_Win_DX11_Standalone_cache_mono_Linear_trunk/5675959/job

**Comment by DennisDeRykeUnity** [comment]
... and the Nightly Universal_Split trunk job run by CI against master commit 9e1ff40 was "just green". 

https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/master/.yamato%252Fall-universal_split.yml%2523Nightly_Universal_Split_trunk/5675191/job

**Pull request merged**
