### PR TITLE
Fix artifacts in volumetric lighting near opaque geometry

### PR DESCRIPTION
**Pull request by EvgeniiG**
# Purpose of this PR

Fix https://fogbugz.unity3d.com/f/cases/1231885/

# Testing status
## Manual Tests
Tested on the graphics tests scenes. More manual testing is needed.

## Automated Tests
Not yet.

## Links
**Yamato**: (Select your branch) https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics
More manual testing first.

# Comments to reviewers
So, there are two solutions.
One is to account for the geometry along the camera ray. If the geometry is within the voxel, I effectively make the voxel shorter.
Another is view shadow bias (disabled by default). I implemented view shadow bias by repurposing our normal shadow bias code. It does not appear to be particularly effective, so I disabled it for now. It can be re-enabled in code.

Here's an example where normal bias would help (although it's probably too expensive):

image

### CODE REVIEW

**Comment by EvgeniiG** [comment]
I fixed the issue described above.

**Comment by EvgeniiG** [comment]
One unfortunate limitation is that, when reprojection is enabled, quickly moving the camera towards or away from thin geometry can produce a similar artifact, since the voxels are large, and they get sliced by geometry, so some (parts of) reprojected voxels are in front, some are behind, and some are inside. Can't think of a way to solve this particular issue.

**Comment by iM0ve** [comment]
Not sure what happened, but it looks like the issue is reverted back as it was at the start.

ArtifactsBack

**Comment by EvgeniiG** [comment]
Hmm, really sorry about that, not sure what happened, either... I am looking into this.

**Comment by EvgeniiG** [comment]
The issue is rather challenging to fix. I've made another attempt. Please take a look.

**Comment by iM0ve** [comment]
The PR brings a major improvement and a minor concern. Could you please take a look if we could address it in any way or just take it as a trade-off.

I discussed the concern with Pierre, he also thinks this is a minor issue. However, in my doc he does agree that the fog near lamps looked more realistic before the PR. See test doc:
https://confluence.unity3d.com/display/HDRP/Fix+artifacts+in+volumetric+lighting+near+opaque+geometry

**Comment by EvgeniiG** [comment]
Thanks for testing! That's an unfortunate limitation of how the problem is solved. Since you want to avoid leaks through the geometry, you have to add some kind of bias to look-ups near this geometry. Since we don't know if the geometry is thin, or if lighting is going to leak, we have to add some bias, anyway. It basically works by virtually pushing the wall towards the camera. The issue will be most pronounced if a light is very close to some geometry.

**Pull request merged**
