### PR TITLE
[VFX] Fix picking & selection pass

### PR DESCRIPTION
**Pull request by PaulDemeulenaere**
---
### Purpose of this PR
Fix selection pass & picking with VFX

Case [#1](https://fogbugz.unity3d.com/f/cases/1382788/) & [#2](https://fogbugz.unity3d.com/f/cases/1402283/)
- The missing picking pass was generating unexpected log error on Vulkan (and probably Metal), it was also the case in URP
- The selection pass was incorrect on HDRP with new SG integration

---
### Testing status
Only Manual (these behavior aren't covered by Yamato)

⚠️ The bounding box must be bigger than the VFX to correctly pick particles ⚠️
**HDRP**
*Fixed*

https://user-images.githubusercontent.com/22494706/154097493-6bce2dc6-c3a5-48d6-9df3-7e726bb38868.mp4

*SG*

https://user-images.githubusercontent.com/22494706/154097516-1734e7dc-3357-48e7-9752-1fadeedb6c26.mp4

**URP**
*Fixed*

https://user-images.githubusercontent.com/22494706/154097569-56f3abfb-4d3e-4a39-b421-9c00b9555fbb.mp4

*SG*

https://user-images.githubusercontent.com/22494706/154097579-d091a55d-17f4-4ada-b7fc-8ccadfb612f1.mp4

⚠️ It's likely I forgot an output (or add a typo), I've mainly tested with unlit mesh & quad.

---
### Comments to reviewers
The picking pass was completly missing, most of the changes are relative to this addition, I extended the SceneSelectionPass.
About the specific behavior for SG, see this [conversation](https://unity.slack.com/archives/G1BTWN88Z/p1644920287478289)

HDRP uses a special path to cancel the expected Camera Relative behavior, see changes in [PickingSpaceTransforms.hlsl](https://github.com/Unity-Technologies/Graphics/pull/7148/files#diff-809842fe899f231195f21b2517205bb8b3a4be79864d6d69bde4fc0620260a88)

Known issue without VFX and using vertex modification in SG, see this [discussion](https://unity.slack.com/archives/C9GUFE86N/p1644586889444389)

### CODE REVIEW

**Review by kecho — APPROVED** [review]

**Review by julienf-unity — APPROVED** [review]

**Comment by VitaVFX** [comment]
Issues found:

Tested on URP/ [Repro package](https://drive.google.com/file/d/1FfQGIXcc6DGTZecsTMSXgbnmZAowNjWR/view?usp=sharing)

- On Vulkan, some of the outputs are not selected (Outputs with Unlit SG assigned) and VFX component contains capsule outline (I assume it comes from Output with SG assigned). 

- Warnings mentioned in the [bug report](https://fogbugz.unity3d.com/f/cases/1382788/), are also thrown:
`Shader requires vertex data and is not compatible with DrawIndexedNullGeometryIndirect.`

Unity_OfVKV6r1AE


Other than that checked on URP and HDRP:
Without SG assigned to Output:
- Lit octagon, triangle, mesh output, quad
- Unlit octagon, triangle, mesh output, quad, point, line
- Forward/HDRP Decals
With Lit/Unlit SG assigned:
- Lit octagon, triangle, mesh output, quad
- Unlit octagon, triangle, mesh output, quad, point, line
- Vertex offset

[URP]
Unity_OfVKV6r1AE

[HDRP] 
Unity_s2ZqofC53d

[Decals]
Unity_eGgpLT4fpe

**Comment by PaulDemeulenaere** [comment]
> * Shader requires vertex data and is not compatible with DrawIndexedNullGeometryIndirect.

Thanks, this warning means I missed a template somewhere, let me find it with your repro.

**Comment by PaulDemeulenaere** [comment]
Fix [issue](https://github.com/Unity-Technologies/Graphics/pull/7148#issuecomment-1043186921) at https://github.com/Unity-Technologies/Graphics/pull/7148/commits/3756589e3651347554160b64816b79c6a2201935

The issue was actually possible to reproduce with URP on Vulkan:
**Before**

https://user-images.githubusercontent.com/22494706/154545799-24fa4042-be9f-41bd-b3e3-00f6113905b3.mp4

**After**

https://user-images.githubusercontent.com/22494706/154545825-1b98c430-c0cb-4768-8d5b-37e141e1598b.mp4

See [repro package](https://drive.google.com/file/d/1BcTbmzwv3A2OnAgV4ri0058wqODcgMxd/view?usp=sharing)

It also fixes the VFX behavior :

https://user-images.githubusercontent.com/22494706/154546127-0ccd5759-21bd-4a95-96b5-e01108342daa.mp4

Originally, this PR was only modifying file in template of VFX but now, this change must be reviewed from someone URP: https://github.com/Unity-Technologies/Graphics/pull/7148/commits/3756589e3651347554160b64816b79c6a2201935

**Review by VitaVFX — APPROVED** [review]
Paul verified and showcased the fixed issues, no other remaining concerns left. Thanks for taking care of this! 🟢

**Review by lukaschod — APPROVED** [review]
From URP Side I see biggest change added PassVariant. And judging from other code outside it looks like it was missing before. Looks good.

**Comment by PaulDemeulenaere** [comment]
N.B.: The formatting issue is about `VoxelizeScene.hlsl`

**Pull request merged**
