### PR TITLE
Sg2/foundry update nov

### PR DESCRIPTION
**Pull request by brett-groshong**
### Purpose of this PR

This change updates `ShaderFoundry` and GTF for `sg2/main`.

### CODE REVIEW

**Comment by Nightmask3** [comment]
- Properties, when connected to any output, can cause node field elements to disappear and throws compile errors and breaks main preview output
- Sample texture nodes throw an exception on creation and do not show preview
- Shader Graph window is always created undocked now, should be opened docked next to the game tab by default unless restoring from a previous editor session where it wasn't
- Exception on opening an empty unlit graph: 
image
-
- Deleting a node doesnt work sometimes but its not consistent

**Comment by brett-groshong** [comment]
`Exception on opening an empty unlit graph` from above has been addressed.

**Comment by brett-groshong** [comment]
`Boolean node shouldn't have a preview` from above has been addressed.

image

**Review by elizabeth-legros — APPROVED** [review]

**Comment by Nightmask3** [comment]
> `Exception on opening an empty unlit graph` from above has been addressed.

Found another case in which this triggers, when you move the window from being docked to undocked or vice-versa, need to guard against multiple invocations of `CreateUIData` or something I imagine

**Comment by Nightmask3** [comment]
Seems like changing blackboard property values doesn't properly update previews sometimes, mainly on value changes right now it seems

https://user-images.githubusercontent.com/13033542/203418805-da23309e-76eb-4ce8-9084-0bd11acee248.mp4

**Comment by brett-groshong** [comment]
@Nightmask3 It seems like those are both new issues with how the update flow is running through GTF. I think we're going to change this immediately. Do you want it updated as part of this branch and then immediately changed, or would you rather merge and live with this for a short time?

**Review by Nightmask3 — APPROVED** [review]
Tested and validated functionality

**Pull request merged**
