### PR TITLE
[HDRP] Updated what's new in HDRP 11

### PR DESCRIPTION
**Pull request by alelievr**
### Purpose of this PR
Update What's new with cubemap field change in volumes

### CODE REVIEW

**Review by JordanL8 — APPROVED** [review]
Rephrased some bits, can you double-check the first sentence "Cubemap fields now... etc" to make sure I understood it correctly before merging?

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
>Cubemap fields now accept both [RenderTextures](https://docs.unity3d.com/Manual/class-RenderTexture.html) and >[CustomRenderTextures](https://docs.unity3d.com/Manual/class-CustomRenderTexture.html) if they are formatted like Cubemaps. >This change affects the `HDRI Sky` and `Physically Based Sky` components and allows you to animate both skies.

the " if they are formatted like Cubemaps." is still weird. @alelievr what do you suggets?

**Comment by alelievr** [comment]
Hum, " if they are using the cubmap mode / dimension" would be better I think (dimension is the correct renderTexture property name)

**Comment by sebastienlagarde** [comment]
> Hum, " if they are using the cubmap mode / dimension" would be better I think (dimension is the correct renderTexture property name)

@JordanL8  ?

**Comment by JordanL8** [comment]
Ah sorry I didn't get any notifications for this. Yeah if cubemap mode / dimension is more correct then sounds good :)

**Comment by JordanL8** [comment]
I'll update this

**Comment by JordanL8** [comment]
All good?

**Comment by alelievr** [comment]
Yeah :)

**Review by sebastienlagarde — APPROVED** [review]

**Pull request merged**
