### PR TITLE
Adding (refactoring to) Gbuffer optional slot 3

### PR DESCRIPTION
**Pull request by jonuuukas**
---
### Purpose of this PR
During the RenderPass Input attachment PR, I was asked to refactor GBuffer4 defines to use the existing OPTIONAL_SLOT define logic. This PR introduces those changes as we agreed to add it in a follow up PR. 
---
### Testing status
Manually tested on Editor, iOS and Android (Deferred renderer only, as forward is unaffected)
---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by kaychang-unity — APPROVED** [review]
Thanks!

**Review by phi-lira — APPROVED** [review]

**Review by ernestasKupciunas — APPROVED** [review]
Looks good. No issues found related to this PR. Tested using URP Template project.

Devices under testing:
VLNQA00217, Razer Phone 2, 9.0.0, Snapdragon 845 SDM845, Adreno 630
VLNQA00268, Samsung Galaxy S10+, 10.0.0, Exynos 9 9820, Mali-G76
OnePlus Nord, 10, Snapdragon 765G SM7250-AB, Adreno 620
iPad Air4, SoC: A14, iOS: 14.0
iPhone 12Pro, SoC: A14, iOS: 14.1

Unity used for testing:
Version: 2021.2.0a18.2582
Revision: trunk 5605789000ce
Built: Sun, 16 May 2021 07:07:00 GMT

**Review by hdb-unity — APPROVED** [review]
**Result** Approving without manual testing. Did not check the automated test results (I expect they will be green to merge).

**Why?** Discussed this has isolated halo effect and is already manually tested.

**Comment by phi-lira** [comment]
Let me know when it finishes, I'll look at failures.

**Pull request merged**
