### PR TITLE
[11.x] Avoid the system 'AppendLine' during generation and serialization

### PR DESCRIPTION
**Pull request by jessebarker**
The system call uses the local environment newline which can cause
    problems when sharing shadergraph files between Windows and other
    systems.  This makes the newline explicitly "\n".
---
### Purpose of this PR
Fix for:
[https://fogbugz.unity3d.com/f/cases/1286430/](url)

New ShaderGraph shaders created on Windows had CR/LF line endings for certain scopes.  This could cause file difference detection to engage on an unmodified shader file when shared between users on different platforms.  This PR fixes that.

---
### Testing status
I created new shadergraph shaders on a Mac, and Chris could load them on Windows and show no differences after loading.
Chris was also able to create a new shader on Windows with no "\n" (CR) characters.

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by cdxntchou — APPROVED** [review]

**Comment by cdxntchou** [comment]
Need to modify the shadergraph changelog

**Review by ghost — APPROVED** [review]
I think the developer manual testing is sufficient for this fix.

**Comment by jessebarker** [comment]
I've compared the Yamato results for this PR against the ones for the nearest ancestor to my branch, and the results appear similar, so I don't believe I've introduced any new issues.

**Comment by alindmanUnity** [comment]
yamato status matches master, merging

**Pull request merged**
