### PR TITLE
Fix LitTessellation heightmap displacement with planar and triplanar mapping

### PR DESCRIPTION
**Pull request by FrancescoC-unity**
Fix for https://fogbugz.unity3d.com/f/cases/1342302/ 

There was an issue with keywords that removed the planar and triplanar mapping calculations from domain shaders, which would of course lead to problems. 

This is fixed and is also adding a test with displacement with the various mapping. 

I am going to be running yamato to get the ref images. 

**Before**
beforeTess

**After**
afterTess

### CODE REVIEW

**Comment by FrancescoC-unity** [comment]
Note: I have to push an additional change for the vertex part.

**Comment by FrancescoC-unity** [comment]
I need to make a different scene as the repro scene was not covering all issues and I misunderstood the degree of the issue. Code fix is correct, but more can be done in testing. Adding it now.

**Comment by TomasKiniulis** [comment]
Testing is sufficient, but looks like yamato is completely failing, DX12 that actually manages to run tests skips this test scene.

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
Currently DX12 yamato is good. All the issue are instability (like all the other builder), go to merge

**Comment by sebastienlagarde** [comment]
ah sorry I see we need to regenerate pcitures, laaunching Yamato

**Comment by FrancescoC-unity** [comment]
Argh yeah sorry forgot to re-kick the jobs myself as the one I triggered failed for unrelated reasons.

**Review by sebastienlagarde — APPROVED** [review]

**Pull request merged**
