### PR TITLE
Fix case 1314361 - Continuous bake triggering with realtime Environment and Enlighten

### PR DESCRIPTION
**Pull request by pigselated**
Case:
https://fogbugz.unity3d.com/f/cases/1314361/

When rendering a preview camera the skybox material is modified causing the GI baking to get a different hash for the sky settings this will in turn trigger baking steps. Showing any material preview will thus trigger baking continuously. This is fixed by checking the type of camera when updating the ambient probe and early out when dealing with a preview camera.

Proof of fix:
Video before: https://imgur.com/qf5HiIm.mp4
Video after: https://imgur.com/O74s4yB.mp4

Manually tested:
* HDRI realtime sky with realtime GI and baked GI in reproducer
* Gradient sky with realtime GI and baked GI in reproducer

### CODE REVIEW

**Comment by pigselated** [comment]
Sorry about that. Converted to draft now.

**Review by JulienIgnace-Unity — APPROVED** [review]

**Review by remi-chapelain — APPROVED** [review]
This looks pretty safe given the changes and what has been tested ! Approving ✔️ 
If possible in the future, giving a meaningful title (instead of the bug case) for the PR could help us a tiny bit, thanks a lot ! :)

**Comment by pigselated** [comment]
> This looks pretty safe given the changes and what has been tested ! Approving ✔️
> If possible in the future, giving a meaningful title (instead of the bug case) for the PR could help us a tiny bit, thanks a lot ! :)

Good point. Have fixed the title.

**Comment by sebastienlagarde** [comment]
I am updtating the changelog for this PR

**Pull request merged**
