### PR TITLE
2021.1/backport/terrain density blending

### PR DESCRIPTION
**Pull request by spaceburp**
### Checklist for PR maker
- [x] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [x] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [x] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [x] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?
Backport for case 1311571. Parent PR https://github.com/Unity-Technologies/Graphics/pull/3083

---
### Testing status
Describe what manual/automated tests were performed for this PR
- Manually tested painting and verifying that artifacts previously seen have been removed
- Manually tested 2 - 4 layer blending with different layers with different Opacity as Density states
- Manually tested +4 layer blending and verified that density blending is disabled with >4 Terrain Layers
- Manually tested Heightbased Blending feature for < 4 layers to make sure nothing broke there
- Ran Graphics Tests for URP_Terrain test project
- Created graphics tests for Opacity as Density blend with < 4 layers
- Graphics tests for checking basemap generation

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Did a quick double check on the basemap because I remember there being issues there. Everything looks good!

**Review by phi-lira — APPROVED** [review]

**Comment by phi-lira** [comment]
@spaceburp can you check the yamato status?
  @Unity-Technologies/gfx-qa-urp can you review it?

**Review by erikabar — APPROVED** [review]
since it's a backport I think this PR is properly covered by dev, approving without additional testing

**Comment by spaceburp** [comment]
@phi-lira i'll merge once tests be passin

**Comment by spaceburp** [comment]
tests green

**Pull request merged**
