### PR TITLE
Fix issue where node inputs would misalign from their ports

### PR DESCRIPTION
**Pull request by marctem**
### **Please read**
Fix for https://fogbugz.unity3d.com/f/cases/1224480/. This recurring bug keeps coming back due to an out-of-date optimization in the NodeView structure. I removed the optimization because the UIR renderer doesn't need it, and simplified the node architecture to ensure node inputs stay with their ports.

### Checklist for PR maker
- [X] Have you updated the changelog? Each package has a `CHANGELOG.md` file.

---
### Testing status

**Manual Tests**: What did you do?
- [X] Opened test project + Run graphic tests locally
- Other: 
Created lots of nodes, re-ordered ports on CFN and Subgraphs, expanded/collapsed node port and preview sections.

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)
None; it's all UI. Did verify existing port tests work.

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/78-ScriptableRenderPipeline

### CODE REVIEW

**Review by cdxntchou — APPROVED** [review]

**Review by elizabeth-legros — APPROVED** [review]

**Comment by LandonTownsendUnity** [comment]
On this branch, right clicking the graph and using the searcher now seems to search for nodes as if you're dragging out from a vector output. As a result, it is now impossible to create quite a few nodes from right click, including all master nodes.
image
Additionally, lines attached to default inputs now draw on top of the nodes:
image
After a very small amount of testing I've noticed a fair share of other weird UI inconsistencies/regressions as well:
image
Are we sure we want this much code change to fix one bug? This PR has a huge technical risk and halo effect and is going to need a lot of testing, and even then I will probably not find all of the bugs it may cause.

**Comment by LandonTownsendUnity** [comment]
Nodes without inputs and nodes without outputs now have "separators" on them that disappear when you move them or plug things into them:
image
image
image

**Comment by LandonTownsendUnity** [comment]
collapsepropagationbug

**Comment by marctem** [comment]
- Fixed the empty vertical blocks on nodes when you expand/collapse them
- Fixed tiny useless input tab on Sampler port

- Remaining issue: Port Input edges still appear above node instead of behind.

**Comment by alindmanUnity** [comment]
Just one more visual difference I've noticed that be fixed later: the node edges are squared off instead of rounded for some reason. You can see above in Landon's comparisons of the this branch to master of the normal node

**Review by alindmanUnity — APPROVED** [review]

**Review by ghost — APPROVED** [review]
Confirmed both bug fixes.

**Pull request merged**
