### PR TITLE
[Backport][2020.3 / 10.x.x] Fix for Opaque Texture + MSAA being rendered black on old Apple GPUs 

### PR DESCRIPTION
**Pull request by manuele-bonanno**
Backport of [this PR](https://github.com/Unity-Technologies/Graphics/pull/2863)

### Purpose of this PR
fix for [ISS case 1319143](https://fogbugz.unity3d.com/f/cases/1319143/).

new API SystemInfo.supportsStoreAndResolveAction (bump to 2020.3.4f1 min required version) [PR](https://ono.unity3d.com/unity/unity/pull-request/121862/_/2020.3/mobile/store_and_resolve_action_api#comment-952883).

Older Apple GPUs don't support ResolveAndStore store actions. Because of this we fall back to a Resolve store action, which discards the multisampled RT contents. Any following Load load action will then load a discarded RT, resulting in a black texture.

Because of this we need to disable MSAA when performing a separate Opaque Texture pass on hardware without StoreAndResolve support (i.e. Apple GPUs <= A8).

---
### Testing status
Tested locally using the fogbugz issue repro project.

**Before**:
image

**After**:
image

### CODE REVIEW

**Review by ellioman — APPROVED** [review]

**Comment by manuele-bonanno** [comment]
the tests are currently failing because they are not running agains latest 2020.3/staging trunk (2020.3/4f1) but against an earlier version (2020.3/3f1). The new API introduced requires latest

**Review by vaidasma — APPROVED** [review]
Verified on iPad Air 2 (11.0.3)

**Comment by manuele-bonanno** [comment]
all failed tests are because 2020.3 trunk was using an older version than 2020.3.4f1 which is needed for this PR. Tests are passing against the 2020.3.4f1 custom revision

**Review by marctem — APPROVED** [review]

**Comment by ellioman** [comment]
Yamato failures are known and not related to this PR.

**Pull request merged**
