### PR TITLE
[HDRP] Fix incorrect light list indexing when TAA is enabled

### PR DESCRIPTION
**Pull request by pmavridis**
### Purpose of this PR
https://fogbugz.unity3d.com/f/cases/1352444/

When indexing into the light list, we need to take into account the jittered projection matrix when TAA is enabled.

Before this PR, some tiles in the planar reflection do not have the correct number of reflection probes and part of the reflection is missing (and flickers because on every frame the error is different based on the TAA jitter):
image

After this PR, all tiles in the planar reflection have the correct number of reflection probes and the reflection is not flickering:
image

---
### Testing status
The ticket does not include a repro scene, so I've built a very simple scene as you see above.
After this PR, the reflection does not flicker.

Note: I have not tested XR, which might be affected by this PR.

### CODE REVIEW

**Review by JulienIgnace-Unity — COMMENTED** [review]
I see we are only changing the DeferredUseComputeAsPixel version of deferred. Isn't there similar code in other versions?

**Review by FrancescoC-unity — APPROVED** [review]

**Comment by FrancescoC-unity** [comment]
> I see we are only changing the DeferredUseComputeAsPixel version of deferred. Isn't there similar code in other versions?

I think you might have been tricked by github diff viewer, the change is the prepare light function

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
good catch!

**Comment by JulienIgnace-Unity** [comment]
> I think you might have been tricked by github diff viewer, the change is the prepare light function

I have been tricked by my own bad eye sight :D
All is good then!

**Review by JulienIgnace-Unity — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
For QA: merging, test should be enough

**Pull request merged**
