### PR TITLE
Improve light AABB generation #2

### PR DESCRIPTION
**Pull request by EvgeniiG**
### Purpose of this PR
Light AABB generation is the first part of the light list generation algorithm (used for tiled and clustered lighting).
Had to recreate https://github.com/Unity-Technologies/Graphics/pull/1574 because our branches are extremely divergent.

There are two issues with the current implementation:
1) it's slow (214.5 us for 3 lights on the base PS4);
2) it's underdocumented, and thus difficult to understand, maintain, and optimize.

I have rewritten the code. Highlights include:
* a single unified algorithm (1 kernel) that handles all types of projection matrices;
* thoroughly documented code (cannot claim that it's simple, as the task itself is not simple);
* high performance: 214.5 us -> 77 us for 3 lights (2.78x speedup), 8 threads/light -> 4 threads/light (2x improvement).

I focused on algorithmic rather than low-level optimization. The generated code is not particularly optimal.

---
### Testing status

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally
- [x] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [x] C# and shader warnings (suppress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)
- Other: 

**Automated Tests**: Used existing tests.

**Yamato**: (Select your branch):
https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Flight-aabb-2/.yamato%252F_abv.yml%2523all_project_ci_trunk

Any test projects to go with this to help reviewers?

---

### CODE REVIEW

**Comment by EvgeniiG** [comment]
I renamed "dumb" compiler to "obtuse". We could also go with "doltish" or "dim-witted" if you like.
https://www.merriam-webster.com/thesaurus/dumb

**Comment by EvgeniiG** [comment]
Test 5002 fails when run locally.

image

The screen is black. No rendering occurs.

**Comment by EvgeniiG** [comment]
Fixed by merging the staging branch again.

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
> Test 5002 fails when run locally.
> 
> image
> 
> The screen is black. No rendering occurs.

When you are suspicious about local run you can trigger Yamato.

**Comment by sebastienlagarde** [comment]
Note: was all good (and Yamato almost green) except few test on metal, relaunching a Yamato with latest for sanity check: https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Flight-aabb-2/.yamato%252F_abv.yml%2523all_project_ci_trunk/3611602/job

**Comment by sebastienlagarde** [comment]
So there is a failure on Mac with this PR: https://yamato-artifactviewer.prd.cds.internal.unity3d.com/0c232a74-7208-4b9b-8f80-c47b938dba80%2Flogs%2FTestProjects%2FHDRP_Tests%2Ftest-results%2Ftest-results/TestReportV1.html . It is significant. Adding @jessebarker as well for awareness.

**Comment by jessebarker** [comment]
@sebastienlagarde Looking at those results, I actually think the "expected" results are wrong and the generated results are correct (or at least more correct than the expected images).  Certainly, those match what I see when I run the tests locally.  I'm curious about the "eye" test.  On an Intel GPU locally, I don't get any color chart background (it's black), and just the eyes in the foreground.

**Comment by sebastienlagarde** [comment]
> @sebastienlagarde Looking at those results, I actually think the "expected" results are wrong and the generated results are correct (or at least more correct than the expected images). Certainly, those match what I see when I run the tests locally. I'm curious about the "eye" test. On an Intel GPU locally, I don't get any color chart background (it's black), and just the eyes in the foreground.

@jessebarker you are absolutely right, I was confusing the two shots. So now all is fix. This is awesome! :)

**Pull request merged**
