### PR TITLE
Make shadow cascade debug colors match editor UI colors.

### PR DESCRIPTION
**Pull request by arttu-peltonen**
### Purpose of this PR
Making sure Shadow Cascade debug colors in the viewport match the ones in the editor UI. The colors are not 100% the same in order to have better contrast in the viewport under varying lighting conditions.

URP before:
image

URP after:
image

HDRP before:
image

HDRP after:
image

Also fixed apparent typo resulting in too bright color in the UI:
before: 
image
after:
image

---
### Testing status
Checked URP & HDRP look as expected.

### CODE REVIEW

**Review by nigeljw-unity — APPROVED** [review]
LGTM

**Review by TheoWong-pixel — APPROVED** [review]

**Review by sebastienlagarde — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
good catch, thanks

**Comment by arttu-peltonen** [comment]
@sebastienlagarde this should be good to go. Fixed HDRP test images for a test that used cascade debug mode, URP doesn't have a corresponding test. Failures in both test suites but couldn't spot anything that would seem related.

**Review by RSlysz — APPROVED** [review]
Nice catch for the typo. It should be me, sorry.

**Pull request merged**
