### PR TITLE
[2021.1][VFX] staging backports

### PR DESCRIPTION
**Pull request by julienf-unity**
### Purpose of this PR
**Added**
- Added support for Texture2D Arrays in Flipbooks

**Changed**
- Sphere and Cube outputs are now experimental
- Property Binder : Handle Remove Component removing linked hidden scriptable objectfields
- Property Binder : Prevent multiple VFXPropertyBinder within the same game object

**Fixed**
- Modified Sign operator node output for float when input is 0.0f [Case 1299922](https://fogbugz.unity3d.com/f/cases/1299922/)
- An existing link can be remade.
- Use alphabetical order in type list in blackboard "+" button [Case 1304109](https://issuetracker.unity3d.com/product/unity/issues/guid/1304109/)
- Consistently displays the Age Particles checkbox in Update context [Case 1221557](https://issuetracker.unity3d.com/product/unity/issues/guid/1221557/)
- Fix compute culling compilation in URP [Case 1309174](https://fogbugz.unity3d.com/f/cases/1309174/)
- pCache: Unexpected ditable field in Mesh Statistics, Save & Cancel pCache, error trying to access not readable texture [Case 1122417](https://issuetracker.unity3d.com/product/unity/issues/guid/1122417/)
- Handle correctly locked VisualEffectAsset with version control system [Case 1261051](https://issuetracker.unity3d.com/product/unity/issues/guid/1261051/)
- Artefact in VFXView using efficient debug mode in component target board [Case 1243947](https://issuetracker.unity3d.com/product/unity/issues/guid/1243947/)
- Compilation error due to direct access to GetWorldToObjectMatrix instead of VFXGetWorldToObjectMatrix [Case 1308481](https://issuetracker.unity3d.com/product/unity/issues/guid/1308481/)
- Safe Normalization of Cross Products in Orient blocks [Case 1272724](https://issuetracker.unity3d.com/product/unity/issues/guid/1272724)
- Property Binder : Undo after reset [Case 1293794](https://issuetracker.unity3d.com/product/unity/issues/guid/1293794/)
- Property Binder : Allow copy/past from a game object to another
- Deleting a context node and a block while both are selected throws a null ref exception. [Case 315578](https://issuetracker.unity3d.com/product/unity/issues/guid/1315578/)

---
### Testing status
Tests launched locally

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by PaulDemeulenaere** [comment]
A backport is missing in this PR, it explains failure with XR: https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/2021.1%252Fvfx%252Fstaging/.yamato%252Fvfx_hdrp-win-dx11.yml%2523VFX_HDRP_Win_DX11_playmode_XR_mono_Linear_2021.1/5499335/job/artifacts

image
image

Probably this change : 67c19ccb918b11b61a375af26cd97e8d8f7ef515

**Comment by julienf-unity** [comment]
I backported the commit you mentionned @PaulDemeulenaere

**Review by PaulDemeulenaere — APPROVED** [review]
I did a quick overview (skipping change in .vfx files) and didn't notice unexpected change.

**Review by VitaSkruibyte — APPROVED** [review]

**Comment by PaulDemeulenaere** [comment]
Ready to be merged @julienf-unity 
image

**Pull request merged**
