### PR TITLE
[VFX/ShaderGraph] Workflow improvement : Emission, UX & VFXTarget

### PR DESCRIPTION
**Pull request by PaulDemeulenaere**
### Purpose of this PR
Address some issues with VFX Target & ShaderGraph reported by @peeweek. 

1. Minor change in UX : rename toggle for Alpha & use an enum field to be consistent with HDRP.

_change_ui_shaderGraph

2. ~Change _isVFXTarget_ rule (see https://github.com/Unity-Technologies/Graphics/pull/1005/files#diff-45653c9c3a01dce1cf23b2ec38567f3fR322)~

~**_Before_** If **first** target is "VisualEffectTarget" then VFX~

_Order_Before_issue

~**_After_** If **any** target is "VisualEffectTarget" then VFX~

_Order_After_issue

~We can't really mix a VFX target with other target yet, this constraint comes from the ShaderImporter which exclusively outputs a shader **or** a ShaderGraphVfxAsset.~

@sebastienlagarde ~This change is pretty important : now, if we choose the target *everything* in shaderGraph, it will *not* generate a shader but a ShaderGraphVfxAsset. /!\~~

*==> Change reverted at* : https://github.com/Unity-Technologies/Graphics/pull/1005/commits/94c02495400888ddca200b33ae89fe6e6ce3afb5 see https://unity.slack.com/archives/CCCSH1HGB/p1593446599029900?thread_ts=1593446230.028700&cid=CCCSH1HGB

3. Rework BaseColor & Emission
Most of change done in this additionnal change : https://github.com/Unity-Technologies/Graphics/pull/1005/commits/1dbeeeb0cee388eb0365880cb5aa4cb1be26dff9

_exposure_test

- Allow Emission with VFXTarget
- Fix VFXApplyPreExposure for PlanarPrimitive using the ShaderGraph (it was working for Mesh primitive), only unlit (see [this](https://github.com/Unity-Technologies/Graphics/blob/eb080a08b2231243200c58bb89fd8f13effc205e/com.unity.render-pipelines.high-definition/Editor/VFXGraph/Outputs/VFXAbstractParticleHDRPLitOutput.cs#L163)).
- Add a GraphicTest (only for HDRP, in URP, since exposure multiplier is alway 1.0, it leads to a simpler behavior : `color = baseColor + emissive`)

---
### Testing status
- Tested locally, the change of isTarget could be problematic for user clicking on "Everything" in target.
- Added a graphicTest with an exposure between 0 & 1 (with reference using HDRP shadergraph target).
image

### CODE REVIEW

**Comment by PaulDemeulenaere** [comment]
Got a failure while running metal :
*Expected*
image
*Actual*
image

> The "Actual" has more data than "Expected", I suppose it's a reference image not update to date ?

**Comment by sebastienlagarde** [comment]
@PaulDemeulenaere yes, a fix for metal have landed in C++, the screenshots have been updated on master.

**Comment by PaulDemeulenaere** [comment]
Observed an issue on URP/Metal/OSX : 
*Expected*
image

*Actual*
image

It doesn't seem related to these changes.

**Comment by sebastienlagarde** [comment]
@PaulDemeulenaere  nope. Exploding geoemtry as you see is random on Mac. Since Yesterday, a fix have land on C++ side which should fix it now. So basically a merge of master and a re-run should fix all your trouble on Mac :)

**Comment by PaulDemeulenaere** [comment]
Made a mistake in template code : `GetCurrentExposureMultiplier`
I thought this function was in global parameter but it's declared in https://github.com/Unity-Technologies/Graphics/blob/459546c96b1d9f9ada372ac7ce9130a531fdb1e6/com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl

**Comment by marctem** [comment]
I'm not sure this is the right fix for Shader Graph users. Bringing discussion to slack.

**Comment by PaulDemeulenaere** [comment]
> I'm not sure this is the right fix for Shader Graph users. Bringing discussion to slack.

Agree, VFXTarget as First/Any should be removed from this PR, it has been done here : https://github.com/Unity-Technologies/Graphics/pull/1005/commits/94c02495400888ddca200b33ae89fe6e6ce3afb5

Tested locally at : https://github.com/Unity-Technologies/Graphics/pull/1005/commits/888f6b9fadbe185087230c2dd456f42ebc1617ef

**Pull request merged**
