### PR TITLE
Disable Batching Option in Graph Inspector

### PR DESCRIPTION
**Pull request by mehmetcanakbay**
### Purpose of this PR

If someone needs to disable batching for some reason (such as using object node on multiple objects), they can now do it in Shader Graph, instead of generating the code and then pasting it on a blank shader file to use.
For more information, I had to do disable it in a project I was developing, in it, I was using object node to get the scale of the object. If you used the same sprite, they would batch and object-scale node wouldnt work at all. Disabling batching makes it work.

Related forum post: https://forum.unity.com/threads/shader-graph-object-position-node-is-wrong-on-multiple-objects.744917/

Without Disable Batching

With Disable Batching

### CODE REVIEW

**Review by bencloward — COMMENTED** [review]
The location where you've placed the option is odd. Nothing belongs in between the target designation and the settings for the target. If it's part of the URP-specific settings, it should go somewhere in the Universal section. Does it work in HDRP?

**Comment by mehmetcanakbay** [comment]
> The location where you've placed the option is odd. Nothing belongs in between the target designation and the settings for the target. If it's part of the URP-specific settings, it should go somewhere in the Universal section. Does it work in HDRP?

It's not URP-specific. This is a part I especially was careful of, I wanted to not edit the Target files, because that would result in me editing every Target for this. In the Generator.cs file, instead I loop for every SubShaderDescriptor and edit the variable in there. So this should work in every target, Built-In, URP, and HDRP. 

https://github.com/mehmetcanakbay/Graphics/blob/3588c3c211b25d1ee51ae2c6f978d12db4a9101c/Packages/com.unity.shadergraph/Editor/Generation/Processors/Generator.cs#L299-L306

Just to be sure, I just opened a HDRP project, and while I couldnt reproduce the same problem I had in 2D, DisableBatching tag is in the generated shader file and it changes depending on whatever I check the toggle or not.

Regarding the location, my line of thinking was how I implemented it. Get the targets, disable the batching then. But I agree, visually it does not look right. If you give me the go, I'll change its position to be between Precision and Target Settings label.

**Comment by bencloward** [comment]
> Regarding the location, my line of thinking was how I implemented it. Get the targets, then disable the batching. But I agree, visually it does not look right. If you give me the go, I'll change its position to be between Precision and Target Settings label.

Yes - I think that spot makes more sense.  Thanks!

**Review by bencloward — APPROVED** [review]
Looks good to me.  Nice work!

**Comment by mehmetcanakbay** [comment]
@bencloward Should I update this PR so that there wont be any conflicting files? From what I see interally you guys are working on this. Should I close this PR?
Dont have much experience contributing. I hope you dont mind possibly meaningless questions like these.

**Pull request closed without merging**
