### PR TITLE
[HDRP][Path Tracing] Cleaned up dirtiness handling when using multiple cameras at once

### PR DESCRIPTION
**Pull request by eturquin**
This PR addresses the following bug: https://fogbugz.unity3d.com/f/cases/1376940

More generally, this will fix potential problems when having multiple cameras, with different acceleration structures, in which case their resp. accumulations would keep being reset every frame if they were displayed at the same time.

Tested on the scene provided in the accompanying Fogbugz ticket.

### CODE REVIEW

**Comment by eturquin** [comment]
One test (5010) breaks, I'll check what's going on.

**Comment by eturquin** [comment]
Should be good now.

**Review by iM0ve — APPROVED** [review]
Small scale change, checking the repro and running tests should be sufficient

**Review by sebastienlagarde — APPROVED** [review]

**Comment by alejobrainz** [comment]
Hi.  We just noticed that this fix produces a crash on our project.  In our use case, we have a tool that creates a new scene and instances a lighting/camera setup plus a character.  If we run this script a few consecutive times while having the game view open, the editor will crash.  The crash log is as follows:

=================================================================
	Native Crash Reporting
=================================================================
Got a UNKNOWN while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at UnityEngine.Experimental.Rendering.RayTracingAccelerationStructure:GetSize <0x00090>
	  at UnityEngine.Rendering.HighDefinition.HDRenderPipeline:CheckDirtiness <0x00382>
	  at UnityEngine.Rendering.HighDefinition.HDRenderPipeline:RenderPathTracing <0x0027a>
	  at UnityEngine.Rendering.HighDefinition.HDRenderPipeline:RecordRenderGraph <0x01762>
	  at UnityEngine.Rendering.HighDefinition.HDRenderPipeline:ExecuteWithRenderGraph <0x00602>
	  at UnityEngine.Rendering.HighDefinition.HDRenderPipeline:ExecuteRenderRequest <0x01812>
	  at UnityEngine.Rendering.HighDefinition.HDRenderPipeline:Render <0x0610a>
	  at UnityEngine.Rendering.RenderPipeline:InternalRender <0x00058>
	  at UnityEngine.Rendering.RenderPipelineManager:DoRenderLoop_Internal <0x001c2>
	  at <Module>:runtime_invoke_void_object_intptr_object_AtomicSafetyHandle <0x000c7>
	  at <unknown> <0xffffffff>
	  at UnityEditor.EditorGUIUtility:RenderPlayModeViewCamerasInternal_Injected <0x000a7>
	  at UnityEditor.EditorGUIUtility:RenderPlayModeViewCamerasInternal <0x00042>
	  at UnityEditor.PlayModeView:RenderView <0x004b2>
	  at UnityEditor.GameView:OnGUI <0x011ba>
	  at UnityEditor.HostView:InvokeOnGUI <0x00159>
	  at UnityEditor.DockArea:DrawView <0x00042>
	  at UnityEditor.DockArea:OldOnGUI <0x00afa>
	  at UnityEngine.UIElements.IMGUIContainer:DoOnGUI <0x008ce>
	  at UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent <0x0040a>
	  at UnityEngine.UIElements.IMGUIContainer:DoIMGUIRepaint <0x004ea>
	  at UnityEngine.UIElements.UIR.RenderChainCommand:ExecuteNonDrawMesh <0x00543>
	  at UnityEngine.UIElements.UIR.UIRenderDevice:EvaluateChain <0x01612>
	  at UnityEngine.UIElements.UIR.RenderChain:Render <0x006e2>
	  at UnityEngine.UIElements.UIRRepaintUpdater:Update <0x00252>
	  at UnityEngine.UIElements.VisualTreeUpdater:UpdateVisualTreePhase <0x0009d>
	  at UnityEngine.UIElements.Panel:UpdateForRepaint <0x000aa>
	  at UnityEngine.UIElements.Panel:Repaint <0x001ba>
	  at UnityEngine.UIElements.UIElementsUtility:DoDispatch <0x000de>
	  at UnityEngine.UIElements.UIElementsUtility:UnityEngine.UIElements.IUIElementsUtility.ProcessEvent <0x000f2>
	  at UnityEngine.UIElements.UIEventRegistration:ProcessEvent <0x0008e>
	  at <>c:<.cctor>b__1_2 <0x0002a>
	  at UnityEngine.GUIUtility:ProcessEvent <0x0005c>
	  at <Module>:runtime_invoke_void_int_intptr_intptr& <0x00095>
=================================================================
Received signal SIGSEGV
Obtained 2 stack frames
RtlLookupFunctionEntry returned NULL function. Aborting stack walk.
<Missing stacktrace information>

Apparently the crash happens when checking the acceleration structure size:
ulong accelSize = m_CurrentRAS.GetSize();

**Pull request merged**
