### PR TITLE
[Fogbugz # 1365368] Fixing debug views for drs

### PR DESCRIPTION
**Pull request by kecho**
### Purpose of this PR
Fixing all the broken debug views for DRS. 
These have been broken for a long time.

https://fogbugz.unity3d.com/f/cases/1365368/

---
### Testing status
Tested on dx12, PC with DRS on, at force resolution percentage of 20.

| Feature               |  Software DRS | Hardware DRS | DLSS + Software DRS | DLSS + Software DRS | TAAU + Hardware DRS | TAAU + Hardware DRS |
| -------------------   |  ------------ | ------------ | ------------------- | ------------------- | ------------------- | ------------------- |
| Material debug menu   |  Pass         | Pass         | Pass                | Pass                | Pass                | Pass                |
| Lighting debug menu   (ray tracing options not tested) |  Pass          | Pass         |  Color Pyramid broken (unrelated, need a new PR) | Color Pyramid broken (unrelated, need a new PR)  |  Pass |  Pass |
| Rendering debug menu  | Pass          | Pass          | Pass          | Pass          | Pass         | Pass         |

Full list of debug options in the bug.

### Comment to QA
---
There are 2 bugs that have been discovered.
* First one is with Color pyramid. There is a fogbugz tracked and ill attack it next
* There is a problem when in dx12, hardware drs (any filter / algorithm). Must start with dual camera, forced drs, and with drs enabled on the camera.  Hit play, then disable drs on the camera. Notice that the resolution is corrupted. This is mostly a bug with the forced option. Let me know if this qualifies as a bug and please qa try to repro it.

Apart from these issues Everything looked peachy. QA feel free to add to the test matrix above.

### CODE REVIEW

**Review by remi-chapelain — CHANGES_REQUESTED** [review]
I just tried this PR and encountered an issue when showing the HDRP Debugger when DLSS was on. (By the way, this also happen on master). This errors prevent from testing the PR.

https://user-images.githubusercontent.com/57442369/140083450-2bea6b7e-64d4-4044-a65b-205851e7acb8.mp4

**Comment by kecho** [comment]
@remi-chapelain absolutely weird. Could you try on a different project? / New project? I think I encountered this once and went away. It's definitely a bug, but I don't want to block this pr.
Feel free to create a new bug with this problem. If the PR is still after the workaround above blocked then this is a 'lets drop everything' issue and gotta fix it asap.

**Comment by remi-chapelain** [comment]
Yep, [logged it](https://fogbugz.unity3d.com/f/cases/1377986/), also repro on master. 
However, the PR will be blocked either way since we can't test debug mode with DLSS :|

**Review by remi-chapelain — CHANGES_REQUESTED** [review]
Much better :). Most of the debug view are fixed. tested Software / Hardware
All tests were done in force resolution at 20% to exacerbate possible problems. 
I found a few exceptions though: 

**Rendering**
- Full Screen Debug Mode > Lens Flare Data Driven fails ONLY WITH DLSS ([black screen](https://unity.gyazo.com/c65eb3dcea0dbec50134ce68cc04935b))

**Decals**
- Display Atlas: Position and Scale of the displayed atlas is not the same with DRS on ([repro](https://unity.gyazo.com/c65eb3dcea0dbec50134ce68cc04935b))

**Lighting**
- Tile/Cluster/Material Feature Variants Debug: this one I'm not entirely sure what to expect, it's just we are seeing the cluster / tile at input resolution leaving really big rectangles ([repro](https://unity.gyazo.com/c02fa125a51c98f838996dfa840beca3))
- SkyReflection / Cookie Atlas / Planar Reflection Atlas / Local Volumetric Fog Atlas: Same issue than with Decals atlas, atlas position and scale is not right for those 4 ([repro](https://unity.gyazo.com/346bf40185d4c622722030887b5732b7))

**Comment by kecho** [comment]
@remi-chapelain Done. The new cluster debug view should look like this
image

The gray menu at the bottom will be scaled. The tiles however must remain resolution dependant. Sorry this took a while I had to rewrite a lot of pieces so it would work with DRS properly.

Tested with DRS hardware & software.

I also fixed the debug views from the atlases so they dont get offset.

**Review by remi-chapelain — CHANGES_REQUESTED** [review]
We're getting there. 

Among the things reported, there's only one thing that appears to be not working. 
Rendering > Full Screen Debug Mode > LensFlare. 
With DLSS there's still black, with DRS, it's still scaled down. 

https://user-images.githubusercontent.com/57442369/142459152-f165967d-cfb2-47b2-bce6-3db8be9cac9e.mp4

I used the lensFlareSamples from HDRP Package to test it (interiorScene)

**Comment by kecho** [comment]
> We're getting there.
> 
> Among the things reported, there's only one thing that appears to be not working. Rendering > Full Screen Debug Mode > LensFlare. With DLSS there's still black, with DRS, it's still scaled down.
> 
>  06ea1a1dff9141506e52df74720af89c.mp4 
> I used the lensFlareSamples from HDRP Package to test it (interiorScene)

Fixed! lmk if this works

**Review by remi-chapelain — APPROVED** [review]
Last issue fixed ! ✔️

**Pull request merged**
