### PR TITLE
Fix GLES3 cubemap array support

### PR DESCRIPTION
**Pull request by hkr**
### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Fix case 1285132, a compile error when trying to use SAMPLE_TEXTURECUBE_ARRAY_LOD with OpenGL ES 3.x

---
### Testing status
manual with repro project

### CODE REVIEW

**Review by phi-lira — APPROVED** [review]
LGTM. Do we need to have something similar to OpenGL core?

**Comment by hkr** [comment]
> LGTM. Do we need to have something similar to OpenGL core?

Had a quick look and I don't think we need to change the gl core version.

**Review by phi-lira — APPROVED** [review]

**Comment by phi-lira** [comment]
Sorry, I ended up missing this PR. It should have been merged a while ago. Running yamato.

**Comment by phi-lira** [comment]
Failures not introduced by this PR.

**Pull request merged**
