### PR TITLE
Limit MAX_VISIBLE_LIGHTS to 16 on OpenGL ES 2.0 or 3.0 devices

### PR DESCRIPTION
**Pull request by hkr**
ES 3.0 and 2.0 only support MAX_VISIBLE_LIGHTS=16

### **Please read**
**PR workflow guidelines**
* SRP ABV will start automatically on Yamato when you open your PR
* Changes to docs and md files will **not** trigger ABV jobs 
* Consider making use of **draft PRs** if you are not 100% sure that your PR is ready for review
* ABV will restart if you add a new commit to a branch with an open PR (hence why you should consider using draft PRs)
* Adding [skip ci] (case insensitive) to the title of PRs will stop any jobs being trigger automatically - you will need to open Yamato and find your branch to run ABV
* You can also add [skip ci] to commit messages to prevent CI from running on that push
* Add [cancel old ci] to your commit message if you've made changes you want to test and no longer need the previous jobs

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR.
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

---
### Testing status

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)
- Other: 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics

Any test projects to go with this to help reviewers?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Comment by pbbastian** [comment]
Is this a backport of a PR to master?

**Comment by hkr** [comment]
@pbbastian It is a backport of https://github.com/Unity-Technologies/Graphics/pull/686 but since 8.x does not have Hybrid renderer and the extra shader variants that come with it the change is different. I'm still discussing this with @phi-lira. I think you got added as reviewer automatically.

**Comment by pbbastian** [comment]
Is this up to date with the original PR, and generally ready for proper review?

**Comment by hkr** [comment]
> Is this up to date with the original PR, and generally ready for proper review?

The solution used in the original PR cannot be used in older URP versions because older URP versions don't have extra shader variants for Hybrid V2.

But this version should essentially do the same thing.

**Comment by hkr** [comment]
It is ready for a proper review.

**Comment by hkr** [comment]
> Can you add to the changelog?
> Add a [Skip CI] to the commit message to tell Yamato not to run as there's no reason to run Yamato on changelog changes :)

Did that but then had to fix a conflict...

**Comment by ellioman** [comment]
Yeah, that happens quite regularly unfortunately. 
Best approach is to fix those conflicts at the very end once you've gotten a green Yamato.

Few things I I'm wondering about:
- You're adding a subshader in Lit for the GLES3. Do we not need to do that for the other shaders as well, like SimpleLit?
- The DepthNormals pass that got recently added is missing in the new Subshader.
- I would move the new GLES3 subshader below the current one we have, so the most common 4.5 is the first one, then the 4.5 GLES, then 2.0...

**Comment by hkr** [comment]
> * You're adding a subshader in Lit for the GLES3. Do we not need to do that for the other shaders as well, like SimpleLit?
I will have a look at this. Does the SimpleLit shader support shadows from multiple lights?


> * The DepthNormals pass that got recently added is missing in the new Subshader.
I don't see this pass in 8.x

> * I would move the new GLES3 subshader below the current one we have, so the most common 4.5 is the first one, then the 4.5 GLES, then 2.0...
8.x doesn't have the common target 4.5 SubShader. If we had that I could just backport the fix as in 10.x.

**Comment by ellioman** [comment]
I completely missed the part where this is a backport to 8.x.x.
So the DepthNormals comment from me is irrelevant.

But yeah, we have multiple shaders with _ADDITIONAL_LIGHT_SHADOWS variant.

**Pull request closed without merging**
