### PR TITLE
DoF UI/UX improvements

### PR DESCRIPTION
**Pull request by pmavridis**
### Purpose of this PR

https://fogbugz.unity3d.com/f/cases/1240204/

This PR implements the UI/UX improvements for DoF that we recently discussed. After the changes, the UI looks like this:

image

Notably:
- Quality settings are always visible and editable
- Selecting a quality presets reflects the correct values in the UI controls
- Editing a quality control automatically sets the quality to custom
- Switching back to custom from a preset, remembers the last custom settings used (including override states).
- The override check boxes are indented for this control, as seen in the screen (and discussed on Slack).

There is a lot of code in this PR to implement this functionality, but we should be able to re-use it when implementing the same for other volume components (apart from DoF). The new functions are not a public API, so it should be easy to change them in the future.

As expected, there are no changes (or overhead) in the runtime. All changes affect only the editor.

---
### Testing status
I have tested changing various presets in DoF, clicking the checkboxes, disabling the control etc.

### CODE REVIEW

**Comment by pmavridis** [comment]
Note: If we are OK with this, then I must also update the screenshot in the documentation before we merge.

**Comment by iM0ve** [comment]
Review Status: In Progress

**Issues**
1) Changing Quality settings does not register for Undo. Can result in weird UI, for example will say Hight settings, but all the sliders would be set to Low.

bM7S1nqmYW

**Comment by pmavridis** [comment]
> 1. Maybe related to issue 2, but it still occurs. Lowering a parameter reduces visual fidelity, but raising it back up doesnt revert the visual change. Only works if you rever the value via Quality mode (not via slider).

These two issues are indeed related and both happen because the runtime values get out-of-sync with the reflected values in the Editor UI. I'm still trying to figure out what is causing this (it is related to the reflection system) and will post an update.

**Comment by pmavridis** [comment]
In the end, it was not exactly a bug, but more a UX issue. Here is what's happening:
- In the quality settings you have a few parameters set to not be overridden.
- By design, non-overridden parameters are replaced by the volume system with the default value for this parameter (which is not shown in the UI) if no other volume overrides this. This can be confusing, and initially I though it was a bug.
- When the quality is set to custom, quality parameters behave similar to other parameters (so the ones that are set to "no override" will be replaced with default values).
- When the quality is set to high (or another preset), all quality settings will be overridden with values from the presets (I believe this makes sense, because "high" has a specific meaning. If you want "high" but with one parameter modified, then it is not "high" anymore, it is custom).
- So when you automatically switch to custom by moving one slider, because some parameters are set to not-override, for these parameters you are also switching from the high-preset to the default value. 

So I'm making these "UX" changes to make things better:
- When you switch to a preset, all quality parameters are set to "override" - all checkboxes will be active (this communicates to the user that all these values are actually used by the preset). This way, when you switch to custom by modifying one of them, you will get what you expect: the settings of the preset with only one of the quality parameter changed. 
- When the user sets the quality field to non-override (the "parent" of the quality settings), I grey-out all quality presets. 

I believe there is still a UX issue: for non-override parameters we generally don't show what value is used. But this not specific to quality settings, so it should be addressed in another PR. I will start a discussion on Slack regarding this.

**Comment by pmavridis** [comment]
> Please add UX in the loop when modifying UX.

We already had a few meetings with UX discussing these changes and there is also a slack thread where Theo gives his input regarding indentation. 

I agree that these changes need to be applied globally (not only the indentation but also the quality settings behaviour) and since @johnpars has exactly this task, perhaps  he can continue working from this state and make a final PR for everything. 

This PR was just  addressing the linked FogBugz.

**Comment by pmavridis** [comment]
Closing this PR since @johnpars will open a new one with improvements for all volume components with quality settings.

**Comment by johnpars** [comment]
Opened a draft here for discussion (see reviewer notes): #1296

**Pull request closed without merging**
