### PR TITLE
Various Volumetric Clouds improvements

### PR DESCRIPTION
**Pull request by anisunity**
- Moved the quality ui section of the volumetric clouds.
- Moved the density, erosion and ambient occlusion curves ui of the volumetric clouds.
- Changed the volumetric clouds presets.
- Changed the maximal step size based on the cloud layer thickness.
- Increase the maximal multi-scattering value.
- Decrease the maximal density multiplier value.
- Removed the non uniform weight distrbution for light sample (volumetric clouds).
- Reduced the minimal threshold for cloud density (support very light clouds).
- Changed the values of the forward and backward eccentricity.
- Adjust the minimal cloud distance based on the cloud layer size.
- Evaluate the sun luminance at the center of the raymarching volume instead of the earth surface.
- Reduce the erosion occlusion intensity.
- Reduce the maximal mip level when doing light rays (volumetric clouds).
- Change the default curves for density and erosion (volumetric clouds).
- Change default volumetric clouds values (powder effect, erosion occlusion, speed multipliers).
- Made the wind orientation code a non additional property.
- Increase the minimal sigma value to 0.04 (more physically accurate).

image

@pierre-unity Needs to do a pass on the presets see what he wants to change.
@remi-chapelain we'll need to update the tests screenshots after that

Testing status
Volumetric cloud tests are failing locally (expected)
Pair tested the changes with @pierre-unity

### CODE REVIEW

**Review by sebastienlagarde — APPROVED** [review]

**Comment by anisunity** [comment]
Applied the latest changes requested by @pierre-unity

**Comment by iM0ve** [comment]
Review: In progress

Having just a quick look found that there are quite a few warnings, could we address them in this PR or should we track it separately?

image

**Comment by anisunity** [comment]
Will be adressed in this PR, i'll do it

**Comment by anisunity** [comment]
Shader warning fixed

**Review by iM0ve — APPROVED** [review]
Updated my review above, all issues fixed and looks good to go.

**Pull request merged**
