### PR TITLE
Universal/staging

### PR DESCRIPTION
**Pull request by phi-lira**
- Fixed Screen Space Decal to work with fog. [1383719] (#6703) 
- Make particle shader blending consistent with standard shaders. (#6861) 
- [Universal] RenderPass RTHandles refactor (#6456) 
- Universal bugfix - Missing keyword SHADOWS_SHADOWMASK for ShaderGraph using deferred rendering (#6681) 
- Adding fragment/vertex declarations to some KeywordDescriptors in ShaderGraph (#6917)
- Fix mobile detection for light count to match shaders. (#6837)

Nightly https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/universal%252Fstaging/.yamato%252Fall-urp.yml%2523Nightly_URP_trunk/11380517/job

### CODE REVIEW

**Review by ernestasKupciunas — APPROVED** [review]
Universal Template scene was used to run on multiple platforms to check for the regressions. https://yamato.cds.internal.unity3d.com/jobs/1724-reach-qa-graphics-template-urp/tree/master/.yamato%252FAll.yml%2523trunk_Run_All/11340631/job/pipeline

In addition, I have tested BoatAttack project with and without Render Pass enabled on these platforms:
- MacBook Pro (16-inch, 2021), CPU: Apple M1 Max, Memory: 64 GB, macOS: Monterey 12.1

- VLNQA00268, Samsung Galaxy S10+, 10.0.0, Exynos 9 9820, Mali-G76

- OnePlus Nord, 10, Snapdragon 765G SM7250-AB, Adreno 620

All the descriptions of the PRs look good, RTO has been performed(if needed)

**Review by aleksandrasdzikia — APPROVED** [review]
Lgtm.

Case: 1378545 looks fixed. Additionally played around with URP  Examples project with different settings and run on mobile devices. 

Devices used: 
* MacBook Pro (16-inch, 2021), CPU: Apple M1 Max, Memory: 64 GB, macOS: Monterey 12.0
* Galaxy Note10 USA
* Huawei P20

**Comment by phi-lira** [comment]
There seems to be an instability in iphone tests, caused by a timeout on Fog 112 test. Investigating.

**Comment by phi-lira** [comment]
URP Nightly is green except for one instability in iPhone test and known issues already fixed in master. 
We will handle the instability this follow up PR https://github.com/Unity-Technologies/Graphics/pull/7036.  https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/universal%252Fstaging/.yamato%252Fall-urp.yml%2523Nightly_URP_trunk/11380517/job

**Pull request merged**
