### PR TITLE
Fixed shadowCascadeBlendCullingFactor to be 1.0

### PR DESCRIPTION
**Pull request by nigeljw-unity**
Fixed shadowCascadeBlendCullingFactor to be 1.0 so that we do no erroneously cull castors

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [x] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
shadowCascadeBlendCullingFactor was being set to 0.6, but this is only supposed to be set when using cascade blending which is not support in URP

---
### Testing status
Verfied this change agaisnt the URP template and using the stats to see the castor count is corrected.
---

### CODE REVIEW

**Review by kaychang-unity — APPROVED** [review]

**Review by erikabar — APPROVED** [review]
looks like a minimal change so approving without additional testing

**Review by adrien-de-tocqueville — APPROVED** [review]

**Comment by sebastienlagarde** [comment]
Hi, can you confirm it is a change that will come with your C++ PR? as curently this change have been done by Ugyar to fix an issue.

**Review by ellioman — APPROVED** [review]

**Review by eh-unity — APPROVED** [review]
LGTM.

**Comment by nigeljw-unity** [comment]
@sebastienlagarde there is no trunk change that accompanies this at the moment. This should be ok by itself. It will increase the static castor count and decrease performance slightly, but that is the correct behaviour. My minimal enclosing sphere change (https://ono.unity3d.com/unity/unity/pull-request/131872/_/2021.2/minimal_enclosing_cascade_sphere) will reduce the cascade overlap and reduce the visible static castor count, which will mitigate the increase in castor count and performance loss from this change to the blend culling factor.

I am investigating the correctness ComputeVisibleSplitMask function in trunk for the resulting set of static castors seperately at the moment, but that will be an indepdent change from this one.

Can you direct me to the change that Uygar made that you reference? This change should still ideallty merge.

**Pull request merged**
